export {
  BuiltInAgentIdSchema,
  AgentStateSchema,
  AgentSpawnedSchema,
  AgentStateChangedSchema,
  AgentOutputSchema,
  AgentCompletedSchema,
  AgentKilledSchema,
  AgentEventPayloadSchema,
  type AgentSpawned,
  type AgentStateChanged,
  type AgentOutput,
  type AgentCompleted,
  type AgentKilled,
  type AgentEventPayload,
} from "./agent.js";

export {
  TerminalSpawnOptionsSchema,
  TerminalResizePayloadSchema,
  CopyTreeFormatSchema,
  CopyTreeOptionsSchema,
  CopyTreeGeneratePayloadSchema,
  CopyTreeInjectPayloadSchema,
  CopyTreeProgressSchema,
  FileReadPayloadSchema,
  VoiceInputCorrectPayloadSchema,
  SystemOpenExternalPayloadSchema,
  SystemOpenPathPayloadSchema,
  SystemShowItemInFolderUnconfinedPayloadSchema,
  SystemOpenInEditorPayloadSchema,
  TerminalReplayHistoryPayloadSchema,
  DevPreviewStartPayloadSchema,
  WorktreeSetActivePayloadSchema,
  WorktreeCreatePayloadSchema,
  TabGroupLocationSchema,
  TabGroupInputSchema,
  sanitizeTabGroups,
  TerminalSnapshotSchema,
  filterValidTerminalEntries,
  type TerminalSpawnOptions as ValidatedTerminalSpawnOptions,
  type TerminalResizePayload as ValidatedTerminalResizePayload,
  type CopyTreeOptions as ValidatedCopyTreeOptions,
  type CopyTreeGeneratePayload as ValidatedCopyTreeGeneratePayload,
  type CopyTreeInjectPayload as ValidatedCopyTreeInjectPayload,
  type CopyTreeProgress as ValidatedCopyTreeProgress,
  type VoiceInputCorrectPayload as ValidatedVoiceInputCorrectPayload,
  type SystemOpenExternalPayload as ValidatedSystemOpenExternalPayload,
  type SystemOpenPathPayload as ValidatedSystemOpenPathPayload,
  type TerminalReplayHistoryPayload as ValidatedTerminalReplayHistoryPayload,
  type DevPreviewStartPayload as ValidatedDevPreviewStartPayload,
  type WorktreeSetActivePayload as ValidatedWorktreeSetActivePayload,
  type WorktreeCreatePayload as ValidatedWorktreeCreatePayload,
  type TabGroupInput,
  type TerminalSnapshotEntry,
  AssistantHostEventSchema,
  AssistantHostCommandSchema,
  AssistantHostSessionDescriptorSchema,
  parseAssistantHostEvent,
  parseAssistantHostCommand,
  parseAssistantHostSessionDescriptor,
  ASSISTANT_HOST_PROTOCOL_VERSION,
} from "./ipc.js";

export {
  PackageJsonScriptsSchema,
  PackageJsonSchema,
  WorktreeSummaryResponseSchema,
  ProjectIdentityResponseSchema,
  SimplifiedProjectIdentitySchema,
  IssueExtractionResponseSchema,
  GitStatusCodeSchema,
  GitStatusEntrySchema,
  WorktreeChangesSchema,
  GitWorktreeEntrySchema,
  safeParse,
  parseOrThrow,
  type PackageJsonScripts,
  type PackageJson,
  type WorktreeSummaryResponse,
  type ProjectIdentityResponse,
  type SimplifiedProjectIdentity,
  type IssueExtractionResponse,
  type GitStatusCode,
  type GitStatusEntry,
  type WorktreeChanges as ValidatedWorktreeChanges,
  type GitWorktreeEntry,
} from "./external.js";

// `./plugin.js` is deliberately NOT re-exported here: its ~96 zod schemas and
// `semver` import evaluate at module load, and this barrel sits in the eager
// boot graph of several IPC handlers. Plugin install/validate consumers import
// `./plugin.js` directly; boot-path identifier helpers live in
// `./pluginIdentifiers.js`.
export { SCOPED_PLUGIN_NAME_PATTERN } from "./pluginIdentifiers.js";
