// AUTO-GENERATED by scripts/codegen/ipc-renderer.mjs — do not edit by hand.
// Run `npm run codegen:ipc-renderer` to regenerate. Source: the
// `*_METHOD_CHANNELS` constants exported by each
// electron/ipc/handlers/*.preload.ts (files with
// `export const RENDERER_API_SKIP = true` are intentionally skipped).
// The hand-maintained ElectronAPI in api.ts extends this interface.

import type { IpcInvokeMap } from "./maps.js";

export interface GeneratedElectronAPI {
  accessibility: {
    getEnabled(
      ...args: IpcInvokeMap["accessibility:get-enabled"]["args"]
    ): Promise<IpcInvokeMap["accessibility:get-enabled"]["result"]>;
  };
  agentCapabilities: {
    getAgentIds(
      ...args: IpcInvokeMap["agent-capabilities:get-agent-ids"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-agent-ids"]["result"]>;
    getAgentMetadata(
      ...args: IpcInvokeMap["agent-capabilities:get-agent-metadata"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-agent-metadata"]["result"]>;
    getCcrPresets(
      ...args: IpcInvokeMap["agent-capabilities:get-ccr-presets"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-ccr-presets"]["result"]>;
    getRegistry(
      ...args: IpcInvokeMap["agent-capabilities:get-registry"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-registry"]["result"]>;
    getResolvedModelList(
      ...args: IpcInvokeMap["agent-capabilities:get-resolved-model-list"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-resolved-model-list"]["result"]>;
    isAgentEnabled(
      ...args: IpcInvokeMap["agent-capabilities:is-agent-enabled"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:is-agent-enabled"]["result"]>;
  };
  app: {
    getVersionInfo(
      ...args: IpcInvokeMap["app:get-version-info"]["args"]
    ): Promise<IpcInvokeMap["app:get-version-info"]["result"]>;
  };
  cli: {
    getStatus(
      ...args: IpcInvokeMap["cli:get-status"]["args"]
    ): Promise<IpcInvokeMap["cli:get-status"]["result"]>;
    install(
      ...args: IpcInvokeMap["cli:install"]["args"]
    ): Promise<IpcInvokeMap["cli:install"]["result"]>;
  };
  clipboard: {
    readSelection(
      ...args: IpcInvokeMap["clipboard:read-selection"]["args"]
    ): Promise<IpcInvokeMap["clipboard:read-selection"]["result"]>;
    saveImage(
      ...args: IpcInvokeMap["clipboard:save-image"]["args"]
    ): Promise<IpcInvokeMap["clipboard:save-image"]["result"]>;
    thumbnailFromPath(
      ...args: IpcInvokeMap["clipboard:thumbnail-from-path"]["args"]
    ): Promise<IpcInvokeMap["clipboard:thumbnail-from-path"]["result"]>;
    writeImage(
      ...args: IpcInvokeMap["clipboard:write-image"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-image"]["result"]>;
    writeSelection(
      ...args: IpcInvokeMap["clipboard:write-selection"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-selection"]["result"]>;
    writeText(
      ...args: IpcInvokeMap["clipboard:write-text"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-text"]["result"]>;
  };
  commands: {
    execute(
      ...args: IpcInvokeMap["commands:execute"]["args"]
    ): Promise<IpcInvokeMap["commands:execute"]["result"]>;
    get(
      ...args: IpcInvokeMap["commands:get"]["args"]
    ): Promise<IpcInvokeMap["commands:get"]["result"]>;
    getBuilder(
      ...args: IpcInvokeMap["commands:get-builder"]["args"]
    ): Promise<IpcInvokeMap["commands:get-builder"]["result"]>;
    list(
      ...args: IpcInvokeMap["commands:list"]["args"]
    ): Promise<IpcInvokeMap["commands:list"]["result"]>;
  };
  connectivity: {
    getState(
      ...args: IpcInvokeMap["connectivity:get-state"]["args"]
    ): Promise<IpcInvokeMap["connectivity:get-state"]["result"]>;
  };
  copyTreeHistory: {
    getRecords(
      ...args: IpcInvokeMap["copy-tree-history:get-records"]["args"]
    ): Promise<IpcInvokeMap["copy-tree-history:get-records"]["result"]>;
  };
  devPreview: {
    ensure(
      ...args: IpcInvokeMap["dev-preview:ensure"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:ensure"]["result"]>;
    getAllSessions(
      ...args: IpcInvokeMap["dev-preview:get-all-sessions"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-all-sessions"]["result"]>;
    getByWorktree(
      ...args: IpcInvokeMap["dev-preview:get-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-by-worktree"]["result"]>;
    getDestructivePreviewMeta(
      ...args: IpcInvokeMap["dev-preview:get-destructive-preview-meta"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-destructive-preview-meta"]["result"]>;
    getDestructivePreviewSizes(
      ...args: IpcInvokeMap["dev-preview:get-destructive-preview-sizes"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-destructive-preview-sizes"]["result"]>;
    getDiagnostics(
      ...args: IpcInvokeMap["dev-preview:get-diagnostics"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-diagnostics"]["result"]>;
    getProxyPort(
      ...args: IpcInvokeMap["dev-preview:get-proxy-port"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-proxy-port"]["result"]>;
    getState(
      ...args: IpcInvokeMap["dev-preview:get-state"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-state"]["result"]>;
    mintBrowserToken(
      ...args: IpcInvokeMap["dev-preview:mint-browser-token"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:mint-browser-token"]["result"]>;
    reinstallAndRestart(
      ...args: IpcInvokeMap["dev-preview:reinstall-and-restart"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:reinstall-and-restart"]["result"]>;
    restart(
      ...args: IpcInvokeMap["dev-preview:restart"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart"]["result"]>;
    restartAndClearCache(
      ...args: IpcInvokeMap["dev-preview:restart-and-clear-cache"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart-and-clear-cache"]["result"]>;
    restartByWorktree(
      ...args: IpcInvokeMap["dev-preview:restart-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart-by-worktree"]["result"]>;
    stop(
      ...args: IpcInvokeMap["dev-preview:stop"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop"]["result"]>;
    stopByPanel(
      ...args: IpcInvokeMap["dev-preview:stop-by-panel"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop-by-panel"]["result"]>;
    stopByWorktree(
      ...args: IpcInvokeMap["dev-preview:stop-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop-by-worktree"]["result"]>;
    stopDevServerByWorktree(
      ...args: IpcInvokeMap["dev-preview:stop-dev-server-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop-dev-server-by-worktree"]["result"]>;
  };
  diffMedia: {
    readFileVersions(
      ...args: IpcInvokeMap["diff-media:read-file-versions"]["args"]
    ): Promise<IpcInvokeMap["diff-media:read-file-versions"]["result"]>;
  };
  eventInspector: {
    clear(
      ...args: IpcInvokeMap["event-inspector:clear"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:clear"]["result"]>;
    getEvents(
      ...args: IpcInvokeMap["event-inspector:get-events"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:get-events"]["result"]>;
    getFiltered(
      ...args: IpcInvokeMap["event-inspector:get-filtered"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:get-filtered"]["result"]>;
  };
  fileBrowser: {
    listDirectory(
      ...args: IpcInvokeMap["file-browser:list-directory"]["args"]
    ): Promise<IpcInvokeMap["file-browser:list-directory"]["result"]>;
    statPaths(
      ...args: IpcInvokeMap["file-browser:stat-paths"]["args"]
    ): Promise<IpcInvokeMap["file-browser:stat-paths"]["result"]>;
  };
  fileWatch: {
    fingerprint(
      ...args: IpcInvokeMap["file-watch:fingerprint"]["args"]
    ): Promise<IpcInvokeMap["file-watch:fingerprint"]["result"]>;
  };
  fleet: {
    getSnapshot(
      ...args: IpcInvokeMap["fleet:get-snapshot"]["args"]
    ): Promise<IpcInvokeMap["fleet:get-snapshot"]["result"]>;
  };
  forgeAudit: {
    clearLog(
      ...args: IpcInvokeMap["forge-audit:clear-log"]["args"]
    ): Promise<IpcInvokeMap["forge-audit:clear-log"]["result"]>;
    exportLog(
      ...args: IpcInvokeMap["forge-audit:export-log"]["args"]
    ): Promise<IpcInvokeMap["forge-audit:export-log"]["result"]>;
    getConfig(
      ...args: IpcInvokeMap["forge-audit:get-config"]["args"]
    ): Promise<IpcInvokeMap["forge-audit:get-config"]["result"]>;
    getRecords(
      ...args: IpcInvokeMap["forge-audit:get-records"]["args"]
    ): Promise<IpcInvokeMap["forge-audit:get-records"]["result"]>;
    getStats(
      ...args: IpcInvokeMap["forge-audit:get-stats"]["args"]
    ): Promise<IpcInvokeMap["forge-audit:get-stats"]["result"]>;
    setEnabled(
      ...args: IpcInvokeMap["forge-audit:set-enabled"]["args"]
    ): Promise<IpcInvokeMap["forge-audit:set-enabled"]["result"]>;
  };
  forgeRecommendation: {
    getDismissed(
      ...args: IpcInvokeMap["forge-recommendation:get-dismissed"]["args"]
    ): Promise<IpcInvokeMap["forge-recommendation:get-dismissed"]["result"]>;
    markDismissed(
      ...args: IpcInvokeMap["forge-recommendation:mark-dismissed"]["args"]
    ): Promise<IpcInvokeMap["forge-recommendation:mark-dismissed"]["result"]>;
  };
  gemini: {
    enableAlternateBuffer(
      ...args: IpcInvokeMap["gemini:enable-alternate-buffer"]["args"]
    ): Promise<IpcInvokeMap["gemini:enable-alternate-buffer"]["result"]>;
    getStatus(
      ...args: IpcInvokeMap["gemini:get-status"]["args"]
    ): Promise<IpcInvokeMap["gemini:get-status"]["result"]>;
  };
  help: {
    getFolderPath(
      ...args: IpcInvokeMap["help:get-folder-path"]["args"]
    ): Promise<IpcInvokeMap["help:get-folder-path"]["result"]>;
    getPinnedActionContext(
      ...args: IpcInvokeMap["help:get-pinned-action-context"]["args"]
    ): Promise<IpcInvokeMap["help:get-pinned-action-context"]["result"]>;
    markTerminal(
      ...args: IpcInvokeMap["help:mark-terminal"]["args"]
    ): Promise<IpcInvokeMap["help:mark-terminal"]["result"]>;
    openAssistantContentFolder(
      ...args: IpcInvokeMap["help:open-assistant-content-folder"]["args"]
    ): Promise<IpcInvokeMap["help:open-assistant-content-folder"]["result"]>;
    peekPendingHibernation(
      ...args: IpcInvokeMap["help:peek-pending-hibernation"]["args"]
    ): Promise<IpcInvokeMap["help:peek-pending-hibernation"]["result"]>;
    provisionSession(
      ...args: IpcInvokeMap["help:provision-session"]["args"]
    ): Promise<IpcInvokeMap["help:provision-session"]["result"]>;
    reportPanelOpen(
      ...args: IpcInvokeMap["help:report-panel-open"]["args"]
    ): Promise<IpcInvokeMap["help:report-panel-open"]["result"]>;
    restorePendingHibernation(
      ...args: IpcInvokeMap["help:restore-pending-hibernation"]["args"]
    ): Promise<IpcInvokeMap["help:restore-pending-hibernation"]["result"]>;
    revokeSession(
      ...args: IpcInvokeMap["help:revoke-session"]["args"]
    ): Promise<IpcInvokeMap["help:revoke-session"]["result"]>;
    takePendingHibernation(
      ...args: IpcInvokeMap["help:take-pending-hibernation"]["args"]
    ): Promise<IpcInvokeMap["help:take-pending-hibernation"]["result"]>;
    unmarkTerminal(
      ...args: IpcInvokeMap["help:unmark-terminal"]["args"]
    ): Promise<IpcInvokeMap["help:unmark-terminal"]["result"]>;
  };
  helpAssistant: {
    getLiveSessionStatus(
      ...args: IpcInvokeMap["help-assistant:get-live-session-status"]["args"]
    ): Promise<IpcInvokeMap["help-assistant:get-live-session-status"]["result"]>;
    getSettings(
      ...args: IpcInvokeMap["help-assistant:get-settings"]["args"]
    ): Promise<IpcInvokeMap["help-assistant:get-settings"]["result"]>;
    setSettings(
      ...args: IpcInvokeMap["help-assistant:set-settings"]["args"]
    ): Promise<IpcInvokeMap["help-assistant:set-settings"]["result"]>;
  };
  hibernation: {
    getConfig(
      ...args: IpcInvokeMap["hibernation:get-config"]["args"]
    ): Promise<IpcInvokeMap["hibernation:get-config"]["result"]>;
    updateConfig(
      ...args: IpcInvokeMap["hibernation:update-config"]["args"]
    ): Promise<IpcInvokeMap["hibernation:update-config"]["result"]>;
  };
  mcpServer: {
    clearAuditLog(
      ...args: IpcInvokeMap["mcp-server:clear-audit-log"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:clear-audit-log"]["result"]>;
    clearTurnOutcomeLog(
      ...args: IpcInvokeMap["mcp-server:clear-turn-outcome-log"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:clear-turn-outcome-log"]["result"]>;
    disconnectBearer(
      ...args: IpcInvokeMap["mcp-server:disconnect-bearer"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:disconnect-bearer"]["result"]>;
    exportAuditLog(
      ...args: IpcInvokeMap["mcp-server:export-audit-log"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:export-audit-log"]["result"]>;
    getAuditConfig(
      ...args: IpcInvokeMap["mcp-server:get-audit-config"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-audit-config"]["result"]>;
    getAuditRecords(
      ...args: IpcInvokeMap["mcp-server:get-audit-records"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-audit-records"]["result"]>;
    getAuditStats(
      ...args: IpcInvokeMap["mcp-server:get-audit-stats"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-audit-stats"]["result"]>;
    getConfigSnippet(
      ...args: IpcInvokeMap["mcp-server:get-config-snippet"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-config-snippet"]["result"]>;
    getLogRecords(
      ...args: IpcInvokeMap["mcp-server:get-log-records"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-log-records"]["result"]>;
    getRuntimeState(
      ...args: IpcInvokeMap["mcp-server:get-runtime-state"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-runtime-state"]["result"]>;
    getStatus(
      ...args: IpcInvokeMap["mcp-server:get-status"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-status"]["result"]>;
    getTurnOutcomeRecords(
      ...args: IpcInvokeMap["mcp-server:get-turn-outcome-records"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-turn-outcome-records"]["result"]>;
    issueGrant(
      ...args: IpcInvokeMap["mcp-server:issue-grant"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:issue-grant"]["result"]>;
    issueNativeGrant(
      ...args: IpcInvokeMap["mcp-server:issue-native-grant"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:issue-native-grant"]["result"]>;
    listActiveBearers(
      ...args: IpcInvokeMap["mcp-server:list-active-bearers"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:list-active-bearers"]["result"]>;
    listActiveClients(
      ...args: IpcInvokeMap["mcp-server:list-active-clients"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:list-active-clients"]["result"]>;
    listHelpSessionBearers(
      ...args: IpcInvokeMap["mcp-server:list-help-session-bearers"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:list-help-session-bearers"]["result"]>;
    resetDenialCounts(
      ...args: IpcInvokeMap["mcp-server:reset-denial-counts"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:reset-denial-counts"]["result"]>;
    revokeNativeGrant(
      ...args: IpcInvokeMap["mcp-server:revoke-native-grant"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:revoke-native-grant"]["result"]>;
    revokeSessionGrants(
      ...args: IpcInvokeMap["mcp-server:revoke-session-grants"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:revoke-session-grants"]["result"]>;
    rotateApiKey(
      ...args: IpcInvokeMap["mcp-server:rotate-api-key"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:rotate-api-key"]["result"]>;
    setAuditEnabled(
      ...args: IpcInvokeMap["mcp-server:set-audit-enabled"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-audit-enabled"]["result"]>;
    setAuditMaxRecords(
      ...args: IpcInvokeMap["mcp-server:set-audit-max-records"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-audit-max-records"]["result"]>;
    setEnabled(
      ...args: IpcInvokeMap["mcp-server:set-enabled"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-enabled"]["result"]>;
    setPort(
      ...args: IpcInvokeMap["mcp-server:set-port"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-port"]["result"]>;
    setSessionTier(
      ...args: IpcInvokeMap["mcp-server:set-session-tier"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-session-tier"]["result"]>;
  };
  menu: {
    showContext(
      ...args: IpcInvokeMap["menu:show-context"]["args"]
    ): Promise<IpcInvokeMap["menu:show-context"]["result"]>;
  };
  milestones: {
    get(
      ...args: IpcInvokeMap["milestones:get"]["args"]
    ): Promise<IpcInvokeMap["milestones:get"]["result"]>;
    markShown(
      ...args: IpcInvokeMap["milestones:mark-shown"]["args"]
    ): Promise<IpcInvokeMap["milestones:mark-shown"]["result"]>;
  };
  onboarding: {
    complete(
      ...args: IpcInvokeMap["onboarding:complete"]["args"]
    ): Promise<IpcInvokeMap["onboarding:complete"]["result"]>;
    dismissChecklist(
      ...args: IpcInvokeMap["onboarding:checklist-dismiss"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-dismiss"]["result"]>;
    dismissSetupBanner(
      ...args: IpcInvokeMap["onboarding:dismiss-setup-banner"]["args"]
    ): Promise<IpcInvokeMap["onboarding:dismiss-setup-banner"]["result"]>;
    dismissWelcomeCard(
      ...args: IpcInvokeMap["onboarding:dismiss-welcome-card"]["args"]
    ): Promise<IpcInvokeMap["onboarding:dismiss-welcome-card"]["result"]>;
    get(
      ...args: IpcInvokeMap["onboarding:get"]["args"]
    ): Promise<IpcInvokeMap["onboarding:get"]["result"]>;
    getChecklist(
      ...args: IpcInvokeMap["onboarding:checklist-get"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-get"]["result"]>;
    markAgentsSeen(
      ...args: IpcInvokeMap["onboarding:mark-agents-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-agents-seen"]["result"]>;
    markChecklistCelebrationShown(
      ...args: IpcInvokeMap["onboarding:checklist-mark-celebration-shown"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-mark-celebration-shown"]["result"]>;
    markChecklistItem(
      ...args: IpcInvokeMap["onboarding:checklist-mark-item"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-mark-item"]["result"]>;
    markNewsletterSeen(
      ...args: IpcInvokeMap["onboarding:mark-newsletter-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-newsletter-seen"]["result"]>;
    markToastSeen(
      ...args: IpcInvokeMap["onboarding:mark-toast-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-toast-seen"]["result"]>;
    markWaitingNudgeSeen(
      ...args: IpcInvokeMap["onboarding:mark-waiting-nudge-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-waiting-nudge-seen"]["result"]>;
    recordAgentFirstSeen(
      ...args: IpcInvokeMap["onboarding:record-agent-first-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:record-agent-first-seen"]["result"]>;
    setStep(
      ...args: IpcInvokeMap["onboarding:set-step"]["args"]
    ): Promise<IpcInvokeMap["onboarding:set-step"]["result"]>;
  };
  osDnd: {
    getState(
      ...args: IpcInvokeMap["os-dnd:get-state"]["args"]
    ): Promise<IpcInvokeMap["os-dnd:get-state"]["result"]>;
  };
  paintSurface: {
    applyWebglThresholds(
      ...args: IpcInvokeMap["paint-surface:apply-webgl-thresholds"]["args"]
    ): Promise<IpcInvokeMap["paint-surface:apply-webgl-thresholds"]["result"]>;
    createSurface(
      ...args: IpcInvokeMap["paint-surface:create"]["args"]
    ): Promise<IpcInvokeMap["paint-surface:create"]["result"]>;
    destroySurface(
      ...args: IpcInvokeMap["paint-surface:destroy"]["args"]
    ): Promise<IpcInvokeMap["paint-surface:destroy"]["result"]>;
    setSurfaceBounds(
      ...args: IpcInvokeMap["paint-surface:set-bounds"]["args"]
    ): Promise<IpcInvokeMap["paint-surface:set-bounds"]["result"]>;
  };
  plugin: {
    activateForView(
      ...args: IpcInvokeMap["plugin:activate-for-view"]["args"]
    ): Promise<IpcInvokeMap["plugin:activate-for-view"]["result"]>;
    cancelInstall(
      ...args: IpcInvokeMap["plugin:cancel-install"]["args"]
    ): Promise<IpcInvokeMap["plugin:cancel-install"]["result"]>;
    checkForUpdate(
      ...args: IpcInvokeMap["plugin:check-for-update"]["args"]
    ): Promise<IpcInvokeMap["plugin:check-for-update"]["result"]>;
    clearAuditLog(
      ...args: IpcInvokeMap["plugin:clear-audit-log"]["args"]
    ): Promise<IpcInvokeMap["plugin:clear-audit-log"]["result"]>;
    contextMenuItems(
      ...args: IpcInvokeMap["plugin:context-menu-items"]["args"]
    ): Promise<IpcInvokeMap["plugin:context-menu-items"]["result"]>;
    deleteSettingValue(
      ...args: IpcInvokeMap["plugin:settings-delete-value"]["args"]
    ): Promise<IpcInvokeMap["plugin:settings-delete-value"]["result"]>;
    exportAuditLog(
      ...args: IpcInvokeMap["plugin:export-audit-log"]["args"]
    ): Promise<IpcInvokeMap["plugin:export-audit-log"]["result"]>;
    getActions(
      ...args: IpcInvokeMap["plugin:actions-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-get"]["result"]>;
    getAgents(
      ...args: IpcInvokeMap["plugin:agents-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:agents-get"]["result"]>;
    getAuditConfig(
      ...args: IpcInvokeMap["plugin:get-audit-config"]["args"]
    ): Promise<IpcInvokeMap["plugin:get-audit-config"]["result"]>;
    getAuditRecords(
      ...args: IpcInvokeMap["plugin:get-audit-records"]["args"]
    ): Promise<IpcInvokeMap["plugin:get-audit-records"]["result"]>;
    getBackgroundUpdateCheckSettings(
      ...args: IpcInvokeMap["plugin:bg-update-check-settings-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:bg-update-check-settings-get"]["result"]>;
    getDecorations(
      ...args: IpcInvokeMap["plugin:file-decorations-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:file-decorations-get"]["result"]>;
    getDiagnosticsSnapshot(
      ...args: IpcInvokeMap["plugin:get-diagnostics-snapshot"]["args"]
    ): Promise<IpcInvokeMap["plugin:get-diagnostics-snapshot"]["result"]>;
    getForgeProviders(
      ...args: IpcInvokeMap["plugin:forge-providers-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:forge-providers-get"]["result"]>;
    getLatestBackgroundUpdateCheck(
      ...args: IpcInvokeMap["plugin:bg-update-check-latest"]["args"]
    ): Promise<IpcInvokeMap["plugin:bg-update-check-latest"]["result"]>;
    getPanelKinds(
      ...args: IpcInvokeMap["plugin:panel-kinds-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:panel-kinds-get"]["result"]>;
    getSettingValues(
      ...args: IpcInvokeMap["plugin:settings-get-values"]["args"]
    ): Promise<IpcInvokeMap["plugin:settings-get-values"]["result"]>;
    getWorktreeStatus(
      ...args: IpcInvokeMap["plugin:worktree-status-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:worktree-status-get"]["result"]>;
    install(
      ...args: IpcInvokeMap["plugin:install"]["args"]
    ): Promise<IpcInvokeMap["plugin:install"]["result"]>;
    installFromFile(
      ...args: IpcInvokeMap["plugin:install-from-file"]["args"]
    ): Promise<IpcInvokeMap["plugin:install-from-file"]["result"]>;
    installFromPath(
      ...args: IpcInvokeMap["plugin:install-from-path"]["args"]
    ): Promise<IpcInvokeMap["plugin:install-from-path"]["result"]>;
    installFromUrl(
      ...args: IpcInvokeMap["plugin:install-from-url"]["args"]
    ): Promise<IpcInvokeMap["plugin:install-from-url"]["result"]>;
    keybindings(
      ...args: IpcInvokeMap["plugin:keybindings"]["args"]
    ): Promise<IpcInvokeMap["plugin:keybindings"]["result"]>;
    list(
      ...args: IpcInvokeMap["plugin:list"]["args"]
    ): Promise<IpcInvokeMap["plugin:list"]["result"]>;
    pathExists(
      ...args: IpcInvokeMap["plugin:path-exists"]["args"]
    ): Promise<IpcInvokeMap["plugin:path-exists"]["result"]>;
    pickPath(
      ...args: IpcInvokeMap["plugin:pick-path"]["args"]
    ): Promise<IpcInvokeMap["plugin:pick-path"]["result"]>;
    registerAction(
      ...args: IpcInvokeMap["plugin:actions-register"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-register"]["result"]>;
    reportPanelLifecycle(
      ...args: IpcInvokeMap["plugin:report-panel-lifecycle"]["args"]
    ): Promise<IpcInvokeMap["plugin:report-panel-lifecycle"]["result"]>;
    revealSecretSetting(
      ...args: IpcInvokeMap["plugin:settings-reveal-secret"]["args"]
    ): Promise<IpcInvokeMap["plugin:settings-reveal-secret"]["result"]>;
    setAuditEnabled(
      ...args: IpcInvokeMap["plugin:set-audit-enabled"]["args"]
    ): Promise<IpcInvokeMap["plugin:set-audit-enabled"]["result"]>;
    setAuditMaxRecords(
      ...args: IpcInvokeMap["plugin:set-audit-max-records"]["args"]
    ): Promise<IpcInvokeMap["plugin:set-audit-max-records"]["result"]>;
    setBackgroundUpdateCheckSettings(
      ...args: IpcInvokeMap["plugin:bg-update-check-settings-set"]["args"]
    ): Promise<IpcInvokeMap["plugin:bg-update-check-settings-set"]["result"]>;
    setEnabled(
      ...args: IpcInvokeMap["plugin:set-enabled"]["args"]
    ): Promise<IpcInvokeMap["plugin:set-enabled"]["result"]>;
    setSettingValue(
      ...args: IpcInvokeMap["plugin:settings-set-value"]["args"]
    ): Promise<IpcInvokeMap["plugin:settings-set-value"]["result"]>;
    toolbarButtons(
      ...args: IpcInvokeMap["plugin:toolbar-buttons"]["args"]
    ): Promise<IpcInvokeMap["plugin:toolbar-buttons"]["result"]>;
    uninstall(
      ...args: IpcInvokeMap["plugin:uninstall"]["args"]
    ): Promise<IpcInvokeMap["plugin:uninstall"]["result"]>;
    unregisterAction(
      ...args: IpcInvokeMap["plugin:actions-unregister"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-unregister"]["result"]>;
    validateActionIds(
      ...args: IpcInvokeMap["plugin:validate-action-ids"]["args"]
    ): Promise<IpcInvokeMap["plugin:validate-action-ids"]["result"]>;
  };
  pluginCapability: {
    acknowledgeConsent(
      ...args: IpcInvokeMap["plugin-capability:acknowledge-consent"]["args"]
    ): Promise<IpcInvokeMap["plugin-capability:acknowledge-consent"]["result"]>;
    resolveConsent(
      ...args: IpcInvokeMap["plugin-capability:resolve-consent"]["args"]
    ): Promise<IpcInvokeMap["plugin-capability:resolve-consent"]["result"]>;
  };
  pluginMcp: {
    callTool(
      ...args: IpcInvokeMap["plugin-mcp:call-tool"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:call-tool"]["result"]>;
    getConfig(
      ...args: IpcInvokeMap["plugin-mcp:get-config"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:get-config"]["result"]>;
    getFullSchema(
      ...args: IpcInvokeMap["plugin-mcp:get-full-schema"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:get-full-schema"]["result"]>;
    getStderr(
      ...args: IpcInvokeMap["plugin-mcp:get-stderr"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:get-stderr"]["result"]>;
    list(
      ...args: IpcInvokeMap["plugin-mcp:list"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:list"]["result"]>;
    listTools(
      ...args: IpcInvokeMap["plugin-mcp:list-tools"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:list-tools"]["result"]>;
    resolveConsent(
      ...args: IpcInvokeMap["plugin-mcp:resolve-consent"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:resolve-consent"]["result"]>;
    restart(
      ...args: IpcInvokeMap["plugin-mcp:restart"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:restart"]["result"]>;
    setConfig(
      ...args: IpcInvokeMap["plugin-mcp:set-config"]["args"]
    ): Promise<IpcInvokeMap["plugin-mcp:set-config"]["result"]>;
  };
  pluginProcess: {
    list(
      ...args: IpcInvokeMap["plugin-process:list"]["args"]
    ): Promise<IpcInvokeMap["plugin-process:list"]["result"]>;
  };
  portal: {
    closeTab(
      ...args: IpcInvokeMap["portal:close-tab"]["args"]
    ): Promise<IpcInvokeMap["portal:close-tab"]["result"]>;
    create(
      ...args: IpcInvokeMap["portal:create"]["args"]
    ): Promise<IpcInvokeMap["portal:create"]["result"]>;
    goBack(
      ...args: IpcInvokeMap["portal:go-back"]["args"]
    ): Promise<IpcInvokeMap["portal:go-back"]["result"]>;
    goForward(
      ...args: IpcInvokeMap["portal:go-forward"]["args"]
    ): Promise<IpcInvokeMap["portal:go-forward"]["result"]>;
    hide(
      ...args: IpcInvokeMap["portal:hide"]["args"]
    ): Promise<IpcInvokeMap["portal:hide"]["result"]>;
    navigate(
      ...args: IpcInvokeMap["portal:navigate"]["args"]
    ): Promise<IpcInvokeMap["portal:navigate"]["result"]>;
    reload(
      ...args: IpcInvokeMap["portal:reload"]["args"]
    ): Promise<IpcInvokeMap["portal:reload"]["result"]>;
    resize(
      ...args: IpcInvokeMap["portal:resize"]["args"]
    ): Promise<IpcInvokeMap["portal:resize"]["result"]>;
    show(
      ...args: IpcInvokeMap["portal:show"]["args"]
    ): Promise<IpcInvokeMap["portal:show"]["result"]>;
    showNewTabMenu(
      ...args: IpcInvokeMap["portal:show-new-tab-menu"]["args"]
    ): Promise<IpcInvokeMap["portal:show-new-tab-menu"]["result"]>;
  };
  privacy: {
    clearCache(
      ...args: IpcInvokeMap["privacy:clear-cache"]["args"]
    ): Promise<IpcInvokeMap["privacy:clear-cache"]["result"]>;
    getDataFolderPath(
      ...args: IpcInvokeMap["privacy:get-data-folder-path"]["args"]
    ): Promise<IpcInvokeMap["privacy:get-data-folder-path"]["result"]>;
    getSettings(
      ...args: IpcInvokeMap["privacy:get-settings"]["args"]
    ): Promise<IpcInvokeMap["privacy:get-settings"]["result"]>;
    openDataFolder(
      ...args: IpcInvokeMap["privacy:open-data-folder"]["args"]
    ): Promise<IpcInvokeMap["privacy:open-data-folder"]["result"]>;
    resetAllData(
      ...args: IpcInvokeMap["privacy:reset-all-data"]["args"]
    ): Promise<IpcInvokeMap["privacy:reset-all-data"]["result"]>;
    setLogRetention(
      ...args: IpcInvokeMap["privacy:set-log-retention"]["args"]
    ): Promise<IpcInvokeMap["privacy:set-log-retention"]["result"]>;
    setTelemetryLevel(
      ...args: IpcInvokeMap["privacy:set-telemetry-level"]["args"]
    ): Promise<IpcInvokeMap["privacy:set-telemetry-level"]["result"]>;
  };
  projectHistory: {
    peek(
      ...args: IpcInvokeMap["project-history:peek"]["args"]
    ): Promise<IpcInvokeMap["project-history:peek"]["result"]>;
  };
  projectRelocation: {
    apply(
      ...args: IpcInvokeMap["project-relocation:apply"]["args"]
    ): Promise<IpcInvokeMap["project-relocation:apply"]["result"]>;
    preview(
      ...args: IpcInvokeMap["project-relocation:preview"]["args"]
    ): Promise<IpcInvokeMap["project-relocation:preview"]["result"]>;
  };
  remoteAccess: {
    approvePairing(
      ...args: IpcInvokeMap["remote-access:approve-pairing"]["args"]
    ): Promise<IpcInvokeMap["remote-access:approve-pairing"]["result"]>;
    disconnectAllDevices(
      ...args: IpcInvokeMap["remote-access:disconnect-all-devices"]["args"]
    ): Promise<IpcInvokeMap["remote-access:disconnect-all-devices"]["result"]>;
    disconnectDevice(
      ...args: IpcInvokeMap["remote-access:disconnect-device"]["args"]
    ): Promise<IpcInvokeMap["remote-access:disconnect-device"]["result"]>;
    getState(
      ...args: IpcInvokeMap["remote-access:get-state"]["args"]
    ): Promise<IpcInvokeMap["remote-access:get-state"]["result"]>;
    openPairingWindow(
      ...args: IpcInvokeMap["remote-access:open-pairing-window"]["args"]
    ): Promise<IpcInvokeMap["remote-access:open-pairing-window"]["result"]>;
    rejectPairing(
      ...args: IpcInvokeMap["remote-access:reject-pairing"]["args"]
    ): Promise<IpcInvokeMap["remote-access:reject-pairing"]["result"]>;
    revokeDevice(
      ...args: IpcInvokeMap["remote-access:revoke-device"]["args"]
    ): Promise<IpcInvokeMap["remote-access:revoke-device"]["result"]>;
    setDeviceCapabilities(
      ...args: IpcInvokeMap["remote-access:set-device-capabilities"]["args"]
    ): Promise<IpcInvokeMap["remote-access:set-device-capabilities"]["result"]>;
    updateConfig(
      ...args: IpcInvokeMap["remote-access:update-config"]["args"]
    ): Promise<IpcInvokeMap["remote-access:update-config"]["result"]>;
  };
  remotePanelProjection: {
    publish(
      ...args: IpcInvokeMap["remote-panel-projection:publish"]["args"]
    ): Promise<IpcInvokeMap["remote-panel-projection:publish"]["result"]>;
  };
  runHistory: {
    append(
      ...args: IpcInvokeMap["run-history:append"]["args"]
    ): Promise<IpcInvokeMap["run-history:append"]["result"]>;
    clear(
      ...args: IpcInvokeMap["run-history:clear"]["args"]
    ): Promise<IpcInvokeMap["run-history:clear"]["result"]>;
    getRecords(
      ...args: IpcInvokeMap["run-history:get-records"]["args"]
    ): Promise<IpcInvokeMap["run-history:get-records"]["result"]>;
  };
  sentry: {
    getConsentState(
      ...args: IpcInvokeMap["sentry:get-consent-state"]["args"]
    ): Promise<IpcInvokeMap["sentry:get-consent-state"]["result"]>;
  };
  shortcutHints: {
    getCounts(
      ...args: IpcInvokeMap["shortcut-hints:get-counts"]["args"]
    ): Promise<IpcInvokeMap["shortcut-hints:get-counts"]["result"]>;
    getHintedHover(
      ...args: IpcInvokeMap["shortcut-hints:get-hinted-hover"]["args"]
    ): Promise<IpcInvokeMap["shortcut-hints:get-hinted-hover"]["result"]>;
    incrementCount(
      ...args: IpcInvokeMap["shortcut-hints:increment-count"]["args"]
    ): Promise<IpcInvokeMap["shortcut-hints:increment-count"]["result"]>;
    setHintedHover(
      ...args: IpcInvokeMap["shortcut-hints:set-hinted-hover"]["args"]
    ): Promise<IpcInvokeMap["shortcut-hints:set-hinted-hover"]["result"]>;
  };
  slashCommands: {
    list(
      ...args: IpcInvokeMap["slash-commands:list"]["args"]
    ): Promise<IpcInvokeMap["slash-commands:list"]["result"]>;
  };
  system: {
    getMemorySnapshot(
      ...args: IpcInvokeMap["system:get-memory-snapshot"]["args"]
    ): Promise<IpcInvokeMap["system:get-memory-snapshot"]["result"]>;
    getResourceProfile(
      ...args: IpcInvokeMap["system:get-resource-profile"]["args"]
    ): Promise<IpcInvokeMap["system:get-resource-profile"]["result"]>;
    getResourceProfileSnapshot(
      ...args: IpcInvokeMap["system:get-resource-profile-snapshot"]["args"]
    ): Promise<IpcInvokeMap["system:get-resource-profile-snapshot"]["result"]>;
    getWhySlowSnapshot(
      ...args: IpcInvokeMap["system:get-why-slow-snapshot"]["args"]
    ): Promise<IpcInvokeMap["system:get-why-slow-snapshot"]["result"]>;
    reportTerminalRendererDiagnostics(
      ...args: IpcInvokeMap["system:report-terminal-renderer-diagnostics"]["args"]
    ): Promise<IpcInvokeMap["system:report-terminal-renderer-diagnostics"]["result"]>;
    requestInteractiveOverride(
      ...args: IpcInvokeMap["system:request-interactive-override"]["args"]
    ): Promise<IpcInvokeMap["system:request-interactive-override"]["result"]>;
  };
  systemSleep: {
    getAwakeTime(
      ...args: IpcInvokeMap["system-sleep:get-awake-time"]["args"]
    ): Promise<IpcInvokeMap["system-sleep:get-awake-time"]["result"]>;
    getMetrics(
      ...args: IpcInvokeMap["system-sleep:get-metrics"]["args"]
    ): Promise<IpcInvokeMap["system-sleep:get-metrics"]["result"]>;
    reset(
      ...args: IpcInvokeMap["system-sleep:reset"]["args"]
    ): Promise<IpcInvokeMap["system-sleep:reset"]["result"]>;
  };
  webview: {
    captureScreenshot(
      ...args: IpcInvokeMap["webview:capture-screenshot"]["args"]
    ): Promise<IpcInvokeMap["webview:capture-screenshot"]["result"]>;
    getNavigationHistory(
      ...args: IpcInvokeMap["webview:get-navigation-history"]["args"]
    ): Promise<IpcInvokeMap["webview:get-navigation-history"]["result"]>;
    goToHistoryIndex(
      ...args: IpcInvokeMap["webview:go-to-history-index"]["args"]
    ): Promise<IpcInvokeMap["webview:go-to-history-index"]["result"]>;
  };
  windowChrome: {
    setBannerSeverity(
      ...args: IpcInvokeMap["window-chrome:set-banner-severity"]["args"]
    ): Promise<IpcInvokeMap["window-chrome:set-banner-severity"]["result"]>;
  };
}
