// AUTO-GENERATED by scripts/codegen/ipc-renderer.mjs — do not edit by hand.
// Run `npm run codegen:ipc-renderer` to regenerate. Source: the
// `*_METHOD_CHANNELS` constants exported by each
// electron/ipc/handlers/*.preload.ts (files with
// `export const RENDERER_API_SKIP = true` are intentionally skipped).
// The hand-maintained ElectronAPI in api.ts extends this interface.

import type { IpcInvokeMap } from "./maps.js";

export interface GeneratedElectronAPI {
  accessibility: {
    getEnabled(
      ...args: IpcInvokeMap["accessibility:get-enabled"]["args"]
    ): Promise<IpcInvokeMap["accessibility:get-enabled"]["result"]>;
  };
  agentCapabilities: {
    getAgentIds(
      ...args: IpcInvokeMap["agent-capabilities:get-agent-ids"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-agent-ids"]["result"]>;
    getAgentMetadata(
      ...args: IpcInvokeMap["agent-capabilities:get-agent-metadata"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-agent-metadata"]["result"]>;
    getCcrPresets(
      ...args: IpcInvokeMap["agent-capabilities:get-ccr-presets"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-ccr-presets"]["result"]>;
    getRegistry(
      ...args: IpcInvokeMap["agent-capabilities:get-registry"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-registry"]["result"]>;
    getResolvedModelList(
      ...args: IpcInvokeMap["agent-capabilities:get-resolved-model-list"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:get-resolved-model-list"]["result"]>;
    isAgentEnabled(
      ...args: IpcInvokeMap["agent-capabilities:is-agent-enabled"]["args"]
    ): Promise<IpcInvokeMap["agent-capabilities:is-agent-enabled"]["result"]>;
  };
  cli: {
    getStatus(
      ...args: IpcInvokeMap["cli:get-status"]["args"]
    ): Promise<IpcInvokeMap["cli:get-status"]["result"]>;
    install(
      ...args: IpcInvokeMap["cli:install"]["args"]
    ): Promise<IpcInvokeMap["cli:install"]["result"]>;
  };
  clipboard: {
    readSelection(
      ...args: IpcInvokeMap["clipboard:read-selection"]["args"]
    ): Promise<IpcInvokeMap["clipboard:read-selection"]["result"]>;
    saveImage(
      ...args: IpcInvokeMap["clipboard:save-image"]["args"]
    ): Promise<IpcInvokeMap["clipboard:save-image"]["result"]>;
    thumbnailFromPath(
      ...args: IpcInvokeMap["clipboard:thumbnail-from-path"]["args"]
    ): Promise<IpcInvokeMap["clipboard:thumbnail-from-path"]["result"]>;
    writeImage(
      ...args: IpcInvokeMap["clipboard:write-image"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-image"]["result"]>;
    writeSelection(
      ...args: IpcInvokeMap["clipboard:write-selection"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-selection"]["result"]>;
    writeText(
      ...args: IpcInvokeMap["clipboard:write-text"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-text"]["result"]>;
  };
  commands: {
    execute(
      ...args: IpcInvokeMap["commands:execute"]["args"]
    ): Promise<IpcInvokeMap["commands:execute"]["result"]>;
    get(
      ...args: IpcInvokeMap["commands:get"]["args"]
    ): Promise<IpcInvokeMap["commands:get"]["result"]>;
    getBuilder(
      ...args: IpcInvokeMap["commands:get-builder"]["args"]
    ): Promise<IpcInvokeMap["commands:get-builder"]["result"]>;
    list(
      ...args: IpcInvokeMap["commands:list"]["args"]
    ): Promise<IpcInvokeMap["commands:list"]["result"]>;
  };
  connectivity: {
    getState(
      ...args: IpcInvokeMap["connectivity:get-state"]["args"]
    ): Promise<IpcInvokeMap["connectivity:get-state"]["result"]>;
  };
  devPreview: {
    ensure(
      ...args: IpcInvokeMap["dev-preview:ensure"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:ensure"]["result"]>;
    getByWorktree(
      ...args: IpcInvokeMap["dev-preview:get-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-by-worktree"]["result"]>;
    getDestructivePreviewMeta(
      ...args: IpcInvokeMap["dev-preview:get-destructive-preview-meta"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-destructive-preview-meta"]["result"]>;
    getDestructivePreviewSizes(
      ...args: IpcInvokeMap["dev-preview:get-destructive-preview-sizes"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-destructive-preview-sizes"]["result"]>;
    getState(
      ...args: IpcInvokeMap["dev-preview:get-state"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-state"]["result"]>;
    reinstallAndRestart(
      ...args: IpcInvokeMap["dev-preview:reinstall-and-restart"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:reinstall-and-restart"]["result"]>;
    restart(
      ...args: IpcInvokeMap["dev-preview:restart"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart"]["result"]>;
    restartAndClearCache(
      ...args: IpcInvokeMap["dev-preview:restart-and-clear-cache"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart-and-clear-cache"]["result"]>;
    restartByWorktree(
      ...args: IpcInvokeMap["dev-preview:restart-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart-by-worktree"]["result"]>;
    stop(
      ...args: IpcInvokeMap["dev-preview:stop"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop"]["result"]>;
    stopByPanel(
      ...args: IpcInvokeMap["dev-preview:stop-by-panel"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop-by-panel"]["result"]>;
    stopByWorktree(
      ...args: IpcInvokeMap["dev-preview:stop-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop-by-worktree"]["result"]>;
    stopDevServerByWorktree(
      ...args: IpcInvokeMap["dev-preview:stop-dev-server-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop-dev-server-by-worktree"]["result"]>;
  };
  eventInspector: {
    clear(
      ...args: IpcInvokeMap["event-inspector:clear"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:clear"]["result"]>;
    getEvents(
      ...args: IpcInvokeMap["event-inspector:get-events"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:get-events"]["result"]>;
    getFiltered(
      ...args: IpcInvokeMap["event-inspector:get-filtered"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:get-filtered"]["result"]>;
  };
  gemini: {
    enableAlternateBuffer(
      ...args: IpcInvokeMap["gemini:enable-alternate-buffer"]["args"]
    ): Promise<IpcInvokeMap["gemini:enable-alternate-buffer"]["result"]>;
    getStatus(
      ...args: IpcInvokeMap["gemini:get-status"]["args"]
    ): Promise<IpcInvokeMap["gemini:get-status"]["result"]>;
  };
  help: {
    getFolderPath(
      ...args: IpcInvokeMap["help:get-folder-path"]["args"]
    ): Promise<IpcInvokeMap["help:get-folder-path"]["result"]>;
    getPinnedActionContext(
      ...args: IpcInvokeMap["help:get-pinned-action-context"]["args"]
    ): Promise<IpcInvokeMap["help:get-pinned-action-context"]["result"]>;
    markTerminal(
      ...args: IpcInvokeMap["help:mark-terminal"]["args"]
    ): Promise<IpcInvokeMap["help:mark-terminal"]["result"]>;
    provisionSession(
      ...args: IpcInvokeMap["help:provision-session"]["args"]
    ): Promise<IpcInvokeMap["help:provision-session"]["result"]>;
    revokeSession(
      ...args: IpcInvokeMap["help:revoke-session"]["args"]
    ): Promise<IpcInvokeMap["help:revoke-session"]["result"]>;
    takePendingHibernation(
      ...args: IpcInvokeMap["help:take-pending-hibernation"]["args"]
    ): Promise<IpcInvokeMap["help:take-pending-hibernation"]["result"]>;
    unmarkTerminal(
      ...args: IpcInvokeMap["help:unmark-terminal"]["args"]
    ): Promise<IpcInvokeMap["help:unmark-terminal"]["result"]>;
  };
  helpAssistant: {
    getSettings(
      ...args: IpcInvokeMap["help-assistant:get-settings"]["args"]
    ): Promise<IpcInvokeMap["help-assistant:get-settings"]["result"]>;
    setSettings(
      ...args: IpcInvokeMap["help-assistant:set-settings"]["args"]
    ): Promise<IpcInvokeMap["help-assistant:set-settings"]["result"]>;
  };
  hibernation: {
    getConfig(
      ...args: IpcInvokeMap["hibernation:get-config"]["args"]
    ): Promise<IpcInvokeMap["hibernation:get-config"]["result"]>;
    updateConfig(
      ...args: IpcInvokeMap["hibernation:update-config"]["args"]
    ): Promise<IpcInvokeMap["hibernation:update-config"]["result"]>;
  };
  mcpServer: {
    clearAuditLog(
      ...args: IpcInvokeMap["mcp-server:clear-audit-log"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:clear-audit-log"]["result"]>;
    clearTurnOutcomeLog(
      ...args: IpcInvokeMap["mcp-server:clear-turn-outcome-log"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:clear-turn-outcome-log"]["result"]>;
    disconnectBearer(
      ...args: IpcInvokeMap["mcp-server:disconnect-bearer"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:disconnect-bearer"]["result"]>;
    exportAuditLog(
      ...args: IpcInvokeMap["mcp-server:export-audit-log"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:export-audit-log"]["result"]>;
    getAuditConfig(
      ...args: IpcInvokeMap["mcp-server:get-audit-config"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-audit-config"]["result"]>;
    getAuditRecords(
      ...args: IpcInvokeMap["mcp-server:get-audit-records"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-audit-records"]["result"]>;
    getAuditStats(
      ...args: IpcInvokeMap["mcp-server:get-audit-stats"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-audit-stats"]["result"]>;
    getConfigSnippet(
      ...args: IpcInvokeMap["mcp-server:get-config-snippet"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-config-snippet"]["result"]>;
    getRuntimeState(
      ...args: IpcInvokeMap["mcp-server:get-runtime-state"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-runtime-state"]["result"]>;
    getStatus(
      ...args: IpcInvokeMap["mcp-server:get-status"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-status"]["result"]>;
    getTurnOutcomeRecords(
      ...args: IpcInvokeMap["mcp-server:get-turn-outcome-records"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:get-turn-outcome-records"]["result"]>;
    issueGrant(
      ...args: IpcInvokeMap["mcp-server:issue-grant"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:issue-grant"]["result"]>;
    listActiveBearers(
      ...args: IpcInvokeMap["mcp-server:list-active-bearers"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:list-active-bearers"]["result"]>;
    listActiveClients(
      ...args: IpcInvokeMap["mcp-server:list-active-clients"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:list-active-clients"]["result"]>;
    revokeSessionGrants(
      ...args: IpcInvokeMap["mcp-server:revoke-session-grants"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:revoke-session-grants"]["result"]>;
    rotateApiKey(
      ...args: IpcInvokeMap["mcp-server:rotate-api-key"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:rotate-api-key"]["result"]>;
    setAuditEnabled(
      ...args: IpcInvokeMap["mcp-server:set-audit-enabled"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-audit-enabled"]["result"]>;
    setAuditMaxRecords(
      ...args: IpcInvokeMap["mcp-server:set-audit-max-records"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-audit-max-records"]["result"]>;
    setEnabled(
      ...args: IpcInvokeMap["mcp-server:set-enabled"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-enabled"]["result"]>;
    setPort(
      ...args: IpcInvokeMap["mcp-server:set-port"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-port"]["result"]>;
    setSessionTier(
      ...args: IpcInvokeMap["mcp-server:set-session-tier"]["args"]
    ): Promise<IpcInvokeMap["mcp-server:set-session-tier"]["result"]>;
  };
  menu: {
    showContext(
      ...args: IpcInvokeMap["menu:show-context"]["args"]
    ): Promise<IpcInvokeMap["menu:show-context"]["result"]>;
  };
  milestones: {
    get(
      ...args: IpcInvokeMap["milestones:get"]["args"]
    ): Promise<IpcInvokeMap["milestones:get"]["result"]>;
    markShown(
      ...args: IpcInvokeMap["milestones:mark-shown"]["args"]
    ): Promise<IpcInvokeMap["milestones:mark-shown"]["result"]>;
  };
  onboarding: {
    complete(
      ...args: IpcInvokeMap["onboarding:complete"]["args"]
    ): Promise<IpcInvokeMap["onboarding:complete"]["result"]>;
    dismissChecklist(
      ...args: IpcInvokeMap["onboarding:checklist-dismiss"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-dismiss"]["result"]>;
    dismissSetupBanner(
      ...args: IpcInvokeMap["onboarding:dismiss-setup-banner"]["args"]
    ): Promise<IpcInvokeMap["onboarding:dismiss-setup-banner"]["result"]>;
    dismissWelcomeCard(
      ...args: IpcInvokeMap["onboarding:dismiss-welcome-card"]["args"]
    ): Promise<IpcInvokeMap["onboarding:dismiss-welcome-card"]["result"]>;
    get(
      ...args: IpcInvokeMap["onboarding:get"]["args"]
    ): Promise<IpcInvokeMap["onboarding:get"]["result"]>;
    getChecklist(
      ...args: IpcInvokeMap["onboarding:checklist-get"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-get"]["result"]>;
    markAgentsSeen(
      ...args: IpcInvokeMap["onboarding:mark-agents-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-agents-seen"]["result"]>;
    markChecklistCelebrationShown(
      ...args: IpcInvokeMap["onboarding:checklist-mark-celebration-shown"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-mark-celebration-shown"]["result"]>;
    markChecklistItem(
      ...args: IpcInvokeMap["onboarding:checklist-mark-item"]["args"]
    ): Promise<IpcInvokeMap["onboarding:checklist-mark-item"]["result"]>;
    markNewsletterSeen(
      ...args: IpcInvokeMap["onboarding:mark-newsletter-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-newsletter-seen"]["result"]>;
    markToastSeen(
      ...args: IpcInvokeMap["onboarding:mark-toast-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-toast-seen"]["result"]>;
    markWaitingNudgeSeen(
      ...args: IpcInvokeMap["onboarding:mark-waiting-nudge-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:mark-waiting-nudge-seen"]["result"]>;
    recordAgentFirstSeen(
      ...args: IpcInvokeMap["onboarding:record-agent-first-seen"]["args"]
    ): Promise<IpcInvokeMap["onboarding:record-agent-first-seen"]["result"]>;
    setStep(
      ...args: IpcInvokeMap["onboarding:set-step"]["args"]
    ): Promise<IpcInvokeMap["onboarding:set-step"]["result"]>;
  };
  plugin: {
    getActions(
      ...args: IpcInvokeMap["plugin:actions-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-get"]["result"]>;
    getDecorations(
      ...args: IpcInvokeMap["plugin:file-decorations-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:file-decorations-get"]["result"]>;
    getForgeProviders(
      ...args: IpcInvokeMap["plugin:forge-providers-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:forge-providers-get"]["result"]>;
    getPanelKinds(
      ...args: IpcInvokeMap["plugin:panel-kinds-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:panel-kinds-get"]["result"]>;
    list(
      ...args: IpcInvokeMap["plugin:list"]["args"]
    ): Promise<IpcInvokeMap["plugin:list"]["result"]>;
    menuItems(
      ...args: IpcInvokeMap["plugin:menu-items"]["args"]
    ): Promise<IpcInvokeMap["plugin:menu-items"]["result"]>;
    registerAction(
      ...args: IpcInvokeMap["plugin:actions-register"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-register"]["result"]>;
    toolbarButtons(
      ...args: IpcInvokeMap["plugin:toolbar-buttons"]["args"]
    ): Promise<IpcInvokeMap["plugin:toolbar-buttons"]["result"]>;
    unregisterAction(
      ...args: IpcInvokeMap["plugin:actions-unregister"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-unregister"]["result"]>;
    validateActionIds(
      ...args: IpcInvokeMap["plugin:validate-action-ids"]["args"]
    ): Promise<IpcInvokeMap["plugin:validate-action-ids"]["result"]>;
  };
  portal: {
    closeTab(
      ...args: IpcInvokeMap["portal:close-tab"]["args"]
    ): Promise<IpcInvokeMap["portal:close-tab"]["result"]>;
    create(
      ...args: IpcInvokeMap["portal:create"]["args"]
    ): Promise<IpcInvokeMap["portal:create"]["result"]>;
    goBack(
      ...args: IpcInvokeMap["portal:go-back"]["args"]
    ): Promise<IpcInvokeMap["portal:go-back"]["result"]>;
    goForward(
      ...args: IpcInvokeMap["portal:go-forward"]["args"]
    ): Promise<IpcInvokeMap["portal:go-forward"]["result"]>;
    hide(
      ...args: IpcInvokeMap["portal:hide"]["args"]
    ): Promise<IpcInvokeMap["portal:hide"]["result"]>;
    navigate(
      ...args: IpcInvokeMap["portal:navigate"]["args"]
    ): Promise<IpcInvokeMap["portal:navigate"]["result"]>;
    reload(
      ...args: IpcInvokeMap["portal:reload"]["args"]
    ): Promise<IpcInvokeMap["portal:reload"]["result"]>;
    resize(
      ...args: IpcInvokeMap["portal:resize"]["args"]
    ): Promise<IpcInvokeMap["portal:resize"]["result"]>;
    show(
      ...args: IpcInvokeMap["portal:show"]["args"]
    ): Promise<IpcInvokeMap["portal:show"]["result"]>;
    showNewTabMenu(
      ...args: IpcInvokeMap["portal:show-new-tab-menu"]["args"]
    ): Promise<IpcInvokeMap["portal:show-new-tab-menu"]["result"]>;
  };
  privacy: {
    clearCache(
      ...args: IpcInvokeMap["privacy:clear-cache"]["args"]
    ): Promise<IpcInvokeMap["privacy:clear-cache"]["result"]>;
    getDataFolderPath(
      ...args: IpcInvokeMap["privacy:get-data-folder-path"]["args"]
    ): Promise<IpcInvokeMap["privacy:get-data-folder-path"]["result"]>;
    getSettings(
      ...args: IpcInvokeMap["privacy:get-settings"]["args"]
    ): Promise<IpcInvokeMap["privacy:get-settings"]["result"]>;
    openDataFolder(
      ...args: IpcInvokeMap["privacy:open-data-folder"]["args"]
    ): Promise<IpcInvokeMap["privacy:open-data-folder"]["result"]>;
    resetAllData(
      ...args: IpcInvokeMap["privacy:reset-all-data"]["args"]
    ): Promise<IpcInvokeMap["privacy:reset-all-data"]["result"]>;
    setLogRetention(
      ...args: IpcInvokeMap["privacy:set-log-retention"]["args"]
    ): Promise<IpcInvokeMap["privacy:set-log-retention"]["result"]>;
    setTelemetryLevel(
      ...args: IpcInvokeMap["privacy:set-telemetry-level"]["args"]
    ): Promise<IpcInvokeMap["privacy:set-telemetry-level"]["result"]>;
  };
  sentry: {
    getConsentState(
      ...args: IpcInvokeMap["sentry:get-consent-state"]["args"]
    ): Promise<IpcInvokeMap["sentry:get-consent-state"]["result"]>;
  };
  shortcutHints: {
    getCounts(
      ...args: IpcInvokeMap["shortcut-hints:get-counts"]["args"]
    ): Promise<IpcInvokeMap["shortcut-hints:get-counts"]["result"]>;
    incrementCount(
      ...args: IpcInvokeMap["shortcut-hints:increment-count"]["args"]
    ): Promise<IpcInvokeMap["shortcut-hints:increment-count"]["result"]>;
  };
  slashCommands: {
    list(
      ...args: IpcInvokeMap["slash-commands:list"]["args"]
    ): Promise<IpcInvokeMap["slash-commands:list"]["result"]>;
  };
  systemSleep: {
    getAwakeTime(
      ...args: IpcInvokeMap["system-sleep:get-awake-time"]["args"]
    ): Promise<IpcInvokeMap["system-sleep:get-awake-time"]["result"]>;
    getMetrics(
      ...args: IpcInvokeMap["system-sleep:get-metrics"]["args"]
    ): Promise<IpcInvokeMap["system-sleep:get-metrics"]["result"]>;
    reset(
      ...args: IpcInvokeMap["system-sleep:reset"]["args"]
    ): Promise<IpcInvokeMap["system-sleep:reset"]["result"]>;
  };
}
