// AUTO-GENERATED by scripts/codegen/ipc-map.mjs — do not edit by hand.
// Run `npm run codegen:ipc` to regenerate. Source: defineIpcNamespace blocks
// in electron/ipc/handlers/. The hand-maintained IpcInvokeMap in maps.ts
// extends this interface.

export interface GeneratedIpcInvokeMap {
  "accessibility:get-enabled": {
    args: [];
    result: boolean;
  };
  "agent-capabilities:get-agent-ids": {
    args: [];
    result: string[];
  };
  "agent-capabilities:get-agent-metadata": {
    args: [agentId: string];
    result: import("./agentCapabilities.js").AgentMetadata | null;
  };
  "agent-capabilities:get-ccr-presets": {
    args: [];
    result: import("../../config/agentRegistry.js").AgentPreset[];
  };
  "agent-capabilities:get-registry": {
    args: [];
    result: import("./agentCapabilities.js").AgentRegistry;
  };
  "agent-capabilities:get-resolved-model-list": {
    args: [agentId: string];
    result: import("./agentCapabilities.js").ResolvedModelCatalog | null;
  };
  "agent-capabilities:is-agent-enabled": {
    args: [agentId: string];
    result: boolean;
  };
  "agent-session:clear": {
    args: [payload: { worktreeId?: string | undefined }];
    result: void;
  };
  "agent-session:list": {
    args: [payload: { worktreeId?: string | undefined }];
    result: import("./agentSessionHistory.js").AgentSessionRecord[];
  };
  "agent-settings:set-global": {
    args: [value: boolean];
    result: import("../agentSettings.js").AgentSettings;
  };
  "app:clear-quarantined-panel": {
    args: [panelId: string];
    result: { cleared: boolean };
  };
  "app:dismiss-rosetta-warning": {
    args: [];
    result: void;
  };
  "app:get-version-info": {
    args: [];
    result: import("./app.js").AppVersionInfo;
  };
  "artifact:apply-patch": {
    args: [options: import("./agent.js").ApplyPatchOptions];
    result: import("./agent.js").ApplyPatchResult;
  };
  "artifact:save-to-file": {
    args: [options: import("./agent.js").SaveArtifactOptions];
    result: import("./agent.js").SaveArtifactResult | null;
  };
  "cli:get-status": {
    args: [];
    result: import("./system.js").CliInstallStatus;
  };
  "cli:install": {
    args: [];
    result: import("./system.js").CliInstallStatus;
  };
  "clipboard:read-selection": {
    args: [];
    result: { text: string };
  };
  "clipboard:save-image": {
    args: [];
    result: { filePath: string; thumbnailDataUrl: string };
  };
  "clipboard:thumbnail-from-path": {
    args: [filePath: string];
    result: { filePath: string; thumbnailDataUrl: string };
  };
  "clipboard:write-image": {
    args: [pngData: Uint8Array<ArrayBufferLike>];
    result: void;
  };
  "clipboard:write-selection": {
    args: [text: string];
    result: void;
  };
  "clipboard:write-text": {
    args: [text: string];
    result: void;
  };
  "commands:execute": {
    args: [payload: import("../commands.js").CommandExecutePayload];
    result: import("../commands.js").CommandResult<unknown>;
  };
  "commands:get": {
    args: [payload: import("../commands.js").CommandGetPayload];
    result: import("../commands.js").CommandManifestEntry | null;
  };
  "commands:get-builder": {
    args: [commandId: string];
    result: { steps: import("../commands.js").BuilderStep[] } | null;
  };
  "commands:list": {
    args: [context?: import("../commands.js").CommandContext | undefined];
    result: import("../commands.js").CommandManifestEntry[];
  };
  "connectivity:get-state": {
    args: [];
    result: import("./connectivity.js").ServiceConnectivitySnapshot;
  };
  "demo:annotate": {
    args: [payload: import("./demo.js").DemoAnnotatePayload];
    result: import("./demo.js").DemoAnnotateResult;
  };
  "demo:click": {
    args: [];
    result: void;
  };
  "demo:dismiss-annotation": {
    args: [payload: import("./demo.js").DemoDismissAnnotationPayload];
    result: void;
  };
  "demo:dismiss-spotlight": {
    args: [];
    result: void;
  };
  "demo:drag": {
    args: [payload: import("./demo.js").DemoDragPayload];
    result: void;
  };
  "demo:get-capture-status": {
    args: [];
    result: import("./demo.js").DemoCaptureStatus;
  };
  "demo:move-to": {
    args: [payload: import("./demo.js").DemoMoveToPayload];
    result: void;
  };
  "demo:move-to-selector": {
    args: [payload: import("./demo.js").DemoMoveToSelectorPayload];
    result: void;
  };
  "demo:pause": {
    args: [];
    result: void;
  };
  "demo:press-key": {
    args: [payload: import("./demo.js").DemoPressKeyPayload];
    result: void;
  };
  "demo:resume": {
    args: [];
    result: void;
  };
  "demo:screenshot": {
    args: [];
    result: import("./demo.js").DemoScreenshotResult;
  };
  "demo:scroll": {
    args: [payload: import("./demo.js").DemoScrollPayload];
    result: void;
  };
  "demo:send-key-to-terminal": {
    args: [payload: import("./demo.js").DemoSendKeyToTerminalPayload];
    result: void;
  };
  "demo:sleep": {
    args: [payload: import("./demo.js").DemoSleepPayload];
    result: void;
  };
  "demo:spotlight": {
    args: [payload: import("./demo.js").DemoSpotlightPayload];
    result: void;
  };
  "demo:start-capture": {
    args: [payload: import("./demo.js").DemoStartCapturePayload];
    result: import("./demo.js").DemoStartCaptureResult;
  };
  "demo:stop-capture": {
    args: [];
    result: import("./demo.js").DemoStopCaptureResult;
  };
  "demo:type": {
    args: [payload: import("./demo.js").DemoTypePayload];
    result: void;
  };
  "demo:type-in-terminal": {
    args: [payload: import("./demo.js").DemoTypeInTerminalPayload];
    result: void;
  };
  "demo:wait-for-idle": {
    args: [payload: import("./demo.js").DemoWaitForIdlePayload];
    result: void;
  };
  "demo:wait-for-selector": {
    args: [payload: import("./demo.js").DemoWaitForSelectorPayload];
    result: void;
  };
  "dev-preview:ensure": {
    args: [request: import("./devPreview.js").DevPreviewEnsureRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:get-all-sessions": {
    args: [];
    result: import("./devPreview.js").DevPreviewSessionState[];
  };
  "dev-preview:get-by-worktree": {
    args: [request: import("./devPreview.js").DevPreviewGetByWorktreeRequest];
    result: import("./devPreview.js").DevPreviewSessionState | null;
  };
  "dev-preview:get-destructive-preview-meta": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewDestructivePreviewMeta;
  };
  "dev-preview:get-destructive-preview-sizes": {
    args: [request: import("./devPreview.js").DevPreviewDestructivePreviewSizesRequest];
    result: import("./devPreview.js").DevPreviewDestructivePreviewSizes;
  };
  "dev-preview:get-proxy-port": {
    args: [];
    result: import("./devPreview.js").DevPreviewProxyInfo;
  };
  "dev-preview:get-state": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:mint-browser-token": {
    args: [__0: { panelId: string; projectId: string; redirectPath: string }];
    result: import("./devPreview.js").DevPreviewMintBrowserTokenResult;
  };
  "dev-preview:reinstall-and-restart": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:restart": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:restart-and-clear-cache": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:restart-by-worktree": {
    args: [request: import("./devPreview.js").DevPreviewRestartByWorktreeRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:stop": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:stop-by-panel": {
    args: [request: import("./devPreview.js").DevPreviewStopByPanelRequest];
    result: void;
  };
  "dev-preview:stop-by-worktree": {
    args: [request: import("./devPreview.js").DevPreviewStopByWorktreeRequest];
    result: void;
  };
  "dev-preview:stop-dev-server-by-worktree": {
    args: [request: import("./devPreview.js").DevPreviewStopDevServerByWorktreeRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "editor:discover": {
    args: [];
    result: import("../editor.js").DiscoveredEditor[];
  };
  "editor:get-config": {
    args: [projectId?: string | undefined];
    result: {
      preferredEditor: import("../editor.js").EditorConfig | null;
      discoveredEditors: import("../editor.js").DiscoveredEditor[];
    };
  };
  "editor:set-config": {
    args: [payload: import("../editor.js").EditorSetConfigPayload];
    result: void;
  };
  "event-inspector:clear": {
    args: [];
    result: void;
  };
  "event-inspector:get-events": {
    args: [];
    result: import("./events.js").EventRecord[];
  };
  "event-inspector:get-filtered": {
    args: [filters: import("./events.js").EventFilterOptions];
    result: import("./events.js").EventRecord[];
  };
  "forge-audit:clear-log": {
    args: [];
    result: void;
  };
  "forge-audit:export-log": {
    args: [records: import("./forge.js").ForgeAuditRecord[]];
    result: boolean;
  };
  "forge-audit:get-config": {
    args: [];
    result: { enabled: boolean; maxRecords: number };
  };
  "forge-audit:get-records": {
    args: [];
    result: import("./forge.js").ForgeAuditRecord[];
  };
  "forge-audit:get-stats": {
    args: [];
    result: import("./forge.js").ForgeAuditStats;
  };
  "forge-audit:set-enabled": {
    args: [enabled: boolean];
    result: { enabled: boolean; maxRecords: number };
  };
  "forge-recommendation:get-dismissed": {
    args: [];
    result: Record<string, true>;
  };
  "forge-recommendation:mark-dismissed": {
    args: [projectPath: string];
    result: void;
  };
  "forge:add-issue-comment": {
    args: [payload: { cwd: string; issueNumber: number; body: string }];
    result: import("../forge.js").IssueComment;
  };
  "forge:add-issue-label": {
    args: [payload: { cwd: string; issueNumber: number; label: string }];
    result: import("../forge.js").ForgeLabel[];
  };
  "forge:approve-pr": {
    args: [payload: { cwd: string; prNumber: number; body?: string | undefined }];
    result: void;
  };
  "forge:close-issue": {
    args: [
      payload: {
        cwd: string;
        issueNumber: number;
        stateReason?: import("../forge.js").IssueCloseReason | undefined;
      },
    ];
    result: import("../forge.js").Issue;
  };
  "forge:close-pr": {
    args: [payload: { cwd: string; prNumber: number }];
    result: void;
  };
  "forge:comment-on-pr": {
    args: [payload: { cwd: string; prNumber: number; body: string }];
    result: void;
  };
  "forge:convert-pr-to-draft": {
    args: [payload: { cwd: string; prNumber: number }];
    result: void;
  };
  "forge:create-issue": {
    args: [payload: { cwd: string; input: import("../forge.js").CreateIssueInput }];
    result: import("../forge.js").Issue;
  };
  "forge:create-pr": {
    args: [
      payload: {
        cwd: string;
        head: string;
        base: string;
        title: string;
        body?: string | undefined;
        draft?: boolean | undefined;
      },
    ];
    result: import("../forge.js").PR;
  };
  "forge:dismiss-review": {
    args: [payload: { cwd: string; prNumber: number; reviewId: number; message: string }];
    result: void;
  };
  "forge:edit-issue": {
    args: [
      payload: { cwd: string; issueNumber: number; input: import("../forge.js").EditIssueInput },
    ];
    result: import("../forge.js").Issue;
  };
  "forge:edit-pr": {
    args: [
      payload: {
        cwd: string;
        prNumber: number;
        title?: string | undefined;
        body?: string | undefined;
      },
    ];
    result: import("../forge.js").PR;
  };
  "forge:get-first-page-cache": {
    args: [payload: { cwd: string }];
    result: import("./forge.js").ForgeFirstPageCachePayload | null;
  };
  "forge:get-issue-tooltip": {
    args: [payload: { cwd: string; issueNumber: number }];
    result: import("../forge.js").IssueTooltipData | null;
  };
  "forge:get-issues-by-numbers": {
    args: [payload: { cwd: string; numbers: number[] }];
    result: import("../forge.js").Issue[];
  };
  "forge:get-pr-review-threads": {
    args: [payload: { cwd: string; prNumber: number }];
    result: import("../forge.js").ReviewThread[];
  };
  "forge:get-pr-tooltip": {
    args: [payload: { cwd: string; prNumber: number }];
    result: import("../forge.js").PRTooltipData | null;
  };
  "forge:get-project-health": {
    args: [payload: { cwd: string; bypassCache?: boolean | undefined }];
    result: import("./forge.js").ForgeProjectHealthPayload;
  };
  "forge:get-prs-by-numbers": {
    args: [payload: { cwd: string; numbers: number[] }];
    result: import("../forge.js").PR[];
  };
  "forge:get-rate-limit-details": {
    args: [payload: { cwd: string }];
    result: import("../forge.js").RateLimitDetails | null;
  };
  "forge:get-repo-stats": {
    args: [payload: { cwd: string; bypassCache?: boolean | undefined }];
    result: import("./forge.js").ForgeRepositoryStats;
  };
  "forge:get-token-health": {
    args: [payload: { providerId: string }];
    result: import("../forge.js").ForgeTokenHealthState | null;
  };
  "forge:mark-pr-ready-for-review": {
    args: [payload: { cwd: string; prNumber: number }];
    result: void;
  };
  "forge:merge-pr": {
    args: [
      payload: {
        cwd: string;
        prNumber: number;
        mergeMethod?: "merge" | "squash" | "rebase" | undefined;
        commitTitle?: string | undefined;
        commitMessage?: string | undefined;
      },
    ];
    result: void;
  };
  "forge:open-pr": {
    args: [payload: { cwd: string; prNumber: number }];
    result: void;
  };
  "forge:remove-issue-label": {
    args: [payload: { cwd: string; issueNumber: number; label: string }];
    result: import("../forge.js").ForgeLabel[];
  };
  "forge:reopen-issue": {
    args: [payload: { cwd: string; issueNumber: number }];
    result: import("../forge.js").Issue;
  };
  "forge:reopen-pr": {
    args: [payload: { cwd: string; prNumber: number }];
    result: void;
  };
  "forge:request-changes": {
    args: [payload: { cwd: string; prNumber: number; body: string }];
    result: void;
  };
  "forge:request-reviewers": {
    args: [
      payload: {
        cwd: string;
        prNumber: number;
        users?: string[] | undefined;
        teams?: string[] | undefined;
      },
    ];
    result: void;
  };
  "forge:resolve-author-avatar": {
    args: [payload: { cwd: string; email: string }];
    result: string | null;
  };
  "forge:unassign-issue": {
    args: [payload: { cwd: string; issueNumber: number; username: string }];
    result: void;
  };
  "gemini:enable-alternate-buffer": {
    args: [];
    result: { success: boolean };
  };
  "gemini:get-status": {
    args: [];
    result: { exists: boolean; alternateBufferEnabled: boolean; error?: string | undefined };
  };
  "global-env:get": {
    args: [];
    result: Record<string, string>;
  };
  "global-env:set": {
    args: [payload: { variables: Record<string, string> }];
    result: void;
  };
  "global:add-recipe": {
    args: [payload: { recipe: import("../project.js").TerminalRecipe }];
    result: void;
  };
  "global:delete-recipe": {
    args: [payload: { recipeId: string }];
    result: void;
  };
  "global:get-recipes": {
    args: [];
    result: import("../project.js").TerminalRecipe[];
  };
  "global:update-recipe": {
    args: [
      payload: {
        recipeId: string;
        updates: Partial<
          Omit<
            import("../project.js").TerminalRecipe,
            "id" | "worktreeId" | "projectId" | "createdAt"
          >
        >;
      },
    ];
    result: void;
  };
  "help-assistant:get-live-session-status": {
    args: [__1: { sessionId: string }];
    result: import("./api.js").HelpSessionLiveStatus;
  };
  "help-assistant:get-settings": {
    args: [];
    result: import("./api.js").HelpAssistantSettings;
  };
  "help-assistant:set-settings": {
    args: [patch: Partial<import("./api.js").HelpAssistantSettings>];
    result: void;
  };
  "help:get-folder-path": {
    args: [];
    result: string | null;
  };
  "help:get-pinned-action-context": {
    args: [sessionId: string];
    result: import("./help.js").PinnedActionContextSnapshot | null;
  };
  "help:mark-terminal": {
    args: [terminalId: string];
    result: void;
  };
  "help:provision-session": {
    args: [
      input: {
        projectId: string;
        projectPath: string;
        agentId: string;
        context?: import("../actions.js").ActionContext | undefined;
      },
    ];
    result: {
      sessionId: string;
      sessionPath: string;
      token: string;
      tier: import("./maps.js").HelpAssistantTier;
      mcpUrl: string | null;
      windowId: number;
    } | null;
  };
  "help:revoke-session": {
    args: [sessionId: string];
    result: void;
  };
  "help:take-pending-hibernation": {
    args: [projectId: string];
    result: { agentId: string; agentSessionId: string; cwd: string } | null;
  };
  "help:unmark-terminal": {
    args: [terminalId: string];
    result: void;
  };
  "hibernation:get-config": {
    args: [];
    result: import("./hibernation.js").HibernationConfig;
  };
  "hibernation:update-config": {
    args: [config: Partial<import("./hibernation.js").HibernationConfig>];
    result: import("./hibernation.js").HibernationConfig;
  };
  "idle-terminal:close-project": {
    args: [projectId: string];
    result: void;
  };
  "idle-terminal:dismiss-project": {
    args: [projectId: string];
    result: void;
  };
  "idle-terminal:get-config": {
    args: [];
    result: import("./idleTerminals.js").IdleTerminalNotifyConfig;
  };
  "idle-terminal:update-config": {
    args: [config: Partial<import("./idleTerminals.js").IdleTerminalNotifyConfig>];
    result: import("./idleTerminals.js").IdleTerminalNotifyConfig;
  };
  "mcp-server:clear-audit-log": {
    args: [];
    result: void;
  };
  "mcp-server:clear-turn-outcome-log": {
    args: [];
    result: void;
  };
  "mcp-server:disconnect-bearer": {
    args: [tokenHash: string];
    result: import("./mcpServer.js").DisconnectBearerResult;
  };
  "mcp-server:export-audit-log": {
    args: [records: import("./mcpServer.js").McpLogRecord[]];
    result: boolean;
  };
  "mcp-server:get-audit-config": {
    args: [];
    result: { enabled: boolean; maxRecords: number };
  };
  "mcp-server:get-audit-records": {
    args: [];
    result: import("./mcpServer.js").McpAuditRecord[];
  };
  "mcp-server:get-audit-stats": {
    args: [markSeen?: boolean | undefined];
    result: import("./mcpServer.js").McpAuditStats;
  };
  "mcp-server:get-config-snippet": {
    args: [];
    result: string;
  };
  "mcp-server:get-log-records": {
    args: [];
    result: import("./mcpServer.js").McpLogRecord[];
  };
  "mcp-server:get-runtime-state": {
    args: [];
    result: import("./mcpServer.js").McpRuntimeSnapshot;
  };
  "mcp-server:get-status": {
    args: [];
    result: import("./mcpServer.js").McpServerStatusSnapshot;
  };
  "mcp-server:get-turn-outcome-records": {
    args: [];
    result: import("./mcpServer.js").AssistantTurnRecord[];
  };
  "mcp-server:issue-grant": {
    args: [payload: { sessionId: string; toolId: string }];
    result: import("./mcpServer.js").McpIssueGrantResult;
  };
  "mcp-server:issue-native-grant": {
    args: [
      payload: {
        helpSessionId: string;
        allowedTools: string[];
        maxUses?: number | undefined;
        ttlMs?: number | undefined;
      },
    ];
    result: import("./mcpServer.js").McpIssueNativeGrantResult;
  };
  "mcp-server:list-active-bearers": {
    args: [];
    result: import("./mcpServer.js").ActiveBearerRecord[];
  };
  "mcp-server:list-active-clients": {
    args: [];
    result: import("./mcpServer.js").McpActiveClientInfo[];
  };
  "mcp-server:list-help-session-bearers": {
    args: [];
    result: import("./mcpServer.js").HelpSessionBearerRecord[];
  };
  "mcp-server:reset-denial-counts": {
    args: [payload: { sessionId: string }];
    result: void;
  };
  "mcp-server:revoke-native-grant": {
    args: [payload: { grantId: string }];
    result: import("./mcpServer.js").McpRevokeNativeGrantResult;
  };
  "mcp-server:revoke-session-grants": {
    args: [payload: { sessionId: string }];
    result: import("./mcpServer.js").McpRevokeSessionGrantsResult;
  };
  "mcp-server:rotate-api-key": {
    args: [];
    result: string;
  };
  "mcp-server:set-audit-enabled": {
    args: [enabled: boolean];
    result: { enabled: boolean; maxRecords: number };
  };
  "mcp-server:set-audit-max-records": {
    args: [max: number];
    result: { enabled: boolean; maxRecords: number };
  };
  "mcp-server:set-enabled": {
    args: [enabled: boolean];
    result: import("./mcpServer.js").McpServerStatusSnapshot;
  };
  "mcp-server:set-port": {
    args: [port: number | null];
    result: import("./mcpServer.js").McpServerStatusSnapshot;
  };
  "mcp-server:set-session-tier": {
    args: [payload: { sessionId: string; tier: "action" | "workbench" | "system" }];
    result: { sessionId: string; tier: "action" | "workbench" | "system" };
  };
  "menu:show-context": {
    args: [payload: import("../menu.js").ShowContextMenuPayload];
    result: string | null;
  };
  "milestones:get": {
    args: [];
    result: Record<string, boolean>;
  };
  "milestones:mark-shown": {
    args: [milestoneId: string];
    result: void;
  };
  "onboarding:checklist-dismiss": {
    args: [];
    result: void;
  };
  "onboarding:checklist-get": {
    args: [];
    result: import("./maps.js").ChecklistState;
  };
  "onboarding:checklist-mark-celebration-shown": {
    args: [];
    result: void;
  };
  "onboarding:checklist-mark-item": {
    args: [item: import("./maps.js").ChecklistItemId];
    result: void;
  };
  "onboarding:complete": {
    args: [];
    result: void;
  };
  "onboarding:dismiss-setup-banner": {
    args: [];
    result: import("./maps.js").OnboardingState;
  };
  "onboarding:dismiss-welcome-card": {
    args: [];
    result: import("./maps.js").OnboardingState;
  };
  "onboarding:get": {
    args: [];
    result: import("./maps.js").OnboardingState;
  };
  "onboarding:mark-agents-seen": {
    args: [agentIds: string[]];
    result: import("./maps.js").OnboardingState;
  };
  "onboarding:mark-newsletter-seen": {
    args: [];
    result: void;
  };
  "onboarding:mark-toast-seen": {
    args: [];
    result: void;
  };
  "onboarding:mark-waiting-nudge-seen": {
    args: [];
    result: void;
  };
  "onboarding:record-agent-first-seen": {
    args: [agentIds: string[]];
    result: import("./maps.js").OnboardingState;
  };
  "onboarding:set-step": {
    args: [arg: string | { step: string | null; agentSetupIds?: string[] | undefined } | null];
    result: void;
  };
  "os-dnd:get-state": {
    args: [];
    result: boolean | undefined;
  };
  "plugin-capability:resolve-consent": {
    args: [input: import("../pluginCapabilityConsent.js").PluginCapabilityResolveConsentInput];
    result: void;
  };
  "plugin-mcp:call-tool": {
    args: [input: import("./pluginMcp.js").PluginMcpCallToolInput];
    result: import("./pluginMcp.js").PluginMcpCallToolResult;
  };
  "plugin-mcp:get-config": {
    args: [];
    result: import("./pluginMcp.js").PluginMcpConfig;
  };
  "plugin-mcp:get-full-schema": {
    args: [key: import("./pluginMcp.js").PluginMcpToolKey];
    result: import("./pluginMcp.js").PluginMcpGetFullSchemaResult;
  };
  "plugin-mcp:get-stderr": {
    args: [key: import("./pluginMcp.js").PluginMcpServerKey];
    result: import("./pluginMcp.js").PluginMcpStderrResult;
  };
  "plugin-mcp:list": {
    args: [];
    result: import("./pluginMcp.js").PluginMcpServerInfo[];
  };
  "plugin-mcp:list-tools": {
    args: [key: import("./pluginMcp.js").PluginMcpServerKey];
    result: import("./pluginMcp.js").PluginMcpListToolsResult;
  };
  "plugin-mcp:resolve-consent": {
    args: [input: import("./pluginMcp.js").PluginMcpResolveConsentInput];
    result: void;
  };
  "plugin-mcp:restart": {
    args: [key: import("./pluginMcp.js").PluginMcpServerKey];
    result: void;
  };
  "plugin-mcp:set-config": {
    args: [config: import("./pluginMcp.js").PluginMcpConfig];
    result: import("./pluginMcp.js").PluginMcpConfig;
  };
  "plugin-process:list": {
    args: [pluginId?: string | undefined];
    result: import("./pluginProcess.js").PluginProcessInfo[];
  };
  "plugin:actions-get": {
    args: [];
    result: import("../plugin.js").PluginActionDescriptor[];
  };
  "plugin:actions-register": {
    args: [pluginId: string, contribution: import("../plugin.js").PluginActionContribution];
    result: void;
  };
  "plugin:actions-unregister": {
    args: [pluginId: string, actionId: string];
    result: void;
  };
  "plugin:activate-for-view": {
    args: [panelKindId: string];
    result: void;
  };
  "plugin:agents-get": {
    args: [];
    result: Record<string, import("../../config/agentRegistry.js").AgentConfig>;
  };
  "plugin:check-for-update": {
    args: [pluginId: string];
    result: import("../plugin.js").PluginCheckUpdateResult;
  };
  "plugin:clear-audit-log": {
    args: [];
    result: void;
  };
  "plugin:context-menu-items": {
    args: [];
    result: { pluginId: string; item: import("../plugin.js").ContextMenuContribution }[];
  };
  "plugin:export-audit-log": {
    args: [records: import("./pluginAudit.js").PluginActionAuditRecord[]];
    result: boolean;
  };
  "plugin:file-decorations-get": {
    args: [scope: string, paths: string[]];
    result: Record<string, import("../forge.js").FileDecoration>;
  };
  "plugin:forge-providers-get": {
    args: [];
    result: import("../forge.js").RegisteredForgeProvider[];
  };
  "plugin:get-audit-config": {
    args: [];
    result: import("./pluginAudit.js").PluginAuditConfig;
  };
  "plugin:get-audit-records": {
    args: [];
    result: import("./pluginAudit.js").PluginActionAuditRecord[];
  };
  "plugin:get-diagnostics-snapshot": {
    args: [];
    result: import("./pluginDiagnostics.js").PluginDiagnosticsSnapshot;
  };
  "plugin:install": {
    args: [archivePath: string, opts?: import("../plugin.js").PluginInstallOptions | undefined];
    result: import("../plugin.js").PluginInstallResult;
  };
  "plugin:install-from-file": {
    args: [];
    result: import("../plugin.js").PluginInstallResult;
  };
  "plugin:install-from-path": {
    args: [path: string];
    result: import("../plugin.js").PluginInstallResult;
  };
  "plugin:install-from-url": {
    args: [url: string];
    result: import("../plugin.js").PluginInstallResult;
  };
  "plugin:keybindings": {
    args: [];
    result: { pluginId: string; item: import("../plugin.js").KeybindingContribution }[];
  };
  "plugin:list": {
    args: [];
    result: import("../plugin.js").LoadedPluginInfo[];
  };
  "plugin:panel-kinds-get": {
    args: [];
    result: import("../../config/panelKindRegistry.js").PanelKindConfig[];
  };
  "plugin:path-exists": {
    args: [pluginId: string, targetPath: string];
    result: boolean;
  };
  "plugin:pick-path": {
    args: [pluginId: string, request: import("../plugin.js").PluginPickPathRequest];
    result: string | null;
  };
  "plugin:set-audit-enabled": {
    args: [enabled: boolean];
    result: import("./pluginAudit.js").PluginAuditConfig;
  };
  "plugin:set-audit-max-records": {
    args: [max: number];
    result: import("./pluginAudit.js").PluginAuditConfig;
  };
  "plugin:set-enabled": {
    args: [pluginId: string, enabled: boolean];
    result: void;
  };
  "plugin:settings-delete-value": {
    args: [
      pluginId: string,
      key: string,
      scope: import("../plugin.js").PluginSettingsScope,
      projectId: string | null,
    ];
    result: void;
  };
  "plugin:settings-get-values": {
    args: [
      pluginId: string,
      scope: import("../plugin.js").PluginSettingsScope,
      projectId: string | null,
    ];
    result: import("../plugin.js").PluginSettingsUiValues;
  };
  "plugin:settings-reveal-secret": {
    args: [
      pluginId: string,
      key: string,
      scope: import("../plugin.js").PluginSettingsScope,
      projectId: string | null,
    ];
    result: string | null;
  };
  "plugin:settings-set-value": {
    args: [
      pluginId: string,
      key: string,
      value: unknown,
      scope: import("../plugin.js").PluginSettingsScope,
      projectId: string | null,
    ];
    result: void;
  };
  "plugin:toolbar-buttons": {
    args: [];
    result: import("../../config/toolbarButtonRegistry.js").ToolbarButtonConfig[];
  };
  "plugin:uninstall": {
    args: [pluginId: string, deleteSettings?: boolean | undefined];
    result: void;
  };
  "plugin:validate-action-ids": {
    args: [actionIds: string[]];
    result: void;
  };
  "plugin:worktree-status-get": {
    args: [path: string];
    result: import("../plugin.js").PluginWorktreeStatus | null;
  };
  "portal:close-tab": {
    args: [payload: import("../portal.js").PortalCloseTabPayload];
    result: void;
  };
  "portal:create": {
    args: [payload: import("../portal.js").PortalCreatePayload];
    result: void;
  };
  "portal:go-back": {
    args: [tabId: string];
    result: boolean;
  };
  "portal:go-forward": {
    args: [tabId: string];
    result: boolean;
  };
  "portal:hide": {
    args: [];
    result: void;
  };
  "portal:navigate": {
    args: [payload: import("../portal.js").PortalNavigatePayload];
    result: void;
  };
  "portal:reload": {
    args: [tabId: string];
    result: void;
  };
  "portal:resize": {
    args: [bounds: import("../portal.js").PortalBounds];
    result: void;
  };
  "portal:show": {
    args: [payload: import("../portal.js").PortalShowPayload];
    result: void;
  };
  "portal:show-new-tab-menu": {
    args: [payload: import("../portal.js").PortalShowNewTabMenuPayload];
    result: void;
  };
  "privacy:clear-cache": {
    args: [];
    result: void;
  };
  "privacy:get-data-folder-path": {
    args: [];
    result: string;
  };
  "privacy:get-settings": {
    args: [];
    result: {
      telemetryLevel: "off" | "errors" | "full";
      logRetentionDays: 0 | 7 | 30 | 90;
      dataFolderPath: string;
    };
  };
  "privacy:open-data-folder": {
    args: [];
    result: void;
  };
  "privacy:reset-all-data": {
    args: [];
    result: void;
  };
  "privacy:set-log-retention": {
    args: [days: 0 | 7 | 30 | 90];
    result: void;
  };
  "privacy:set-telemetry-level": {
    args: [level: "off" | "errors" | "full"];
    result: void;
  };
  "project:clone-cancel": {
    args: [];
    result: void;
  };
  "project:clone-repo": {
    args: [options: import("./gitClone.js").CloneRepoOptions];
    result: import("./gitClone.js").CloneRepoResult;
  };
  "project:get-draft-inputs": {
    args: [projectId: string];
    result: Record<string, string>;
  };
  "project:get-focus-mode": {
    args: [projectId: string];
    result: {
      focusMode: boolean;
      focusPanelState: import("../project.js").FocusPanelState | undefined;
    };
  };
  "project:get-tab-groups": {
    args: [projectId: string];
    result: import("../panel.js").TabGroup[];
  };
  "project:get-terminal-sizes": {
    args: [projectId: string];
    result: Record<string, { cols: number; rows: number }>;
  };
  "project:get-terminals": {
    args: [projectId: string];
    result: import("../project.js").PanelSnapshot[];
  };
  "project:set-draft-inputs": {
    args: [payload: { projectId: string; draftInputs: Record<string, string> }];
    result: void;
  };
  "project:set-focus-mode": {
    args: [
      payload: {
        projectId: string;
        focusMode: boolean;
        focusPanelState?: { sidebarWidth: number; diagnosticsOpen: boolean } | undefined;
      },
    ];
    result: void;
  };
  "project:set-tab-groups": {
    args: [payload: { projectId: string; tabGroups: import("../panel.js").TabGroup[] }];
    result: void;
  };
  "project:set-terminal-sizes": {
    args: [
      payload: { projectId: string; terminalSizes: Record<string, { cols: number; rows: number }> },
    ];
    result: void;
  };
  "project:set-terminals": {
    args: [payload: { projectId: string; terminals: import("../project.js").PanelSnapshot[] }];
    result: void;
  };
  "run-history:append": {
    args: [input: import("./runHistory.js").RunHistoryAppendInput];
    result: void;
  };
  "run-history:clear": {
    args: [];
    result: void;
  };
  "run-history:get-records": {
    args: [];
    result: import("./runHistory.js").RunHistoryRecord[];
  };
  "scratch:create": {
    args: [name?: string | undefined];
    result: import("../scratch.js").Scratch;
  };
  "scratch:get-all": {
    args: [];
    result: import("../scratch.js").Scratch[];
  };
  "scratch:get-current": {
    args: [];
    result: import("../scratch.js").Scratch | null;
  };
  "scratch:remove": {
    args: [scratchId: string];
    result: void;
  };
  "scratch:save-as-project": {
    args: [scratchId: string];
    result: import("./scratch.js").ScratchSaveAsProjectResult;
  };
  "scratch:switch": {
    args: [scratchId: string];
    result: import("../scratch.js").Scratch;
  };
  "scratch:update": {
    args: [
      scratchId: string,
      updates: { name?: string | undefined; lastOpened?: number | undefined },
    ];
    result: import("../scratch.js").Scratch;
  };
  "sentry:get-consent-state": {
    args: [];
    result: { level: "off" | "errors" | "full"; hasSeenPrompt: boolean };
  };
  "shortcut-hints:get-counts": {
    args: [];
    result: Record<string, number>;
  };
  "shortcut-hints:get-hinted-hover": {
    args: [];
    result: string[];
  };
  "shortcut-hints:increment-count": {
    args: [actionId: string];
    result: void;
  };
  "shortcut-hints:set-hinted-hover": {
    args: [keys: string[]];
    result: void;
  };
  "slash-commands:list": {
    args: [payload: { agentId: string; projectPath?: string | undefined }];
    result: import("../slashCommands.js").SlashCommand[];
  };
  "system-sleep:get-awake-time": {
    args: [startTimestamp: number];
    result: number;
  };
  "system-sleep:get-metrics": {
    args: [];
    result: import("./systemSleep.js").SystemSleepMetrics;
  };
  "system-sleep:reset": {
    args: [];
    result: void;
  };
  "system:get-resource-profile": {
    args: [];
    result: import("../resourceProfile.js").ResourceProfilePayload;
  };
  "telemetry:get": {
    args: [];
    result: { enabled: boolean; hasSeenPrompt: boolean };
  };
  "telemetry:mark-prompt-shown": {
    args: [];
    result: void;
  };
  "telemetry:preview-get-state": {
    args: [];
    result: import("./telemetryPreview.js").TelemetryPreviewState;
  };
  "telemetry:preview-toggle": {
    args: [active: boolean];
    result: import("./telemetryPreview.js").TelemetryPreviewState;
  };
  "telemetry:set-enabled": {
    args: [enabled: boolean];
    result: void;
  };
  "telemetry:track": {
    args: [eventName: string, properties: Record<string, unknown>];
    result: void;
  };
  "terminal-config:get": {
    args: [];
    result: import("./config.js").TerminalConfig;
  };
  "terminal-config:set-cached-project-views": {
    args: [cachedProjectViews: number];
    result: void;
  };
  "terminal-config:set-color-scheme": {
    args: [schemeId: string];
    result: void;
  };
  "terminal-config:set-custom-schemes": {
    args: [schemes: unknown];
    result: void;
  };
  "terminal-config:set-font-family": {
    args: [fontFamily: string];
    result: void;
  };
  "terminal-config:set-font-size": {
    args: [fontSize: number];
    result: void;
  };
  "terminal-config:set-hybrid-input-auto-focus": {
    args: [enabled: boolean];
    result: void;
  };
  "terminal-config:set-hybrid-input-enabled": {
    args: [enabled: boolean];
    result: void;
  };
  "terminal-config:set-memory-leak-auto-restart": {
    args: [thresholdMb: number];
    result: void;
  };
  "terminal-config:set-memory-leak-detection": {
    args: [enabled: boolean];
    result: void;
  };
  "terminal-config:set-performance-mode": {
    args: [performanceMode: boolean];
    result: void;
  };
  "terminal-config:set-recent-scheme-ids": {
    args: [ids: unknown];
    result: void;
  };
  "terminal-config:set-resource-monitoring": {
    args: [enabled: boolean];
    result: void;
  };
  "terminal-config:set-screen-reader-mode": {
    args: [mode: "off" | "auto" | "on"];
    result: void;
  };
  "terminal-config:set-scrollback": {
    args: [scrollbackLines: number];
    result: void;
  };
  "terminal:force-resume": {
    args: [id: string];
    result: void;
  };
  "terminal:get-all": {
    args: [];
    result: import("./terminal.js").BackendTerminalInfo[];
  };
  "terminal:get-analysis-buffer": {
    args: [];
    result: SharedArrayBuffer | null;
  };
  "terminal:get-available": {
    args: [];
    result: import("./terminal.js").BackendTerminalInfo[];
  };
  "terminal:get-by-state": {
    args: [state: string];
    result: import("./terminal.js").BackendTerminalInfo[];
  };
  "terminal:get-for-project": {
    args: [projectId: string];
    result: import("./terminal.js").BackendTerminalInfo[];
  };
  "terminal:get-info": {
    args: [id: string];
    result: import("./terminal.js").TerminalInfoPayload;
  };
  "terminal:get-serialized-state": {
    args: [terminalId: string];
    result: string | null;
  };
  "terminal:get-serialized-states": {
    args: [terminalIds: string[]];
    result: Record<string, string | null>;
  };
  "terminal:get-shared-buffers": {
    args: [];
    result: { visualBuffers: SharedArrayBuffer[]; signalBuffer: SharedArrayBuffer | null };
  };
  "terminal:graceful-kill": {
    args: [id: string];
    result: string | null;
  };
  "terminal:kill": {
    args: [id: string];
    result: void;
  };
  "terminal:reconnect": {
    args: [terminalId: string];
    result: import("./terminal.js").TerminalReconnectResult;
  };
  "terminal:reconnect-bulk": {
    args: [terminalIds: string[]];
    result: Record<string, import("./terminal.js").TerminalReconnectResult>;
  };
  "terminal:replay-history": {
    args: [__0: { terminalId: string; maxLines: number }];
    result: { replayed: number };
  };
  "terminal:restart-service": {
    args: [];
    result: void;
  };
  "terminal:restore": {
    args: [id: string];
    result: boolean;
  };
  "terminal:search-semantic-buffers": {
    args: [query: string, isRegex: boolean];
    result: import("./terminal.js").SemanticSearchMatch[];
  };
  "terminal:spawn": {
    args: [
      validatedOptions: {
        cols: number;
        rows: number;
        id?: string | undefined;
        kind?: string | undefined;
        launchAgentId?: string | undefined;
        projectId?: string | undefined;
        cwd?: string | undefined;
        shell?: string | undefined;
        command?: string | undefined;
        env?: Record<string, string> | undefined;
        title?: string | undefined;
        titleMode?: "default" | "custom" | undefined;
        restore?: boolean | undefined;
        isEphemeral?: boolean | undefined;
        agentLaunchFlags?: string[] | undefined;
        agentModelId?: string | undefined;
        worktreeId?: string | undefined;
        agentPresetId?: string | undefined;
        agentPresetColor?: string | undefined;
        originalAgentPresetId?: string | undefined;
        actionContext?:
          | {
              projectId?: string | undefined;
              projectName?: string | undefined;
              projectPath?: string | undefined;
              activeWorktreeId?: string | undefined;
              activeWorktreeName?: string | undefined;
              activeWorktreePath?: string | undefined;
              activeWorktreeBranch?: string | undefined;
              activeWorktreeIsMain?: boolean | undefined;
              focusedWorktreeId?: string | undefined;
              focusedTerminalId?: string | undefined;
              focusedTerminalKind?: string | undefined;
              focusedTerminalType?: string | undefined;
              focusedTerminalTitle?: string | undefined;
              isSettingsOpen?: boolean | undefined;
              dispatchSource?:
                | "user"
                | "menu"
                | "keybinding"
                | "agent"
                | "context-menu"
                | "plugin"
                | undefined;
            }
          | undefined;
      },
    ];
    result: string;
  };
  "terminal:submit": {
    args: [id: string, text: string];
    result: void;
  };
  "terminal:trash": {
    args: [id: string];
    result: void;
  };
  "terminal:wake": {
    args: [id: string];
    result: { state: string | null; warnings?: string[] | undefined };
  };
  "watchdog:restart": {
    args: [];
    result: void;
  };
  "webview:get-navigation-history": {
    args: [webContentsId: number];
    result: {
      entries: import("../browser.js").BrowserNavigationHistoryEntry[];
      activeIndex: number;
      canGoBack: boolean;
      canGoForward: boolean;
    };
  };
  "webview:go-to-history-index": {
    args: [webContentsId: number, index: number];
    result: void;
  };
  "worktree-config:dismiss-wsl-banner": {
    args: [payload: { worktreeId: string }];
    result: void;
  };
  "worktree-config:get": {
    args: [];
    result: import("./worktree.js").WorktreeConfig;
  };
  "worktree-config:reprobe-wsl": {
    args: [payload: { worktreeId: string }];
    result: void;
  };
  "worktree-config:set-pattern": {
    args: [payload: { pattern: string }];
    result: import("./worktree.js").WorktreeConfig;
  };
  "worktree-config:set-wsl-git": {
    args: [payload: { worktreeId: string; enabled: boolean }];
    result: void;
  };
  "worktree:attach-issue": {
    args: [payload: import("./worktree.js").AttachIssuePayload];
    result: void;
  };
  "worktree:create": {
    args: [
      payload: {
        rootPath: string;
        options: {
          baseBranch: string;
          newBranch: string;
          path: string;
          fromRemote?: boolean | undefined;
          useExistingBranch?: boolean | undefined;
          provisionResource?: boolean | undefined;
          worktreeMode?: string | undefined;
          sourcePrNumber?: number | undefined;
          sourcePrTitle?: string | undefined;
          sourcePrUrl?: string | undefined;
          sourcePrState?: "merged" | "open" | "closed" | undefined;
          sourcePrLinkedIssueNumber?: number | undefined;
        };
      },
    ];
    result: string;
  };
  "worktree:delete": {
    args: [payload: import("./worktree.js").WorktreeDeletePayload];
    result: void;
  };
  "worktree:detach-issue": {
    args: [payload: import("./worktree.js").DetachIssuePayload];
    result: void;
  };
  "worktree:fetch-pr-branch": {
    args: [payload: { rootPath: string; prNumber: number; headRefName: string }];
    result: void;
  };
  "worktree:get-all": {
    args: [];
    result: import("../worktree.js").WorktreeState[];
  };
  "worktree:get-all-issue-associations": {
    args: [];
    result: Record<string, import("./worktree.js").IssueAssociation>;
  };
  "worktree:get-available-branch": {
    args: [payload: { rootPath: string; branchName: string }];
    result: string;
  };
  "worktree:get-default-path": {
    args: [payload: { rootPath: string; branchName: string }];
    result: string;
  };
  "worktree:get-recent-branches": {
    args: [payload: { rootPath: string }];
    result: string[];
  };
  "worktree:list-branches": {
    args: [payload: { rootPath: string }];
    result: import("../git.js").BranchInfo[];
  };
  "worktree:pr-refresh": {
    args: [];
    result: void;
  };
  "worktree:pr-status": {
    args: [];
    result: import("../workspace-host.js").PRServiceStatus | null;
  };
  "worktree:refresh": {
    args: [worktreeId?: string | undefined];
    result: void;
  };
  "worktree:restart-service": {
    args: [];
    result: void;
  };
  "worktree:retry-auth-fetch": {
    args: [];
    result: void;
  };
  "worktree:retry-project-load": {
    args: [];
    result: void;
  };
  "worktree:set-active": {
    args: [payload: { worktreeId: string }];
    result: void;
  };
}
