// AUTO-GENERATED by scripts/codegen/ipc-renderer.mjs — do not edit by hand.
// Run `npm run codegen:ipc-renderer` to regenerate. Source: the
// `*_METHOD_CHANNELS` constants exported by each
// electron/ipc/handlers/*.preload.ts (files with
// `export const RENDERER_API_SKIP = true` are intentionally skipped).
// The hand-maintained ElectronAPI in api.ts extends this interface.

import type { IpcInvokeMap } from "./maps.js";

export interface GeneratedElectronAPI {
  accessibility: {
    getEnabled(
      ...args: IpcInvokeMap["accessibility:get-enabled"]["args"]
    ): Promise<IpcInvokeMap["accessibility:get-enabled"]["result"]>;
  };
  clipboard: {
    readSelection(
      ...args: IpcInvokeMap["clipboard:read-selection"]["args"]
    ): Promise<IpcInvokeMap["clipboard:read-selection"]["result"]>;
    saveImage(
      ...args: IpcInvokeMap["clipboard:save-image"]["args"]
    ): Promise<IpcInvokeMap["clipboard:save-image"]["result"]>;
    thumbnailFromPath(
      ...args: IpcInvokeMap["clipboard:thumbnail-from-path"]["args"]
    ): Promise<IpcInvokeMap["clipboard:thumbnail-from-path"]["result"]>;
    writeImage(
      ...args: IpcInvokeMap["clipboard:write-image"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-image"]["result"]>;
    writeSelection(
      ...args: IpcInvokeMap["clipboard:write-selection"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-selection"]["result"]>;
    writeText(
      ...args: IpcInvokeMap["clipboard:write-text"]["args"]
    ): Promise<IpcInvokeMap["clipboard:write-text"]["result"]>;
  };
  commands: {
    execute(
      ...args: IpcInvokeMap["commands:execute"]["args"]
    ): Promise<IpcInvokeMap["commands:execute"]["result"]>;
    get(
      ...args: IpcInvokeMap["commands:get"]["args"]
    ): Promise<IpcInvokeMap["commands:get"]["result"]>;
    getBuilder(
      ...args: IpcInvokeMap["commands:get-builder"]["args"]
    ): Promise<IpcInvokeMap["commands:get-builder"]["result"]>;
    list(
      ...args: IpcInvokeMap["commands:list"]["args"]
    ): Promise<IpcInvokeMap["commands:list"]["result"]>;
  };
  devPreview: {
    ensure(
      ...args: IpcInvokeMap["dev-preview:ensure"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:ensure"]["result"]>;
    getByWorktree(
      ...args: IpcInvokeMap["dev-preview:get-by-worktree"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-by-worktree"]["result"]>;
    getState(
      ...args: IpcInvokeMap["dev-preview:get-state"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:get-state"]["result"]>;
    reinstallAndRestart(
      ...args: IpcInvokeMap["dev-preview:reinstall-and-restart"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:reinstall-and-restart"]["result"]>;
    restart(
      ...args: IpcInvokeMap["dev-preview:restart"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart"]["result"]>;
    restartAndClearCache(
      ...args: IpcInvokeMap["dev-preview:restart-and-clear-cache"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:restart-and-clear-cache"]["result"]>;
    stop(
      ...args: IpcInvokeMap["dev-preview:stop"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop"]["result"]>;
    stopByPanel(
      ...args: IpcInvokeMap["dev-preview:stop-by-panel"]["args"]
    ): Promise<IpcInvokeMap["dev-preview:stop-by-panel"]["result"]>;
  };
  eventInspector: {
    clear(
      ...args: IpcInvokeMap["event-inspector:clear"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:clear"]["result"]>;
    getEvents(
      ...args: IpcInvokeMap["event-inspector:get-events"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:get-events"]["result"]>;
    getFiltered(
      ...args: IpcInvokeMap["event-inspector:get-filtered"]["args"]
    ): Promise<IpcInvokeMap["event-inspector:get-filtered"]["result"]>;
  };
  help: {
    getFolderPath(
      ...args: IpcInvokeMap["help:get-folder-path"]["args"]
    ): Promise<IpcInvokeMap["help:get-folder-path"]["result"]>;
    markTerminal(
      ...args: IpcInvokeMap["help:mark-terminal"]["args"]
    ): Promise<IpcInvokeMap["help:mark-terminal"]["result"]>;
    provisionSession(
      ...args: IpcInvokeMap["help:provision-session"]["args"]
    ): Promise<IpcInvokeMap["help:provision-session"]["result"]>;
    revokeSession(
      ...args: IpcInvokeMap["help:revoke-session"]["args"]
    ): Promise<IpcInvokeMap["help:revoke-session"]["result"]>;
    takePendingHibernation(
      ...args: IpcInvokeMap["help:take-pending-hibernation"]["args"]
    ): Promise<IpcInvokeMap["help:take-pending-hibernation"]["result"]>;
    unmarkTerminal(
      ...args: IpcInvokeMap["help:unmark-terminal"]["args"]
    ): Promise<IpcInvokeMap["help:unmark-terminal"]["result"]>;
  };
  plugin: {
    getActions(
      ...args: IpcInvokeMap["plugin:actions-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-get"]["result"]>;
    getDecorations(
      ...args: IpcInvokeMap["plugin:file-decorations-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:file-decorations-get"]["result"]>;
    getForgeProviders(
      ...args: IpcInvokeMap["plugin:forge-providers-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:forge-providers-get"]["result"]>;
    getPanelKinds(
      ...args: IpcInvokeMap["plugin:panel-kinds-get"]["args"]
    ): Promise<IpcInvokeMap["plugin:panel-kinds-get"]["result"]>;
    list(
      ...args: IpcInvokeMap["plugin:list"]["args"]
    ): Promise<IpcInvokeMap["plugin:list"]["result"]>;
    menuItems(
      ...args: IpcInvokeMap["plugin:menu-items"]["args"]
    ): Promise<IpcInvokeMap["plugin:menu-items"]["result"]>;
    registerAction(
      ...args: IpcInvokeMap["plugin:actions-register"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-register"]["result"]>;
    toolbarButtons(
      ...args: IpcInvokeMap["plugin:toolbar-buttons"]["args"]
    ): Promise<IpcInvokeMap["plugin:toolbar-buttons"]["result"]>;
    unregisterAction(
      ...args: IpcInvokeMap["plugin:actions-unregister"]["args"]
    ): Promise<IpcInvokeMap["plugin:actions-unregister"]["result"]>;
    validateActionIds(
      ...args: IpcInvokeMap["plugin:validate-action-ids"]["args"]
    ): Promise<IpcInvokeMap["plugin:validate-action-ids"]["result"]>;
  };
  portal: {
    closeTab(
      ...args: IpcInvokeMap["portal:close-tab"]["args"]
    ): Promise<IpcInvokeMap["portal:close-tab"]["result"]>;
    create(
      ...args: IpcInvokeMap["portal:create"]["args"]
    ): Promise<IpcInvokeMap["portal:create"]["result"]>;
    goBack(
      ...args: IpcInvokeMap["portal:go-back"]["args"]
    ): Promise<IpcInvokeMap["portal:go-back"]["result"]>;
    goForward(
      ...args: IpcInvokeMap["portal:go-forward"]["args"]
    ): Promise<IpcInvokeMap["portal:go-forward"]["result"]>;
    hide(
      ...args: IpcInvokeMap["portal:hide"]["args"]
    ): Promise<IpcInvokeMap["portal:hide"]["result"]>;
    navigate(
      ...args: IpcInvokeMap["portal:navigate"]["args"]
    ): Promise<IpcInvokeMap["portal:navigate"]["result"]>;
    reload(
      ...args: IpcInvokeMap["portal:reload"]["args"]
    ): Promise<IpcInvokeMap["portal:reload"]["result"]>;
    resize(
      ...args: IpcInvokeMap["portal:resize"]["args"]
    ): Promise<IpcInvokeMap["portal:resize"]["result"]>;
    show(
      ...args: IpcInvokeMap["portal:show"]["args"]
    ): Promise<IpcInvokeMap["portal:show"]["result"]>;
    showNewTabMenu(
      ...args: IpcInvokeMap["portal:show-new-tab-menu"]["args"]
    ): Promise<IpcInvokeMap["portal:show-new-tab-menu"]["result"]>;
  };
  slashCommands: {
    list(
      ...args: IpcInvokeMap["slash-commands:list"]["args"]
    ): Promise<IpcInvokeMap["slash-commands:list"]["result"]>;
  };
}
