// AUTO-GENERATED by scripts/codegen/ipc-map.mjs — do not edit by hand.
// Run `npm run codegen:ipc` to regenerate. Source: defineIpcNamespace blocks
// in electron/ipc/handlers/. The hand-maintained IpcInvokeMap in maps.ts
// extends this interface.

export interface GeneratedIpcInvokeMap {
  "accessibility:get-enabled": {
    args: [];
    result: boolean;
  };
  "clipboard:read-selection": {
    args: [];
    result: { text: string };
  };
  "clipboard:save-image": {
    args: [];
    result: { filePath: string; thumbnailDataUrl: string };
  };
  "clipboard:thumbnail-from-path": {
    args: [filePath: string];
    result: { filePath: string; thumbnailDataUrl: string };
  };
  "clipboard:write-image": {
    args: [pngData: Uint8Array<ArrayBufferLike>];
    result: void;
  };
  "clipboard:write-selection": {
    args: [text: string];
    result: void;
  };
  "clipboard:write-text": {
    args: [text: string];
    result: void;
  };
  "commands:execute": {
    args: [payload: import("../commands.js").CommandExecutePayload];
    result: import("../commands.js").CommandResult<unknown>;
  };
  "commands:get": {
    args: [payload: import("../commands.js").CommandGetPayload];
    result: import("../commands.js").CommandManifestEntry | null;
  };
  "commands:get-builder": {
    args: [commandId: string];
    result: { steps: import("../commands.js").BuilderStep[] } | null;
  };
  "commands:list": {
    args: [context?: import("../commands.js").CommandContext | undefined];
    result: import("../commands.js").CommandManifestEntry[];
  };
  "demo:annotate": {
    args: [payload: import("./demo.js").DemoAnnotatePayload];
    result: import("./demo.js").DemoAnnotateResult;
  };
  "demo:click": {
    args: [];
    result: void;
  };
  "demo:dismiss-annotation": {
    args: [payload: import("./demo.js").DemoDismissAnnotationPayload];
    result: void;
  };
  "demo:dismiss-spotlight": {
    args: [];
    result: void;
  };
  "demo:drag": {
    args: [payload: import("./demo.js").DemoDragPayload];
    result: void;
  };
  "demo:get-capture-status": {
    args: [];
    result: import("./demo.js").DemoCaptureStatus;
  };
  "demo:move-to": {
    args: [payload: import("./demo.js").DemoMoveToPayload];
    result: void;
  };
  "demo:move-to-selector": {
    args: [payload: import("./demo.js").DemoMoveToSelectorPayload];
    result: void;
  };
  "demo:pause": {
    args: [];
    result: void;
  };
  "demo:press-key": {
    args: [payload: import("./demo.js").DemoPressKeyPayload];
    result: void;
  };
  "demo:resume": {
    args: [];
    result: void;
  };
  "demo:screenshot": {
    args: [];
    result: import("./demo.js").DemoScreenshotResult;
  };
  "demo:scroll": {
    args: [payload: import("./demo.js").DemoScrollPayload];
    result: void;
  };
  "demo:sleep": {
    args: [payload: import("./demo.js").DemoSleepPayload];
    result: void;
  };
  "demo:spotlight": {
    args: [payload: import("./demo.js").DemoSpotlightPayload];
    result: void;
  };
  "demo:start-capture": {
    args: [payload: import("./demo.js").DemoStartCapturePayload];
    result: import("./demo.js").DemoStartCaptureResult;
  };
  "demo:stop-capture": {
    args: [];
    result: import("./demo.js").DemoStopCaptureResult;
  };
  "demo:type": {
    args: [payload: import("./demo.js").DemoTypePayload];
    result: void;
  };
  "demo:wait-for-idle": {
    args: [payload: import("./demo.js").DemoWaitForIdlePayload];
    result: void;
  };
  "demo:wait-for-selector": {
    args: [payload: import("./demo.js").DemoWaitForSelectorPayload];
    result: void;
  };
  "dev-preview:ensure": {
    args: [request: import("./devPreview.js").DevPreviewEnsureRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:get-by-worktree": {
    args: [request: import("./devPreview.js").DevPreviewGetByWorktreeRequest];
    result: import("./devPreview.js").DevPreviewSessionState | null;
  };
  "dev-preview:get-state": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:reinstall-and-restart": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:restart": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:restart-and-clear-cache": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:stop": {
    args: [request: import("./devPreview.js").DevPreviewSessionRequest];
    result: import("./devPreview.js").DevPreviewSessionState;
  };
  "dev-preview:stop-by-panel": {
    args: [request: import("./devPreview.js").DevPreviewStopByPanelRequest];
    result: void;
  };
  "event-inspector:clear": {
    args: [];
    result: void;
  };
  "event-inspector:get-events": {
    args: [];
    result: import("./events.js").EventRecord[];
  };
  "event-inspector:get-filtered": {
    args: [filters: import("./events.js").EventFilterOptions];
    result: import("./events.js").EventRecord[];
  };
  "global-env:get": {
    args: [];
    result: Record<string, string>;
  };
  "global-env:set": {
    args: [payload: { variables: Record<string, string> }];
    result: void;
  };
  "help:get-folder-path": {
    args: [];
    result: string | null;
  };
  "help:mark-terminal": {
    args: [terminalId: string];
    result: void;
  };
  "help:provision-session": {
    args: [
      input: {
        projectId: string;
        projectPath: string;
        agentId: string;
        context?: import("../actions.js").ActionContext | undefined;
      },
    ];
    result: {
      sessionId: string;
      sessionPath: string;
      token: string;
      tier: import("./maps.js").HelpAssistantTier;
      mcpUrl: string | null;
      windowId: number;
    } | null;
  };
  "help:revoke-session": {
    args: [sessionId: string];
    result: void;
  };
  "help:take-pending-hibernation": {
    args: [projectId: string];
    result: { agentId: string; agentSessionId: string; cwd: string } | null;
  };
  "help:unmark-terminal": {
    args: [terminalId: string];
    result: void;
  };
  "plugin:actions-get": {
    args: [];
    result: import("../plugin.js").PluginActionDescriptor[];
  };
  "plugin:actions-register": {
    args: [pluginId: string, contribution: import("../plugin.js").PluginActionContribution];
    result: void;
  };
  "plugin:actions-unregister": {
    args: [pluginId: string, actionId: string];
    result: void;
  };
  "plugin:file-decorations-get": {
    args: [scope: string, paths: string[]];
    result: Record<string, import("../forge.js").FileDecoration>;
  };
  "plugin:forge-providers-get": {
    args: [];
    result: import("../forge.js").RegisteredForgeProvider[];
  };
  "plugin:list": {
    args: [];
    result: import("../plugin.js").LoadedPluginInfo[];
  };
  "plugin:menu-items": {
    args: [];
    result: { pluginId: string; item: import("../plugin.js").MenuItemContribution }[];
  };
  "plugin:panel-kinds-get": {
    args: [];
    result: import("../../config/panelKindRegistry.js").PanelKindConfig[];
  };
  "plugin:toolbar-buttons": {
    args: [];
    result: import("../../config/toolbarButtonRegistry.js").ToolbarButtonConfig[];
  };
  "plugin:validate-action-ids": {
    args: [actionIds: string[]];
    result: void;
  };
  "portal:close-tab": {
    args: [payload: import("../portal.js").PortalCloseTabPayload];
    result: void;
  };
  "portal:create": {
    args: [payload: import("../portal.js").PortalCreatePayload];
    result: void;
  };
  "portal:go-back": {
    args: [tabId: string];
    result: boolean;
  };
  "portal:go-forward": {
    args: [tabId: string];
    result: boolean;
  };
  "portal:hide": {
    args: [];
    result: void;
  };
  "portal:navigate": {
    args: [payload: import("../portal.js").PortalNavigatePayload];
    result: void;
  };
  "portal:reload": {
    args: [tabId: string];
    result: void;
  };
  "portal:resize": {
    args: [bounds: import("../portal.js").PortalBounds];
    result: void;
  };
  "portal:show": {
    args: [payload: import("../portal.js").PortalShowPayload];
    result: void;
  };
  "portal:show-new-tab-menu": {
    args: [payload: import("../portal.js").PortalShowNewTabMenuPayload];
    result: void;
  };
  "scratch:create": {
    args: [name?: string | undefined];
    result: import("../scratch.js").Scratch;
  };
  "scratch:get-all": {
    args: [];
    result: import("../scratch.js").Scratch[];
  };
  "scratch:get-current": {
    args: [];
    result: import("../scratch.js").Scratch | null;
  };
  "scratch:remove": {
    args: [scratchId: string];
    result: void;
  };
  "scratch:save-as-project": {
    args: [scratchId: string];
    result: import("./scratch.js").ScratchSaveAsProjectResult;
  };
  "scratch:switch": {
    args: [scratchId: string];
    result: import("../scratch.js").Scratch;
  };
  "scratch:update": {
    args: [
      scratchId: string,
      updates: { name?: string | undefined; lastOpened?: number | undefined },
    ];
    result: import("../scratch.js").Scratch;
  };
  "slash-commands:list": {
    args: [payload: import("../slashCommands.js").SlashCommandListRequest];
    result: import("../slashCommands.js").SlashCommand[];
  };
}
