import { AGENT_REGISTRY } from "@shared/config/agentRegistry";

import type { KeybindingConfig } from "./keybindingUtils";

export const DEFAULT_KEYBINDINGS: KeybindingConfig[] = [
  {
    actionId: "terminal.close",
    combo: "Cmd+W",
    scope: "global",
    priority: 10,
    description: "Close focused terminal",
    category: "Terminal",
  },
  {
    actionId: "nav.quickSwitcher",
    combo: "Cmd+P",
    scope: "global",
    priority: 0,
    description: "Open Quick Switcher",
    category: "Navigation",
  },
  {
    actionId: "nav.focusRegion.next",
    combo: "F6",
    scope: "global",
    priority: 5,
    description: "Focus next region",
    category: "Navigation",
  },
  {
    actionId: "nav.focusRegion.prev",
    combo: "Shift+F6",
    scope: "global",
    priority: 5,
    description: "Focus previous region",
    category: "Navigation",
  },
  {
    actionId: "terminal.duplicate",
    combo: "Cmd+T",
    scope: "global",
    priority: 0,
    description: "Duplicate focused panel",
    category: "Terminal",
  },
  {
    actionId: "terminal.new",
    combo: "Cmd+Alt+T",
    scope: "global",
    priority: 0,
    description: "New terminal",
    category: "Terminal",
  },
  {
    actionId: "panel.palette",
    combo: "Cmd+N",
    scope: "global",
    priority: 0,
    description: "Open panel palette",
    category: "Panels",
  },
  {
    actionId: "terminal.reopenLast",
    combo: "Cmd+Shift+T",
    scope: "global",
    priority: 0,
    description: "Reopen last closed terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.closeAll",
    combo: "Cmd+K Cmd+W",
    scope: "global",
    priority: 0,
    description: "Close all terminals",
    category: "Terminal",
  },
  {
    actionId: "terminal.killAll",
    combo: "Cmd+K Cmd+K",
    scope: "global",
    priority: 0,
    description: "End all terminals",
    category: "Terminal",
  },
  {
    actionId: "terminal.restartAll",
    combo: "Cmd+K Cmd+R",
    scope: "global",
    priority: 0,
    description: "Restart all terminals",
    category: "Terminal",
  },
  {
    actionId: "terminal.watch",
    combo: "Cmd+Shift+W",
    scope: "global",
    priority: 0,
    description: "Toggle watch on focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.scrollToLastActivity",
    combo: "Cmd+Alt+L",
    scope: "global",
    priority: 0,
    description: "Scroll to last activity",
    category: "Terminal",
  },
  {
    actionId: "terminal.stashInput",
    combo: "Cmd+Shift+S",
    scope: "global",
    priority: 0,
    description: "Stash current input",
    category: "Terminal",
  },
  {
    actionId: "terminal.popStash",
    combo: "Cmd+Shift+X",
    scope: "global",
    priority: 0,
    description: "Restore stashed input",
    category: "Terminal",
  },
  {
    actionId: "layout.undo",
    combo: "Cmd+Alt+Z",
    scope: "global",
    priority: 0,
    description: "Undo last layout change",
    category: "Layout",
  },
  {
    actionId: "layout.redo",
    combo: "Cmd+Alt+Shift+Z",
    scope: "global",
    priority: 0,
    description: "Redo last layout change",
    category: "Layout",
  },
  {
    actionId: "terminal.toggleDock",
    combo: "Cmd+Alt+M",
    scope: "global",
    priority: 0,
    description: "Toggle focused terminal dock state",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusDock",
    combo: "Cmd+Alt+D",
    scope: "global",
    priority: 0,
    description: "Focus active dock terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.toggleDockAll",
    combo: "Cmd+Alt+Shift+M",
    scope: "global",
    priority: 0,
    description: "Toggle all terminals dock state",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusNext",
    combo: "Ctrl+Tab",
    scope: "global",
    priority: 0,
    description: "Focus next terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusPrevious",
    combo: "Ctrl+Shift+Tab",
    scope: "global",
    priority: 0,
    description: "Focus previous terminal",
    category: "Terminal",
  },
  {
    actionId: "tab.next",
    combo: "Cmd+Shift+]",
    scope: "global",
    priority: 0,
    description: "Switch to next tab in focused panel",
    category: "Terminal",
  },
  {
    actionId: "tab.previous",
    combo: "Cmd+Shift+[",
    scope: "global",
    priority: 0,
    description: "Switch to previous tab in focused panel",
    category: "Terminal",
  },
  {
    actionId: "terminal.maximize",
    combo: "Ctrl+Shift+F",
    scope: "global",
    priority: 0,
    description: "Toggle maximize terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveLeft",
    combo: "Cmd+Shift+Alt+ArrowLeft",
    scope: "global",
    priority: 0,
    description: "Move terminal left in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveRight",
    combo: "Cmd+Shift+Alt+ArrowRight",
    scope: "global",
    priority: 0,
    description: "Move terminal right in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveUp",
    combo: "Cmd+Shift+Alt+ArrowUp",
    scope: "global",
    priority: 0,
    description: "Move terminal up in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveDown",
    combo: "Cmd+Shift+Alt+ArrowDown",
    scope: "global",
    priority: 0,
    description: "Move terminal down in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveToDock",
    combo: "Cmd+Shift+Alt+D",
    scope: "global",
    priority: 0,
    description: "Move terminal to dock",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveToGrid",
    combo: "Cmd+Shift+Alt+G",
    scope: "global",
    priority: 0,
    description: "Move terminal to grid",
    category: "Terminal",
  },
  {
    actionId: "agent.palette",
    combo: "Cmd+Shift+A",
    scope: "global",
    priority: 0,
    description: "Open quick switcher",
    category: "Agents",
  },
  ...Object.entries(AGENT_REGISTRY)
    .filter(([, config]) => config.shortcut)
    .map(([id, config]) => ({
      actionId: `agent.${id}`,
      combo: config.shortcut!.replace("Cmd/Ctrl", "Cmd"),
      scope: "global" as const,
      priority: 0,
      description: `Launch ${config.name} agent`,
      category: "Agents",
    })),
  {
    actionId: "agent.terminal",
    combo: "Cmd+Alt+N",
    scope: "global",
    priority: 0,
    description: "Launch terminal in current worktree",
    category: "Agents",
  },
  {
    actionId: "agent.focusNextWaiting",
    combo: "Cmd+Alt+/",
    scope: "global",
    priority: 0,
    description: "Jump to next waiting agent",
    category: "Agents",
  },
  {
    actionId: "agent.focusNextWorking",
    combo: "Cmd+Alt+.",
    scope: "global",
    priority: 0,
    description: "Jump to next working agent",
    category: "Agents",
  },
  {
    actionId: "agent.focusNextAgent",
    combo: "Cmd+Alt+K",
    scope: "global",
    priority: 0,
    description: "Cycle to next agent panel",
    category: "Agents",
  },
  {
    actionId: "agent.focusPreviousAgent",
    combo: "Cmd+Alt+J",
    scope: "global",
    priority: 0,
    description: "Cycle to previous agent panel",
    category: "Agents",
  },
  {
    actionId: "dock.focusNextWaiting",
    combo: "Cmd+Shift+/",
    scope: "global",
    priority: 0,
    description: "Jump to next waiting dock agent",
    category: "Agents",
  },
  {
    actionId: "terminal.inject",
    combo: "Cmd+Shift+I",
    scope: "global",
    priority: 0,
    description: "Inject context into focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.sendToAgent",
    combo: "Cmd+Shift+E",
    scope: "global",
    priority: 0,
    description: "Send selection to another terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.armDefault",
    combo: "Cmd+Shift+B",
    scope: "global",
    priority: 0,
    description: "Arm all eligible agents in the current worktree",
    category: "Terminal",
  },
  // Fleet quick-actions. These are registered at priority 5 so they beat
  // conflicting global bindings (panel.palette at Cmd+N) while the fleet
  // ribbon is visible. When nothing is armed, each action either no-ops
  // (accept/interrupt/restart/kill/trash) or falls through to the
  // conflicting binding (reject → panel.palette) so the UI stays intact.
  // fleet.interrupt has no combo here — it's driven by a custom Esc-Esc
  // double-tap handler in FleetArmingRibbon that avoids the escape-stack
  // LIFO collision a chord binding would cause.
  {
    actionId: "fleet.accept",
    combo: "Cmd+Y",
    scope: "global",
    priority: 5,
    description: "Accept all armed waiting agents",
    category: "Fleet",
  },
  {
    actionId: "fleet.reject",
    combo: "Cmd+N",
    scope: "global",
    priority: 5,
    description: "Reject all armed waiting agents",
    category: "Fleet",
  },
  {
    actionId: "fleet.restart",
    combo: "Cmd+Shift+R",
    scope: "global",
    priority: 5,
    description: "Restart all armed agents",
    category: "Fleet",
  },
  {
    actionId: "fleet.kill",
    combo: "Cmd+Shift+K",
    scope: "global",
    priority: 5,
    description: "Kill all armed terminals",
    category: "Fleet",
  },
  {
    actionId: "fleet.trash",
    combo: "Cmd+Shift+Backspace",
    scope: "global",
    priority: 5,
    description: "Trash all armed terminals",
    category: "Fleet",
  },
  {
    actionId: "terminal.focusFleetComposer",
    combo: "Cmd+Shift+F",
    scope: "global",
    priority: 0,
    description: "Focus the fleet broadcast composer",
    category: "Terminal",
  },
  {
    actionId: "fleet.deck.toggle",
    combo: "Cmd+Alt+Shift+B",
    scope: "global",
    priority: 0,
    description: "Toggle Fleet Deck",
    category: "Fleet",
  },
  // Directional terminal navigation (Ghostty-style: Cmd+Option+Arrow)
  {
    actionId: "terminal.focusUp",
    combo: "Cmd+Alt+ArrowUp",
    scope: "global",
    priority: 0,
    description: "Focus terminal above",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusDown",
    combo: "Cmd+Alt+ArrowDown",
    scope: "global",
    priority: 0,
    description: "Focus terminal below",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusLeft",
    combo: "Cmd+Alt+ArrowLeft",
    scope: "global",
    priority: 0,
    description: "Focus terminal to the left",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusRight",
    combo: "Cmd+Alt+ArrowRight",
    scope: "global",
    priority: 0,
    description: "Focus terminal to the right",
    category: "Terminal",
  },
  // Index-based terminal navigation (Cmd+1-9)
  {
    actionId: "terminal.focusIndex1",
    combo: "Cmd+1",
    scope: "global",
    priority: 0,
    description: "Focus terminal 1",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex2",
    combo: "Cmd+2",
    scope: "global",
    priority: 0,
    description: "Focus terminal 2",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex3",
    combo: "Cmd+3",
    scope: "global",
    priority: 0,
    description: "Focus terminal 3",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex4",
    combo: "Cmd+4",
    scope: "global",
    priority: 0,
    description: "Focus terminal 4",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex5",
    combo: "Cmd+5",
    scope: "global",
    priority: 0,
    description: "Focus terminal 5",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex6",
    combo: "Cmd+6",
    scope: "global",
    priority: 0,
    description: "Focus terminal 6",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex7",
    combo: "Cmd+7",
    scope: "global",
    priority: 0,
    description: "Focus terminal 7",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex8",
    combo: "Cmd+8",
    scope: "global",
    priority: 0,
    description: "Focus terminal 8",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex9",
    combo: "Cmd+9",
    scope: "global",
    priority: 0,
    description: "Focus terminal 9",
    category: "Terminal",
  },
  {
    actionId: "action.palette.open",
    combo: "Cmd+Shift+P",
    scope: "global",
    priority: 0,
    description: "Open command palette",
    category: "Navigation",
  },
  {
    actionId: "action.repeatLast",
    combo: "Cmd+Shift+.",
    scope: "global",
    priority: 0,
    description: "Repeat last action",
    category: "Navigation",
  },
  {
    actionId: "panel.diagnosticsLogs",
    combo: "Ctrl+Shift+L",
    scope: "global",
    priority: 0,
    description: "Open diagnostics dock to Logs tab",
    category: "Panels",
  },
  {
    actionId: "panel.diagnosticsEvents",
    combo: "Ctrl+Shift+E",
    scope: "global",
    priority: 0,
    description: "Open diagnostics dock to Events tab",
    category: "Panels",
  },
  {
    actionId: "panel.diagnosticsMessages",
    combo: "Ctrl+Shift+M",
    scope: "global",
    priority: 0,
    description: "Open diagnostics dock to Problems tab",
    category: "Panels",
  },
  {
    actionId: "panel.toggleDiagnostics",
    combo: "Cmd+Shift+D",
    scope: "global",
    priority: 0,
    description: "Toggle diagnostics dock",
    category: "Panels",
  },
  {
    actionId: "panel.togglePortal",
    combo: "Cmd+\\",
    scope: "global",
    priority: 0,
    description: "Toggle portal panel",
    category: "Panels",
  },
  {
    actionId: "portal.closeTab",
    combo: "Cmd+W",
    scope: "portal",
    priority: 20,
    description: "Close active portal tab",
    category: "Portal",
  },
  {
    actionId: "portal.nextTab",
    combo: "Ctrl+Tab",
    scope: "portal",
    priority: 20,
    description: "Next portal tab",
    category: "Portal",
  },
  {
    actionId: "portal.prevTab",
    combo: "Ctrl+Shift+Tab",
    scope: "portal",
    priority: 20,
    description: "Previous portal tab",
    category: "Portal",
  },
  {
    actionId: "portal.newTab",
    combo: "Cmd+T",
    scope: "portal",
    priority: 20,
    description: "New portal tab",
    category: "Portal",
  },
  {
    actionId: "nav.toggleSidebar",
    combo: "Cmd+B",
    scope: "global",
    priority: 0,
    description: "Toggle sidebar",
    category: "Navigation",
  },
  {
    actionId: "worktree.switch1",
    combo: "Cmd+Alt+1",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 1",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch2",
    combo: "Cmd+Alt+2",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 2",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch3",
    combo: "Cmd+Alt+3",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 3",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch4",
    combo: "Cmd+Alt+4",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 4",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch5",
    combo: "Cmd+Alt+5",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 5",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch6",
    combo: "Cmd+Alt+6",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 6",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch7",
    combo: "Cmd+Alt+7",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 7",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch8",
    combo: "Cmd+Alt+8",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 8",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch9",
    combo: "Cmd+Alt+9",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 9",
    category: "Worktrees",
  },
  {
    actionId: "worktree.next",
    combo: "Cmd+Alt+]",
    scope: "global",
    priority: 0,
    description: "Switch to next worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.previous",
    combo: "Cmd+Alt+[",
    scope: "global",
    priority: 0,
    description: "Switch to previous worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.openPalette",
    combo: "Cmd+K W",
    scope: "global",
    priority: 0,
    description: "Open worktree palette",
    category: "Worktrees",
  },
  {
    actionId: "worktree.overview",
    combo: "Cmd+Shift+O",
    scope: "global",
    priority: 0,
    description: "Toggle worktrees overview",
    category: "Worktrees",
  },
  {
    actionId: "project.switcherPalette",
    combo: "Cmd+Alt+P",
    scope: "global",
    priority: 0,
    description: "Open project switcher",
    category: "Project",
  },
  {
    actionId: "project.mruCycleOlder",
    combo: "Cmd+Alt+-",
    scope: "global",
    priority: 10,
    description: "Switch to previous project (hold to scrub older)",
    category: "Project",
  },
  {
    actionId: "project.mruCycleNewer",
    combo: "Cmd+Alt+=",
    scope: "global",
    priority: 10,
    description: "Switch to previous project (hold to scrub newer)",
    category: "Project",
  },
  {
    actionId: "notes.openPalette",
    combo: "Cmd+Shift+N",
    scope: "global",
    priority: 0,
    description: "Open notes palette",
    category: "Notes",
  },
  {
    actionId: "app.theme.pick",
    combo: "Cmd+K T",
    scope: "global",
    priority: 0,
    description: "Open theme palette",
    category: "App",
  },
  {
    actionId: "help.shortcuts",
    combo: "Cmd+K Cmd+S",
    scope: "global",
    priority: 0,
    description: "Open keyboard shortcuts reference",
    category: "Help",
  },
  {
    actionId: "help.shortcutsAlt",
    combo: "Cmd+/",
    scope: "global",
    priority: 0,
    description: "Open keyboard shortcuts reference",
    category: "Help",
  },
  {
    actionId: "help.launchAgent",
    combo: "Cmd+Shift+H",
    scope: "global",
    priority: 0,
    description: "Launch help agent",
    category: "Help",
  },
  {
    actionId: "app.newWindow",
    combo: "Cmd+Shift+Alt+N",
    scope: "global",
    priority: 0,
    description: "Open a new window",
    category: "System",
  },
  {
    actionId: "app.settings",
    combo: "Cmd+,",
    scope: "global",
    priority: 0,
    description: "Open settings",
    category: "System",
  },
  {
    actionId: "voiceInput.toggle",
    combo: "Cmd+Shift+V",
    scope: "global",
    priority: 0,
    description: "Toggle voice dictation",
    category: "Voice",
  },
  {
    actionId: "find.inFocusedPanel",
    combo: "Cmd+F",
    scope: "global",
    priority: 0,
    description: "Find in focused panel",
    category: "Search",
  },
  {
    actionId: "window.zoomIn",
    combo: "Cmd+=",
    scope: "global",
    priority: 0,
    description: "Zoom in",
    category: "View",
  },
  {
    actionId: "window.zoomOut",
    combo: "Cmd+-",
    scope: "global",
    priority: 0,
    description: "Zoom out",
    category: "View",
  },
  {
    actionId: "window.zoomReset",
    combo: "Cmd+0",
    scope: "global",
    priority: 0,
    description: "Reset zoom",
    category: "View",
  },
  {
    actionId: "modal.close",
    combo: "Escape",
    scope: "modal",
    priority: 10,
    description: "Close modal dialog",
    category: "System",
  },
  {
    actionId: "worktree.up",
    combo: "ArrowUp",
    scope: "worktreeList",
    priority: 5,
    description: "Move up in worktree list",
    category: "Worktrees",
  },
  {
    actionId: "worktree.down",
    combo: "ArrowDown",
    scope: "worktreeList",
    priority: 5,
    description: "Move down in worktree list",
    category: "Worktrees",
  },
  {
    actionId: "worktree.upVim",
    combo: "k",
    scope: "worktreeList",
    priority: 5,
    description: "Move up in worktree list (vim)",
    category: "Worktrees",
  },
  {
    actionId: "worktree.downVim",
    combo: "j",
    scope: "worktreeList",
    priority: 5,
    description: "Move down in worktree list (vim)",
    category: "Worktrees",
  },
  {
    actionId: "worktree.home",
    combo: "Home",
    scope: "worktreeList",
    priority: 5,
    description: "Go to first worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.end",
    combo: "End",
    scope: "worktreeList",
    priority: 5,
    description: "Go to last worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.select",
    combo: "Enter",
    scope: "worktreeList",
    priority: 5,
    description: "Select worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.selectSpace",
    combo: "Space",
    scope: "worktreeList",
    priority: 5,
    description: "Select worktree (space)",
    category: "Worktrees",
  },
  {
    actionId: "worktree.copyTree",
    combo: "Cmd+Shift+C",
    scope: "global",
    priority: 0,
    description: "Copy tree context for active worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.openEditor",
    combo: "e",
    scope: "worktreeList",
    priority: 5,
    description: "Open in editor",
    category: "Worktrees",
  },
  {
    actionId: "terminal.contextMenu",
    combo: "Shift+F10",
    scope: "global",
    priority: 0,
    description: "Open focused panel context menu",
    category: "Panels",
  },
  // Git write operations (Cmd+K chord prefix)
  {
    actionId: "git.stageAll",
    combo: "Cmd+K Cmd+A",
    scope: "global",
    priority: 0,
    description: "Stage all changes",
    category: "Git",
  },
  {
    actionId: "git.commit",
    combo: "Cmd+K Cmd+C",
    scope: "global",
    priority: 0,
    description: "Commit staged changes",
    category: "Git",
  },
  {
    actionId: "git.push",
    combo: "Cmd+K Cmd+P",
    scope: "global",
    priority: 0,
    description: "Push to remote",
    category: "Git",
  },
  // Worktree session bulk operations (Cmd+K chord prefix)
  {
    actionId: "worktree.sessions.minimizeAll",
    combo: "Cmd+K Cmd+M",
    scope: "global",
    priority: 0,
    description: "Dock all sessions in active worktree",
    category: "Worktree Sessions",
  },
  {
    actionId: "worktree.sessions.maximizeAll",
    combo: "Cmd+K Cmd+X",
    scope: "global",
    priority: 0,
    description: "Maximize all sessions in active worktree",
    category: "Worktree Sessions",
  },
  {
    actionId: "worktree.sessions.resetRenderers",
    combo: "Cmd+K Cmd+N",
    scope: "global",
    priority: 0,
    description: "Reset renderers for all sessions in active worktree",
    category: "Worktree Sessions",
  },
];
