import { describe, it, expect } from "vitest";
import type { File } from "gitdiff-parser";
import {
  getFilePath,
  estimateFileDiffBytes,
  shouldCollapseByDefault,
  DIFF_SOFT_COLLAPSE_BYTES,
} from "../diffCollapseUtils";

function makeFile(overrides: Partial<File> = {}): File {
  return {
    hunks: [],
    oldEndingNewLine: true,
    newEndingNewLine: true,
    oldMode: "100644",
    newMode: "100644",
    oldRevision: "abc123",
    newRevision: "def456",
    oldPath: "",
    newPath: "",
    type: "modify",
    ...overrides,
  };
}

describe("getFilePath", () => {
  it("returns newPath when set", () => {
    expect(getFilePath(makeFile({ newPath: "src/foo.ts" }))).toBe("src/foo.ts");
  });

  it("falls back to oldPath", () => {
    expect(getFilePath(makeFile({ oldPath: "src/bar.ts", newPath: "/dev/null" }))).toBe(
      "src/bar.ts"
    );
  });

  it("filters /dev/null", () => {
    expect(getFilePath(makeFile({ newPath: "/dev/null" }))).toBe("");
  });

  it("returns empty string when both paths are /dev/null", () => {
    expect(getFilePath(makeFile({ oldPath: "/dev/null", newPath: "/dev/null" }))).toBe("");
  });
});

describe("estimateFileDiffBytes", () => {
  it("returns 0 for empty hunks", () => {
    expect(estimateFileDiffBytes(makeFile({ hunks: [] }))).toBe(0);
  });

  it("sums hunk header and change content lengths", () => {
    const file = makeFile({
      hunks: [
        {
          content: "@@ -1,3 +1,3 @@\n",
          oldStart: 1,
          newStart: 1,
          oldLines: 3,
          newLines: 3,
          changes: [
            {
              type: "normal" as const,
              content: " line1\n",
              isNormal: true,
              oldLineNumber: 1,
              newLineNumber: 1,
            },
            { type: "insert" as const, content: "+new line\n", isInsert: true, lineNumber: 2 },
            { type: "delete" as const, content: "-old line\n", isDelete: true, lineNumber: 3 },
            {
              type: "normal" as const,
              content: " line3\n",
              isNormal: true,
              oldLineNumber: 3,
              newLineNumber: 3,
            },
          ],
        },
      ],
    });
    expect(estimateFileDiffBytes(file)).toBeGreaterThan(0);
  });

  it("handles undefined hunks", () => {
    expect(estimateFileDiffBytes(makeFile({ hunks: undefined as unknown as File["hunks"] }))).toBe(
      0
    );
  });
});

describe("shouldCollapseByDefault", () => {
  it("collapses generated file by default (path-based)", () => {
    const file = makeFile({ newPath: "package-lock.json" });
    const result = shouldCollapseByDefault(file);
    expect(result.collapse).toBe(true);
    expect(result.reason).toBe("generated");
  });

  it("collapses generated file by content marker (added file with DO NOT EDIT)", () => {
    const file = makeFile({
      type: "add",
      newPath: "proto/messages.go",
      hunks: [
        {
          content: "@@ -0,0 +1,5 @@\n",
          oldStart: 0,
          newStart: 1,
          oldLines: 0,
          newLines: 5,
          changes: [
            {
              type: "insert" as const,
              content: "// Code generated by protoc-gen-go. DO NOT EDIT.\n",
              isInsert: true,
              lineNumber: 1,
            },
          ],
        },
      ],
    });
    const result = shouldCollapseByDefault(file);
    expect(result.collapse).toBe(true);
    expect(result.reason).toBe("generated");
  });

  it("collapses large non-generated file", () => {
    let content = "";
    for (let i = 0; i < DIFF_SOFT_COLLAPSE_BYTES + 1; i++) {
      content += "x";
    }
    const file = makeFile({
      newPath: "src/large.ts",
      hunks: [
        {
          content: "hdr\n",
          oldStart: 1,
          newStart: 1,
          oldLines: 1,
          newLines: 1,
          changes: [
            {
              type: "normal" as const,
              content,
              isNormal: true,
              oldLineNumber: 1,
              newLineNumber: 1,
            },
          ],
        },
      ],
    });
    const result = shouldCollapseByDefault(file);
    expect(result.collapse).toBe(true);
    expect(result.reason).toBe("large");
  });

  it("does not collapse small normal file", () => {
    const file = makeFile({
      newPath: "src/small.ts",
      hunks: [
        {
          content: "@@ -1,1 +1,1 @@\n",
          oldStart: 1,
          newStart: 1,
          oldLines: 1,
          newLines: 1,
          changes: [
            {
              type: "normal" as const,
              content: "small\n",
              isNormal: true,
              oldLineNumber: 1,
              newLineNumber: 1,
            },
          ],
        },
      ],
    });
    const result = shouldCollapseByDefault(file);
    expect(result.collapse).toBe(false);
    expect(result.reason).toBeNull();
  });

  it("collapses generated file regardless of size", () => {
    const file = makeFile({
      newPath: "Cargo.lock",
      hunks: [
        {
          content: "@@ -1,1 +1,1 @@\n",
          oldStart: 1,
          newStart: 1,
          oldLines: 1,
          newLines: 1,
          changes: [
            {
              type: "normal" as const,
              content: "tiny\n",
              isNormal: true,
              oldLineNumber: 1,
              newLineNumber: 1,
            },
          ],
        },
      ],
    });
    const result = shouldCollapseByDefault(file);
    expect(result.collapse).toBe(true);
    expect(result.reason).toBe("generated");
  });

  it("does not collapse file exactly at threshold", () => {
    const content = "x".repeat(DIFF_SOFT_COLLAPSE_BYTES);
    const file = makeFile({
      newPath: "src/at-limit.ts",
      hunks: [
        {
          content: "",
          oldStart: 1,
          newStart: 1,
          oldLines: 1,
          newLines: 1,
          changes: [
            {
              type: "normal" as const,
              content,
              isNormal: true,
              oldLineNumber: 1,
              newLineNumber: 1,
            },
          ],
        },
      ],
    });
    const result = shouldCollapseByDefault(file);
    expect(result.collapse).toBe(false);
  });

  it("collapses file one byte over threshold", () => {
    const content = "x".repeat(DIFF_SOFT_COLLAPSE_BYTES + 1);
    const file = makeFile({
      newPath: "src/over-limit.ts",
      hunks: [
        {
          content: "",
          oldStart: 1,
          newStart: 1,
          oldLines: 1,
          newLines: 1,
          changes: [
            {
              type: "normal" as const,
              content,
              isNormal: true,
              oldLineNumber: 1,
              newLineNumber: 1,
            },
          ],
        },
      ],
    });
    const result = shouldCollapseByDefault(file);
    expect(result.collapse).toBe(true);
    expect(result.reason).toBe("large");
  });

  it("estimates exact byte count for known content", () => {
    const file = makeFile({
      newPath: "src/exact.ts",
      hunks: [
        {
          content: "@@ -1,1 +1,1 @@\n",
          oldStart: 1,
          newStart: 1,
          oldLines: 1,
          newLines: 1,
          changes: [
            {
              type: "normal" as const,
              content: "hello\n",
              isNormal: true,
              oldLineNumber: 1,
              newLineNumber: 1,
            },
          ],
        },
      ],
    });
    const hdrLen = "@@ -1,1 +1,1 @@\n".length;
    const changeLen = "hello\n".length;
    expect(estimateFileDiffBytes(file)).toBe(hdrLen + changeLen);
  });
});
