import type { KeybindingConfig } from "../types/keybinding.js";

// The single source of truth for shipped keybindings, shared cross-process:
// the renderer KeybindingService seeds from it (src/services/defaultKeybindings.ts
// wrapper) and the main process derives native menu accelerators from it
// (electron/services/menuAccelerators.ts) so the menu can never drift from
// what the keyboard actually does.
const CORE_KEYBINDINGS: KeybindingConfig[] = [
  {
    actionId: "terminal.close",
    combo: "Cmd+W",
    scope: "global",
    priority: 10,
    description: "Close focused terminal",
    category: "Terminal",
  },
  {
    actionId: "nav.quickSwitcher",
    combo: "Cmd+P",
    scope: "global",
    priority: 0,
    description: "Open Quick Switcher",
    category: "Navigation",
  },
  {
    actionId: "nav.focusRegion.next",
    combo: "F6",
    scope: "global",
    priority: 5,
    description: "Focus next region",
    category: "Navigation",
  },
  {
    actionId: "nav.focusRegion.prev",
    combo: "Shift+F6",
    scope: "global",
    priority: 5,
    description: "Focus previous region",
    category: "Navigation",
  },
  {
    actionId: "terminal.duplicate",
    combo: "Cmd+T",
    scope: "global",
    priority: 0,
    description: "Duplicate focused panel",
    category: "Terminal",
  },
  {
    actionId: "terminal.new",
    combo: "Cmd+Alt+T",
    scope: "global",
    priority: 0,
    description: "New terminal",
    category: "Terminal",
  },
  {
    actionId: "panel.palette",
    combo: "Cmd+N",
    scope: "global",
    priority: 0,
    description: "Open panel palette",
    category: "Panels",
  },
  {
    actionId: "terminal.reopenLast",
    combo: "Cmd+Shift+T",
    scope: "global",
    priority: 0,
    description: "Reopen last closed terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.resumeSessions",
    combo: "Cmd+K Cmd+R",
    scope: "global",
    priority: 0,
    description: "Resume a closed session",
    category: "Terminal",
  },
  {
    actionId: "terminal.closeAll",
    combo: "Cmd+K Cmd+W",
    scope: "global",
    priority: 0,
    description: "Close all terminals",
    category: "Terminal",
  },
  {
    actionId: "terminal.restartAll",
    combo: "Cmd+K Cmd+A",
    scope: "global",
    priority: 0,
    description: "Restart all terminals",
    category: "Terminal",
  },
  {
    actionId: "terminal.kill",
    combo: "Cmd+K Cmd+Q",
    scope: "global",
    priority: 0,
    description: "Kill focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.restart",
    combo: "Cmd+K Cmd+E",
    scope: "global",
    priority: 0,
    description: "Restart focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.forceResume",
    combo: "Cmd+K Cmd+U",
    scope: "global",
    priority: 0,
    description: "Force resume focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.redraw",
    combo: "Cmd+K Cmd+D",
    scope: "global",
    priority: 0,
    description: "Redraw focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.rename",
    combo: "Cmd+K Cmd+L",
    scope: "global",
    priority: 0,
    description: "Rename focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.watch",
    combo: "Cmd+Shift+W",
    scope: "global",
    priority: 0,
    description: "Toggle watch on focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.scrollToLastActivity",
    combo: "Cmd+Alt+L",
    scope: "global",
    priority: 0,
    description: "Scroll to last activity",
    category: "Terminal",
  },
  {
    actionId: "terminal.stashInput",
    combo: "Cmd+Shift+S",
    scope: "global",
    priority: 0,
    description: "Stash current input",
    category: "Terminal",
  },
  {
    actionId: "terminal.popStash",
    combo: "Cmd+Shift+X",
    scope: "global",
    priority: 0,
    description: "Restore stashed input",
    category: "Terminal",
  },
  {
    actionId: "layout.undo",
    combo: "Cmd+Alt+Z",
    scope: "global",
    priority: 0,
    description: "Undo last layout change",
    category: "Layout",
  },
  {
    actionId: "layout.redo",
    combo: "Cmd+Alt+Shift+Z",
    scope: "global",
    priority: 0,
    description: "Redo last layout change",
    category: "Layout",
  },
  {
    actionId: "terminal.toggleDock",
    combo: "Cmd+Alt+M",
    scope: "global",
    priority: 0,
    description: "Toggle focused terminal dock state",
    category: "Terminal",
  },
  {
    actionId: "terminal.toggleDockAll",
    combo: "Cmd+Alt+Shift+M",
    scope: "global",
    priority: 0,
    description: "Toggle all terminals dock state",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusNext",
    combo: "Ctrl+Tab",
    scope: "global",
    priority: 0,
    description: "Focus next terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusPrevious",
    combo: "Ctrl+Shift+Tab",
    scope: "global",
    priority: 0,
    description: "Focus previous terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusAlternate",
    combo: "Cmd+Alt+`",
    scope: "global",
    priority: 0,
    description: "Toggle focus between current and previously focused panel",
    category: "Terminal",
  },
  {
    actionId: "tab.next",
    combo: "Cmd+Shift+]",
    scope: "global",
    priority: 0,
    description: "Switch to next tab in focused panel",
    category: "Terminal",
  },
  {
    actionId: "tab.previous",
    combo: "Cmd+Shift+[",
    scope: "global",
    priority: 0,
    description: "Switch to previous tab in focused panel",
    category: "Terminal",
  },
  {
    actionId: "terminal.maximize",
    combo: "Ctrl+Shift+F",
    scope: "global",
    priority: 0,
    description: "Toggle maximize terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveLeft",
    combo: "Cmd+Shift+Alt+ArrowLeft",
    scope: "global",
    priority: 0,
    description: "Move terminal left in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveRight",
    combo: "Cmd+Shift+Alt+ArrowRight",
    scope: "global",
    priority: 0,
    description: "Move terminal right in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveUp",
    combo: "Cmd+Shift+Alt+ArrowUp",
    scope: "global",
    priority: 0,
    description: "Move terminal up in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveDown",
    combo: "Cmd+Shift+Alt+ArrowDown",
    scope: "global",
    priority: 0,
    description: "Move terminal down in grid",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveToDock",
    combo: "Cmd+Shift+Alt+D",
    scope: "global",
    priority: 0,
    description: "Move terminal to dock",
    category: "Terminal",
  },
  {
    actionId: "terminal.moveToGrid",
    combo: "Cmd+Shift+Alt+G",
    scope: "global",
    priority: 0,
    description: "Move terminal to grid",
    category: "Terminal",
  },
  {
    actionId: "agent.palette",
    combo: "Cmd+Shift+A",
    scope: "global",
    priority: 0,
    description: "Open quick switcher",
    category: "Agents",
  },
  {
    actionId: "agent.claude",
    combo: "Cmd+Alt+C",
    scope: "global",
    priority: 0,
    description: "Launch Claude Code agent",
    category: "Agents",
  },
  {
    actionId: "agent.gemini",
    combo: "Cmd+Alt+G",
    scope: "global",
    priority: 0,
    description: "Launch Gemini agent",
    category: "Agents",
  },
  {
    actionId: "agent.codex",
    combo: "Cmd+Alt+X",
    scope: "global",
    priority: 0,
    description: "Launch Codex agent",
    category: "Agents",
  },
  {
    actionId: "agent.opencode",
    combo: "",
    scope: "global",
    priority: 0,
    description: "Launch OpenCode agent",
    category: "Agents",
  },
  {
    actionId: "agent.cursor",
    combo: "",
    scope: "global",
    priority: 0,
    description: "Launch Cursor agent",
    category: "Agents",
  },
  {
    actionId: "agent.kiro",
    combo: "",
    scope: "global",
    priority: 0,
    description: "Launch Kiro agent",
    category: "Agents",
  },
  {
    actionId: "agent.copilot",
    combo: "",
    scope: "global",
    priority: 0,
    description: "Launch GitHub Copilot agent",
    category: "Agents",
  },
  {
    actionId: "agent.kimi",
    combo: "",
    scope: "global",
    priority: 0,
    description: "Launch Kimi Code agent",
    category: "Agents",
  },
  {
    actionId: "agent.terminal",
    combo: "Cmd+Alt+N",
    scope: "global",
    priority: 0,
    description: "Launch terminal in current worktree",
    category: "Agents",
  },
  {
    actionId: "agent.browser",
    combo: "Cmd+Alt+B",
    scope: "global",
    priority: 0,
    description: "Launch browser panel in current worktree",
    category: "Agents",
  },
  {
    actionId: "agent.focusNextWaiting",
    combo: "Cmd+Alt+/",
    scope: "global",
    priority: 0,
    description: "Jump to next waiting agent",
    category: "Agents",
  },
  {
    actionId: "agent.focusNextWaitingGlobal",
    combo: "Cmd+Shift+Alt+/",
    scope: "global",
    priority: 0,
    description: "Jump to next waiting agent across all projects",
    category: "Agents",
  },
  {
    actionId: "agent.focusNextWorking",
    combo: "Cmd+Alt+.",
    scope: "global",
    priority: 0,
    description: "Jump to next working agent",
    category: "Agents",
  },
  {
    actionId: "agent.focusNextAgent",
    combo: "Cmd+Alt+K",
    scope: "global",
    priority: 0,
    description: "Cycle to next agent panel",
    category: "Agents",
  },
  {
    actionId: "agent.focusPreviousAgent",
    combo: "Cmd+Alt+J",
    scope: "global",
    priority: 0,
    description: "Cycle to previous agent panel",
    category: "Agents",
  },
  {
    actionId: "dock.focusNextWaiting",
    combo: "Cmd+Shift+/",
    scope: "global",
    priority: 0,
    description: "Jump to next waiting dock agent",
    category: "Agents",
  },
  {
    actionId: "terminal.inject",
    combo: "Cmd+Shift+I",
    scope: "global",
    priority: 0,
    description: "Inject context into focused terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.sendToAgent",
    combo: "Cmd+Shift+E",
    scope: "global",
    priority: 0,
    description: "Send selection to another terminal",
    category: "Terminal",
  },
  {
    actionId: "terminal.armDefault",
    combo: "Cmd+Shift+B",
    scope: "global",
    priority: 0,
    description: "Arm all eligible terminals in the current worktree",
    category: "Terminal",
  },
  // Fleet quick-actions. Registered at priority 5 (ELEVATED) so they outrank
  // any future global binding on the same combo while the fleet ribbon is
  // visible; when nothing is armed each action no-ops so the UI stays intact.
  // fleet.reject is Cmd+Shift+Y — the shifted twin of fleet.accept (Cmd+Y) —
  // NOT Cmd+N: a destructive-adjacent broadcast ("n⏎" to every armed agent)
  // must never sit on a reflexive "new" key whose meaning flips with
  // transient ribbon state (and the native New Worktree accelerator swallowed
  // Cmd+N on macOS anyway, so the old binding never fired there).
  // fleet.interrupt has no combo here — it's driven by a custom Esc-Esc
  // double-tap handler in FleetArmingRibbon that avoids the escape-stack
  // LIFO collision a chord binding would cause.
  {
    actionId: "fleet.armFocused",
    combo: "Cmd+J",
    scope: "global",
    priority: 0,
    description: "Toggle arm focused pane (Join the fleet)",
    category: "Fleet",
  },
  {
    actionId: "fleet.armFocused",
    combo: "X",
    scope: "worktreeGrid",
    priority: 5,
    description: "Toggle arm focused pane (no modifier, grid only)",
    category: "Fleet",
  },
  {
    actionId: "fleet.armAll",
    combo: "Cmd+Alt+A",
    scope: "global",
    priority: 0,
    description: "Arm all eligible terminals in current worktree",
    category: "Fleet",
  },
  {
    actionId: "fleet.accept",
    combo: "Cmd+Y",
    scope: "global",
    priority: 5,
    description: "Accept all armed waiting agents",
    category: "Fleet",
  },
  {
    actionId: "fleet.reject",
    combo: "Cmd+Shift+Y",
    scope: "global",
    priority: 5,
    description: "Reject all armed waiting agents",
    category: "Fleet",
  },
  {
    actionId: "fleet.restart",
    combo: "Cmd+Shift+R",
    scope: "global",
    priority: 5,
    description: "Restart all armed agents",
    category: "Fleet",
  },
  {
    actionId: "fleet.kill",
    combo: "Cmd+Shift+K",
    scope: "global",
    priority: 5,
    description: "Kill all armed terminals",
    category: "Fleet",
  },
  {
    actionId: "fleet.trash",
    combo: "Cmd+Shift+Backspace",
    scope: "global",
    priority: 5,
    description: "Trash all armed terminals",
    category: "Fleet",
  },
  // Directional terminal navigation (Ghostty-style: Cmd+Option+Arrow)
  {
    actionId: "terminal.focusUp",
    combo: "Cmd+Alt+ArrowUp",
    scope: "global",
    priority: 0,
    description: "Focus terminal above",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusDown",
    combo: "Cmd+Alt+ArrowDown",
    scope: "global",
    priority: 0,
    description: "Focus terminal below",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusLeft",
    combo: "Cmd+Alt+ArrowLeft",
    scope: "global",
    priority: 0,
    description: "Focus terminal to the left",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusRight",
    combo: "Cmd+Alt+ArrowRight",
    scope: "global",
    priority: 0,
    description: "Focus terminal to the right",
    category: "Terminal",
  },
  // Index-based terminal navigation (Cmd+1-9)
  {
    actionId: "terminal.focusIndex1",
    combo: "Cmd+1",
    scope: "global",
    priority: 0,
    description: "Focus terminal 1",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex2",
    combo: "Cmd+2",
    scope: "global",
    priority: 0,
    description: "Focus terminal 2",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex3",
    combo: "Cmd+3",
    scope: "global",
    priority: 0,
    description: "Focus terminal 3",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex4",
    combo: "Cmd+4",
    scope: "global",
    priority: 0,
    description: "Focus terminal 4",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex5",
    combo: "Cmd+5",
    scope: "global",
    priority: 0,
    description: "Focus terminal 5",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex6",
    combo: "Cmd+6",
    scope: "global",
    priority: 0,
    description: "Focus terminal 6",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex7",
    combo: "Cmd+7",
    scope: "global",
    priority: 0,
    description: "Focus terminal 7",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex8",
    combo: "Cmd+8",
    scope: "global",
    priority: 0,
    description: "Focus terminal 8",
    category: "Terminal",
  },
  {
    actionId: "terminal.focusIndex9",
    combo: "Cmd+9",
    scope: "global",
    priority: 0,
    description: "Focus terminal 9",
    category: "Terminal",
  },
  {
    actionId: "action.palette.open",
    combo: "Cmd+Shift+P",
    scope: "global",
    priority: 0,
    description: "Open command palette",
    category: "Navigation",
  },
  {
    actionId: "action.repeatLast",
    combo: "Cmd+Shift+.",
    scope: "global",
    priority: 0,
    description: "Repeat last action",
    category: "Navigation",
  },
  {
    actionId: "panel.diagnosticsLogs",
    combo: "Ctrl+Shift+L",
    scope: "global",
    priority: 0,
    description: "Open diagnostics dock to Logs tab",
    category: "Panels",
  },
  {
    actionId: "panel.diagnosticsMessages",
    combo: "Ctrl+Shift+M",
    scope: "global",
    priority: 0,
    description: "Open diagnostics dock to Problems tab",
    category: "Panels",
  },
  {
    actionId: "panel.toggleDiagnostics",
    combo: "Cmd+Shift+D",
    scope: "global",
    priority: 0,
    description: "Toggle diagnostics dock",
    category: "Panels",
  },
  {
    actionId: "notifications.toggle",
    combo: "Cmd+Shift+N",
    scope: "global",
    priority: 0,
    description: "Toggle notification inbox",
    category: "Panels",
  },
  {
    actionId: "panel.togglePortal",
    combo: "Cmd+\\",
    scope: "global",
    priority: 0,
    description: "Toggle portal panel",
    category: "Panels",
  },
  {
    actionId: "portal.closeTab",
    combo: "Cmd+W",
    scope: "portal",
    priority: 20,
    description: "Close active portal tab",
    category: "Portal",
  },
  {
    actionId: "portal.nextTab",
    combo: "Ctrl+Tab",
    scope: "portal",
    priority: 20,
    description: "Next portal tab",
    category: "Portal",
  },
  {
    actionId: "portal.prevTab",
    combo: "Ctrl+Shift+Tab",
    scope: "portal",
    priority: 20,
    description: "Previous portal tab",
    category: "Portal",
  },
  {
    actionId: "portal.newTab",
    combo: "Cmd+T",
    scope: "portal",
    priority: 20,
    description: "New portal tab",
    category: "Portal",
  },
  {
    actionId: "devPreview.reloadPreview",
    combo: "Cmd+R",
    scope: "dev-preview",
    priority: 20,
    description: "Reload dev preview",
    category: "Dev Preview",
  },
  {
    actionId: "nav.toggleSidebar",
    combo: "Cmd+B",
    scope: "global",
    priority: 0,
    description: "Toggle sidebar",
    category: "Navigation",
  },
  {
    actionId: "nav.toggleFocusMode",
    combo: "Cmd+K Cmd+F",
    scope: "global",
    priority: 0,
    description: "Toggle focus mode (hide sidebar and assistant)",
    category: "Navigation",
  },
  {
    actionId: "worktree.switch1",
    combo: "Cmd+Alt+1",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 1",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch2",
    combo: "Cmd+Alt+2",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 2",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch3",
    combo: "Cmd+Alt+3",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 3",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch4",
    combo: "Cmd+Alt+4",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 4",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch5",
    combo: "Cmd+Alt+5",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 5",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch6",
    combo: "Cmd+Alt+6",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 6",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch7",
    combo: "Cmd+Alt+7",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 7",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch8",
    combo: "Cmd+Alt+8",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 8",
    category: "Worktrees",
  },
  {
    actionId: "worktree.switch9",
    combo: "Cmd+Alt+9",
    scope: "global",
    priority: 0,
    description: "Switch to worktree 9",
    category: "Worktrees",
  },
  {
    actionId: "worktree.next",
    combo: "Cmd+Alt+]",
    scope: "global",
    priority: 0,
    description: "Switch to next worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.previous",
    combo: "Cmd+Alt+[",
    scope: "global",
    priority: 0,
    description: "Switch to previous worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.openPalette",
    combo: "Cmd+K Cmd+O",
    scope: "global",
    priority: 0,
    description: "Open worktree palette",
    category: "Worktrees",
  },
  {
    actionId: "worktree.createDialog.open",
    combo: "Cmd+K Cmd+N",
    scope: "global",
    priority: 0,
    description: "Create a new worktree",
    category: "Worktrees",
  },
  {
    actionId: "worktree.overview",
    combo: "Cmd+Shift+O",
    scope: "global",
    priority: 0,
    description: "Toggle worktrees overview",
    category: "Worktrees",
  },
  {
    actionId: "project.switcherPalette",
    combo: "Cmd+Alt+P",
    scope: "global",
    priority: 0,
    description: "Open project switcher",
    category: "Project",
  },
  {
    actionId: "project.mruCycleOlder",
    combo: "Cmd+Alt+=",
    scope: "global",
    priority: 10,
    description: "Switch project forward",
    category: "Project",
  },
  {
    actionId: "project.mruCycleNewer",
    combo: "Cmd+Shift+Alt+=",
    scope: "global",
    priority: 10,
    description: "Switch project backward",
    category: "Project",
  },
  {
    actionId: "app.theme.pick",
    combo: "Cmd+K Cmd+T",
    scope: "global",
    priority: 0,
    description: "Open theme palette",
    category: "App",
  },
  {
    actionId: "help.shortcuts",
    combo: "Cmd+K Cmd+S",
    scope: "global",
    priority: 0,
    description: "Open keyboard shortcuts reference",
    category: "Help",
  },
  {
    actionId: "help.shortcutsAlt",
    combo: "Cmd+/",
    scope: "global",
    priority: 0,
    description: "Open keyboard shortcuts reference",
    category: "Help",
  },
  {
    actionId: "help.launchAgent",
    combo: "Cmd+Shift+H",
    scope: "global",
    priority: 0,
    description: "Launch help agent",
    category: "Help",
  },
  {
    actionId: "help.togglePanel",
    combo: "Cmd+L",
    scope: "global",
    priority: 0,
    description: "Toggle Daintree Assistant panel",
    category: "Help",
  },
  {
    actionId: "app.newWindow",
    combo: "Cmd+Shift+Alt+N",
    scope: "global",
    priority: 0,
    description: "Open a new window",
    category: "System",
  },
  {
    actionId: "app.settings",
    combo: "Cmd+,",
    scope: "global",
    priority: 0,
    description: "Open settings",
    category: "System",
  },
  {
    actionId: "voiceInput.toggle",
    combo: "Cmd+Shift+V",
    scope: "global",
    priority: 0,
    description: "Toggle voice dictation",
    category: "Voice",
  },
  {
    actionId: "voiceInput.toggleAssistant",
    combo: "Cmd+Shift+Alt+V",
    scope: "global",
    priority: 0,
    description: "Toggle voice dictation in Daintree Assistant",
    category: "Voice",
  },
  {
    actionId: "voiceInput.togglePause",
    combo: "Ctrl+Shift+Space",
    scope: "global",
    priority: 0,
    description: "Pause or resume voice dictation",
    category: "Voice",
  },
  {
    actionId: "find.inFocusedPanel",
    combo: "Cmd+F",
    scope: "global",
    priority: 0,
    description: "Find in focused panel",
    category: "Search",
  },
  {
    actionId: "window.zoomIn",
    combo: "Cmd+=",
    scope: "global",
    priority: 0,
    description: "Zoom in",
    category: "View",
  },
  {
    // Discoverability alias — many users press Cmd+Shift+= for zoom-in even
    // though the physical-key matcher already accepts it via Cmd+=.
    actionId: "window.zoomIn",
    combo: "Cmd+Shift+=",
    scope: "global",
    priority: 0,
    description: "Zoom in",
    category: "View",
  },
  {
    actionId: "window.zoomOut",
    combo: "Cmd+-",
    scope: "global",
    priority: 0,
    description: "Zoom out",
    category: "View",
  },
  {
    actionId: "window.zoomReset",
    combo: "Cmd+0",
    scope: "global",
    priority: 0,
    description: "Reset zoom",
    category: "View",
  },
  // No modal/worktree-list rows here: modal Escape is owned by the escape
  // stack (src/lib/escapeStack.ts) and worktree-list navigation by
  // useWorktreeSidebarKeyboard — the former "modal"/"worktreeList" scoped
  // rows advertised bindings the engine never serviced (the scopes were
  // never pushed). Those keys are documented as fixed in the Keyboard
  // settings tab instead.
  {
    actionId: "worktree.copyTree",
    combo: "Cmd+Shift+C",
    scope: "global",
    priority: 0,
    description: "Copy tree context for active worktree",
    category: "Worktrees",
  },
  {
    actionId: "terminal.contextMenu",
    combo: "Shift+F10",
    scope: "global",
    priority: 0,
    description: "Open focused panel context menu",
    category: "Panels",
  },
  {
    actionId: "terminal.contextMenu",
    combo: "ContextMenu",
    scope: "global",
    priority: 0,
    description: "Open focused panel context menu",
    category: "Panels",
  },
  // Git write operations (Cmd+K chord prefix)
  {
    actionId: "git.stageAll",
    combo: "Cmd+K Cmd+G",
    scope: "global",
    priority: 0,
    description: "Stage all changes",
    category: "Git",
  },
  {
    actionId: "git.commit",
    combo: "Cmd+K Cmd+C",
    scope: "global",
    priority: 0,
    description: "Commit staged changes",
    category: "Git",
  },
  {
    actionId: "git.push",
    combo: "Cmd+K Cmd+P",
    scope: "global",
    priority: 0,
    description: "Push to remote",
    category: "Git",
  },
  // Worktree session bulk operations (Cmd+K chord prefix)
  {
    actionId: "worktree.sessions.minimizeAll",
    combo: "Cmd+K Cmd+M",
    scope: "global",
    priority: 0,
    description: "Dock all sessions in active worktree",
    category: "Worktree Sessions",
  },
  {
    actionId: "worktree.sessions.maximizeAll",
    combo: "Cmd+K Cmd+X",
    scope: "global",
    priority: 0,
    description: "Maximize all sessions in active worktree",
    category: "Worktree Sessions",
  },
  {
    actionId: "worktree.sessions.resetRenderers",
    combo: "Cmd+K Cmd+V",
    scope: "global",
    priority: 0,
    description: "Reset renderers for all sessions in active worktree",
    category: "Worktree Sessions",
  },
];

const WINDOWS_ONLY_KEYBINDINGS: KeybindingConfig[] = [
  {
    actionId: "terminal.close",
    combo: "Ctrl+F4",
    scope: "global",
    priority: 10,
    description: "Close focused terminal",
    category: "Terminal",
  },
  {
    actionId: "portal.closeTab",
    combo: "Ctrl+F4",
    scope: "portal",
    priority: 20,
    description: "Close active portal tab",
    category: "Portal",
  },
];

/**
 * Platform-parameterized so every consumer states its platform explicitly:
 * the renderer passes its detected platform, the main process passes
 * process.platform, and the docs generator emits both variants regardless of
 * the host OS it runs on.
 */
export function buildDefaultKeybindings(isWindows: boolean): KeybindingConfig[] {
  return isWindows ? [...CORE_KEYBINDINGS, ...WINDOWS_ONLY_KEYBINDINGS] : [...CORE_KEYBINDINGS];
}

export const KEYBINDING_PRIORITY = {
  DEFAULT: 0,
  PLUGIN: 1,
  ELEVATED: 5,
  OVERRIDE: 10,
} as const;
