import type { AppColorScheme } from "@shared/types/appTheme";

export const DEFAULT_APP_SCHEME_ID = "canopy";

export const BUILT_IN_APP_SCHEMES: AppColorScheme[] = [
  {
    id: "canopy",
    name: "Canopy",
    type: "dark",
    builtin: true,
    tokens: {
      "canopy-bg": "#18181b",
      "canopy-sidebar": "#121214",
      "canopy-border": "#27272a",
      "canopy-text": "#e4e4e7",
      "canopy-accent": "#6b8de6",
      surface: "#1c1c20",
      "surface-highlight": "#2a2a2f",
      "grid-bg": "#0d0d0e",
      "canopy-focus": "rgba(255, 255, 255, 0.18)",
      "status-success": "#5dae8b",
      "status-warning": "#d4a043",
      "status-error": "#d97979",
      "status-info": "#7f8ea3",
      "state-active": "#6b8de6",
      "state-idle": "#52525b",
      "state-working": "#6b8de6",
      "state-waiting": "#fbbf24",
      "server-running": "#5dae8b",
      "server-stopped": "#52525b",
      "server-starting": "#d4a043",
      "server-error": "#d97979",
      "terminal-selection": "#1a2744",
    },
  },
  {
    id: "canopy-slate",
    name: "Canopy Slate",
    type: "dark",
    builtin: true,
    tokens: {
      "canopy-bg": "#0f172a",
      "canopy-sidebar": "#0a1120",
      "canopy-border": "#1e293b",
      "canopy-text": "#e2e8f0",
      "canopy-accent": "#3b82f6",
      surface: "#131e32",
      "surface-highlight": "#1e2d45",
      "grid-bg": "#080d1a",
      "canopy-focus": "rgba(255, 255, 255, 0.18)",
      "status-success": "#4ade80",
      "status-warning": "#fbbf24",
      "status-error": "#f87171",
      "status-info": "#94a3b8",
      "state-active": "#3b82f6",
      "state-idle": "#334155",
      "state-working": "#3b82f6",
      "state-waiting": "#fbbf24",
      "server-running": "#4ade80",
      "server-stopped": "#334155",
      "server-starting": "#fbbf24",
      "server-error": "#f87171",
      "terminal-selection": "#1e3a5f",
    },
  },
];
