import type { ITheme } from "@xterm/xterm";
import {
  DEFAULT_APP_SCHEME_ID as DEFAULT_APP_THEME_ID,
  getTerminalThemeFromAppScheme,
  resolveAppTheme,
} from "@shared/theme";

export interface TerminalColorScheme {
  id: string;
  name: string;
  type: "dark" | "light";
  builtin: boolean;
  colors: ITheme;
}

export const ANSI_COLOR_KEYS = [
  "background",
  "foreground",
  "cursor",
  "cursorAccent",
  "selectionBackground",
  "selectionForeground",
  "black",
  "red",
  "green",
  "yellow",
  "blue",
  "magenta",
  "cyan",
  "white",
  "brightBlack",
  "brightRed",
  "brightGreen",
  "brightYellow",
  "brightBlue",
  "brightMagenta",
  "brightCyan",
  "brightWhite",
] as const;

export type AnsiColorKey = (typeof ANSI_COLOR_KEYS)[number];

export const DEFAULT_SCHEME_ID = "canopy";

const defaultAppScheme = resolveAppTheme(DEFAULT_APP_THEME_ID);
const daintreeAppScheme = resolveAppTheme("daintree");
const highlandsAppScheme = resolveAppTheme("highlands");

export const BUILT_IN_SCHEMES: TerminalColorScheme[] = [
  {
    id: "canopy",
    name: "Match App Theme",
    type: defaultAppScheme.type,
    builtin: true,
    colors: getTerminalThemeFromAppScheme(defaultAppScheme),
  },
  {
    id: "daintree",
    name: "Daintree",
    type: "dark",
    builtin: true,
    colors: getTerminalThemeFromAppScheme(daintreeAppScheme),
  },
  {
    id: "highlands",
    name: "Highlands",
    type: "dark",
    builtin: true,
    colors: getTerminalThemeFromAppScheme(highlandsAppScheme),
  },
  {
    id: "fiordland",
    name: "Fiordland",
    type: "dark",
    builtin: true,
    colors: {
      background: "#070D12",
      foreground: "#B5C7D6",
      cursor: "#88C0D0",
      cursorAccent: "#070D12",
      selectionBackground: "#162E3A",
      selectionForeground: "#D4E3EF",
      black: "#1C2E3D",
      red: "#D06775",
      green: "#66A88B",
      yellow: "#C4A671",
      blue: "#6B9CD6",
      magenta: "#B382B8",
      cyan: "#58AFB6",
      white: "#B5C7D6",
      brightBlack: "#2E4458",
      brightRed: "#E2838F",
      brightGreen: "#81C2A5",
      brightYellow: "#DEC08C",
      brightBlue: "#8DB9EE",
      brightMagenta: "#CCA1D0",
      brightCyan: "#74CAD1",
      brightWhite: "#D4E3EF",
    },
  },
  {
    id: "canopy-ember",
    name: "Canopy Ember",
    type: "dark",
    builtin: true,
    colors: {
      background: "#211916",
      foreground: "#e8ddd2",
      cursor: "#d7af7b",
      cursorAccent: "#211916",
      selectionBackground: "#433028",
      selectionForeground: "#f3e8dd",
      black: "#16100e",
      red: "#d16d5c",
      green: "#8fa06d",
      yellow: "#d4aa5e",
      blue: "#7d9fbb",
      magenta: "#b189c0",
      cyan: "#7fb6ad",
      white: "#d0c4b8",
      brightBlack: "#6d5c54",
      brightRed: "#e08573",
      brightGreen: "#a8c07d",
      brightYellow: "#e6bf6b",
      brightBlue: "#97b7d1",
      brightMagenta: "#c7a1d4",
      brightCyan: "#98cbc2",
      brightWhite: "#f3ebe4",
    },
  },
  {
    id: "redwoods",
    name: "Redwoods",
    type: "dark",
    builtin: true,
    colors: {
      background: "#1A1210",
      foreground: "#D8CCB8",
      cursor: "#C8A060",
      cursorAccent: "#1A1210",
      selectionBackground: "#3A2218",
      selectionForeground: "#D8CCB8",
      black: "#2A1C17",
      red: "#C46C5C",
      green: "#85A37A",
      yellow: "#CFA962",
      blue: "#7D9FBB",
      magenta: "#A888B0",
      cyan: "#79B5AC",
      white: "#C8BCAA",
      brightBlack: "#4A3428",
      brightRed: "#D4806E",
      brightGreen: "#9CB890",
      brightYellow: "#DFC078",
      brightBlue: "#8FB5CC",
      brightMagenta: "#BC9EC0",
      brightCyan: "#8FCCC4",
      brightWhite: "#D8CCB8",
    },
  },
  {
    id: "dracula",
    name: "Dracula",
    type: "dark",
    builtin: true,
    colors: {
      background: "#282a36",
      foreground: "#f8f8f2",
      cursor: "#f8f8f2",
      cursorAccent: "#282a36",
      selectionBackground: "#44475a",
      selectionForeground: "#f8f8f2",
      black: "#21222c",
      red: "#ff5555",
      green: "#50fa7b",
      yellow: "#f1fa8c",
      blue: "#bd93f9",
      magenta: "#ff79c6",
      cyan: "#8be9fd",
      white: "#f8f8f2",
      brightBlack: "#6272a4",
      brightRed: "#ff6e6e",
      brightGreen: "#69ff94",
      brightYellow: "#ffffa5",
      brightBlue: "#d6acff",
      brightMagenta: "#ff92df",
      brightCyan: "#a4ffff",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "one-dark",
    name: "One Dark",
    type: "dark",
    builtin: true,
    colors: {
      background: "#282c34",
      foreground: "#abb2bf",
      cursor: "#528bff",
      cursorAccent: "#282c34",
      selectionBackground: "#3e4451",
      selectionForeground: "#abb2bf",
      black: "#282c34",
      red: "#e06c75",
      green: "#98c379",
      yellow: "#e5c07b",
      blue: "#61afef",
      magenta: "#c678dd",
      cyan: "#56b6c2",
      white: "#abb2bf",
      brightBlack: "#5c6370",
      brightRed: "#e06c75",
      brightGreen: "#98c379",
      brightYellow: "#e5c07b",
      brightBlue: "#61afef",
      brightMagenta: "#c678dd",
      brightCyan: "#56b6c2",
      brightWhite: "#ffffff",
    },
  },
  {
    id: "monokai",
    name: "Monokai",
    type: "dark",
    builtin: true,
    colors: {
      background: "#272822",
      foreground: "#f8f8f2",
      cursor: "#f8f8f0",
      cursorAccent: "#272822",
      selectionBackground: "#49483e",
      selectionForeground: "#f8f8f2",
      black: "#272822",
      red: "#f92672",
      green: "#a6e22e",
      yellow: "#f4bf75",
      blue: "#66d9ef",
      magenta: "#ae81ff",
      cyan: "#a1efe4",
      white: "#f8f8f2",
      brightBlack: "#75715e",
      brightRed: "#f92672",
      brightGreen: "#a6e22e",
      brightYellow: "#f4bf75",
      brightBlue: "#66d9ef",
      brightMagenta: "#ae81ff",
      brightCyan: "#a1efe4",
      brightWhite: "#f9f8f5",
    },
  },
  {
    id: "solarized-dark",
    name: "Solarized Dark",
    type: "dark",
    builtin: true,
    colors: {
      background: "#002b36",
      foreground: "#839496",
      cursor: "#839496",
      cursorAccent: "#002b36",
      selectionBackground: "#073642",
      selectionForeground: "#93a1a1",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#586e75",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    id: "solarized-light",
    name: "Solarized Light",
    type: "light",
    builtin: true,
    colors: {
      background: "#fdf6e3",
      foreground: "#657b83",
      cursor: "#657b83",
      cursorAccent: "#fdf6e3",
      selectionBackground: "#eee8d5",
      selectionForeground: "#586e75",
      black: "#073642",
      red: "#dc322f",
      green: "#859900",
      yellow: "#b58900",
      blue: "#268bd2",
      magenta: "#d33682",
      cyan: "#2aa198",
      white: "#eee8d5",
      brightBlack: "#586e75",
      brightRed: "#cb4b16",
      brightGreen: "#586e75",
      brightYellow: "#657b83",
      brightBlue: "#839496",
      brightMagenta: "#6c71c4",
      brightCyan: "#93a1a1",
      brightWhite: "#fdf6e3",
    },
  },
  {
    id: "github-dark",
    name: "GitHub Dark",
    type: "dark",
    builtin: true,
    colors: {
      background: "#0d1117",
      foreground: "#c9d1d9",
      cursor: "#c9d1d9",
      cursorAccent: "#0d1117",
      selectionBackground: "#264f78",
      selectionForeground: "#c9d1d9",
      black: "#484f58",
      red: "#ff7b72",
      green: "#3fb950",
      yellow: "#d29922",
      blue: "#58a6ff",
      magenta: "#bc8cff",
      cyan: "#39c5cf",
      white: "#b1bac4",
      brightBlack: "#6e7681",
      brightRed: "#ffa198",
      brightGreen: "#56d364",
      brightYellow: "#e3b341",
      brightBlue: "#79c0ff",
      brightMagenta: "#d2a8ff",
      brightCyan: "#56d4dd",
      brightWhite: "#f0f6fc",
    },
  },
  {
    id: "catppuccin-mocha",
    name: "Catppuccin Mocha",
    type: "dark",
    builtin: true,
    colors: {
      background: "#1e1e2e",
      foreground: "#cdd6f4",
      cursor: "#f5e0dc",
      cursorAccent: "#1e1e2e",
      selectionBackground: "#45475a",
      selectionForeground: "#cdd6f4",
      black: "#45475a",
      red: "#f38ba8",
      green: "#a6e3a1",
      yellow: "#f9e2af",
      blue: "#89b4fa",
      magenta: "#f5c2e7",
      cyan: "#94e2d5",
      white: "#bac2de",
      brightBlack: "#585b70",
      brightRed: "#f38ba8",
      brightGreen: "#a6e3a1",
      brightYellow: "#f9e2af",
      brightBlue: "#89b4fa",
      brightMagenta: "#f5c2e7",
      brightCyan: "#94e2d5",
      brightWhite: "#a6adc8",
    },
  },
  // Source: Tokyo Night by enkia — MIT license, github.com/enkia/tokyo-night-vscode-theme
  {
    id: "tokyo-night",
    name: "Tokyo Night",
    type: "dark",
    builtin: true,
    colors: {
      background: "#1a1b26",
      foreground: "#a9b1d6",
      cursor: "#c0caf5",
      cursorAccent: "#1a1b26",
      selectionBackground: "#33467c",
      selectionForeground: "#a9b1d6",
      black: "#15161e",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#bb9af7",
      cyan: "#7dcfff",
      white: "#a9b1d6",
      brightBlack: "#414868",
      brightRed: "#f7768e",
      brightGreen: "#9ece6a",
      brightYellow: "#e0af68",
      brightBlue: "#7aa2f7",
      brightMagenta: "#bb9af7",
      brightCyan: "#7dcfff",
      brightWhite: "#c0caf5",
    },
  },
  // Source: Gruvbox by morhetz — MIT license, github.com/morhetz/gruvbox
  {
    id: "gruvbox-dark",
    name: "Gruvbox Dark",
    type: "dark",
    builtin: true,
    colors: {
      background: "#282828",
      foreground: "#ebdbb2",
      cursor: "#ebdbb2",
      cursorAccent: "#282828",
      selectionBackground: "#665c54",
      selectionForeground: "#ebdbb2",
      black: "#282828",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#a89984",
      brightBlack: "#928374",
      brightRed: "#fb4934",
      brightGreen: "#b8bb26",
      brightYellow: "#fabd2f",
      brightBlue: "#83a598",
      brightMagenta: "#d3869b",
      brightCyan: "#8ec07c",
      brightWhite: "#ebdbb2",
    },
  },
  // Source: Everforest by sainnhe — MIT license, github.com/sainnhe/everforest
  {
    id: "everforest-dark",
    name: "Everforest Dark",
    type: "dark",
    builtin: true,
    colors: {
      background: "#2d353b",
      foreground: "#d3c6aa",
      cursor: "#d3c6aa",
      cursorAccent: "#2d353b",
      selectionBackground: "#525c62",
      selectionForeground: "#d3c6aa",
      black: "#475258",
      red: "#e67e80",
      green: "#a7c080",
      yellow: "#dbbc7f",
      blue: "#7fbbb3",
      magenta: "#d699b6",
      cyan: "#83c092",
      white: "#d3c6aa",
      brightBlack: "#475258",
      brightRed: "#e67e80",
      brightGreen: "#a7c080",
      brightYellow: "#dbbc7f",
      brightBlue: "#7fbbb3",
      brightMagenta: "#d699b6",
      brightCyan: "#83c092",
      brightWhite: "#d3c6aa",
    },
  },
  // Source: Oceanic Next by voronianski — MIT license, github.com/voronianski/oceanic-next-color-scheme
  {
    id: "oceanic-next",
    name: "Oceanic Next",
    type: "dark",
    builtin: true,
    colors: {
      background: "#1b2b34",
      foreground: "#d8dee9",
      cursor: "#d8dee9",
      cursorAccent: "#1b2b34",
      selectionBackground: "#4f5b66",
      selectionForeground: "#d8dee9",
      black: "#1b2b34",
      red: "#ec5f67",
      green: "#99c794",
      yellow: "#fac863",
      blue: "#6699cc",
      magenta: "#c594c5",
      cyan: "#5fb3b3",
      white: "#d8dee9",
      brightBlack: "#65737e",
      brightRed: "#ec5f67",
      brightGreen: "#99c794",
      brightYellow: "#fac863",
      brightBlue: "#6699cc",
      brightMagenta: "#c594c5",
      brightCyan: "#5fb3b3",
      brightWhite: "#ffffff",
    },
  },
  // Source: Kanagawa Dragon by rebelot — MIT license, github.com/rebelot/kanagawa.nvim
  {
    id: "kanagawa-dragon",
    name: "Kanagawa Dragon",
    type: "dark",
    builtin: true,
    colors: {
      background: "#181616",
      foreground: "#c5c9c5",
      cursor: "#c8c093",
      cursorAccent: "#181616",
      selectionBackground: "#2d4f67",
      selectionForeground: "#c5c9c5",
      black: "#0d0c0c",
      red: "#c4746e",
      green: "#8a9a7b",
      yellow: "#c4b28a",
      blue: "#8ba4b0",
      magenta: "#a292a3",
      cyan: "#8ea4a2",
      white: "#c5c9c5",
      brightBlack: "#a6a69c",
      brightRed: "#e46876",
      brightGreen: "#87a987",
      brightYellow: "#e2c08d",
      brightBlue: "#7fb4ca",
      brightMagenta: "#938aa9",
      brightCyan: "#7aa89f",
      brightWhite: "#c8c093",
    },
  },
  // Source: Tomorrow Night by Chris Kempson — MIT license, github.com/chriskempson/tomorrow-theme
  {
    id: "tomorrow-night",
    name: "Tomorrow Night",
    type: "dark",
    builtin: true,
    colors: {
      background: "#1d1f21",
      foreground: "#c5c8c6",
      cursor: "#aeafad",
      cursorAccent: "#1d1f21",
      selectionBackground: "#373b41",
      selectionForeground: "#c5c8c6",
      black: "#1d1f21",
      red: "#cc6666",
      green: "#b5bd68",
      yellow: "#f0c674",
      blue: "#81a2be",
      magenta: "#b294bb",
      cyan: "#8abeb7",
      white: "#c5c8c6",
      brightBlack: "#666666",
      brightRed: "#d54e53",
      brightGreen: "#b9ca4a",
      brightYellow: "#e7c547",
      brightBlue: "#7aa6da",
      brightMagenta: "#c397d8",
      brightCyan: "#70c0b1",
      brightWhite: "#eaeaea",
    },
  },
  // Source: Rosé Pine Dawn by rosé-pine — MIT license, github.com/rose-pine/rose-pine-theme
  {
    id: "rose-pine-dawn",
    name: "Rosé Pine Dawn",
    type: "light",
    builtin: true,
    colors: {
      background: "#faf4ed",
      foreground: "#575279",
      cursor: "#cecacd",
      cursorAccent: "#faf4ed",
      selectionBackground: "#dfdad9",
      selectionForeground: "#575279",
      black: "#f2e9e1",
      red: "#b4637a",
      green: "#286983",
      yellow: "#ea9d34",
      blue: "#56949f",
      magenta: "#907aa9",
      cyan: "#d7827e",
      white: "#575279",
      brightBlack: "#9893a5",
      brightRed: "#b4637a",
      brightGreen: "#286983",
      brightYellow: "#ea9d34",
      brightBlue: "#56949f",
      brightMagenta: "#907aa9",
      brightCyan: "#d7827e",
      brightWhite: "#575279",
    },
  },
  // Source: Catppuccin Latte by catppuccin — MIT license, github.com/catppuccin/catppuccin
  {
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    type: "light",
    builtin: true,
    colors: {
      background: "#eff1f5",
      foreground: "#4c4f69",
      cursor: "#dc8a78",
      cursorAccent: "#eff1f5",
      selectionBackground: "#acb0be",
      selectionForeground: "#4c4f69",
      black: "#5c5f77",
      red: "#d20f39",
      green: "#40a02b",
      yellow: "#df8e1d",
      blue: "#1e66f5",
      magenta: "#ea76cb",
      cyan: "#179299",
      white: "#acb0be",
      brightBlack: "#6c6f85",
      brightRed: "#d20f39",
      brightGreen: "#40a02b",
      brightYellow: "#df8e1d",
      brightBlue: "#1e66f5",
      brightMagenta: "#ea76cb",
      brightCyan: "#179299",
      brightWhite: "#bcc0cc",
    },
  },
  // Source: Atom One Light by Atom — MIT license, github.com/atom/atom
  {
    id: "atom-one-light",
    name: "Atom One Light",
    type: "light",
    builtin: true,
    colors: {
      background: "#fafafa",
      foreground: "#383a42",
      cursor: "#526fff",
      cursorAccent: "#fafafa",
      selectionBackground: "#ebedef",
      selectionForeground: "#383a42",
      black: "#000000",
      red: "#e45649",
      green: "#50a14f",
      yellow: "#c18401",
      blue: "#4078f2",
      magenta: "#a626a4",
      cyan: "#0184bc",
      white: "#a0a1a7",
      brightBlack: "#696c77",
      brightRed: "#e45649",
      brightGreen: "#50a14f",
      brightYellow: "#c18401",
      brightBlue: "#4078f2",
      brightMagenta: "#a626a4",
      brightCyan: "#0184bc",
      brightWhite: "#ffffff",
    },
  },
  // Source: Gruvbox Light by morhetz — MIT license, github.com/morhetz/gruvbox
  {
    id: "gruvbox-light",
    name: "Gruvbox Light",
    type: "light",
    builtin: true,
    colors: {
      background: "#fbf1c7",
      foreground: "#3c3836",
      cursor: "#3c3836",
      cursorAccent: "#fbf1c7",
      selectionBackground: "#d5c4a1",
      selectionForeground: "#3c3836",
      black: "#fbf1c7",
      red: "#cc241d",
      green: "#98971a",
      yellow: "#d79921",
      blue: "#458588",
      magenta: "#b16286",
      cyan: "#689d6a",
      white: "#7c6f64",
      brightBlack: "#928374",
      brightRed: "#9d0006",
      brightGreen: "#79740e",
      brightYellow: "#b57614",
      brightBlue: "#076678",
      brightMagenta: "#8f3f71",
      brightCyan: "#427b58",
      brightWhite: "#3c3836",
    },
  },
  // Source: Ayu Light by ayu-theme — MIT license, github.com/ayu-theme/ayu-vim
  {
    id: "ayu-light",
    name: "Ayu Light",
    type: "light",
    builtin: true,
    colors: {
      background: "#fafafa",
      foreground: "#5c6166",
      cursor: "#ff6a00",
      cursorAccent: "#fafafa",
      selectionBackground: "#f0eeee",
      selectionForeground: "#5c6166",
      black: "#000000",
      red: "#f07178",
      green: "#86b300",
      yellow: "#f2ae49",
      blue: "#399ee6",
      magenta: "#a37acc",
      cyan: "#4dbf99",
      white: "#ffffff",
      brightBlack: "#323232",
      brightRed: "#f07178",
      brightGreen: "#86b300",
      brightYellow: "#f2ae49",
      brightBlue: "#399ee6",
      brightMagenta: "#a37acc",
      brightCyan: "#4dbf99",
      brightWhite: "#ffffff",
    },
  },
  // Hokkaido — frost-blue winter palette, cool-shifted ANSI colors
  {
    id: "hokkaido",
    name: "Hokkaido",
    type: "light",
    builtin: true,
    colors: {
      background: "#FAFCFD",
      foreground: "#2B3540",
      cursor: "#3E7D86",
      cursorAccent: "#FAFCFD",
      selectionBackground: "#D0E4EE",
      selectionForeground: "#2B3540",
      black: "#2B3540",
      red: "#BF616A",
      green: "#4A8C5C",
      yellow: "#A07A2E",
      blue: "#5E81AC",
      magenta: "#7B5C8C",
      cyan: "#3E7D86",
      white: "#C8D8E4",
      brightBlack: "#5A6B7A",
      brightRed: "#D9747D",
      brightGreen: "#62A872",
      brightYellow: "#C49A3E",
      brightBlue: "#7AA0C8",
      brightMagenta: "#9A7AAA",
      brightCyan: "#5A9EA8",
      brightWhite: "#EEF3F7",
    },
  },
];

export function getSchemeById(id: string): TerminalColorScheme | undefined {
  return BUILT_IN_SCHEMES.find((s) => s.id === id);
}

export const APP_THEME_TERMINAL_SCHEME_MAP: Record<string, string> = {
  daintree: "daintree",
  fiordland: "fiordland",
  highlands: "highlands",
  arashiyama: "canopy-ember",
  galapagos: "github-dark",
  namib: "canopy-ember",
  redwoods: "redwoods",
  bondi: "solarized-light",
  svalbard: "atom-one-light",
  atacama: "atom-one-light",
  serengeti: "solarized-light",
  hokkaido: "hokkaido",
};

export function getMappedTerminalScheme(appThemeId: string): TerminalColorScheme | undefined {
  const terminalSchemeId = APP_THEME_TERMINAL_SCHEME_MAP[appThemeId];
  return terminalSchemeId ? getSchemeById(terminalSchemeId) : undefined;
}
