/** A bundled browser adapter, including every dependency that shares class identities. */
export interface PluginDocumentPackage {
  name: string;
  version: string;
  /** SHA-256 of the complete emitted JavaScript, generated by plugin-vite. */
  buildId: string;
  entryUrl: string;
  /** Default: plugin instance. Document scope explicitly shares with other trusted plugins. */
  scope?: "plugin" | "document";
}

export const PLUGIN_DOCUMENT_PACKAGE_BRIDGE = "__daintreeDocumentPackagesV1";

export interface PluginDocumentPackageBridge {
  load(moduleUrl: string, descriptor: PluginDocumentPackage): Promise<unknown>;
}
