/**
 * Terminal Activity Types
 *
 * Types for semantic terminal activity detection.
 * Enables human-readable status updates and terminal classification.
 */

/**
 * Terminal task classification types.
 * - interactive: Short-lived commands, REPLs, prompts requiring user input
 * - background: Long-running processes (dev servers, watchers, databases)
 * - idle: Completed tasks with no activity
 */
export type TerminalTaskType = "interactive" | "background" | "idle";

/**
 * Terminal activity status.
 * - working: Terminal is actively processing
 * - waiting: Terminal is waiting for user input
 * - success: Task completed successfully
 * - failure: Task failed or encountered an error
 */
export type TerminalActivityStatus = "working" | "waiting" | "success" | "failure";

/**
 * Semantic activity information for a terminal.
 * Generated by AI analysis of recent terminal output.
 */
export interface TerminalActivity {
  /** Terminal identifier */
  terminalId: string;

  /** Human-readable status (max 6 words, active voice) */
  headline: string;

  /** Current operational status */
  status: TerminalActivityStatus;

  /** Terminal classification for UI/UX decisions */
  type: TerminalTaskType;

  /** AI confidence in classification (0.0 to 1.0) */
  confidence: number;

  /** Unix timestamp when analysis was performed */
  timestamp: number;
}

/**
 * Payload for terminal:activity IPC event.
 * Extends TerminalActivity with optional context fields.
 */
export interface TerminalActivityPayload extends TerminalActivity {
  /** Associated worktree ID (if applicable) */
  worktreeId?: string;
  /** Last detected command for this terminal (e.g., 'npm run dev') */
  lastCommand?: string;
}

/** A terminal grid size, in cells. */
export interface TerminalGeometry {
  cols: number;
  rows: number;
}

/**
 * A SerializeAddon snapshot bundled with the grid it was captured at (#11552).
 *
 * The addon emits a hard `\r\n` at every row boundary not marked `isWrapped`
 * and omits the break where a row was exactly filled. Both encodings are only
 * decodable at the capture width, so a snapshot replayed into a differently
 * sized terminal commits real newlines mid-phrase and welds full-width rules
 * onto the following line — damage no later reflow can undo, because it is
 * baked into cell data. Carrying `cols`/`rows` alongside `data` lets every
 * replay site size its target to the capture grid first, write, then reflow to
 * the live grid with xterm's own algorithm.
 */
export interface SerializedTerminalSnapshot extends TerminalGeometry {
  data: string;
}

/** Upper bound for a plausible terminal grid; guards replay against a corrupt or hostile geometry. */
export const MAX_TERMINAL_GRID_DIMENSION = 2000;

/**
 * Round `value` into the grid range every terminal layer agrees on. Callers that
 * drive BOTH grids (xterm and the PTY) must normalize once and pass the same
 * number to each — clamping independently per layer is what lets the two sides
 * settle at different widths and never reconcile (#11641).
 */
export function normalizeTerminalGridDimension(value: number): number {
  if (!Number.isFinite(value)) return 1;
  return Math.max(1, Math.min(MAX_TERMINAL_GRID_DIMENSION, Math.floor(value)));
}

/**
 * True when `value` is a grid a terminal could actually have been captured at.
 * Replay sizes a real xterm to these numbers, so anything non-integral, zero,
 * negative or absurd must degrade to "no geometry" (replay verbatim) rather
 * than allocate a 2-billion-column buffer.
 */
export function isValidTerminalGeometry(value: unknown): value is TerminalGeometry {
  if (typeof value !== "object" || value === null) return false;
  const { cols, rows } = value as Partial<TerminalGeometry>;
  return (
    typeof cols === "number" &&
    typeof rows === "number" &&
    Number.isInteger(cols) &&
    Number.isInteger(rows) &&
    cols >= 1 &&
    rows >= 1 &&
    cols <= MAX_TERMINAL_GRID_DIMENSION &&
    rows <= MAX_TERMINAL_GRID_DIMENSION
  );
}

/**
 * The grid a container with no layout produces, which is the hole #12442 came
 * through. A hidden pane measures 0x0; FitAddon's own floor — and the
 * `colsForWidth`/`rowsForHeight` twins that reproduce it deliberately — answer
 * exactly 2x1, `normalizeTerminalGridDimension` maps a non-finite measurement to
 * 1, and `isValidTerminalGeometry` accepts both. Every layer downstream then
 * recorded that as a real measurement: the PTY, the snapshot header, the
 * persisted `terminalSizes` map. The CLI painted its frame into a 2-column PTY
 * and the overflow was in scrollback for good.
 *
 * Kept this low on purpose. It is the floor no REAL pane can reach, which is
 * what lets it be enforced unconditionally — including at the PTY boundary,
 * where a request's provenance is unknowable. A pane at the smallest supported
 * size (`MIN_TERMINAL_WIDTH_PX` x `MIN_TERMINAL_HEIGHT_PX`) and the largest
 * supported font measures about 23x4, so a floor that excluded four rows would
 * clip a pane somebody is looking at, permanently — trading this bug for a worse
 * one. {@link isPlausibleTerminalGeometry} is the strict floor, and it applies
 * only where nothing measured the grid at all.
 */
export const COLLAPSED_TERMINAL_COLS = 2;
export const COLLAPSED_TERMINAL_ROWS = 1;

/**
 * True when `value` is the degenerate grid an unlaid-out box yields rather than
 * a measurement — at or under {@link COLLAPSED_TERMINAL_COLS} x
 * {@link COLLAPSED_TERMINAL_ROWS}, or not a structurally valid grid at all.
 *
 * Phrased as a rejection test because that is how every call site reads it. A
 * collapsed grid is refused, never clamped upward: inventing a grid nobody
 * measured splits xterm from the PTY exactly as thoroughly as a tiny one does,
 * so callers hold the geometry they already have.
 */
export function isCollapsedTerminalGeometry(value: unknown): boolean {
  if (!isValidTerminalGeometry(value)) return true;
  return value.cols <= COLLAPSED_TERMINAL_COLS || value.rows <= COLLAPSED_TERMINAL_ROWS;
}

/**
 * Smallest grid a pane a user could actually work in describes.
 *
 * 20 columns is the floor `calculateTerminalDimensions` already refuses to
 * estimate below, so it is the number this codebase has long treated as the
 * narrowest pane worth booting. 5 rows is well under that estimator's 10-row
 * floor and still excludes the collapse.
 */
export const MIN_PLAUSIBLE_TERMINAL_COLS = 20;
export const MIN_PLAUSIBLE_TERMINAL_ROWS = 5;

/**
 * True when `value` is a grid a pane could plausibly have been MEASURED at.
 *
 * The strict floor, and the one that answers what #12442 actually asks. The
 * three origins it names all produce a number with no measurement behind it: a
 * grid derived from cached cell metrics with no live layout, a grid scaled for a
 * detached background view, and a grid replayed out of persistence or a target
 * cache. There, anything below a workable pane is evidence the box was never
 * laid out, and refusing costs only staleness — both grids stay put and the
 * reveal-time fresh measurement corrects them.
 *
 * It must NOT gate a live measurement of a visible box. A pane at the smallest
 * supported size and the largest supported font genuinely measures under this
 * floor, and refusing a real measurement leaves xterm bigger than its container
 * with its content clipped — permanently, since every later fit of that same
 * container refuses too. Those paths take {@link isCollapsedTerminalGeometry}.
 */
export function isPlausibleTerminalGeometry(value: unknown): value is TerminalGeometry {
  if (!isValidTerminalGeometry(value)) return false;
  return value.cols >= MIN_PLAUSIBLE_TERMINAL_COLS && value.rows >= MIN_PLAUSIBLE_TERMINAL_ROWS;
}
