// AUTO-GENERATED by scripts/codegen/portal-theme.ts — do not edit by hand.
// Run `npm run codegen:portal-theme` to regenerate from the TypeScript Daintree theme source.

const Map<String, Object?> generatedDaintreeAppearanceJson = <String, Object?>{
  "version": 1,
  "revision": 0,
  "themeId": "daintree",
  "displayName": "Daintree",
  "polarity": "dark",
  "surfaces": {
    "grid": "#0e0e0dff",
    "chrome": "#131312ff",
    "canvas": "#19191aff",
    "toolbar": "#131312ff",
    "panel": "#1d1d1eff",
    "elevatedPanel": "#2b2b2cff",
    "input": "#2b2b2cff",
    "inset": "#ffffff08",
    "hover": "#ffffff0d",
    "active": "#ffffff14"
  },
  "text": {
    "primary": "#e4e4e7ff",
    "secondary": "#a1a1aaff",
    "muted": "#8a8a93ff",
    "placeholder": "#8a8a93ff",
    "inverse": "#19191aff",
    "link": "#36ce94ff"
  },
  "borders": {
    "default": "#282828ff",
    "subtle": "#ffffff14",
    "strong": "#ffffff24",
    "divider": "#ffffff0d",
    "interactive": "#ffffff33"
  },
  "accent": {
    "primary": "#36ce94ff",
    "foreground": "#19191aff",
    "soft": "#36ce942e",
    "muted": "#36ce944d",
    "focusRing": "#36ce948c"
  },
  "status": {
    "success": {
      "foreground": "#6b8d72ff",
      "surface": "#6b8d721a"
    },
    "warning": {
      "foreground": "#c59a4eff",
      "surface": "#c59a4e1a"
    },
    "danger": {
      "foreground": "#c8746cff",
      "surface": "#c8746c1a"
    },
    "info": {
      "foreground": "#7b8c96ff",
      "surface": "#7b8c961a"
    }
  },
  "activity": {
    "active": {
      "foreground": "#2eb37cff",
      "surface": "#6b8d721a"
    },
    "idle": {
      "foreground": "#52525bff",
      "surface": "#ffffff0d"
    },
    "working": {
      "foreground": "#2eb37cff",
      "surface": "#6b8d721a"
    },
    "waiting": {
      "foreground": "#fbbf24ff",
      "surface": "#c59a4e1a"
    },
    "completed": {
      "foreground": "#6b8d72ff",
      "surface": "#6b8d721a"
    }
  },
  "terminal": {
    "background": "#19191aff",
    "foreground": "#e4e4e7ff",
    "muted": "#8a8a93ff",
    "cursor": "#36ce94ff",
    "cursorAccent": "#19191aff",
    "selection": "#1a2c22ff",
    "black": "#19191aff",
    "red": "#e07a70ff",
    "green": "#2fbf85ff",
    "yellow": "#ecb23fff",
    "blue": "#5fb3e8ff",
    "magenta": "#bf93ecff",
    "cyan": "#4fc8d8ff",
    "white": "#e4e4e7ff",
    "brightBlack": "#52525bff",
    "brightRed": "#eb9a91ff",
    "brightGreen": "#5bd6a4ff",
    "brightYellow": "#ecc777ff",
    "brightBlue": "#93cdf0ff",
    "brightMagenta": "#d4b0f2ff",
    "brightCyan": "#86dde2ff",
    "brightWhite": "#fafafaff"
  },
  "strategy": {
    "radiusScale": 1
  }
};

const Map<String, Object?> generatedBondiAppearanceJson = <String, Object?>{
  "version": 1,
  "revision": 0,
  "themeId": "bondi",
  "displayName": "Bondi Beach",
  "polarity": "light",
  "surfaces": {
    "grid": "#dcd8caff",
    "chrome": "#edeae0ff",
    "canvas": "#f3f1eaff",
    "toolbar": "#efeee9ff",
    "panel": "#f9f8f3ff",
    "elevatedPanel": "#ffffffff",
    "input": "#fdfcf8ff",
    "inset": "#f1efe8ff",
    "hover": "#322e2611",
    "active": "#322e261c"
  },
  "text": {
    "primary": "#1c2028ff",
    "secondary": "#454d56ff",
    "muted": "#555b62ff",
    "placeholder": "#1c202899",
    "inverse": "#fdfdfeff",
    "link": "#0f5b41ff"
  },
  "borders": {
    "default": "#d1cdc3ff",
    "subtle": "#0f141b17",
    "strong": "#0f141b2e",
    "divider": "#0f141b16",
    "interactive": "#0f141b33"
  },
  "accent": {
    "primary": "#178463ff",
    "foreground": "#fdfdfeff",
    "soft": "#1784632e",
    "muted": "#1784634d",
    "focusRing": "#17846359"
  },
  "status": {
    "success": {
      "foreground": "#1c7b54ff",
      "surface": "#1c7b5414"
    },
    "warning": {
      "foreground": "#9d6309ff",
      "surface": "#9d630914"
    },
    "danger": {
      "foreground": "#a83c34ff",
      "surface": "#a83c3414"
    },
    "info": {
      "foreground": "#1e6fa0ff",
      "surface": "#1e6fa014"
    }
  },
  "activity": {
    "active": {
      "foreground": "#1c7b54ff",
      "surface": "#1c7b5414"
    },
    "idle": {
      "foreground": "#5f6a76ff",
      "surface": "#322e2611"
    },
    "working": {
      "foreground": "#1c7b54ff",
      "surface": "#1c7b5414"
    },
    "waiting": {
      "foreground": "#97680dff",
      "surface": "#9d630914"
    },
    "completed": {
      "foreground": "#1c7b54ff",
      "surface": "#1c7b5414"
    }
  },
  "terminal": {
    "background": "#1e252eff",
    "foreground": "#c8d0d9ff",
    "muted": "#6b7783ff",
    "cursor": "#f5b814ff",
    "cursorAccent": "#1e252eff",
    "selection": "#123941ff",
    "black": "#1c2028ff",
    "red": "#e05c5cff",
    "green": "#2ebd88ff",
    "yellow": "#f5b814ff",
    "blue": "#37a6d9ff",
    "magenta": "#ae6bf2ff",
    "cyan": "#0fa8c0ff",
    "white": "#c8d0d9ff",
    "brightBlack": "#66727fff",
    "brightRed": "#f07f77ff",
    "brightGreen": "#56d1a3ff",
    "brightYellow": "#efca61ff",
    "brightBlue": "#7ec9edff",
    "brightMagenta": "#c39deeff",
    "brightCyan": "#6fdbe1ff",
    "brightWhite": "#e8f4fdff"
  },
  "strategy": {
    "radiusScale": 1
  }
};
