// Generated by `npm run tour:audio` — do not edit by hand.
import type { TourTimingManifest } from "./tourTypes";

export const TOUR_TIMING_MANIFEST: TourTimingManifest = {
  version: 1,
  voice: "inworld-simon",
  chapters: {
    welcome: {
      duration: 16.507,
      cues: {
        first: 6.94,
        grid: 9.04,
      },
      captions: [
        {
          start: 0,
          end: 1.54,
          text: "Welcome to Daintree.",
        },
        {
          start: 1.54,
          end: 6.94,
          text: "It's one window for the coding agents you already use, like Claude Code and Codex.",
        },
        {
          start: 6.94,
          end: 14.02,
          text: "Instead of juggling terminal tabs, you run several of them side by side, and keep an eye on all of them at once.",
        },
        {
          start: 14.02,
          end: 16.507,
          text: "Let's take a quick look around.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/welcome-ae60e660417c.ogg",
      narrationHash: "9d3c7a5c",
      voice: "inworld-simon",
    },
    worktrees: {
      duration: 20.927,
      cues: {
        list: 4.13,
        plus: 15.01,
        name: 17.7,
        create: 18.67,
      },
      captions: [
        {
          start: 0.03,
          end: 4.13,
          text: "Everything starts with a project: any git repository you open.",
        },
        {
          start: 4.13,
          end: 6.37,
          text: "Its worktrees sit down the left.",
        },
        {
          start: 6.37,
          end: 15.01,
          text: "Each one is a separate working folder on its own branch, so use one per task, and agents on different tasks never touch each other's files.",
        },
        {
          start: 15.01,
          end: 20.927,
          text: "To start a new task, click the plus button, name its branch, and create the worktree.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/worktrees-01c3d4c939ff.ogg",
      narrationHash: "0d3a08fd",
      voice: "inworld-simon",
    },
    agents: {
      duration: 22.067,
      cues: {
        pick: 6.92,
        click: 9.2,
        open: 9.86,
        type: 13.1,
        send: 18.2,
      },
      captions: [
        {
          start: 0.03,
          end: 6.92,
          text: "Daintree works with whichever agent command line tools you've installed, like Claude Code, Codex, or Antigravity.",
        },
        {
          start: 6.92,
          end: 9.2,
          text: "Each one gets a button in the toolbar.",
        },
        {
          start: 9.2,
          end: 13.1,
          text: "Click it, and the agent opens in a panel inside the current worktree.",
        },
        {
          start: 13.1,
          end: 18.2,
          text: "Type into the bar at the bottom of the panel, or click into the terminal and type there directly.",
        },
        {
          start: 18.2,
          end: 22.067,
          text: "Press Enter, and your prompt goes straight to the agent.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/agents-4a1f90d0c6f7.ogg",
      narrationHash: "23ba2c7d",
      voice: "inworld-simon",
    },
    state: {
      duration: 21.467,
      cues: {
        working: 3.27,
        waiting: 5.18,
        done: 8.14,
        pill: 11.93,
        jump: 15.67,
        answer: 17.76,
      },
      captions: [
        {
          start: 0.03,
          end: 3.27,
          text: "Every panel shows what Daintree can see of its agent.",
        },
        {
          start: 3.27,
          end: 5.18,
          text: "A spinner means it's working.",
        },
        {
          start: 5.18,
          end: 11.93,
          text: "A hollow circle means it looks like it's waiting for you, and a check means it's finished its turn, ready for you to review.",
        },
        {
          start: 11.93,
          end: 15.67,
          text: "When agents are waiting, the counter at the bottom right shows how many.",
        },
        {
          start: 15.67,
          end: 21.467,
          text: "Click it to jump straight to one, answer it in its panel, and it gets back to work.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/state-e6e941b6288a.ogg",
      narrationHash: "543ac1c7",
      voice: "inworld-simon",
    },
    fleet: {
      duration: 21.907,
      cues: {
        pick: 3.38,
        bolt: 5.71,
        armed: 12.66,
        type: 15.73,
        send: 17.38,
      },
      captions: [
        {
          start: 0,
          end: 3.38,
          text: "A fleet is a group of agents that all receive the same prompt.",
        },
        {
          start: 3.38,
          end: 10.33,
          text: "Shift-click each panel you want in it, or use the lightning bolt in the sidebar to add every agent in a worktree.",
        },
        {
          start: 10.33,
          end: 12.66,
          text: "Shift-click again to take one out.",
        },
        {
          start: 12.66,
          end: 15.73,
          text: "Panels in the fleet are marked with a small radio tower.",
        },
        {
          start: 15.73,
          end: 21.907,
          text: "Now type in any one of them, press Enter, and every agent in the fleet gets the prompt.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/fleet-6af3408f71e1.ogg",
      narrationHash: "a19786e2",
      voice: "inworld-simon",
    },
    review: {
      duration: 18.507,
      cues: {
        files: 6.61,
        open: 9.62,
        diff: 12.59,
        commit: 14.04,
      },
      captions: [
        {
          start: 0.06,
          end: 4.82,
          text: "When an agent finishes, you can simply ask it to commit and push the work for you.",
        },
        {
          start: 4.82,
          end: 9.62,
          text: "If you'd rather review it yourself, its worktree in the sidebar shows what changed.",
        },
        {
          start: 9.62,
          end: 14.04,
          text: "Press Review and Commit to see every file that changed, and step through the diff.",
        },
        {
          start: 14.04,
          end: 18.507,
          text: "Then write a message, and commit and push the branch, right from here.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/review-121ee75dc8e1.ogg",
      narrationHash: "3efc52a2",
      voice: "inworld-simon",
    },
    files: {
      duration: 16.507,
      cues: {
        open: 2.52,
        pick: 8.73,
        ref: 11.03,
      },
      captions: [
        {
          start: 0,
          end: 2.52,
          text: "You don't need to leave Daintree to look at the code.",
        },
        {
          start: 2.52,
          end: 8.73,
          text: "Browse files in the toolbar opens the current worktree's files in a panel, right beside your agents.",
        },
        {
          start: 8.73,
          end: 11.03,
          text: "Click any file to view its source.",
        },
        {
          start: 11.03,
          end: 16.507,
          text: "And drag any file onto an agent's panel to drop its path into the prompt.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/files-93471104c816.ogg",
      narrationHash: "196eeb2d",
      voice: "inworld-simon",
    },
    context: {
      duration: 21.027,
      cues: {
        copy: 9.32,
        paste: 14.47,
        portal: 18.52,
      },
      captions: [
        {
          start: 0,
          end: 9.32,
          text: "Sometimes you'll want a web-based agent, like ChatGPT or Claude on the web, to see your whole codebase, since they often come with much bigger allowances.",
        },
        {
          start: 9.32,
          end: 14.47,
          text: "Copy context in the toolbar packs the entire worktree into one block on your clipboard.",
        },
        {
          start: 14.47,
          end: 21.027,
          text: "Paste it into any web chat, including the ones in Daintree's Portal, right here in the side panel.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/context-71e740194b83.ogg",
      narrationHash: "6dbdd7c9",
      voice: "inworld-simon",
    },
    preview: {
      duration: 20.447,
      cues: {
        launch: 4.9,
        start: 9.6,
        live: 13.09,
        console: 15.89,
      },
      captions: [
        {
          start: 0,
          end: 4.9,
          text: "For a web project, you can watch your app change while the agents work on it.",
        },
        {
          start: 4.9,
          end: 9.6,
          text: "Open the launcher from the plus in the toolbar, and pick Dev preview.",
        },
        {
          start: 9.6,
          end: 15.89,
          text: "Daintree finds your dev script and starts the server for you, and the page updates as the code changes.",
        },
        {
          start: 15.89,
          end: 20.447,
          text: "The server's logs and the browser console sit just below it.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/preview-11060ab9e756.ogg",
      narrationHash: "cf5a82cc",
      voice: "inworld-simon",
    },
    github: {
      duration: 22.027,
      cues: {
        pill: 4.58,
        list: 10.27,
        pick: 11.7,
        badge: 15.35,
      },
      captions: [
        {
          start: 0,
          end: 4.58,
          text: "Daintree works with whichever code forge you're on, GitHub or GitLab.",
        },
        {
          start: 4.58,
          end: 10.27,
          text: "Once your project is connected, the counts in the toolbar are its open issues and pull requests.",
        },
        {
          start: 10.27,
          end: 15.35,
          text: "Click one to browse them, and choose an issue to start a worktree for it, already linked.",
        },
        {
          start: 15.35,
          end: 22.027,
          text: "Later, once a pull request is open, its status and automated checks show right on the worktree's card.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/github-cc8c998ed254.ogg",
      narrationHash: "f70d09d6",
      voice: "inworld-simon",
    },
    pilot: {
      duration: 18.387,
      cues: {
        open: 2.86,
        sort: 6.11,
        park: 12.72,
      },
      captions: [
        {
          start: 0,
          end: 6.11,
          text: "Once you have agents running in more than one project, press Command Option O to open Pilot.",
        },
        {
          start: 6.11,
          end: 12.72,
          text: "It lists every agent everywhere, grouped by project, with whatever is waiting on you at the top of each group.",
        },
        {
          start: 12.72,
          end: 18.387,
          text: "Anything that can wait, you can park, and it stays out of your way until you're ready.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/pilot-8695ef74d3e6.ogg",
      narrationHash: "2efbe841",
      voice: "inworld-simon",
    },
    assistant: {
      duration: 26.907,
      cues: {
        open: 7.1,
        ask: 9.29,
        act: 11.74,
        watch: 16.48,
        runs: 19.82,
      },
      captions: [
        {
          start: 0,
          end: 7.1,
          text: "Finally, the Daintree Assistant: an agent that runs Daintree for you, while your other agents write the code.",
        },
        {
          start: 7.1,
          end: 9.29,
          text: "Open it from the right of the toolbar.",
        },
        {
          start: 9.29,
          end: 16.48,
          text: "Ask for what you want in plain words, and it creates worktrees, starts agents, and sends them their instructions.",
        },
        {
          start: 16.48,
          end: 19.82,
          text: "Then it keeps an eye on them, and tells you when one needs you.",
        },
        {
          start: 19.82,
          end: 26.907,
          text: "It runs on an agent you already have, like Claude Code or Codex, so there's nothing extra to set up.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/assistant-d34ae43d15b1.ogg",
      narrationHash: "91c954cc",
      voice: "inworld-simon",
    },
    palette: {
      duration: 15.127,
      cues: {
        palette: 2.25,
        help: 8.63,
      },
      captions: [
        {
          start: 0,
          end: 4.35,
          text: "When you can't remember where something lives, press Command Shift P.",
        },
        {
          start: 4.35,
          end: 8.63,
          text: "Type what you want to do, and every action in Daintree is right there.",
        },
        {
          start: 8.63,
          end: 15.127,
          text: "The Help menu has this tour, the Getting Started checklist, and all the keyboard shortcuts.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/palette-fd4194f13ebf.ogg",
      narrationHash: "b4acb39e",
      voice: "inworld-simon",
    },
    outro: {
      duration: 15.926,
      cues: {
        logo: 0,
        why: 5.69,
        next: 11.02,
      },
      captions: [
        {
          start: 0,
          end: 1.25,
          text: "That's Daintree.",
        },
        {
          start: 1.25,
          end: 11.02,
          text: "The agents you already use, side by side, each on its own task, and one place to see what they're doing, step in when they need you, and ship what they build.",
        },
        {
          start: 11.02,
          end: 15.926,
          text: "Next, the Getting Started checklist walks you through your first task.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/outro-fd7a079a7868.ogg",
      narrationHash: "a8ad537d",
      voice: "inworld-simon",
    },
  },
};
