// Generated by `npm run tour:audio` — do not edit by hand.
import type { TourTimingManifest } from "./tourTypes";

export const TOUR_TIMING_MANIFEST: TourTimingManifest = {
  version: 1,
  voice: "inworld-simon",
  chapters: {
    welcome: {
      duration: 14.127,
      cues: {
        first: 1.49,
        grid: 6.28,
      },
      captions: [
        {
          start: 0,
          end: 1.49,
          text: "Welcome to Daintree.",
        },
        {
          start: 1.49,
          end: 4.14,
          text: "It's a home for your AI coding agents.",
        },
        {
          start: 4.14,
          end: 11.57,
          text: "Instead of juggling terminal tabs, you run several agents side by side, and keep an eye on all of them from one window.",
        },
        {
          start: 11.57,
          end: 14.127,
          text: "Let's take a quick look around.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/welcome-98289a45686c.ogg",
      narrationHash: "8a31d867",
    },
    worktrees: {
      duration: 20.147,
      cues: {
        list: 4.16,
        plus: 14.16,
        name: 16.89,
        create: 17.91,
      },
      captions: [
        {
          start: 0.03,
          end: 4.16,
          text: "Everything starts with a project, which is any git repository.",
        },
        {
          start: 4.16,
          end: 6.32,
          text: "Its worktrees sit down the left.",
        },
        {
          start: 6.32,
          end: 14.16,
          text: "Each one is a separate copy of the repo on its own branch, so agents working on different tasks never trip over each other's changes.",
        },
        {
          start: 14.16,
          end: 20.147,
          text: "To start something new, click the plus button, name the branch, and create the worktree.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/worktrees-4976b795f1cb.ogg",
      narrationHash: "766f81ad",
    },
    agents: {
      duration: 16.767,
      cues: {
        pick: 5.88,
        open: 7.43,
        type: 10.42,
        send: 12.75,
      },
      captions: [
        {
          start: 0.08,
          end: 5.88,
          text: "Daintree works with the agent tools you already have, like Claude Code, Codex, and Gemini.",
        },
        {
          start: 5.88,
          end: 10.42,
          text: "Click an agent in the toolbar, and it opens in a panel inside the current worktree.",
        },
        {
          start: 10.42,
          end: 12.75,
          text: "Type into the bar at the bottom of the panel.",
        },
        {
          start: 12.75,
          end: 16.767,
          text: "Press Enter, and your prompt goes straight to the agent.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/agents-109c93cf3273.ogg",
      narrationHash: "7a8d2e1d",
    },
    state: {
      duration: 16.067,
      cues: {
        working: 3.43,
        waiting: 5.39,
        done: 8.42,
        pill: 10.39,
        jump: 13.31,
      },
      captions: [
        {
          start: 0.06,
          end: 3.43,
          text: "Every panel shows what Daintree can see of its agent.",
        },
        {
          start: 3.43,
          end: 5.39,
          text: "A spinner means it's working.",
        },
        {
          start: 5.39,
          end: 10.39,
          text: "A hollow circle means it looks like it's waiting for you, and a check means it's finished.",
        },
        {
          start: 10.39,
          end: 13.31,
          text: "When agents are waiting, the dock shows how many.",
        },
        {
          start: 13.31,
          end: 16.067,
          text: "Click it to jump straight to them.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/state-82af15593937.ogg",
      narrationHash: "801931cf",
    },
    fleet: {
      duration: 17.307,
      cues: {
        menu: 3.24,
        armed: 7.88,
        type: 11.11,
        send: 12.89,
      },
      captions: [
        {
          start: 0,
          end: 3.24,
          text: "Sometimes several agents need the same instruction.",
        },
        {
          start: 3.24,
          end: 7.88,
          text: "Right-click a panel and choose Add to fleet, or press Command J.",
        },
        {
          start: 7.88,
          end: 11.11,
          text: "Panels in the fleet are marked with a small radio tower.",
        },
        {
          start: 11.11,
          end: 17.307,
          text: "Now type in any one of them, press Enter, and the prompt goes to the whole fleet at once.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/fleet-083ff28bc23c.ogg",
      narrationHash: "9c482db6",
    },
    review: {
      duration: 17.807,
      cues: {
        files: 3.94,
        diff: 7.36,
        commit: 9.11,
        outro: 12.65,
      },
      captions: [
        {
          start: 0,
          end: 3.94,
          text: "When an agent finishes, check its work before it goes anywhere.",
        },
        {
          start: 3.94,
          end: 9.11,
          text: "Open the worktree's changes to see every file it touched, and step through the diff.",
        },
        {
          start: 9.11,
          end: 12.65,
          text: "Then write a message, and commit and push, right from here.",
        },
        {
          start: 12.65,
          end: 13.85,
          text: "That's the essentials.",
        },
        {
          start: 13.85,
          end: 17.807,
          text: "You can replay this tour any time from the Help menu.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/review-a5a661d7ebe6.ogg",
      narrationHash: "c76f7faa",
    },
  },
};
