// Generated by `npm run tour:audio` — do not edit by hand.
import type { TourTimingManifest } from "./tourTypes";

export const TOUR_TIMING_MANIFEST: TourTimingManifest = {
  version: 1,
  voice: "inworld-simon",
  chapters: {
    welcome: {
      duration: 16.487,
      cues: {
        first: 5.03,
        second: 5.85,
        grid: 9.07,
        watch: 11.7,
      },
      captions: [
        {
          start: 0,
          end: 1.62,
          text: "Welcome to Daintree.",
        },
        {
          start: 1.62,
          end: 6.9,
          text: "It's one window for the coding agents you already use, like Claude Code and Codex.",
        },
        {
          start: 6.9,
          end: 13.96,
          text: "Instead of juggling terminal tabs, you run several of them side by side, and keep an eye on all of them at once.",
        },
        {
          start: 13.96,
          end: 16.487,
          text: "Let's take a quick look around.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/welcome-8639e3f2b920.ogg",
      narrationHash: "a383ea0c",
      voice: "inworld-simon",
    },
    worktrees: {
      duration: 25.487,
      cues: {
        project: 0.93,
        list: 5.09,
        branch: 9.32,
        plus: 15.72,
        name: 18.29,
        create: 20.38,
      },
      captions: [
        {
          start: 0.03,
          end: 3.36,
          text: "Everything starts with a project: any folder you open.",
        },
        {
          start: 3.36,
          end: 7.19,
          text: "When it's a git repository, its worktrees sit down the left.",
        },
        {
          start: 7.19,
          end: 15.72,
          text: "Each one is a separate working folder on its own branch, so use one per task, and agents on different tasks don't step on each other's files.",
        },
        {
          start: 15.72,
          end: 21.88,
          text: "To start a new task, click the plus button, name its branch, like add search, and create the worktree.",
        },
        {
          start: 21.88,
          end: 25.487,
          text: "It opens empty, ready for its first agent.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/worktrees-a23de8c83fad.ogg",
      narrationHash: "3dd1be0b",
      voice: "inworld-simon",
    },
    agents: {
      duration: 26.587,
      cues: {
        agents: 3.87,
        pick: 7.29,
        launcher: 9.48,
        click: 12.77,
        open: 13.67,
        type: 16.78,
        send: 19.57,
        term: 21.41,
      },
      captions: [
        {
          start: 0,
          end: 7.29,
          text: "Daintree works with any agent command line tool you've installed, like Claude Code, Codex, or Antigravity.",
        },
        {
          start: 7.29,
          end: 12.77,
          text: "Your agents get buttons in the toolbar, and the plus button lists every one you have installed.",
        },
        {
          start: 12.77,
          end: 16.78,
          text: "Click one, and it opens in a panel inside the current worktree.",
        },
        {
          start: 16.78,
          end: 21.41,
          text: "Type your prompt into the bar at the bottom of the panel, and press Enter to send it.",
        },
        {
          start: 21.41,
          end: 26.587,
          text: "Or click into the terminal itself and type there, just like any other terminal.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/agents-96ca0ea416c6.ogg",
      narrationHash: "622428a8",
      voice: "inworld-simon",
    },
    state: {
      duration: 20.747,
      cues: {
        working: 3.05,
        waiting: 4.91,
        done: 7.69,
        pill: 11.03,
        jump: 14.75,
        pick: 16.18,
        answer: 17.81,
      },
      captions: [
        {
          start: 0.03,
          end: 3.05,
          text: "Every panel shows what Daintree can see of its agent.",
        },
        {
          start: 3.05,
          end: 4.91,
          text: "A spinner means it's working.",
        },
        {
          start: 4.91,
          end: 11.03,
          text: "A hollow circle means it looks like it's waiting for you, and a check means it looks finished, ready for you to review.",
        },
        {
          start: 11.03,
          end: 14.75,
          text: "When agents are waiting, the counter at the bottom right shows how many.",
        },
        {
          start: 14.75,
          end: 20.747,
          text: "Click it to see which ones, pick one to jump to its panel, answer it, and it gets back to work.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/state-1a96f0a312bf.ogg",
      narrationHash: "8f953bfb",
      voice: "inworld-simon",
    },
    fleet: {
      duration: 25.567,
      cues: {
        pick: 3.7,
        out: 6.28,
        armed: 8.65,
        bolt: 11.44,
        type: 15.38,
        send: 19.13,
        exit: 21.86,
      },
      captions: [
        {
          start: 0.03,
          end: 3.7,
          text: "A fleet is a group of agents that all receive the same prompt.",
        },
        {
          start: 3.7,
          end: 8.65,
          text: "Shift-click a panel's title bar to add it, and shift-click again to take it out.",
        },
        {
          start: 8.65,
          end: 11.44,
          text: "Panels in the fleet show a small radio tower.",
        },
        {
          start: 11.44,
          end: 15.38,
          text: "You can also click the lightning bolt in the sidebar to pick them from a list.",
        },
        {
          start: 15.38,
          end: 19.13,
          text: "Now type in any one of them, and your words appear in the others too.",
        },
        {
          start: 19.13,
          end: 21.86,
          text: "Press Enter, and every agent gets the prompt.",
        },
        {
          start: 21.86,
          end: 25.567,
          text: "Click any panel without Shift to leave the fleet.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/fleet-342c1e571257.ogg",
      narrationHash: "bb50f9e2",
      voice: "inworld-simon",
    },
    review: {
      duration: 19.107,
      cues: {
        ask: 2.04,
        files: 6.5,
        open: 9.27,
        diff: 12.55,
        commit: 14.08,
      },
      captions: [
        {
          start: 0,
          end: 4.74,
          text: "When an agent finishes, you can simply ask it to commit and push the work for you.",
        },
        {
          start: 4.74,
          end: 9.27,
          text: "If you'd rather review it yourself, its worktree in the sidebar shows what changed.",
        },
        {
          start: 9.27,
          end: 14.08,
          text: "Press Review and commit to see every file that changed, and step through the diff.",
        },
        {
          start: 14.08,
          end: 19.107,
          text: "Then write a message, and commit and push the branch, right from here.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/review-b599b67dc29b.ogg",
      narrationHash: "4d02b14a",
      voice: "inworld-simon",
    },
    files: {
      duration: 18.147,
      cues: {
        open: 2.62,
        pick: 8.9,
        ref: 11.21,
        drop: 13.23,
      },
      captions: [
        {
          start: 0.06,
          end: 2.62,
          text: "You don't need to leave Daintree to look at the code.",
        },
        {
          start: 2.62,
          end: 8.9,
          text: "Browse files in the toolbar opens the current worktree's files in a panel, right beside your agents.",
        },
        {
          start: 8.9,
          end: 11.21,
          text: "Click any file to view its source.",
        },
        {
          start: 11.21,
          end: 18.147,
          text: "Then drag it onto an agent's panel, and a reference to that file drops into the prompt bar, ready to send.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/files-dc9a7a128692.ogg",
      narrationHash: "d01455a2",
      voice: "inworld-simon",
    },
    context: {
      duration: 18.527,
      cues: {
        copy: 8.11,
        portal: 13.43,
        paste: 15.41,
      },
      captions: [
        {
          start: 0,
          end: 8.11,
          text: "Web chats like ChatGPT or Claude often come with bigger allowances, so sometimes you'll want them to see your whole codebase.",
        },
        {
          start: 8.11,
          end: 13.43,
          text: "Copy context in the toolbar copies the entire worktree to your clipboard in one go.",
        },
        {
          start: 13.43,
          end: 18.527,
          text: "Open the Portal in the side panel, and paste it into any web chat there.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/context-5f81fe32ff10.ogg",
      narrationHash: "489bd8e2",
      voice: "inworld-simon",
    },
    preview: {
      duration: 22.107,
      cues: {
        launch: 4.52,
        pickpreview: 7.62,
        start: 13.13,
        live: 14.01,
        console: 16.67,
      },
      captions: [
        {
          start: 0,
          end: 4.52,
          text: "For a web project, you can watch your app change while the agents work on it.",
        },
        {
          start: 4.52,
          end: 9.08,
          text: "Open the launcher from the plus in the toolbar, and pick Dev preview.",
        },
        {
          start: 9.08,
          end: 13.13,
          text: "The first time, Daintree finds your dev script and asks to run it.",
        },
        {
          start: 13.13,
          end: 16.67,
          text: "Click Run, and the page updates as the code changes.",
        },
        {
          start: 16.67,
          end: 22.107,
          text: "The console button opens the server's logs and the browser console underneath.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/preview-02b37c9fb4a1.ogg",
      narrationHash: "331508b0",
      voice: "inworld-simon",
    },
    github: {
      duration: 32.187,
      cues: {
        pill: 4.42,
        list: 10.97,
        pick: 16.76,
        choose: 18.28,
        create: 22.58,
        badge: 25.87,
      },
      captions: [
        {
          start: 0.03,
          end: 4.42,
          text: "Daintree works with whichever code forge you're on, GitHub or GitLab.",
        },
        {
          start: 4.42,
          end: 10.97,
          text: "Once you add your token in Settings, the counts in the toolbar are the project's open issues and pull requests.",
        },
        {
          start: 10.97,
          end: 12.66,
          text: "Click one to browse them.",
        },
        {
          start: 12.66,
          end: 20.1,
          text: "Clicking an issue's title opens it in your browser; to work on it here, open its actions menu and choose Create worktree.",
        },
        {
          start: 20.1,
          end: 22.58,
          text: "The form opens with the branch already named.",
        },
        {
          start: 22.58,
          end: 25.87,
          text: "Create it, and the worktree stays tied to that issue.",
        },
        {
          start: 25.87,
          end: 32.187,
          text: "Later, once a pull request is open, its status and checks show right on the worktree's card.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/github-33a2b331ed03.ogg",
      narrationHash: "18f5d2b2",
      voice: "inworld-simon",
    },
    pilot: {
      duration: 19.647,
      cues: {
        open: 2.94,
        sort: 8.16,
        park: 10.9,
      },
      captions: [
        {
          start: 0,
          end: 6.47,
          text: "Once you have agents running in more than one project, press Command Option O to see all your agents at once.",
        },
        {
          start: 6.47,
          end: 10.9,
          text: "They're grouped by project, with whatever is waiting on you at the top of each group.",
        },
        {
          start: 10.9,
          end: 14.44,
          text: "If something can wait, press Option Enter to park it.",
        },
        {
          start: 14.44,
          end: 19.647,
          text: "The agent keeps running, but it stops asking for your attention until you're ready.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/pilot-8b1da895dafa.ogg",
      narrationHash: "63850fed",
      voice: "inworld-simon",
    },
    assistant: {
      duration: 27.587,
      cues: {
        open: 7.09,
        start: 9.2,
        ask: 10.31,
        act: 12.52,
        watch: 17.23,
        tell: 18.73,
        runs: 20.44,
      },
      captions: [
        {
          start: 0,
          end: 7.09,
          text: "Finally, the Daintree Assistant: an agent that runs Daintree for you, while your other agents write the code.",
        },
        {
          start: 7.09,
          end: 10.31,
          text: "Open it from the right of the toolbar, and start it.",
        },
        {
          start: 10.31,
          end: 17.23,
          text: "Ask for what you want in plain words, and it creates worktrees, starts agents, and sends them their instructions.",
        },
        {
          start: 17.23,
          end: 20.44,
          text: "Then it keeps an eye on them, and tells you when one needs you.",
        },
        {
          start: 20.44,
          end: 27.587,
          text: "It runs on an agent you already have, like Claude Code or Codex, so there's no extra subscription.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/assistant-9cabfd22ba58.ogg",
      narrationHash: "c3cc547f",
      voice: "inworld-simon",
    },
    palette: {
      duration: 14.766,
      cues: {
        palette: 2.19,
        type: 4.19,
        help: 8.36,
      },
      captions: [
        {
          start: 0.06,
          end: 4.19,
          text: "When you can't remember where something lives, press Command Shift P.",
        },
        {
          start: 4.19,
          end: 8.36,
          text: "Type what you want to do, and every action in Daintree is right there.",
        },
        {
          start: 8.36,
          end: 14.766,
          text: "The Help menu has this tour, the Getting Started checklist, and all the keyboard shortcuts.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/palette-4da818618bb4.ogg",
      narrationHash: "c9b12358",
      voice: "inworld-simon",
    },
    outro: {
      duration: 16.587,
      cues: {
        logo: 0,
        side: 2.85,
        task: 4.42,
        see: 6.54,
        ship: 9.61,
        next: 11.1,
      },
      captions: [
        {
          start: 0,
          end: 1.28,
          text: "That's Daintree.",
        },
        {
          start: 1.28,
          end: 11.1,
          text: "The agents you already use, side by side, each on its own task, and one place to see what they're doing, step in when they need you, and ship what they build.",
        },
        {
          start: 11.1,
          end: 16.587,
          text: "Next, the Getting Started checklist walks you through running your first agents.",
        },
      ],
      audioUrl: "https://cdn.daintree.org/tour/inworld-simon/outro-54a66c117161.ogg",
      narrationHash: "f1e91cc7",
      voice: "inworld-simon",
    },
  },
};
