// Generated by `npm run tour:audio` — do not edit by hand.

/** The tour's length in whole minutes, from the same timings the player uses. */
export const TOUR_MINUTES = 5;

/** Chapter titles in play order. */
export const TOUR_CHAPTER_TITLES: readonly string[] = [
  "Welcome to Daintree",
  "One task, one worktree",
  "Launch any installed agent",
  "See who needs you",
  "One prompt, many agents",
  "Browse your files",
  "Hand your codebase to a web chat",
  "Preview your app live",
  "Work from your issues",
  "Review and push",
  "All your agents at once",
  "Meet the Daintree Assistant",
  "Find anything",
  "That's Daintree",
];
