import { CHANNEL_LOCALITY, getChannelLocality } from "./channelLocality.js";

/**
 * Who may call each host-side channel while a project's drive lease is held
 * (see `DriveLeaseService`).
 *
 * - `free`: anyone attached to the project may call it: reads, a view's own
 *   attachment and flow control, host-wide settings, and taking the lease.
 * - `driver`: it changes a project (worktrees, git, terminals, the saved
 *   layout, project settings), so only that project's lease holder may call
 *   it, or anyone while nobody holds it. Refused with `DRIVEN_ELSEWHERE`. The
 *   project is the one the call targets, found through
 *   {@link CHANNEL_LEASE_TARGETS}, not the one the caller is showing.
 * - `handler`: the handler enforces the lease itself, per terminal rather
 *   than per caller's project (terminal input, submit and resizes).
 *
 * The dispatcher applies it to link calls from remote views, and to calls
 * from this machine's own views once the lease service exists (Host mode);
 * without it, as for anyone who never used Remote Hosts, nothing is checked.
 * A local view's hybrid call mixes this machine's fields into the same write,
 * so only its `host` channels are checked here; a link call's hybrid host leg
 * is. `app:set-state`'s handler holds a local view's host-owned fields to the
 * lease itself.
 *
 * The record is total over the host and hybrid channels, so a new one that
 * doesn't declare its policy fails typecheck.
 */
export type LeasePolicy = "free" | "driver" | "handler";

type HostSideChannel = {
  [K in keyof typeof CHANNEL_LOCALITY]: (typeof CHANNEL_LOCALITY)[K] extends "shell" ? never : K;
}[keyof typeof CHANNEL_LOCALITY];

export const CHANNEL_LEASE_POLICY = {
  "agent-capabilities:get-agent-ids": "free",
  "agent-capabilities:get-agent-metadata": "free",
  "agent-capabilities:get-ccr-presets": "free",
  "agent-capabilities:get-registry": "free",
  "agent-capabilities:get-resolved-model-list": "free",
  "agent-capabilities:is-agent-enabled": "free",
  "agent-help:get": "free",
  "agent-presets:updated": "free",
  "agent-session:clear": "free",
  "agent-session:delete-bookmark": "free",
  "agent-session:get-retention": "free",
  "agent-session:list": "free",
  "agent-session:list-bookmarks": "free",
  "agent-session:prepare-bookmark": "driver",
  "agent-session:promote-bookmark": "free",
  "agent-session:rename-bookmark": "free",
  "agent-session:set-retention": "free",
  "agent-settings:get": "free",
  "agent-settings:reset": "free",
  "agent-settings:set": "free",
  "agent-settings:set-global": "free",
  "agent-settings:set-global-inline": "free",
  "agent-settings:stamp-version": "free",
  "app-agent:confirmation-response": "free",
  "app-agent:dispatch-action-response": "free",
  "app-agent:get-config": "free",
  "app-agent:has-api-key": "free",
  "app-agent:set-config": "free",
  "app-agent:test-api-key": "free",
  "app-agent:test-model": "free",
  "app:boot": "free",
  "app:clear-quarantined-panel": "free",
  "app:config-reloaded": "free",
  "app:get-state": "free",
  "app:hydrate": "free",
  "app:reload-config": "free",
  "app:set-state": "driver",
  "artifact:apply-patch": "driver",
  "artifact:detected": "free",
  "artifact:save-to-file": "driver",
  "claude:list-subagents": "free",
  "claude:read-subagent-transcript": "free",
  "clipboard:pick-attachments": "free",
  "clipboard:save-image": "free",
  "clipboard:thumbnail-from-path": "free",
  "codex:find-sessions": "free",
  "codex:list-subagents": "free",
  "codex:read-quota": "free",
  "codex:refresh-quota": "free",
  "codex:read-subagent-transcript": "free",
  "codex:resolve-resume-latest-session": "free",
  "commands:execute": "driver",
  "commands:get": "free",
  "commands:get-builder": "free",
  "commands:list": "free",
  "config-bundle:apply-import": "free",
  "config-bundle:export": "free",
  "config-bundle:imported": "free",
  "config-bundle:preview-import": "free",
  "connectivity:get-state": "free",
  "connectivity:service-changed": "free",
  "copy-tree-history:get-records": "free",
  "copytree:available": "free",
  "copytree:cancel": "free",
  "copytree:generate": "free",
  "copytree:generate-and-copy-file": "free",
  "copytree:get-file-tree": "free",
  "copytree:inject": "driver",
  "copytree:progress": "free",
  "copytree:test-config": "free",
  "dev-preview:all-sessions-changed": "free",
  "dev-preview:ensure": "driver",
  "dev-preview:get-all-sessions": "free",
  "dev-preview:get-by-worktree": "free",
  "dev-preview:get-destructive-preview-meta": "free",
  "dev-preview:get-destructive-preview-sizes": "free",
  "dev-preview:get-diagnostics": "free",
  "dev-preview:get-proxy-port": "free",
  "dev-preview:get-state": "free",
  "dev-preview:mint-browser-token": "free",
  "dev-preview:reinstall-and-restart": "driver",
  "dev-preview:restart": "driver",
  "dev-preview:restart-and-clear-cache": "driver",
  "dev-preview:restart-by-worktree": "driver",
  "dev-preview:state-changed": "free",
  "dev-preview:stop": "driver",
  "dev-preview:stop-by-panel": "driver",
  "dev-preview:stop-by-worktree": "driver",
  "dev-preview:stop-dev-server-by-worktree": "driver",
  "diff-media:read-file-versions": "free",
  "drive-lease:event": "free",
  "drive-lease:get": "free",
  "drive-lease:take-over": "free",
  "editor:get-config": "free",
  "editor:set-config": "free",
  "event-inspector:clear": "free",
  "event-inspector:event-batch": "free",
  "event-inspector:get-events": "free",
  "event-inspector:get-filtered": "free",
  "event-inspector:subscribe": "free",
  "event-inspector:unsubscribe": "free",
  "events:emit": "free",
  "events:push": "free",
  "file-browser:list-directory": "free",
  "file-browser:stat-paths": "free",
  "file-watch:fingerprint": "free",
  "files:read": "free",
  "files:search": "free",
  "fleet:get-snapshot": "free",
  "fleet:park-run": "free",
  "fleet:snapshot-updated": "free",
  "fleet:snooze-run": "free",
  "fleet:unpark-run": "free",
  "fleet:unsnooze-run": "free",
  "forge-audit:clear-log": "free",
  "forge-audit:export-log": "free",
  "forge-audit:get-config": "free",
  "forge-audit:get-records": "free",
  "forge-audit:get-stats": "free",
  "forge-audit:set-enabled": "free",
  "forge-recommendation:get-dismissed": "free",
  "forge-recommendation:mark-dismissed": "free",
  "forge:add-issue-comment": "free",
  "forge:add-issue-label": "free",
  "forge:approve-pr": "free",
  "forge:assign-issue": "free",
  "forge:classify-push-error": "free",
  "forge:clear-credential": "free",
  "forge:close-issue": "free",
  "forge:close-pr": "free",
  "forge:comment-on-pr": "free",
  "forge:commit-credential-import": "free",
  "forge:convert-pr-to-draft": "free",
  "forge:create-issue": "free",
  "forge:create-pr": "free",
  "forge:dismiss-review": "free",
  "forge:edit-issue": "free",
  "forge:edit-pr": "free",
  "forge:get-checks": "free",
  "forge:get-ci-status": "free",
  "forge:get-credential-status": "free",
  "forge:get-current-user": "free",
  "forge:get-first-page-cache": "free",
  "forge:get-issue": "free",
  "forge:get-issue-tooltip": "free",
  "forge:get-issue-url": "free",
  "forge:get-issues-by-numbers": "free",
  "forge:get-pr": "free",
  "forge:get-pr-review-threads": "free",
  "forge:get-pr-tooltip": "free",
  "forge:get-project-health": "free",
  "forge:get-providers": "free",
  "forge:get-prs-by-numbers": "free",
  "forge:get-rate-limit-details": "free",
  "forge:get-repo-metadata": "free",
  "forge:get-repo-stats": "free",
  "forge:get-repo-url": "free",
  "forge:get-settings": "free",
  "forge:get-token-health": "free",
  "forge:list-issue-comments": "free",
  "forge:list-issues": "free",
  "forge:list-prs": "free",
  "forge:mark-pr-ready-for-review": "free",
  "forge:merge-pr": "free",
  "forge:open-commits": "free",
  "forge:open-issue": "free",
  "forge:open-issues": "free",
  "forge:open-pr": "free",
  "forge:open-prs": "free",
  "forge:open-repo": "free",
  "forge:preview-credential-import": "free",
  "forge:rate-limit-changed": "free",
  "forge:remove-issue-label": "free",
  "forge:reopen-issue": "free",
  "forge:reopen-pr": "free",
  "forge:repo-counts-updated": "free",
  "forge:repo-stats-and-page-updated": "free",
  "forge:request-changes": "free",
  "forge:request-reviewers": "free",
  "forge:resolve-author-avatar": "free",
  "forge:resolve-provider": "free",
  "forge:set-credential": "free",
  "forge:set-default-provider": "free",
  "forge:token-health-changed": "free",
  "forge:unassign-issue": "free",
  "forge:validate-token": "free",
  "gemini:enable-alternate-buffer": "free",
  "gemini:get-status": "free",
  "git:abort-repository-operation": "driver",
  "git:checkout-ours-theirs": "driver",
  "git:commit": "driver",
  "git:compare-worktrees": "free",
  "git:continue-repository-operation": "driver",
  "git:fetch": "driver",
  "git:force-push-with-lease": "driver",
  "git:get-file-diff": "free",
  "git:get-project-pulse": "free",
  "git:get-staging-status": "free",
  "git:get-username": "free",
  "git:get-working-diff": "free",
  "git:list-base-integration-commits": "free",
  "git:list-commits": "free",
  "git:list-push-commits": "free",
  "git:list-rebase-commits": "free",
  "git:list-remote-commits": "free",
  "git:mark-safe-directory": "free",
  "git:merge-base-into-branch": "driver",
  "git:pull-rebase": "driver",
  "git:push": "driver",
  "git:push-progress": "free",
  "git:rebase-onto-base": "driver",
  "git:scan-conflict-markers": "free",
  "git:stage-all": "driver",
  "git:stage-file": "driver",
  "git:stage-files": "driver",
  "git:unstage-all": "driver",
  "git:unstage-file": "driver",
  "git:unstage-files": "driver",
  "global-env:get": "free",
  "global-env:set": "free",
  "global:add-recipe": "free",
  "global:delete-recipe": "free",
  "global:get-recipes": "free",
  "global:update-recipe": "free",
  "help-assistant:get-live-session-status": "free",
  "help-assistant:get-settings": "free",
  "help-assistant:set-settings": "free",
  "help:get-folder-path": "free",
  "help:get-pinned-action-context": "free",
  "help:list-pending-hibernation-slots": "free",
  "help:mark-terminal": "free",
  "help:peek-pending-hibernation": "free",
  "help:provision-session": "driver",
  "help:report-panel-open": "free",
  "help:restore-pending-hibernation": "driver",
  "help:revoke-session": "driver",
  "help:take-pending-hibernation": "driver",
  "help:unmark-terminal": "free",
  "hibernation:get-config": "free",
  "hibernation:project-hibernated": "free",
  "hibernation:update-config": "free",
  "host-files:get-picker-roots": "free",
  "host-files:list-directory": "free",
  "idle-background:closed": "free",
  "idle-background:get-config": "free",
  "idle-background:update-config": "free",
  "idle-terminal:close-project": "driver",
  "idle-terminal:dismiss-project": "free",
  "idle-terminal:get-config": "free",
  "idle-terminal:notify": "free",
  "idle-terminal:update-config": "free",
  "issue:detected": "free",
  "issue:not-found": "free",
  "keep-awake:get-state": "free",
  "keep-awake:state-changed": "free",
  "keep-awake:update-config": "free",
  "mcp-server:adopt-terminal": "driver",
  "mcp-server:clear-audit-log": "free",
  "mcp-server:clear-turn-outcome-log": "free",
  "mcp-server:disconnect-bearer": "free",
  "mcp-server:export-audit-log": "free",
  "mcp-server:get-audit-config": "free",
  "mcp-server:get-audit-records": "free",
  "mcp-server:get-audit-stats": "free",
  "mcp-server:get-config-snippet": "free",
  "mcp-server:get-log-records": "free",
  "mcp-server:get-pane-wake-enabled": "free",
  "mcp-server:get-pane-watch-state": "free",
  "mcp-server:get-runtime-state": "free",
  "mcp-server:get-status": "free",
  "mcp-server:get-turn-outcome-records": "free",
  "mcp-server:grant-lifecycle": "free",
  "mcp-server:help-display-image": "free",
  "mcp-server:issue-grant": "free",
  "mcp-server:issue-native-grant": "free",
  "mcp-server:list-active-bearers": "free",
  "mcp-server:list-active-clients": "free",
  "mcp-server:list-help-session-bearers": "free",
  "mcp-server:list-orchestrator-panes": "free",
  "mcp-server:list-terminal-adoptions": "free",
  "mcp-server:release-terminal-adoption": "driver",
  "mcp-server:reset-denial-counts": "free",
  "mcp-server:revoke-native-grant": "free",
  "mcp-server:revoke-session-grants": "free",
  "mcp-server:rotate-api-key": "free",
  "mcp-server:runtime-state-changed": "free",
  "mcp-server:session-revoked": "free",
  "mcp-server:set-audit-enabled": "free",
  "mcp-server:set-audit-max-records": "free",
  "mcp-server:set-enabled": "free",
  "mcp-server:set-pane-wake-enabled": "free",
  "mcp-server:set-port": "free",
  "mcp-server:set-session-tier": "free",
  "mcp-server:stop-pane-watches": "driver",
  "mcp-server:tier-not-permitted": "free",
  "mcp-server:tool-call-settled": "free",
  "mcp-server:tool-call-started": "free",
  "mcp-server:turn-outcome-alert": "free",
  "notification:session-mute-set": "free",
  "notification:settings-get": "free",
  "notification:settings-set": "free",
  "notification:show-watch": "free",
  "notification:sync-watched": "free",
  "notification:update": "free",
  "notification:waiting-acknowledge": "free",
  "notification:working-pulse-acknowledge": "free",
  "operations:cancel": "driver",
  "operations:event": "free",
  "operations:get-status": "free",
  "operations:list": "free",
  "plugin-agent-mcp:list-project-endpoints": "free",
  "plugin-agent-mcp:set-project-endpoint-enabled": "free",
  "plugin-mcp:call-tool": "free",
  "plugin-mcp:get-config": "free",
  "plugin-mcp:get-full-schema": "free",
  "plugin-mcp:get-stderr": "free",
  "plugin-mcp:list": "free",
  "plugin-mcp:list-tools": "free",
  "plugin-mcp:resolve-consent": "free",
  "plugin-mcp:restart": "free",
  "plugin-mcp:set-config": "free",
  "plugin-process:list": "free",
  "plugin:actions-get": "free",
  "plugin:actions-register": "free",
  "plugin:actions-unregister": "free",
  "plugin:activate-for-view": "free",
  "plugin:agents-get": "free",
  "plugin:bg-update-check-latest": "free",
  "plugin:bg-update-check-settings-get": "free",
  "plugin:bg-update-check-settings-set": "free",
  "plugin:cancel-install": "free",
  "plugin:check-for-update": "free",
  "plugin:clear-audit-log": "free",
  "plugin:context-menu-items": "free",
  "plugin:export-audit-log": "free",
  "plugin:file-decorations-get": "free",
  "plugin:forge-providers-get": "free",
  "plugin:get-audit-config": "free",
  "plugin:get-audit-records": "free",
  "plugin:get-diagnostics-snapshot": "free",
  "plugin:install": "free",
  "plugin:install-from-file": "free",
  "plugin:install-from-path": "free",
  "plugin:install-from-url": "free",
  "plugin:install-progress": "free",
  "plugin:invoke": "free",
  "plugin:keybindings": "free",
  "plugin:list": "free",
  "plugin:tours-get": "free",
  "plugin:panel-kinds-get": "free",
  "plugin:panel-reload-request": "free",
  "plugin:panel-reload-response": "free",
  "plugin:path-exists": "free",
  "plugin:pick-path": "free",
  "plugin:project-activate-staged": "driver",
  "plugin:project-list": "free",
  "plugin:project-reload": "driver",
  "plugin:project-set-muted": "driver",
  "plugin:project-set-trust": "driver",
  "plugin:project-surface-choice-set": "driver",
  "plugin:project-surface-choices-get": "free",
  "plugin:project-surfaces-get": "free",
  "plugin:project-visibility-get": "free",
  "plugin:project-visibility-set": "driver",
  "plugin:recipe-metadata-update": "free",
  "plugin:recipe-record-use": "free",
  "plugin:recipes-get": "free",
  "plugin:report-panel-inventory": "free",
  "plugin:report-panel-lifecycle": "free",
  "plugin:restart-worker": "free",
  "plugin:runtime-statuses-get": "free",
  "plugin:set-audit-enabled": "free",
  "plugin:set-audit-max-records": "free",
  "plugin:set-enabled": "free",
  "plugin:settings-delete-value": "free",
  "plugin:settings-get-values": "free",
  "plugin:settings-reveal-secret": "free",
  "plugin:settings-set-value": "free",
  "plugin:toolbar-buttons": "free",
  "plugin:uninstall": "free",
  "plugin:validate-action-ids": "free",
  "plugin:validate-manifest": "free",
  "plugin:visibility-default-set": "free",
  "plugin:worktree-status-get": "free",
  "pr:cleared": "free",
  "pr:detected": "free",
  "project-match:find": "free",
  "project-match:find-worktree-for-branch": "free",
  "project-match:scan": "free",
  "project-match:take-pending-setup": "driver",
  "project-presence:changed": "free",
  "project-presence:get-snapshot": "free",
  "project-relocation:apply": "driver",
  "project-relocation:preview": "free",
  "project:add": "free",
  "project:add-recipe": "driver",
  "project:check-missing": "free",
  "project:clone-cancel": "free",
  "project:clone-progress": "free",
  "project:clone-repo": "free",
  "project:close": "driver",
  "project:create-folder": "free",
  "project:delete-inrepo-recipe": "driver",
  "project:delete-recipe": "driver",
  "project:detect-runners": "free",
  "project:disable-in-repo-settings": "driver",
  "project:enable-in-repo-settings": "driver",
  "project:get-all": "free",
  "project:get-bulk-stats": "free",
  "project:get-current": "free",
  "project:get-draft-inputs": "free",
  "project:get-focus-mode": "free",
  "project:get-inrepo-presets": "free",
  "project:get-inrepo-recipes": "free",
  "project:get-notification-overrides": "free",
  "project:get-recipes": "free",
  "project:get-settings": "free",
  "project:get-stats": "free",
  "project:get-tab-groups": "free",
  "project:get-terminal-sizes": "free",
  "project:get-terminals": "free",
  "project:init-git": "driver",
  "project:init-git-guided": "driver",
  "project:init-git-progress": "free",
  "project:list-remotes": "free",
  "project:locate": "free",
  "project:on-switch": "free",
  "project:open-dialog": "free",
  "project:open-git-init-dialog": "free",
  "project:prefetch-hydrate": "free",
  "project:read-claude-md": "free",
  "project:remove": "driver",
  "project:removed": "free",
  "project:reopen": "free",
  "project:save-recipes": "driver",
  "project:save-settings": "driver",
  "project:set-draft-inputs": "driver",
  "project:set-focus-mode": "driver",
  "project:set-tab-groups": "driver",
  "project:set-terminal-sizes": "driver",
  "project:set-terminals": "driver",
  "project:sleep": "driver",
  "project:slept": "free",
  "project:stats-updated": "free",
  "project:switch": "free",
  "project:sync-inrepo-recipes": "driver",
  "project:update": "driver",
  "project:update-inrepo-recipe": "driver",
  "project:update-recipe": "driver",
  "project:updated": "free",
  "project:worktree-load-status": "free",
  "project:write-claude-md": "driver",
  "run-history:append": "free",
  "run-history:clear": "free",
  "run-history:get-records": "free",
  "scratch:create": "free",
  "scratch:get-all": "free",
  "scratch:get-current": "free",
  "scratch:on-switch": "free",
  "scratch:remove": "free",
  "scratch:removed": "free",
  "scratch:save-as-project": "free",
  "scratch:switch": "free",
  "scratch:update": "free",
  "scratch:updated": "free",
  "session-restore:get-config": "free",
  "session-restore:update-config": "free",
  "setup:agent-install": "free",
  "setup:agent-install-progress": "free",
  "slash-commands:list": "free",
  "system:check-command": "free",
  "system:check-directory": "free",
  "system:check-tool": "free",
  "system:get-agent-cli-details": "free",
  "system:get-agent-update-settings": "free",
  "system:get-agent-version": "free",
  "system:get-agent-versions": "free",
  "system:get-cli-availability": "free",
  "system:get-home-dir": "free",
  "system:get-resource-profile": "free",
  "system:get-resource-profile-snapshot": "free",
  "system:get-tmp-dir": "free",
  "system:health-check": "free",
  "system:health-check-specs": "free",
  "system:open-in-editor": "free",
  "system:open-path": "free",
  "system:refresh-agent-versions": "free",
  "system:refresh-cli-availability": "free",
  "system:set-agent-update-settings": "free",
  "system:show-item-in-folder": "free",
  "system:show-item-in-folder-unconfined": "free",
  "system:start-agent-update": "free",
  "terminal-config:get": "free",
  "terminal-config:set-hybrid-input-auto-focus": "free",
  "terminal-config:set-hybrid-input-enabled": "free",
  "terminal-config:set-memory-leak-auto-restart": "free",
  "terminal-config:set-memory-leak-detection": "free",
  "terminal-config:set-performance-mode": "free",
  "terminal-config:set-resource-monitoring": "free",
  "terminal-config:set-scrollback": "free",
  "terminal:acknowledge-data": "free",
  "terminal:activity": "free",
  "terminal:agent-title-state": "free",
  "terminal:batch-double-escape": "handler",
  "terminal:broadcast-write": "handler",
  "terminal:broadcast-write-result": "free",
  "terminal:data": "free",
  "terminal:error": "free",
  "terminal:force-resume": "free",
  "terminal:get-all": "free",
  "terminal:get-analysis-buffer": "free",
  "terminal:get-available": "free",
  "terminal:get-by-state": "free",
  "terminal:get-for-project": "free",
  "terminal:get-host-memory-pause": "free",
  "terminal:get-info": "free",
  "terminal:get-output-activity": "free",
  "terminal:get-serialized-state": "free",
  "terminal:get-serialized-states": "free",
  "terminal:get-shared-buffers": "free",
  "terminal:get-submissions": "free",
  "terminal:graceful-kill": "driver",
  "terminal:input": "handler",
  "terminal:kill": "driver",
  "terminal:reconnect": "free",
  "terminal:reconnect-bulk": "free",
  "terminal:reduce-scrollback": "free",
  "terminal:release-worker-ingest-port": "free",
  "terminal:replay-history": "free",
  "terminal:request-worker-ingest-port": "free",
  "terminal:resize": "handler",
  "terminal:resource-metrics": "free",
  "terminal:restart-service": "driver",
  "terminal:restore": "driver",
  "terminal:restore-scrollback": "free",
  "terminal:restored": "free",
  "terminal:search-semantic-buffers": "free",
  "terminal:send-key": "handler",
  "terminal:set-activity-tier": "free",
  "terminal:set-focused": "free",
  "terminal:spawn": "driver",
  "terminal:status": "free",
  "terminal:submit": "handler",
  "terminal:trash": "driver",
  "terminal:trashed": "free",
  "terminal:update-observed-title": "free",
  "terminal:update-title": "driver",
  "terminal:update-worktree-id": "driver",
  "user-agent-registry:add": "free",
  "user-agent-registry:get": "free",
  "user-agent-registry:remove": "free",
  "user-agent-registry:update": "free",
  "watchdog:restart": "free",
  "workspace-residency:get": "free",
  "workspace-residency:set": "free",
  "workspace:list": "free",
  "worktree-config:dismiss-wsl-banner": "free",
  "worktree-config:get": "free",
  "worktree-config:reprobe-wsl": "free",
  "worktree-config:set-pattern": "free",
  "worktree-config:set-wsl-git": "free",
  "worktree:activated": "free",
  "worktree:attach-issue": "driver",
  "worktree:create": "driver",
  "worktree:delete": "driver",
  "worktree:detach-issue": "driver",
  "worktree:fetch-pr-branch": "driver",
  "worktree:get-all": "free",
  "worktree:get-all-issue-associations": "free",
  "worktree:get-all-with-status": "free",
  "worktree:get-available-branch": "free",
  "worktree:get-default-path": "free",
  "worktree:get-recent-branches": "free",
  "worktree:host-disconnected": "free",
  "worktree:list-branches": "free",
  "worktree:pr-refresh": "free",
  "worktree:pr-status": "free",
  "worktree:refresh": "free",
  "worktree:remove": "free",
  "worktree:restart-service": "driver",
  "worktree:retry-auth-fetch": "free",
  "worktree:retry-project-load": "free",
  "worktree:set-active": "free",
} as const satisfies Record<HostSideChannel, LeasePolicy>;

/**
 * Where a call's argument sits: the argument's index, then the keys into it.
 */
export type LeaseArgPath = readonly [index: number, ...keys: string[]];

/**
 * One way a `driver` call names the project it changes. Each is resolved from
 * what this Host itself records, never from what the caller says it is
 * showing: a repository path to the registered project it belongs to, a
 * terminal id to the project its pty-host record names, a worktree id (its
 * path) to its repository's project, an operation, preview panel or assistant
 * session to the project it was started for.
 *
 * - `caller`: the project the calling view is bound to, for a handler that acts
 *   on exactly that (`ctx.projectId`).
 * - `every-project`: host-wide, so it changes every project anyone drives here.
 * - `optional: true` skips an argument that is absent; `optional: "caller"`
 *   falls back to the caller's project instead, and `"current-project"` to
 *   this Host's current project, for a handler that falls back to it.
 *   Otherwise an absent argument leaves the target unresolved, and the call
 *   is refused.
 * - `unowned: "allow"`: a path inside no registered project changes none.
 */
export type LeaseTargetSource =
  | { readonly from: "caller" }
  | { readonly from: "every-project" }
  | {
      readonly from: "project" | "worktree" | "terminal";
      readonly at: LeaseArgPath;
      readonly optional?: true | "caller" | "current-project";
    }
  | {
      readonly from: "path";
      readonly at: LeaseArgPath;
      readonly optional?: true | "caller";
      readonly unowned?: "allow";
    }
  | {
      readonly from: "operation" | "dev-preview-panel" | "help-session";
      readonly at: LeaseArgPath;
    };

/** Every project a `driver` call may change: all of them must be driven by its caller. */
export type LeaseTarget = readonly LeaseTargetSource[];

type DriverChannel = {
  [K in keyof typeof CHANNEL_LEASE_POLICY]: (typeof CHANNEL_LEASE_POLICY)[K] extends "driver"
    ? K
    : never;
}[keyof typeof CHANNEL_LEASE_POLICY];

const CALLER: LeaseTarget = [{ from: "caller" }];
const PROJECT_ARG: LeaseTarget = [{ from: "project", at: [0] }];
const PROJECT_FIELD: LeaseTarget = [{ from: "project", at: [0, "projectId"] }];
const CWD_ARG: LeaseTarget = [{ from: "path", at: [0] }];
const CWD_FIELD: LeaseTarget = [{ from: "path", at: [0, "cwd"] }];
const TERMINAL_ARG: LeaseTarget = [{ from: "terminal", at: [0] }];
const WORKTREE_FIELD: LeaseTarget = [{ from: "worktree", at: [0, "worktreeId"] }];

/**
 * How the lease gate finds the project each `driver` channel changes. Total
 * over the driver channels, so a new one that doesn't say fails typecheck; the
 * gate checks the lease on every project it names, not the caller's own.
 */
export const CHANNEL_LEASE_TARGETS = {
  "agent-session:prepare-bookmark": [{ from: "terminal", at: [0, "terminalId"] }],
  "app:set-state": CALLER,
  "artifact:apply-patch": CWD_FIELD,
  "artifact:save-to-file": [{ from: "path", at: [0, "cwd"], optional: "caller", unowned: "allow" }],
  "commands:execute": [
    { from: "project", at: [0, "context", "projectId"], optional: "caller" },
    { from: "terminal", at: [0, "context", "terminalId"], optional: true },
    { from: "worktree", at: [0, "context", "worktreeId"], optional: true },
    { from: "path", at: [0, "context", "cwd"], optional: true },
  ],
  "copytree:inject": [
    { from: "terminal", at: [0, "terminalId"] },
    { from: "worktree", at: [0, "worktreeId"] },
  ],
  "dev-preview:ensure": [
    { from: "project", at: [0, "projectId"] },
    { from: "path", at: [0, "cwd"], unowned: "allow" },
  ],
  "dev-preview:reinstall-and-restart": PROJECT_FIELD,
  "dev-preview:restart": PROJECT_FIELD,
  "dev-preview:restart-and-clear-cache": PROJECT_FIELD,
  "dev-preview:restart-by-worktree": WORKTREE_FIELD,
  "dev-preview:stop": PROJECT_FIELD,
  "dev-preview:stop-by-panel": [{ from: "dev-preview-panel", at: [0, "panelId"] }],
  "dev-preview:stop-by-worktree": WORKTREE_FIELD,
  "dev-preview:stop-dev-server-by-worktree": WORKTREE_FIELD,
  "git:abort-repository-operation": CWD_ARG,
  "git:checkout-ours-theirs": CWD_FIELD,
  "git:commit": CWD_FIELD,
  "git:continue-repository-operation": CWD_ARG,
  "git:fetch": CWD_FIELD,
  "git:force-push-with-lease": CWD_FIELD,
  "git:merge-base-into-branch": CWD_FIELD,
  "git:pull-rebase": CWD_FIELD,
  "git:push": CWD_FIELD,
  "git:rebase-onto-base": CWD_FIELD,
  "git:stage-all": CWD_ARG,
  "git:stage-file": CWD_FIELD,
  "git:stage-files": CWD_FIELD,
  "git:unstage-all": CWD_ARG,
  "git:unstage-file": CWD_FIELD,
  "git:unstage-files": CWD_FIELD,
  "help:provision-session": [
    { from: "project", at: [0, "projectId"] },
    { from: "path", at: [0, "projectPath"] },
  ],
  "help:restore-pending-hibernation": PROJECT_ARG,
  "help:revoke-session": [{ from: "help-session", at: [0] }],
  "help:take-pending-hibernation": PROJECT_ARG,
  "idle-terminal:close-project": PROJECT_ARG,
  "mcp-server:adopt-terminal": [{ from: "terminal", at: [0, "terminalId"] }],
  "mcp-server:release-terminal-adoption": [{ from: "terminal", at: [0, "terminalId"] }],
  "mcp-server:stop-pane-watches": TERMINAL_ARG,
  "operations:cancel": [{ from: "operation", at: [0, "opId"] }],
  "plugin:project-activate-staged": CALLER,
  "plugin:project-reload": CALLER,
  "plugin:project-set-muted": CALLER,
  "plugin:project-set-trust": CALLER,
  "plugin:project-surface-choice-set": CALLER,
  "plugin:project-visibility-set": CALLER,
  "project-match:take-pending-setup": PROJECT_FIELD,
  "project-relocation:apply": PROJECT_FIELD,
  "project:add-recipe": PROJECT_FIELD,
  "project:close": PROJECT_ARG,
  "project:delete-inrepo-recipe": PROJECT_FIELD,
  "project:delete-recipe": PROJECT_FIELD,
  "project:disable-in-repo-settings": PROJECT_ARG,
  "project:enable-in-repo-settings": PROJECT_ARG,
  "project:init-git": [{ from: "path", at: [0], unowned: "allow" }],
  "project:init-git-guided": [{ from: "path", at: [0, "directoryPath"], unowned: "allow" }],
  "project:remove": PROJECT_ARG,
  "project:save-recipes": PROJECT_FIELD,
  "project:save-settings": PROJECT_FIELD,
  "project:set-draft-inputs": PROJECT_FIELD,
  "project:set-focus-mode": PROJECT_FIELD,
  "project:set-tab-groups": PROJECT_FIELD,
  "project:set-terminal-sizes": PROJECT_FIELD,
  "project:set-terminals": PROJECT_FIELD,
  "project:sleep": PROJECT_ARG,
  "project:sync-inrepo-recipes": PROJECT_FIELD,
  "project:update": PROJECT_ARG,
  "project:update-inrepo-recipe": PROJECT_FIELD,
  "project:update-recipe": PROJECT_FIELD,
  "project:write-claude-md": PROJECT_FIELD,
  "terminal:graceful-kill": TERMINAL_ARG,
  "terminal:kill": TERMINAL_ARG,
  "terminal:restart-service": [{ from: "every-project" }],
  "terminal:restore": TERMINAL_ARG,
  // With no projectId the handler spawns into this Host's current project.
  "terminal:spawn": [
    { from: "project", at: [0, "projectId"], optional: "current-project" },
    { from: "path", at: [0, "cwd"], optional: true, unowned: "allow" },
  ],
  "terminal:trash": TERMINAL_ARG,
  "terminal:update-title": [{ from: "terminal", at: [0, "id"] }],
  "terminal:update-worktree-id": [{ from: "terminal", at: [0, "id"] }],
  "worktree:attach-issue": WORKTREE_FIELD,
  "worktree:create": [{ from: "path", at: [0, "rootPath"] }],
  "worktree:delete": WORKTREE_FIELD,
  "worktree:detach-issue": WORKTREE_FIELD,
  "worktree:fetch-pr-branch": [{ from: "path", at: [0, "rootPath"] }],
  "worktree:restart-service": CALLER,
} as const satisfies Record<DriverChannel, LeaseTarget>;

/** How a `driver` channel's target project is found; null for any other channel. */
export function getChannelLeaseTarget(channel: string): LeaseTarget | null {
  if (!Object.hasOwn(CHANNEL_LEASE_TARGETS, channel)) return null;
  return (CHANNEL_LEASE_TARGETS as Record<string, LeaseTarget>)[channel]!;
}

/** The channel's lease policy; `free` for anything the record doesn't name (events, shell channels). */
export function getChannelLeasePolicy(channel: string): LeasePolicy {
  if (!Object.hasOwn(CHANNEL_LEASE_POLICY, channel)) return "free";
  return (CHANNEL_LEASE_POLICY as Record<string, LeasePolicy>)[channel]!;
}

/**
 * Whether a call on `channel` needs the caller to drive its project. A local
 * view is only held to it on `host` channels; see {@link CHANNEL_LEASE_POLICY}.
 */
export function requiresDriveLease(channel: string, caller: "link" | "local"): boolean {
  if (getChannelLeasePolicy(channel) !== "driver") return false;
  return caller === "link" || getChannelLocality(channel) === "host";
}
