export const SEL = {
  toolbar: {
    toggleSidebar: '[aria-label="Toggle Sidebar"]',
    openTerminal: '[aria-label="Open Terminal"]',
    openSettings: '[aria-label="Open settings"]',
    openBrowser: '[aria-label="Open Browser"]',
    openDevPreview: '[aria-label="Open Dev Preview"]',
    copyContext: '[aria-label="Copy Context"]',
    notesButton: '[aria-label="Notes"]',
    projectSwitcherTrigger: '[data-testid="project-switcher-trigger"]',
    sidecarToggle: '[aria-label="Toggle Sidecar"]',
  },
  sidebar: {
    resizeHandle: '[aria-label="Resize sidebar"]',
  },
  settings: {
    heading: 'h2:has-text("Settings")',
    closeButton: '[aria-label="Close settings"]',
    navSidebar: ".w-48",
    projectPulseToggle: '[aria-label="Project Pulse Toggle"]',
    performanceModeToggle: '[aria-label="Performance Mode Toggle"]',
    fontFamilySelect: 'select[aria-label="Terminal font family"]',
    subtabNav: '[aria-label="Subtab navigation"]',
    searchInput: '[aria-label="Search settings"]',
    searchClear: '[aria-label="Clear search"]',
    shortcutsSearchInput: 'input[placeholder="Search shortcuts..."]',
    shortcutRecordPrompt: 'button:has-text("Click to record shortcut")',
    shortcutCancelButton: 'button:has-text("Cancel")',
    shortcutResetButton: '[aria-label="Reset to default"]',
    shortcutResetAllButton: 'button:has-text("Reset All")',
    notifCompletedCheckbox: "#notif-completed",
    notifWaitingCheckbox: "#notif-waiting",
    notifFailedCheckbox: "#notif-failed",
    notifSoundToggle: '[aria-label="Play sound for notifications"]',
  },
  panel: {
    gridPanel: '[data-panel-location="grid"]',
    dockPanel: '[data-panel-location="dock"]',
    anyPanel: "[data-panel-id]",
    close: '[data-testid="panel-close"]',
    maximize: '[aria-label*="Maximize"]',
    exitFocus: '[aria-label*="Exit Focus"]',
    overflowMenu: '[aria-label="More panel actions"]',
    minimize: '[data-testid="panel-move-to-dock"]',
    restoreFromDock: '[aria-label*="Restore to grid"]',
    duplicate: '[aria-label="Duplicate panel as new tab"]',
    restart: '[data-testid="panel-restart"]',
    restartConfirm: '[data-testid="panel-restart-confirm"]',
    tabList: '[role="tablist"][aria-label="Panel tabs"]',
    tab: '[role="tab"]',
  },
  terminal: {
    xtermRows: ".xterm-screen",
    xtermViewport: ".xterm-viewport",
    cmEditor: ".cm-content",
    titleButton: '[aria-label*="title"]',
    searchInput: "[data-terminal-search-input]",
    searchClose: '[aria-label="Close search"]',
    searchPrevious: '[aria-label="Previous match"]',
    searchNext: '[aria-label="Next match"]',
    searchCaseToggle: '[aria-label="Toggle case sensitivity"]',
    searchRegexToggle: '[aria-label="Toggle regex mode"]',
    searchStatus: "[data-terminal-search-status]",
  },
  worktree: {
    card: (branch: string) => `[data-worktree-branch="${branch}"]`,
    actionsMenu: '[data-testid="worktree-actions-menu"]',
    newDialog: '[data-testid="new-worktree-dialog"]',
    branchNameInput: '[data-testid="branch-name-input"]',
    createButton: '[data-testid="create-worktree-button"]',
    deleteDialog: '[data-testid="delete-worktree-dialog"]',
    deleteConfirm: '[data-testid="delete-worktree-confirm"]',
    searchInput: '[aria-label="Search worktrees"]',
    searchClear: '[aria-label="Clear search and filters"]',
    reviewHubButton: '[aria-label="Open Review & Commit"]',
    filterButton: '[aria-label="Filter and sort worktrees"]',
    filterPopover: '[data-testid="worktree-filter-popover"]',
    openOverviewButton: '[aria-label="Open worktrees overview"]',
    overviewModal: '[role="dialog"][aria-labelledby="worktree-overview-title"]',
    overviewClose: '[aria-label="Close overview"]',
    quickCreatePalette: '[role="dialog"][aria-label="Quick create worktree palette"]',
    quickCreateCustomize: "#quick-create-option-__customize__",
  },
  dock: {
    container: "#dock-container",
  },
  browser: {
    addressBar: '[data-testid="browser-address-bar"]',
    backButton: '[data-testid="browser-back"]',
    forwardButton: '[data-testid="browser-forward"]',
    reloadButton: '[data-testid="browser-reload"]',
    navBack: '[aria-label="Go back"]',
    navForward: '[aria-label="Go forward"]',
    navReload: '[aria-label="Reload page"]',
    zoomIn: '[aria-label="Zoom in"]',
    zoomOut: '[aria-label="Zoom out"]',
    zoomReset: '[aria-label="Reset zoom"]',
  },
  devPreview: {
    consoleToggle: '[aria-label="Show Terminal"], [aria-label="Hide Terminal"]',
  },
  projectSwitcher: {
    palette: '[data-testid="project-switcher-palette"]',
    addButton: '[data-testid="project-add-button"]',
    projectSettings: 'button:has-text("Project Settings")',
    projectSettingsAlt: 'button:has-text("Settings")',
    closeButton: '[aria-label="Close project"]',
  },
  trash: {
    container: '[data-testid="trash-container"]',
  },
  notes: {
    palette: '[data-testid="notes-palette"]',
  },
  pulse: {
    heatmap: '[role="img"][aria-label*="Activity over"]',
    rangeTrigger: '[aria-label="Change time range"]',
    refreshButton: '[aria-label="Refresh"]',
  },
  reviewHub: {
    container: '[data-testid="review-hub"]',
    diffMode: '[data-testid="review-hub-diff-mode"]',
    close: '[data-testid="review-hub-close"]',
    commitMessageInput: 'textarea[placeholder="Commit message…"]',
    commitButton: (count: number) => `button:has-text("Commit (${count})")`,
    cleanState: 'text="Working tree clean"',
    stageButton: (path: string) => `[aria-label="Stage ${path}"]`,
    unstageButton: (path: string) => `[aria-label="Unstage ${path}"]`,
  },
  welcome: {
    openFolder: 'button:has-text("Open Folder")',
  },
  onboarding: {
    heading: 'h2:has-text("Set up your project")',
    projectNameInput: '[aria-label="Project Name"]',
    finishButton: 'button:has-text("Finish")',
  },
  agent: {
    panel: '[aria-label^="Claude agent:"]',
    startButton: '[aria-label="Start Claude Agent"]',
  },
  opencodeAgent: {
    panel: '[aria-label^="OpenCode agent:"]',
    startButton: '[aria-label="Start OpenCode Agent"]',
  },
  fileViewer: {
    dialog: '[data-testid="file-viewer-dialog"]',
    closeButton: '[aria-label="Close dialog"]',
    metadataBar: '[data-testid="file-viewer-metadata"]',
    image: "img",
  },
  crashRecovery: {
    dialog: '[data-testid="crash-recovery-dialog"]',
    panelList: '[data-testid="panel-list"]',
    toggleAllButton: '[data-testid="toggle-all-button"]',
    detailsToggle: '[data-testid="details-toggle"]',
    detailsSection: '[data-testid="details-section"]',
    restoreSelectedButton: '[data-testid="restore-selected-button"]',
    restoreButton: '[data-testid="restore-button"]',
    freshButton: '[data-testid="fresh-button"]',
    autoRestoreCheckbox: '[data-testid="auto-restore-checkbox"]',
    autoRestoreLabel: '[data-testid="auto-restore-label"]',
    suspectWarning: '[data-testid="suspect-warning"]',
    panelRow: (id: string) => `[data-testid="panel-row-${id}"]`,
    panelCheckbox: (id: string) => `[data-testid="panel-checkbox-${id}"]`,
    suspectBadge: (id: string) => `[data-testid="suspect-badge-${id}"]`,
  },
  projectSettings: {
    heading: 'h2:has-text("Project Settings")',
    closeButton: '[aria-label="Close settings"]',
    recipesTab: '.w-48 button:has-text("Recipes")',
    addRecipeButton: 'button:has-text("Add Recipe")',
    editRecipeButton: (name: string) => `[aria-label="Edit recipe ${name}"]`,
    deleteRecipeButton: (name: string) => `[aria-label="Delete recipe ${name}"]`,
  },
  recipeEditor: {
    nameInput: "#recipe-name",
    showInEmptyState: "#show-in-empty-state",
    terminalType: (i: number) => `#terminal-type-${i}`,
    terminalTitle: (i: number) => `#terminal-title-${i}`,
    terminalCommand: (i: number) => `#terminal-command-${i}`,
    terminalExitBehavior: (i: number) => `#terminal-exit-behavior-${i}`,
    addTerminalButton: 'button:has-text("+ Add Terminal")',
    createButton: 'button:has-text("Create Recipe")',
    updateButton: 'button:has-text("Update Recipe")',
    cancelButton: 'button:has-text("Cancel")',
  },
  diagnostics: {
    dock: '[aria-label="Diagnostics dock"]',
    resizeHandle: '[aria-label="Resize diagnostics dock"]',
    closeButton: '[aria-label="Close diagnostics dock"]',
    tabList: '[aria-label="Diagnostics tabs"]',
    tab: (name: string) => `#diagnostics-${name}-tab`,
    panel: (name: string) => `#diagnostics-${name}-panel`,
  },
  notifications: {
    bellButton: '[aria-label^="Notifications"]',
    emptyState: 'text="No notifications yet"',
    configureButton: 'button:has-text("Configure")',
    clearAllButton: 'button:has-text("Clear all")',
  },
  actionPalette: {
    dialog: '[role="dialog"][aria-label="Action palette"]',
    searchInput: '[aria-label="Search actions"]',
    list: "#action-palette-list",
    options: '#action-palette-list [role="option"]',
  },
  quickSwitcher: {
    dialog: '[role="dialog"][aria-label="Quick switcher"]',
    searchInput: '[aria-label="Search terminals, agents, and worktrees"]',
    list: "#quick-switcher-list",
    options: '#quick-switcher-list [role="option"]',
  },
  commandPicker: {
    openButton: '[aria-label="Open command picker"]',
    dialog: '[role="dialog"][aria-label="Command picker"]',
    searchInput: '[aria-label="Search commands"]',
    list: "#command-list",
    options: '#command-list [role="option"]',
  },
} as const;
