export const SEL = {
  toolbar: {
    toggleSidebar: '[aria-label="Toggle Sidebar"]',
    openTerminal: '[aria-label="Open Terminal"]',
    openSettings: '[aria-label="Open settings"]',
    openBrowser: '[aria-label="Open Browser"]',
    openDevPreview: '[aria-label="Open Dev Preview"]',
    copyContext: '[aria-label="Copy Context"]',
    projectSwitcherTrigger: '[data-testid="project-switcher-trigger"]',
    portalToggle: '[aria-label*="web chat"]',
  },
  portal: {
    region: 'aside[aria-label="Portal"]',
    resizeHandle: '[aria-label="Resize portal panel"]',
    launchpadHeading: 'h2:has-text("New Chat")',
    container: '[aria-label="Portal"]',
    tab: '[role="tab"]',
    tabList: '[role="tablist"]',
    newTab: '[aria-label="New Tab"]',
    goBack: '[aria-label="Go back"]',
    goForward: '[aria-label="Go forward"]',
    reload: '[aria-label="Reload"]',
    closePortal: '[aria-label="Close portal"]',
    closeTab: (title: string) => `[aria-label="Close ${title}"]`,
  },
  sidebar: {
    resizeHandle: '[aria-label="Resize sidebar"]',
    aside: 'aside[aria-label="Sidebar"]',
  },
  settings: {
    heading: 'h2:has-text("Settings")',
    closeButton: '[aria-label="Close settings"]',
    navSidebar: ".settings-sidebar",
    projectPulseToggle: '[aria-label="Project Pulse Toggle"]',
    performanceModeToggle: '[aria-label="Performance Mode Toggle"]',
    fontFamilySelect: '[aria-label="Terminal font family"]',
    subtabNav: '[aria-label="Subtab navigation"]',
    searchInput: '[aria-label="Search settings"]',
    searchClear: '[aria-label="Clear search"]',
    shortcutsSearchInput: 'input[placeholder="Search shortcuts..."]',
    shortcutRow: '[data-testid="shortcut-row"]',
    shortcutRecordPrompt: 'button:has-text("Click to record shortcut")',
    shortcutCancelButton: 'button:has-text("Cancel")',
    shortcutResetButton: '[aria-label="Reset to default"]',
    shortcutResetAllButton: 'button:has-text("Reset All")',
    fontSizeInput: '[aria-label="Terminal font size"]',
    developerModeToggle: '[aria-label="Developer Mode Toggle"]',
    agentDropdownTrigger: '[data-testid="agent-selector-trigger"]',
    agentDropdownList: "#agent-selector-list",
    notifCompletedCheckbox: "#notif-completed",
    notifWaitingCheckbox: "#notif-waiting",
    notifEscalationCheckbox: "#notif-waiting-escalation",
    notifSoundToggle: '[aria-label="Play sound for notifications"]',
    soundPreviewButton: 'button:has-text("Preview")',
    themeBrowserDialog: '[role="dialog"][aria-label="Theme browser"]',
    themeListbox: '[role="listbox"][aria-label="Theme list"]',
    changeThemeButton: 'button:has-text("Change theme")',
    accentColorInput: '[data-testid="accent-color-override-input"]',
    accentColorReset: '[data-testid="accent-color-override-reset"]',
    accentContrastWarning: '[role="status"]:has-text("Low contrast")',
    randomThemeButton: 'button:has-text("Random theme")',
    shortcutConflictWarning: "text=Conflicts with:",
    mcpServerToggle: '[aria-label="Enable MCP server"]',
    mcpServerEmptyState: "text=MCP server is off",
    mcpServerEnableButton: 'button:has-text("Turn on MCP server")',
    mcpConnectionMarker: "text=The server binds to 127.0.0.1",
    scopeSelect: '[aria-label="Settings scope"]',
    searchResultsRegion: '[role="region"][aria-label="Search results"]',
  },
  panel: {
    gridPanel: '[data-panel-location="grid"]',
    dockPanel: '[data-panel-location="dock"]',
    anyPanel: "[data-panel-id]",
    close: '[data-testid="panel-close"]',
    maximize: '[aria-label*="Maximize"]',
    restore: '[aria-label*="Restore grid view"]',
    overflowMenu: '[aria-label="More panel actions"]',
    minimize: '[data-testid="panel-move-to-dock"]',
    restoreFromDock: 'button[aria-label*="move to grid"]',
    duplicate: '[aria-label="Duplicate panel as new tab"]',
    restart: '[data-testid="panel-restart"]',
    restartConfirm: '[data-testid="panel-restart-confirm"]',
    tabList: '[role="tablist"][aria-label="Panel tabs"]',
    tab: '[role="tab"]',
  },
  terminal: {
    xtermRows: ".xterm-screen",
    xtermViewport: ".xterm-viewport",
    xtermHelperTextarea: ".xterm-helper-textarea",
    cmEditor: ".cm-content",
    titleButton: '[aria-label*="title"]',
    searchInput: "[data-terminal-search-input]",
    searchClose: '[aria-label="Close search"]',
    searchPrevious: '[aria-label="Previous match"]',
    searchNext: '[aria-label="Next match"]',
    searchCaseToggle: '[aria-label="Toggle case sensitivity"]',
    searchRegexToggle: '[aria-label="Toggle regex mode"]',
    searchStatus: "[data-terminal-search-status]",
    scrollIndicator: '[aria-label="Scroll to latest output"]',
  },
  worktree: {
    card: (branch: string) => `[data-worktree-branch="${branch}"]`,
    mainCard: '[data-worktree-is-main="true"]',
    actionsMenu: '[data-testid="worktree-actions-menu"]',
    newDialog: '[data-testid="new-worktree-dialog"]',
    branchNameInput: '[data-testid="branch-name-input"]',
    createButton: '[data-testid="create-worktree-button"]',
    deleteDialog: '[data-testid="delete-worktree-dialog"]',
    deleteConfirm: '[data-testid="delete-worktree-confirm"]',
    deleteConfirmInput: '[data-testid="delete-worktree-confirm-input"]',
    searchInput: '[aria-label="Search worktrees"]',
    searchClear: '[aria-label="Clear search"]',
    reviewHubButton: '[aria-label="Open Review & Commit"]',
    filterButton: '[aria-label="Filter and sort worktrees"]',
    filterPopover: '[data-testid="worktree-filter-popover"]',
    openOverviewButton: '[aria-label="Open worktrees overview"]',
    overviewModal: '[role="dialog"][aria-labelledby="worktree-overview-title"]',
    overviewClose: '[aria-label="Close overview"]',
    quickCreatePalette: '[role="dialog"][aria-label="Quick create worktree palette"]',
    quickCreateCustomize: "#quick-create-option-__customize__",
    newWorktreeButton: '[aria-label="Create new worktree"]',
    branchModeGroup: '[role="radiogroup"][aria-label="Branch mode"]',
    environmentGroup: '[role="radiogroup"][aria-label="Worktree environment mode"]',
    recipeTrigger: "#recipe-selector-trigger",
    recipeListbox: "#recipe-selector",
    validationError: "#validation-error",
    overviewCell: "[data-worktree-overview-cell]",
    overviewCellFor: (id: string) => `[data-worktree-overview-cell="${id}"]`,
    bulkRemove: '[data-testid="worktree-bulk-remove"]',
    bulkCloseSessions: '[data-testid="worktree-bulk-close-sessions"]',
    clearSelection: '[aria-label="Clear selection"]',
  },
  dock: {
    container: "#dock-container",
  },
  browser: {
    addressBar: '[data-testid="browser-address-bar"]',
    backButton: '[data-testid="browser-back"]',
    forwardButton: '[data-testid="browser-forward"]',
    reloadButton: '[data-testid="browser-reload"]',
    navBack: '[aria-label="Go back"]',
    navForward: '[aria-label="Go forward"]',
    navReload: '[aria-label="Reload page"]',
    zoomIn: '[aria-label="Zoom in"]',
    zoomOut: '[aria-label="Zoom out"]',
    zoomReset: '[aria-label="Reset zoom"]',
    promoteToPortal: '[data-testid="browser-promote-portal"]',
    findInput: 'input[placeholder="Find in page"]',
    findPrev: '[aria-label="Previous match"]',
    findNext: '[aria-label="Next match"]',
    findClose: '[aria-label="Close find bar"]',
  },
  devPreview: {
    consoleToggle: '[aria-label="Toggle output drawer"]',
    consoleTab: '[role="tab"][data-tab="console"]',
    outputTab: '[role="tab"][data-tab="output"]',
  },
  projectSwitcher: {
    palette: '[data-testid="project-switcher-palette"]',
    addButton: '[data-testid="project-add-button"]',
    projectSettings: 'button:has-text("Project Settings")',
    projectSettingsAlt: 'button:has-text("Settings")',
    closeButton: '[aria-label="Close project"]',
  },
  trash: {
    container: '[data-testid="trash-container"]',
  },
  pulse: {
    heatmap: '[data-testid="pulse-heatmap"]',
    rangeTrigger: '[aria-label="Activity range"]',
    refreshButton: '[aria-label="Refresh"]',
    lastUpdated: '[data-testid="pulse-last-updated"]',
  },
  reviewHub: {
    container: '[data-testid="review-hub"]',
    diffMode: '[data-testid="review-hub-diff-mode"]',
    close: '[data-testid="review-hub-close"]',
    commitMessageInput: 'textarea[placeholder="Commit message…"]',
    commitButton: (count: number) => `button:has-text("Commit (${count})")`,
    cleanState: 'text="Working tree clean"',
    stageButton: (path: string) => `[aria-label="Stage ${path}"]`,
    unstageButton: (path: string) => `[aria-label="Unstage ${path}"]`,
    stageAllButton: '[data-testid="review-hub-stage-section-button"]',
    unstageAllButton: '[data-testid="review-hub-unstage-section-button"]',
    fileListToggle: '[data-testid="review-hub-file-list-toggle"]',
    noStagedFiles: 'text="Nothing staged"',
    noUnstagedChanges: 'text="All changes staged"',
  },
  welcome: {
    openFolder: 'button:has-text("Open folder")',
  },
  firstRun: {
    welcomeTitle: 'h1:has-text("Welcome to Daintree")',
    agentTitle: 'text="Choose your AI agents"',
    agentSetupDialog:
      '[role="dialog"]:has-text("Agent Setup"), [role="dialog"]:has-text("Welcome to Daintree")',
    agentSetupBanner: '[data-testid="agent-setup-banner"]',
    agentSetupBannerCta: '[data-testid="agent-setup-banner-cta"]',
    agentSetupBannerDismiss: '[data-testid="agent-setup-banner-dismiss"]',
  },
  agent: {
    panel: '[aria-label^="Claude agent:"]',
    startButton: '[aria-label="Start Claude"]',
    trayButton: '[aria-label^="Agent tray"]',
    chromeAgentPanel: (agentId: string) => `[data-chrome-agent-id="${agentId}"]`,
    everDetectedAgentPanel: '[data-ever-detected-agent="true"]',
  },
  opencodeAgent: {
    panel: '[aria-label^="OpenCode agent:"]',
    startButton: '[aria-label="Start OpenCode"]',
  },
  fileViewer: {
    dialog: '[data-testid="file-viewer-dialog"]',
    closeButton: '[aria-label="Close dialog"]',
    metadataBar: '[data-testid="file-viewer-metadata"]',
    image: "img",
  },
  crashRecovery: {
    dialog: '[data-testid="crash-recovery-dialog"]',
    panelList: '[data-testid="panel-list"]',
    toggleAllButton: '[data-testid="toggle-all-button"]',
    detailsToggle: '[data-testid="details-toggle"]',
    detailsSection: '[data-testid="details-section"]',
    restoreSelectedButton: '[data-testid="restore-selected-button"]',
    restoreButton: '[data-testid="restore-button"]',
    freshButton: '[data-testid="fresh-button"]',
    autoRestoreCheckbox: '[data-testid="auto-restore-checkbox"]',
    autoRestoreLabel: '[data-testid="auto-restore-label"]',
    suspectWarning: '[data-testid="suspect-warning"]',
    panelRow: (id: string) => `[data-testid="panel-row-${id}"]`,
    panelCheckbox: (id: string) => `[data-testid="panel-checkbox-${id}"]`,
    suspectBadge: (id: string) => `[data-testid="suspect-badge-${id}"]`,
  },
  projectSettings: {
    heading: 'h2:has-text("Settings")',
    closeButton: '[aria-label="Close settings"]',
    recipesTab: '.settings-sidebar button:has-text("Recipes")',
    addRecipeButton: 'button:has-text("Add Recipe")',
    editRecipeButton: (name: string) => `[aria-label="Edit recipe ${name}"]`,
    deleteRecipeButton: (name: string) => `[aria-label="Delete recipe ${name}"]`,
  },
  recipeEditor: {
    nameInput: "#recipe-name",
    showInEmptyState: "#show-in-empty-state",
    terminalType: (i: number) => `#terminal-type-${i}`,
    terminalTitle: (i: number) => `#terminal-title-${i}`,
    terminalCommand: (i: number) => `#terminal-command-${i}`,
    terminalExitBehavior: (i: number) => `#terminal-exit-behavior-${i}`,
    addTerminalButton: 'button:has-text("+ Add Terminal")',
    createButton: 'button:has-text("Create Recipe")',
    updateButton: 'button:has-text("Update Recipe")',
    cancelButton: 'button:has-text("Cancel")',
  },
  diagnostics: {
    dock: '[aria-label="Diagnostics dock"]',
    resizeHandle: '[aria-label^="Resize diagnostics dock"]',
    closeButton: '[aria-label="Close diagnostics dock"]',
    tabList: '[aria-label="Diagnostics tabs"]',
    tab: (name: string) => `#diagnostics-${name}-tab`,
    panel: (name: string) => `#diagnostics-${name}-panel`,
  },
  notifications: {
    bellButton: 'button[aria-label^="Notifications"]',
    emptyState: 'text="No notifications yet"',
    configureButton: 'button:has-text("Configure")',
    clearAllButton: 'button:has-text("Clear all")',
  },
  actionPalette: {
    dialog: '[role="dialog"][aria-label="Action palette"]',
    searchInput: '[aria-label="Search actions"]',
    list: "#action-palette-list",
    options: '#action-palette-list [role="option"]',
  },
  quickSwitcher: {
    dialog: '[role="dialog"][aria-label="Quick switcher"]',
    searchInput: '[aria-label="Search terminals, agents, and worktrees"]',
    list: "#quick-switcher-list",
    options: '#quick-switcher-list [role="option"]',
  },
  commandPicker: {
    openButton: '[aria-label="Open command picker"]',
    dialog: '[role="dialog"][aria-label="Command picker"]',
    searchInput: '[aria-label="Search commands"]',
    list: "#command-list",
    options: '#command-list [role="option"]',
  },
  errorBoundary: {
    fallback: '[data-testid="error-fallback"]',
    title: '[data-testid="error-fallback-title"]',
    restartButton: '[data-testid="error-fallback-restart"]',
    reportButton: '[data-testid="error-fallback-report"]',
    logsButton: '[data-testid="error-fallback-logs"]',
  },
  contextMenu: {
    content: '[role="menu"]',
    item: '[role="menuitem"]',
  },
  preset: {
    section: "#agents-presets",
    addButton: '[data-testid="preset-add-button"]',
    selectorTrigger: '[data-testid="preset-selector-trigger"]',
    selectorListbox: '[data-testid="preset-selector-listbox"][data-state="open"]',
    presetRow: "#agents-presets [data-testid]",
    autoBadge: "[data-testid='preset-badge-auto']",
    customBadge: "[data-testid='preset-badge-custom']",
    editButton: '[aria-label^="Edit"]',
    deleteButton: '[aria-label^="Delete"]',
    duplicateButton: '[aria-label^="Duplicate"]',
    toolbarChevron: '[aria-label^="Choose"][aria-label$="preset"]',
    trayLaunchPresetSubmenu: '[data-testid="submenu-trigger"]',
    trayLaunchPresetItem: '[data-testid="submenu-content"] [role="menuitem"]',
    contextPresetSubmenu: '[role="menu"]:text("Launch with Preset")',
    defaultOption: '[data-testid="preset-option-default"]',
    customPresetOption: '[data-testid="preset-selector-listbox"] [role="option"]',
  },
  plugin: {
    manager: '[data-testid="plugin-manager-view"]',
    back: '[aria-label="Back"]',
    close: '[aria-label="Close plugin manager"]',
    list: '[role="listbox"][aria-label="Installed plugins"]',
    option: '[role="listbox"][aria-label="Installed plugins"] [role="option"]',
    filterInput: '[aria-label="Filter plugins"]',
    urlInput: '[aria-label="Plugin URL"]',
    tabOverview: '[role="tab"][data-tab="overview"]',
    tabSettings: '[role="tab"][data-tab="settings"]',
    tabPermissions: '[role="tab"][data-tab="capabilities"]',
  },
} as const;
