// API surface snapshot for @daintreehq/plugin-sdk.
// AUTO-GENERATED by scripts/ci/check-api-surface.mjs; do not edit by hand.
// Run `npm run api-surface:update` after an intentional public API change and commit the result.

/**
 * Thrown for frontmatter that cannot be read: invalid YAML (an alias with no
 * anchor included), a block that is opened but never closed, or YAML that is
 * not a mapping — and by `updateFrontmatter` for an edit that would produce
 * one of those. `line` and `column` are 1-based positions in the whole file,
 * not in the YAML block.
 */
declare class FrontmatterError extends Error {
    readonly code = "FRONTMATTER_INVALID";
    readonly line: number;
    readonly column: number;
    constructor(message: string, line: number, column: number);
}
interface ParsedFrontmatter {
    /** The frontmatter mapping as plain values. `{}` when there is none. */
    data: Record<string, unknown>;
    /** Everything after the closing `---` line, byte-for-byte. */
    body: string;
    /** Whether the text opened with a `---` frontmatter block. */
    hasFrontmatter: boolean;
}
/**
 * Split a document into its YAML frontmatter and body. Frontmatter is a
 * block that opens on the very first line with `---` and closes at the next
 * line that is exactly `---`. A document that does not open with `---` has no
 * frontmatter, and its whole text is the body.
 *
 * Throws {@link FrontmatterError} for invalid YAML (including an alias with no
 * anchor), an unclosed block, or YAML that is not a mapping, so a malformed
 * file is reported rather than read as empty.
 */
declare function parseFrontmatter(text: string): ParsedFrontmatter;
/**
 * Write `data` as a frontmatter block ahead of `body`. `undefined` values are
 * omitted. The body is appended verbatim, so
 * `parseFrontmatter(stringifyFrontmatter(d, b)).body === b`.
 */
declare function stringifyFrontmatter(data: Record<string, unknown>, body: string): string;
/**
 * Change only the named top-level frontmatter keys and leave every other byte
 * of the document alone — comments, key order, quoting, blank lines, and the
 * body. A value of `undefined` deletes the key; a key that is not present yet
 * is appended at the end of the block. A document with no frontmatter gains
 * a block holding the patch.
 *
 * This is what makes a UI edit safe beside an agent's: the two only collide
 * when they touch the same key. Pair it with {@link editFile} so the write
 * itself is also conflict-checked.
 *
 * An edited scalar keeps its trailing comment. A value that becomes (or was)
 * a collection, a multi-line string or an explicitly tagged scalar rewrites
 * that entry's lines in the library's default style, keeping its anchor. A
 * top-level flow mapping (`{ a: 1 }`) cannot be edited in place, so a
 * non-empty patch re-serialises it as a whole.
 *
 * Throws {@link FrontmatterError} when the existing frontmatter is invalid,
 * and when the edit would leave it unreadable — deleting or replacing a value
 * whose anchor another key still refers to.
 */
declare function updateFrontmatter(text: string, patch: Record<string, unknown>): string;

interface JsonlError {
    /** 1-based line number in the input. */
    line: number;
    message: string;
    /** The offending line as written, without its line break. */
    text: string;
}
interface ParsedJsonl {
    /** Every line that parsed, in file order. */
    records: unknown[];
    /** Every non-blank line that did not, in file order. */
    errors: JsonlError[];
}
/**
 * Parse JSON Lines text, collecting a bad line as an error rather than
 * throwing, so one corrupt entry in an append-only log does not hide the rest.
 * Blank lines are skipped and `\r\n` endings are accepted. A final line with
 * no line break that fails to parse is reported as possibly truncated: that
 * is what an interrupted append looks like, though it may just be a malformed
 * last record.
 */
declare function parseJsonl(text: string): ParsedJsonl;
/**
 * One JSON Lines record, line break included, ready to append. JSON escapes
 * every line break inside a string, so the record is always a single line.
 * Throws for a value JSON cannot represent (`undefined`, a function, a symbol).
 */
declare function stringifyJsonlLine(value: unknown): string;

/**
 * The revision `host.fs.writeFile` compares `expectedRevision` against: the
 * lowercase sha256 hex of the file's bytes. A string is hashed as its UTF-8
 * encoding, which is what `writeFile` puts on disk.
 *
 * Async because it uses Web Crypto, so the same function runs in a plugin
 * worker and in a panel view. Pass the bytes from `host.fs.readFileBytes`
 * rather than the text from `readFile` when you hash an existing file: a byte
 * order mark or an invalid UTF-8 sequence does not survive decoding, so the
 * text can hash differently from the file.
 */
declare function contentRevision(content: string | Uint8Array): Promise<string>;

/**
 * Persistent, plugin-scoped key/value settings exposed on
 * {@link PluginHostApi.settings}. Values are stored as JSON at
 * `~/.daintree/plugin-settings/{pluginId}.json` (user scope) or
 * `<projectRoot>/.daintree/plugin-settings/{pluginId}.json` (project scope),
 * with `chmod 0o600` applied on POSIX. Settings declared `type: "secret"` are
 * encrypted at rest through the OS keychain (Electron `safeStorage`), and are
 * never stored under the project root: a project-scoped secret lives in this
 * machine's per-project local file instead (see {@link PluginSettingsScope}).
 * With no keychain available a secret write is refused rather than stored in
 * plaintext. Non-secret values are always plaintext JSON — do not store
 * credentials in non-secret keys.
 *
 * `scope` defaults to `"user"`. Project scope resolves the active project at
 * call time, so it tracks project switches: `get` returns `undefined` and `set`
 * throws when no project is active.
 */
/**
 * Options accepted by long-running host calls (filesystem reads/writes, git
 * reads and mutations, the on-demand worktree-status accessor). Carries an
 * optional {@link AbortSignal} so a plugin can cancel a call it no longer needs
 * — e.g. when a panel the read was feeding has unmounted. An already-aborted
 * signal rejects the call before any I/O; aborting mid-flight rejects with the
 * signal's reason. Always the trailing argument so it never collides with a
 * method's positional parameters.
 */
interface PluginHostCallOptions {
    signal?: AbortSignal;
}
/**
 * What a symbolic link points at, as classified by the host's listing.
 * Present on a {@link PluginFsDirEntry} only for a detailed read of a link.
 *
 * Deliberately mirrors the classification Daintree's own file browser renders,
 * so a plugin presenting a file tree does not have to re-derive it — resolving
 * a link correctly means resolving it against the *canonical* directory it was
 * listed from, which differs from the lexical parent whenever the listed
 * directory is itself reached through a link.
 */
interface PluginFsSymlink {
    /** Absolute path the link resolves to, the way the kernel would resolve it. */
    target: string;
    /**
     * `"file"` and `"directory"` are the resolved, in-scope cases — the only two
     * where `isDirectory` describes the target and descending is allowed.
     * `"broken"` is a target that does not exist. `"external"` is a target that
     * resolves outside the allowed root that contains the listed directory, so
     * the host will refuse to read it through that listing. Conservative: a link
     * into a different allowed root also reads as `"external"`. `"unknown"` is a
     * target that could not be classified at all (a link loop, permission
     * denied) — kept distinct from `"external"` so a UI never reports a link as
     * leaving scope when the truth is that it could not be read.
     */
    targetKind: "file" | "directory" | "broken" | "external" | "unknown";
}
/** One directory entry returned by {@link PluginFsApi.readdir}. */
interface PluginFsDirEntry {
    /** Entry name (basename only — never a path). */
    name: string;
    /** True when the entry is a directory. */
    isDirectory: boolean;
    /**
     * True when the entry is a regular file.
     *
     * On a detailed read a symbolic link is described by what it resolves to, so
     * a link is `isFile` only when its `symlink.targetKind` is `"file"` — a
     * broken or out-of-scope link is neither a file nor a directory, because
     * there is nothing there to open. On a plain read this is the raw directory
     * entry's own kind, so a link reads as neither file nor directory there.
     *
     * Caveat on a detailed read: a non-link entry that is neither a directory nor
     * a regular file — a socket, fifo or device node — is reported as a file,
     * because the underlying listing records only "directory or not". These do
     * not occur in ordinary project trees; treat `isFile` as "not a directory"
     * if your plugin might browse somewhere they do.
     */
    isFile: boolean;
    /** True when the entry is a symbolic link (resolved containment still applies on read). */
    isSymbolicLink: boolean;
    /**
     * Size in bytes. Only present on a detailed read
     * ({@link PluginFsReaddirOptions.detail}), and omitted there for directories
     * and for an unresolved symlink — a link's own size is the byte length of the
     * stored target string, which renders as a real but meaningless file size.
     */
    size?: number;
    /**
     * Last-modified time in epoch milliseconds. Only present on a detailed read.
     * A resolved symlink reports its target's time, because that is what opening
     * the entry would give you.
     */
    mtimeMs?: number;
    /**
     * Present only on a symbolic link, and only on a detailed read. Absence means
     * the entry is a plain file or directory, which is why a consumer can keep
     * reading `isDirectory` and ignore this field entirely.
     */
    symlink?: PluginFsSymlink;
}
/** Options for {@link PluginFsApi.readdir}. */
interface PluginFsReaddirOptions extends PluginHostCallOptions {
    /**
     * Return the same metadata Daintree's own file listing produces — `size`,
     * `mtimeMs`, symlink target and kind — with entries ordered directories-first
     * and then by a numeric-aware name collation.
     *
     * Off by default: a plain read is one `readdir` syscall, while a detailed one
     * additionally `lstat`s every entry and resolves every link, so the cost is
     * opt-in rather than silently imposed on existing callers. Turn it on when
     * you are presenting a file tree — deriving these per entry with your own
     * {@link PluginFsApi.stat} calls costs one host round trip *per entry* and
     * still would not reproduce the link classification or the ordering.
     */
    detail?: boolean;
}
/** File metadata returned by {@link PluginFsApi.stat}. */
interface PluginFsStat {
    isDirectory: boolean;
    isFile: boolean;
    isSymbolicLink: boolean;
    /** Size in bytes. */
    size: number;
    /** Last-modified time, epoch milliseconds. */
    mtimeMs: number;
}
/**
 * Options for {@link PluginFsApi.writeFile} (#12323). Omitting them is the
 * same write as passing `{}`.
 */
interface PluginFsWriteOptions {
    /**
     * The revision the caller last read — the sha256 hex of the file's bytes,
     * as returned by an earlier write or computed by the caller from
     * {@link PluginFsApi.readFileBytes}. The write is refused with
     * `REVISION_MISMATCH` when the file's current bytes hash differently; the
     * error carries the current revision so the caller can enter a conflict
     * state without a second read. `null` means the file must not exist yet
     * (a create-new write, refused with `TARGET_EXISTS` otherwise). Omit it to
     * write atomically without a freshness check.
     */
    expectedRevision?: string | null;
}
interface PluginFsWriteResult {
    /** sha256 hex of the bytes written — the caller's next `expectedRevision`. */
    revision: string;
}
/**
 * Host-mediated, scope-contained filesystem surface on {@link PluginHostApi.fs}.
 *
 * Every path argument is resolved against the plugin's declared
 * `scopes.fs.allowedPaths` and realpath-contained to one of those roots before
 * any I/O — a traversal (`..`) or a symlink that escapes a root is rejected,
 * mirroring the `plugin://` protocol handler's discipline. This is the runtime
 * enforcement of `scopes.fs.allowedPaths` (previously advisory-only).
 *
 * Reads are gated on `fs:project-read` / `fs:user-data-read`; writes on
 * `fs:project-write` / `fs:user-data-write`. A plugin missing the relevant
 * capability is rejected with a `PERMISSION_REQUIRED:` prefix (the same prefix
 * `useHostChannel` discriminates on); a path outside every allowed root is
 * rejected with a `PATH_NOT_ALLOWED:` prefix. Writes are recorded in the plugin
 * audit trail.
 *
 * Unlike the global `files.read` IPC, {@link readFile} carries NO 500KB / binary
 * cap — it is a deliberate plugin API, not the size-limited preview path.
 *
 * NOT revoke-guarded: a plugin reads/writes from timers and subscription
 * callbacks long after `activate()`. Liveness is plugin membership — once the
 * plugin unloads every method rejects and any active {@link watch} is torn down.
 */
interface PluginFsApi {
    /**
     * Read a file as UTF-8 text. Resolves the contained absolute path; rejects on
     * a missing read capability, an out-of-scope path, or a non-file target. Pass
     * `options.signal` to cancel a read that is no longer needed.
     *
     * A symlink the caller names is followed when it resolves inside a root.
     * Once open, the descriptor must be the entry standing at the contained path
     * (#12618): a leaf swapped for a symlink after containment rejects with
     * `TARGET_IS_SYMLINK`, and a descriptor that is not the file now at the path
     * with `TARGET_UNAVAILABLE`. A read that races a legitimate replace can see
     * the latter and is safe to retry.
     */
    readFile(filePath: string, options?: PluginHostCallOptions): Promise<string>;
    /**
     * Read a file as raw bytes, for the content UTF-8 decoding would corrupt —
     * an image, a font, an archive, anything a plugin wants to hash or hand to a
     * view as a data URL. Same capability gate, containment and cancellation as
     * {@link readFile}, and the same absence of a size cap.
     *
     * A separate method rather than an `encoding`-shaped option on `readFile`:
     * the return type stays unambiguous at every call site, the existing
     * text contract is untouched, and no `string | Uint8Array` union is baked
     * permanently into the published SDK surface.
     */
    readFileBytes(filePath: string, options?: PluginHostCallOptions): Promise<Uint8Array>;
    /**
     * Write UTF-8 text to a file, creating it if absent (parent directories must
     * already exist within scope). Rejects on a missing write capability or an
     * out-of-scope path. Recorded in the audit trail. No cancellation signal —
     * partial-write semantics are deliberately out of scope.
     *
     * Every write is checked (#12323, #12618), with or without `options`: the
     * host serialises writes per resolved path, re-proves containment once the
     * consent prompt and the queue wait are over, refuses a symlink target
     * (`TARGET_IS_SYMLINK`), and — when
     * {@link PluginFsWriteOptions.expectedRevision} is a revision — compares the
     * file's current bytes against it before touching it. The file is then
     * replaced atomically (sibling temp file, flush, rename, original mode
     * preserved), so a file watcher sees the old inode go and a new one arrive.
     * A create-new write (`expectedRevision: null`) is an exclusive create at
     * the target instead, with no temp file. The write resolves the revision of
     * the bytes actually written, so the next `expectedRevision` needs no
     * re-read.
     *
     * What the write promises: a replace never leaves a partial file, every
     * host-mediated writer is serialised, and — given an `expectedRevision` — no
     * change the caller has not seen is clobbered. What it does not promise: a lock against an uncooperative external
     * process — a write that lands between the hash check and the rename is
     * overwritten. The window is small, and callers that care keep their own
     * copy of what they asked to write.
     */
    writeFile(filePath: string, contents: string, options?: PluginFsWriteOptions): Promise<PluginFsWriteResult>;
    /**
     * List a directory's immediate children. Rejects on a missing read capability
     * or an out-of-scope path.
     *
     * Pass `{ detail: true }` to get the metadata and ordering Daintree's own file
     * browser uses — see {@link PluginFsReaddirOptions.detail}.
     */
    readdir(dirPath: string, options?: PluginFsReaddirOptions): Promise<PluginFsDirEntry[]>;
    /** Stat a path. Rejects on a missing read capability or an out-of-scope path. */
    stat(targetPath: string, options?: PluginHostCallOptions): Promise<PluginFsStat>;
    /**
     * Watch one or more contained paths for changes, invoking `callback` with the
     * changed absolute path. `paths` are each resolved and contained at
     * subscription time; an out-of-scope or missing-capability path rejects.
     * Resolves to a disposer that tears the watcher down; all watchers are
     * automatically torn down on unload. Rejects on a missing read capability so
     * authoring mistakes surface loudly. Pass `options.signal` to abort the
     * subscription attempt before it is wired.
     */
    watch(paths: string[], callback: (changedPath: string) => void, options?: PluginHostCallOptions): Promise<() => void>;
}

/**
 * The slice of the host `editFile` needs. `PluginHostApi` satisfies it, and so
 * does any object whose `fs` carries these two methods.
 */
interface EditFileHost {
    readonly fs: Pick<PluginFsApi, "readFileBytes" | "writeFile">;
}
/**
 * Receives the file's current text, or `null` when it does not exist. Return
 * the new text to write it, or the same text, `null` or `undefined` to leave
 * the file as it is. It may run more than once — once per attempt — so it
 * should compute from its argument rather than from state it mutates.
 */
type EditFileTransform = (current: string | null) => string | null | undefined | Promise<string | null | undefined>;
interface EditFileOptions {
    /**
     * How many times to re-read and re-apply after another writer changed the
     * file between this read and this write. Default 5. When they run out, the
     * last conflict error is thrown.
     */
    retries?: number;
}
interface EditFileResult {
    /** Whether this call wrote the file. */
    written: boolean;
    /**
     * The file's revision afterwards: of the bytes written, or of the bytes
     * read when nothing was written. `null` when the file does not exist.
     */
    revision: string | null;
}
/**
 * Read a file, transform its text, and write the result back only if nobody
 * else changed it in between — re-reading and re-applying `transform` when
 * someone did. This is the read → modify → `writeFile({ expectedRevision })`
 * loop every plugin that edits a shared file needs, so an agent's edit to the
 * same file is never clobbered.
 *
 * The file is read as bytes and its revision is the hash of those bytes, so the
 * check is exact even for a file with a byte order mark. A file that is not
 * valid UTF-8 is refused rather than corrupted. A missing file is passed to
 * `transform` as `null`; returning text creates it (a create-new write that
 * fails if the file appears first, which is retried like any other conflict).
 * The parent directory must already exist.
 */
declare function editFile(host: EditFileHost, filePath: string, transform: EditFileTransform, options?: EditFileOptions): Promise<EditFileResult>;

export { type EditFileHost, type EditFileOptions, type EditFileResult, type EditFileTransform, FrontmatterError, type JsonlError, type ParsedFrontmatter, type ParsedJsonl, contentRevision, editFile, parseFrontmatter, parseJsonl, stringifyFrontmatter, stringifyJsonlLine, updateFrontmatter };
