// API surface snapshot for @daintreehq/plugin-sdk.
// AUTO-GENERATED by scripts/ci/check-api-surface.mjs; do not edit by hand.
// Run `npm run api-surface:update` after an intentional public API change and commit the result.

/**
 * What a listed symbolic link points at (#11939).
 *
 * Windows junctions are covered by the same shape with no special-casing: a
 * `Dirent` reports `isSymbolicLink()` true and `isDirectory()` false for both a
 * junction and a directory symlink, and nothing short of reading the target's
 * NT-namespace prefix tells them apart — so nothing here tries to.
 */
interface FileTreeSymlink {
    /**
     * Absolute path the link points at, resolved the way the kernel resolves it
     * — against the canonical directory the entry was listed from, since a raw
     * target like `../acorn/bin/acorn` is relative to where the link lives. That
     * matters when the listed directory is itself reached through a link: the
     * lexical parent and the real parent are different directories, and only the
     * second one gives the target the OS would actually open.
     */
    target: string;
    /**
     * What the target turned out to be, and the single field the browser reads
     * to decide what a link row can do.
     *
     * `"file"` and `"directory"` are the resolved, contained cases — the only
     * two where `isDirectory` reflects the target and descent is allowed.
     * `"broken"` is a target that does not exist. `"external"` is a target that
     * resolves outside the workspace root. `"unknown"` is a target that could
     * not be classified at all (a symlink loop, permission denied) — kept
     * distinct from `"external"` so the UI never tells someone a link points
     * outside their workspace when the truth is that it could not be read.
     *
     * There is deliberately no separate "may I descend" flag. It would be fully
     * derivable from this one, and two fields that must agree are two fields
     * that can disagree.
     */
    targetKind: "file" | "directory" | "broken" | "external" | "unknown";
}
/** File tree node for file picker */
interface FileTreeNode {
    /** File/folder name */
    name: string;
    /** Relative path from worktree root */
    path: string;
    /** Whether this is a directory */
    isDirectory: boolean;
    /** File size in bytes (directories have size 0) */
    size?: number;
    /**
     * Last-modified time in epoch milliseconds, read off the `lstat` the listing
     * already performs — never its own syscall.
     *
     * Absent on nodes that did not come from a live directory read: a tree
     * rehydrated from a persisted snapshot stores structure only, so every
     * consumer needs an answer for "unknown" rather than treating it as 0. It
     * does reach the CopyTree context listing, which applies its include/exclude
     * verdict to the raw listing nodes rather than rebuilding them — the same
     * route `size` already travels.
     */
    mtimeMs?: number;
    /** Children (only populated for directories if expanded) */
    children?: FileTreeNode[];
    /**
     * Present only on symbolic links (#11939). Absence means the entry is a
     * plain file or directory, which is why every consumer can keep reading
     * `isDirectory` and ignore this field entirely.
     *
     * `isDirectory` is true for a link only when `targetKind` is `"directory"`,
     * so a consumer routing on `isDirectory` alone — the CopyTree verdict
     * overlay, the tree's chevron, the expansion fetch — stays correct without
     * ever reading this field.
     *
     * Not carried by the persisted tree snapshot, which stores structure only —
     * a restored out-of-root link comes back as `isDirectory: false` and is
     * therefore still non-descendable, and its decoration returns as soon as the
     * live listing lands.
     */
    symlink?: FileTreeSymlink;
    /**
     * Set when the node contributes nothing to the context CopyTree would
     * generate — an excluded file, or a directory with no includable descendant.
     * Only present on the context listing, and only when the caller opted in with
     * `includeExcluded`; the default listing omits these nodes entirely.
     *
     * There is deliberately no per-node reason. CopyTree 0.16's manifest records
     * only what survived, so an excluded path has no entry to read a reason from,
     * and `stats.excluded.largest` is capped at 50 and ordered by size — pruned
     * directories report size 0 and fall off the list first, which is exactly the
     * case a picker most needs an answer for.
     */
    excluded?: boolean;
}

/** What a file browser orders directory entries by (#11620). */
type FileBrowserSortKey = "name" | "modified" | "size" | "type";
type FileBrowserSortDirection = "asc" | "desc";

/**
 * One rendered line of the tree. The tree is rendered as a flat array rather
 * than nested elements because `react-virtuoso` — the virtualizer already used
 * by the sidebar, logs and console lists — windows a linear item list. Nesting
 * is carried by `depth` and drawn as indentation.
 */
interface FlatTreeRow {
    /** Worktree-relative path; unique across the tree, so it doubles as the React key */
    path: string;
    name: string;
    isDirectory: boolean;
    /** 0 for entries directly under the browser root */
    depth: number;
    /** Directories only: whether this row's children are currently shown */
    isExpanded: boolean;
    /** Directories only: whether a listing for this row is in flight */
    isLoading: boolean;
    /** Byte size for files; undefined for directories */
    size?: number;
    /**
     * Present only on rows that are symbolic links (#11939). `isDirectory` still
     * answers whether the row behaves as a directory — the listing reports the
     * link's *target* kind — so nothing that reads that field needs to know
     * about this one.
     */
    symlink?: FileTreeSymlink;
    /**
     * 1-based position among the row's *visible* siblings, and how many there
     * are. Computed here rather than in the view because only this walk knows
     * what the visibility filter removed: the APG requires `aria-posinset` /
     * `aria-setsize` on a treeitem whose group nesting the DOM does not express,
     * and a virtualized flat list never expresses it. Counting pre-filter would
     * announce positions that do not exist on screen.
     */
    posInSet: number;
    setSize: number;
}
/**
 * The part of a row every entry-level action actually needs: which path, what
 * it's called, and whether it's a directory. Both `FlatTreeRow` and
 * `FolderListingRow` satisfy it structurally, which is what lets the tree and
 * the folder listing share one context-menu builder instead of maintaining two
 * copies of the same menu (#11620).
 */
interface FileEntryLike {
    path: string;
    name: string;
    isDirectory: boolean;
}
/**
 * One rendered line of a folder's contents listing (#11620) — the flat,
 * depth-less counterpart to `FlatTreeRow`. Built from one already-cached
 * directory listing, never its own fetch.
 */
interface FolderListingRow {
    /** Worktree-relative path; unique within the folder, so it doubles as the React key */
    path: string;
    name: string;
    isDirectory: boolean;
    /** Byte size for files; undefined for directories and for snapshot-restored nodes */
    size?: number;
    /** Epoch ms; undefined for snapshot-restored nodes, which carry structure only */
    mtimeMs?: number;
    /**
     * Visible entries directly inside this directory — never recursive, and only
     * when that directory's own listing already happens to be cached. Undefined
     * means "not known", which the row renders as unknown rather than as zero: a
     * folder the user has never opened is not an empty folder.
     */
    itemCount?: number;
    /** Present only on rows that are symbolic links (#11939). */
    symlink?: FileTreeSymlink;
}

/** The sort menu's full state: what to order by, and which way. */
interface FileBrowserSortOrder {
    key: FileBrowserSortKey;
    direction: FileBrowserSortDirection;
}
/**
 * The order the service already returns: folders first, then natural-numeric
 * name (see `FileTreeService`). Sorting by it is a no-op, which is what lets
 * `sortFileNodes` hand back the original array untouched on the default path.
 */
declare const DEFAULT_FILE_SORT: FileBrowserSortOrder;
declare function isDefaultFileSort(sort: FileBrowserSortOrder): boolean;
/**
 * Order one directory's entries for display.
 *
 * Folders always lead, in every key and both directions — the grouping is
 * structural (it is what makes a listing scannable), not part of what the user
 * chose to sort by, and it matches what every file manager does. Direction
 * flips only *within* each group.
 *
 * Returns the input array by reference when the order asked for is the one the
 * service already produced, so the default path costs nothing and the tree's
 * memoized rows keep their identity.
 */
declare function sortFileNodes(nodes: readonly FileTreeNode[], sort: FileBrowserSortOrder): readonly FileTreeNode[];
/**
 * The two visibility controls the browser applies client-side over the raw
 * listing the service now returns (#11330): the app-global always-hidden junk
 * list and the per-panel dotfile toggle. Both filter by entry basename.
 */
interface FileVisibility {
    /** Hide dot-prefixed entries (the per-panel toggle). */
    hideDotfiles: boolean;
    /** Always-hidden basename globs (literal text plus `*` wildcards). */
    alwaysHiddenPatterns: readonly string[];
}
/**
 * Build the per-entry visibility predicate for one panel's current settings. A
 * `true` result means "show this entry".
 */
declare function createVisibilityFilter(visibility: FileVisibility): (name: string) => boolean;
/** How many rows each hiding mechanism is currently removing from the tree. */
interface HiddenRowCounts {
    /** Removed by the per-panel dotfile toggle, and revealable by turning it off. */
    dotfiles: number;
    /** Removed by the app-global always-hidden junk list, which lives in Settings. */
    alwaysHidden: number;
}
declare const NO_HIDDEN_ROWS: HiddenRowCounts;
/**
 * How many rows the two filters are removing from the branches the tree is
 * *currently showing* — the same walk `flattenTree` does, so the number always
 * describes the rows the user could otherwise see right now.
 *
 * Deliberately bounded to loaded, expanded branches. A collapsed folder's
 * contents have usually never been fetched, so any deeper total would be a
 * guess that changes as listings arrive, and a count that climbs on its own
 * while the user is not doing anything is worse than no count at all.
 *
 * The two categories stay separate because their recoveries differ: dotfiles
 * are one toggle away in this panel, while the junk list is an app-global
 * setting. Collapsing them into one number would offer a fix that does not
 * work for half the rows it claims.
 */
declare function countHiddenRows(listings: DirectoryListings, expandedPaths: ReadonlySet<string>, rootPath: string | undefined, visibility: FileVisibility): HiddenRowCounts;
/**
 * Whether the row for a worktree-relative path is currently visible: every path
 * segment below the browser root must pass the filter. Used to reconcile a
 * selection that a visibility change has just hidden. The root's own segments
 * are never tested — the root is the frame, not a row.
 */
declare function isRowPathVisible(relativePath: string, rootPath: string, isVisible: (name: string) => boolean): boolean;
/** Listing state for one directory, keyed by worktree-relative path ("" = root). */
type DirectoryListings = ReadonlyMap<string, readonly FileTreeNode[]>;
/**
 * Flatten the loaded directory listings into the visible row list.
 *
 * Only expanded directories contribute children, and only directories whose
 * listing has already arrived — an expanded-but-unloaded directory renders as a
 * single loading row rather than blocking or collapsing. That is what keeps the
 * tree lazy: expanding a folder is what triggers its fetch, and the row list is
 * always renderable from whatever has arrived so far.
 */
declare function flattenTree(listings: DirectoryListings, expandedPaths: ReadonlySet<string>, loadingPaths: ReadonlySet<string>, rootPath?: string, isVisible?: (name: string) => boolean, sort?: FileBrowserSortOrder): FlatTreeRow[];
/**
 * Build the rows for one folder's contents listing (#11620) from the listing
 * that folder already has cached — never a fetch, and never recursive.
 *
 * Returns null when that folder has not been listed yet, which is the caller's
 * raw "still pending" signal: it is deliberately distinguishable from an empty
 * array (a folder that really holds nothing) so the two never collapse into one
 * indistinguishable state.
 *
 * A directory row's `itemCount` is filled in only when that child's own listing
 * happens to already be cached — expanding it in the tree is what puts it
 * there. Counting means counting *visible* entries, so the number always agrees
 * with what opening the folder would show.
 */
declare function buildFolderListingRows(listings: DirectoryListings, dirPath: string, isVisible?: (name: string) => boolean, sort?: FileBrowserSortOrder): FolderListingRow[] | null;
/**
 * Look one worktree-relative path up in the loaded listings by asking its
 * parent directory, or undefined when that parent has not been listed.
 *
 * This is how the panel learns whether a selection is a file or a folder.
 * Deriving it from the rendered tree rows instead would make the answer depend
 * on what is expanded — and the folder listing can select an entry whose parent
 * is collapsed in the tree, which has no row at all.
 */
declare function findNodeInListings(listings: DirectoryListings, relativePath: string): FileTreeNode | undefined;
/**
 * The directory a worktree-relative path lives in; "" for a root-level entry.
 * This is the listing that answers what the path is, which is why the prune
 * has to keep it alive for as long as something is asking.
 */
declare function parentDirectoryOf(relativePath: string): string;
/**
 * Canonical forward-slash form of a worktree-relative browse root: collapses
 * duplicate separators, drops `.` segments and trailing slashes. Anything
 * traversal-shaped falls back to "" (the worktree root) — a root that can't
 * be trusted must fail toward showing more, never escaping.
 */
declare function canonicalizeRootPath(value: string): string;
/** One level up from a browse root; "" once the last segment is gone. */
declare function parentRootPath(rootPath: string): string;
/**
 * Every ancestor directory of a worktree-relative path, root-first and
 * excluding the path itself. Used to reveal a remembered selection: the
 * directories on the way down have to be expanded before the row exists.
 */
declare function ancestorDirectories(relativePath: string): string[];
/**
 * Where the keyboard should land for a tree key press, or null when the key
 * should fall through to the browser.
 *
 * Pure and separate from the component so the navigation contract — the part
 * with the real edge cases — is testable without a DOM. Follows the tree
 * conventions the issue asks for: right expands, then descends; left collapses,
 * then ascends to the parent.
 */
/**
 * Typeahead: the row a printable-prefix buffer should move the cursor to.
 *
 * Searches forward from the row *after* the cursor and wraps once, so repeating
 * the same letter cycles through every match rather than sticking on the first.
 * The one exception is a buffer that is still being typed (length > 1), which
 * re-tests the cursor row first — otherwise typing `sr` in a folder holding
 * `src` would match `src` on the `s`, then skip past it looking for the next
 * `sr` and land somewhere unrelated.
 *
 * Case-insensitive, and matched against the row `name` rather than the path:
 * the name is what is rendered, and a user typing `p` means the `panels` they
 * can see, not `src/panels`.
 *
 * Returns null when nothing matches, which the caller must treat as "do
 * nothing" — moving the cursor on a failed match would make a typo silently
 * navigate somewhere.
 */
declare function resolveTypeahead(buffer: string, rows: readonly FlatTreeRow[], cursorPath: string | null): string | null;
/**
 * How long a typeahead buffer survives without another keystroke. The WAI-ARIA
 * APG leaves this to the implementation; 1000ms is the long-standing platform
 * default (Windows list views, macOS Finder) and is what a user who pauses
 * mid-word expects to have been forgotten.
 */
declare const TYPEAHEAD_RESET_MS = 1000;
type TreeKeyIntent = {
    type: "select";
    path: string;
} | {
    type: "expand";
    path: string;
} | {
    type: "collapse";
    path: string;
} | {
    type: "activate";
    path: string;
};
declare function resolveTreeKey(key: string, rows: readonly FlatTreeRow[], cursorPath: string | null): TreeKeyIntent | null;

/** Git file status */
type GitStatus = "modified" | "added" | "deleted" | "untracked" | "ignored" | "renamed" | "copied" | "conflicted";

interface FileBrowserGitStatusIndex {
    /** Status of each changed file, keyed by its worktree-relative path. */
    readonly fileStatus: ReadonlyMap<string, GitStatus>;
    /**
     * Worst status anywhere below a directory, keyed by its worktree-relative
     * path. This is what lets a collapsed folder say "something in here changed"
     * without its children ever having been listed.
     */
    readonly folderStatus: ReadonlyMap<string, GitStatus>;
}
/** The shape this module needs off a change; anything wider is the caller's. */
interface IndexableChange {
    relativePath: string;
    status: GitStatus;
}
/**
 * Two flat maps rather than a trie: nothing here enumerates a prefix, it only
 * ever asks "what is the status at exactly this path", so the extra structure
 * would buy nothing and cost a walk per lookup.
 *
 * Built from the changed files alone — dozens to hundreds of entries — never
 * from the tree's lazily-loaded listings, which run to tens of thousands of
 * nodes on a real repository. Construction is linear in total path segments and
 * every lookup is O(1).
 */
declare function buildFileBrowserGitStatusIndex(changes: readonly IndexableChange[]): FileBrowserGitStatusIndex;
/** The marker for one tree row, or undefined when nothing under it changed. */
declare function getFileBrowserRowGitStatus(index: FileBrowserGitStatusIndex | null | undefined, path: string, isDirectory: boolean): GitStatus | undefined;

/**
 * Filename-based file-type classification, shared by Daintree's own file
 * browser and by plugins presenting their own file listings.
 *
 * Deliberately carries no icons and no styling. The category is the durable,
 * curated part — several hundred extensions and basenames, plus the patterns
 * that catch `.eslintrc.json`, `Dockerfile.dev` and `compose.override.yaml` —
 * while which glyph paints it is the consuming UI's business. That split is
 * what lets this ship in the plugin SDK without dragging an icon library or a
 * Tailwind class vocabulary along with it.
 *
 * `ts` is TypeScript, not MPEG transport stream: this is an IDE, and the cost
 * of the two readings is wildly asymmetric.
 */
type FileTypeCategory = "source" | "script" | "data" | "config" | "lock" | "image" | "video" | "audio" | "archive" | "document" | "spreadsheet" | "database" | "font" | "key" | "binary" | "unknown";
/**
 * Classify one file by its name alone.
 *
 * Resolution runs exact basename → pattern → extension → unknown, so the most
 * specific reading of a name always wins. Every step is an O(1) lookup or a
 * short fixed pattern list against module-scope constants, so there is nothing
 * here worth memoizing even when called per visible row.
 *
 * Filename-only by design — no MIME sniffing, no `stat`, no extra round trip.
 * The caller already has the name and nothing else is worth paying for per row.
 */
declare function getFileTypeCategory(filePath: string): FileTypeCategory;

export { DEFAULT_FILE_SORT, type DirectoryListings, type FileBrowserGitStatusIndex, type FileBrowserSortDirection, type FileBrowserSortKey, type FileBrowserSortOrder, type FileEntryLike, type FileTypeCategory, type FileVisibility, type FlatTreeRow, type FolderListingRow, type HiddenRowCounts, NO_HIDDEN_ROWS, TYPEAHEAD_RESET_MS, type TreeKeyIntent, ancestorDirectories, buildFileBrowserGitStatusIndex, buildFolderListingRows, canonicalizeRootPath, countHiddenRows, createVisibilityFilter, findNodeInListings, flattenTree, getFileBrowserRowGitStatus, getFileTypeCategory, isDefaultFileSort, isRowPathVisible, parentDirectoryOf, parentRootPath, resolveTreeKey, resolveTypeahead, sortFileNodes };
