// API surface snapshot for @daintreehq/plugin-sdk.
// AUTO-GENERATED by scripts/ci/check-api-surface.mjs; do not edit by hand.
// Run `npm run api-surface:update` after an intentional public API change and commit the result.

import { ComponentType } from 'react';

/**
 * Public renderer-SDK type surface for `@daintreehq/plugin-sdk/react`.
 *
 * The runtime hooks (`useHostChannel`, `usePluginEvent`) live in `src/hooks/`
 * — the renderer's canonical home, where the `window.electron` ambient global
 * is in scope — and are re-exported verbatim by `packages/plugin-sdk/src/react`
 * so plugin authors and the host bundle share one implementation. These types
 * carry the public signatures; the package's declaration build inlines them.
 */
/**
 * Return shape of the `useHostChannel(pluginId, channel)` hook. `invoke`
 * resolves with the validated channel result on success, or `undefined` if
 * the host rejected the call (the rejection is surfaced via `error`). Only
 * the latest `invoke()` updates `loading` / `error` — stale earlier calls are
 * dropped to keep concurrent invocations coherent.
 */
interface UseHostChannelResult<TArgs, TResult> {
    invoke: (args: TArgs) => Promise<TResult | undefined>;
    loading: boolean;
    error: Error | null;
}
/**
 * Handler signature for `usePluginEvent(pluginId, channel, handler)`. Receives
 * each payload pushed by the plugin's main-side `host.postToPanel(channel,
 * payload)`. Payloads arrive untyped over IPC; `TPayload` narrows the call site
 * — the hook performs no runtime validation (the plugin owns the shape it
 * pushes, mirroring `useHostChannel`'s host-owns-validation contract).
 */
type PluginEventHandler<TPayload> = (payload: TPayload) => void;
/**
 * A reading size for {@link PluginMarkdownProps}, as a rung of Daintree's type
 * scale (11 · 12 · 14 · 16 · 18 · 20 · 24 · 30 px) — the rungs the user's own
 * Markdown text-size control steps through.
 */
type PluginMarkdownFontSize = "2xs" | "xs" | "sm" | "base" | "lg" | "xl" | "2xl" | "3xl";
/**
 * Props of `Markdown` from `@daintreehq/plugin-ui`, the host's own Markdown
 * renderer served to plugin views through the import map. GFM (tables, task
 * lists, strikethrough, autolinks) is on and fenced code is highlighted. Raw
 * HTML in the source is dropped, never rendered, so untrusted text is safe to
 * pass.
 *
 * Links behave as in Daintree's own rendered Markdown: `http(s)` and `mailto`
 * open in the browser, relative links open in the file viewer when they stay
 * inside `rootPath`. Relative images load from disk under the same bound.
 */
interface PluginMarkdownProps {
    /** The Markdown text. */
    source: string;
    /**
     * Absolute path relative links and images resolve against. A path ending in
     * a Markdown extension (`.md`, `.markdown`, `.mdx`, `.mkd`) is read as the
     * document itself and its directory is used; anything else, or a path ending
     * in `/`, is the directory. Omitted, relative references resolve against
     * `rootPath`, or not at all when that is omitted too.
     */
    basePath?: string;
    /**
     * Absolute directory that local images and relative links must stay inside.
     * Defaults to the directory `basePath` resolves to.
     */
    rootPath?: string;
    /** Classes for the document's root element. */
    className?: string;
    /** Reading size. Omitted, the document renders at Daintree's default Markdown size. */
    fontSize?: PluginMarkdownFontSize;
}

/**
 * Typed companion to `host.registerHandler(channel, schema, handler)` for
 * plugin views. Wraps `window.electron.plugin.invoke(pluginId, channel, args)`
 * with single-flight `loading` / `error` state, so a plugin view can call
 * `invoke(args)` from an event handler and render the result without
 * hand-rolling the try/catch shape every time.
 *
 * The hook does not subscribe to the channel's schema — the host owns
 * validation and throws `SCHEMA_ERROR:` / `PERMISSION_REQUIRED:` prefixed
 * errors that surface here as the rejected promise / `error` value. Plugin
 * authors should treat both prefixes as authoring bugs (manifest capability
 * missing, or wrong args shape) rather than runtime failures to surface to
 * end users.
 *
 * Concurrent `invoke()` calls keep only the latest result/error — stale
 * resolutions are dropped so a fast click that triggers two invokes never
 * lets the older response overwrite the newer one. `loading` reflects the
 * latest call only.
 */
declare function useHostChannel<TArgs = unknown, TResult = unknown>(pluginId: string, channel: string): UseHostChannelResult<TArgs, TResult>;

/**
 * Subscribe a plugin view to a host push channel — the renderer side of
 * `host.postToPanel(channel, payload)`. Wraps
 * `window.electron.plugin.on(pluginId, channel, cb)` with automatic teardown so
 * a panel can consume a live stream (poll results, subscription pushes) without
 * hand-managing the unsubscribe disposer on unmount.
 *
 * The latest `handler` is kept in a ref and invoked through a stable wrapper, so
 * passing a fresh inline closure each render does NOT re-subscribe (which would
 * drop in-flight pushes during the resubscribe gap). Only a change to
 * `pluginId` or `channel` tears down and re-opens the subscription.
 *
 * Payloads arrive untyped over IPC (structured-clone). `TPayload` narrows the
 * handler signature for the call site; the hook performs no runtime validation —
 * a plugin owns the shape it pushes, mirroring `useHostChannel`'s
 * host-owns-validation contract.
 */
declare function usePluginEvent<TPayload = unknown>(pluginId: string, channel: string, handler: PluginEventHandler<TPayload>): void;
/**
 * Per-instance sibling of {@link usePluginEvent} — subscribes only to the pushes
 * the plugin's main side targeted at this exact `panelId` via
 * `host.postToPanel(channel, payload, panelId)` (#10618). Two open instances of
 * the same panel kind, each calling this with their own `panelId`, no longer
 * receive each other's pushes. Broadcast pushes (`postToPanel` with no panelId)
 * are NOT delivered here — use {@link usePluginEvent} for those. A panel view
 * gets its instance id from the `panelId` prop the host passes it.
 *
 * Same teardown contract as {@link usePluginEvent}: the latest `handler` is held
 * in a ref behind a stable wrapper, so a fresh inline closure each render does
 * NOT re-subscribe; only a change to `pluginId`, `channel`, or `panelId` tears
 * down and re-opens the subscription.
 */
declare function usePluginPanelEvent<TPayload = unknown>(pluginId: string, channel: string, panelId: string, handler: PluginEventHandler<TPayload>): void;

/** A bundled browser adapter, including every dependency that shares class identities. */
interface PluginDocumentPackage {
    name: string;
    version: string;
    /** SHA-256 of the complete emitted JavaScript, generated by plugin-vite. */
    buildId: string;
    entryUrl: string;
    /** Default: plugin instance. Document scope explicitly shares with other trusted plugins. */
    scope?: "plugin" | "document";
}

/** Retained by the host document across plugin reloads, including failed loads. */
declare function loadDocumentPackage<T = unknown>(moduleUrl: string, descriptor: PluginDocumentPackage): Promise<T>;

/**
 * Counters for one {@link ViewScope}. They describe what the scope itself
 * tracked and nothing else: a resource the view created without registering it
 * is invisible here, so `active: 0` proves nothing about what survived an
 * unmount — a heap snapshot is the tool for that.
 */
interface ViewScopeStats {
    /** Registrations still held: not yet released, cancelled, or fired. */
    readonly active: number;
    /** Cleanups that ran without throwing, including early cancellations and late registrations released on arrival. A one-shot that fired on its own is not counted. */
    readonly released: number;
    /** Cleanups that threw. Each is logged; the rest of the scope is still released. */
    readonly cleanupErrors: number;
    /** Registrations attempted after the scope was disposed. Each is released (or never started) on arrival. */
    readonly lateRegistrations: number;
}
interface ViewScopeOptions {
    /**
     * Called once, after the scope's first disposal has released everything it
     * held — including disposal that happens inside `createViewScope` because the
     * signal was already aborted. Opt-in rather than gated on a build flag: a
     * plugin's panel is a production Vite library build even under
     * `daintree-plugin dev`, so neither `process.env.NODE_ENV` nor
     * `import.meta.env.DEV` says whether anyone is debugging.
     */
    readonly onReport?: (stats: ViewScopeStats) => void;
}
/**
 * A bag of view-owned resources released together. Every method is safe to
 * call after disposal: the resource is released (or never started) on the
 * spot and counted in `lateRegistrations`, so an async continuation that
 * outlives its view attempt cannot leak through the scope.
 *
 * Methods that start something return an idempotent function that releases
 * it early; one-shots (a fired timeout or frame, a `once` listener) forget
 * their registration before the callback runs, so the scope only ever holds
 * what is still live.
 */
interface ViewScope {
    /** True once disposal has started. */
    readonly disposed: boolean;
    /**
     * Aborts when the scope is disposed, before any tracked resource is
     * released. Pass it to `fetch` and other signal-aware APIs; work tied to it
     * directly is not counted in {@link ViewScope.stats}.
     */
    readonly signal: AbortSignal;
    listen<K extends keyof WindowEventMap>(target: Window, type: K, listener: (this: Window, event: WindowEventMap[K]) => void, options?: boolean | AddEventListenerOptions): () => void;
    listen<K extends keyof DocumentEventMap>(target: Document, type: K, listener: (this: Document, event: DocumentEventMap[K]) => void, options?: boolean | AddEventListenerOptions): () => void;
    listen<K extends keyof HTMLElementEventMap>(target: HTMLElement, type: K, listener: (this: HTMLElement, event: HTMLElementEventMap[K]) => void, options?: boolean | AddEventListenerOptions): () => void;
    /**
     * `addEventListener` whose removal is owned by the scope. Each call is an
     * independent subscription, even for a listener already registered. A
     * `signal` in `options` still unsubscribes early, and an already-aborted one
     * subscribes nothing.
     */
    listen(target: EventTarget, type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): () => void;
    setTimeout<A extends unknown[]>(callback: (...args: A) => void, ms?: number, ...args: A): () => void;
    setInterval<A extends unknown[]>(callback: (...args: A) => void, ms?: number, ...args: A): () => void;
    requestAnimationFrame(callback: FrameRequestCallback): () => void;
    /**
     * Adopt a `ResizeObserver`, `MutationObserver`, `IntersectionObserver` or
     * anything else with `disconnect()`, returned as given. Start it before
     * adopting it: a disposed scope disconnects what it adopts on arrival, and an
     * observer started after that would escape the scope. To release one early,
     * register it with {@link ViewScope.add} instead and call the function that
     * returns.
     */
    observe<T extends {
        disconnect(): void;
    }>(observer: T): T;
    /** Adopt a dedicated `Worker` (anything with `terminate()`). */
    worker<T extends {
        terminate(): void;
    }>(worker: T): T;
    /** `URL.createObjectURL` whose `revokeObjectURL` is owned by the scope. */
    objectURL(object: Blob | MediaSource): string;
    /**
     * Adopt a WebGL context from a canvas the view owns. Disposal calls
     * `WEBGL_lose_context.loseContext()` when the extension is available and the
     * context is not already lost, so the GPU allocation goes now rather than at
     * a later GC — Chromium evicts the oldest context once a renderer holds
     * about sixteen.
     */
    webgl<T extends WebGLRenderingContext | WebGL2RenderingContext>(gl: T): T;
    /** Register any synchronous cleanup. The returned function runs it early. */
    add(disposer: () => void): () => void;
    /**
     * Release everything, newest first. Idempotent, never throws: a cleanup that
     * throws is logged and counted, and the rest still run.
     */
    dispose(): void;
    stats(): ViewScopeStats;
}
/**
 * Tie view-owned resources to one mount attempt of a plugin panel view. Pass
 * the view's `disposeSignal`: the scope disposes when it aborts, and when the
 * owning effect calls `dispose()`, whichever comes first.
 *
 * ```tsx
 * useEffect(() => {
 *   const scope = createViewScope(disposeSignal);
 *   scope.listen(window, "resize", onResize);
 *   const observer = new ResizeObserver(onBoxChange);
 *   observer.observe(el);
 *   scope.observe(observer);
 *   return scope.dispose;
 * }, [disposeSignal]);
 * ```
 *
 * Create a fresh scope in each effect setup; a disposed scope cannot be
 * reopened. The scope drops everything it captured once disposed: a stale
 * cancel function retains nothing but the scope's counters, and a stale scope
 * adds only its aborted `signal`, with that signal's reason and listeners.
 */
declare function createViewScope(signal: AbortSignal, options?: ViewScopeOptions): ViewScope;

/**
 * A component from {@link lazyWithPreload}: renders like `React.lazy`, plus
 * `preload()` to fetch its chunk ahead of the first render.
 */
type PreloadableComponent<P, M = unknown> = ComponentType<P> & {
    /** Start (or join) the chunk load. A rejected load is retried by the next call. */
    preload: () => Promise<M>;
    /** True once the chunk has resolved, so a render now cannot suspend. */
    isLoaded: () => boolean;
};
/**
 * `React.lazy` that renders synchronously once its chunk has been preloaded.
 *
 * A plain `lazy()` suspends on its first render even when the chunk was
 * imported moments earlier, and React 19 then holds the Suspense content back
 * for its 300ms fallback throttle — so a preloaded dialog or tab still opens a
 * third of a second late. Here `preload()` records the resolved component and a
 * render that finds it renders it directly. Anything rendered before the chunk
 * lands suspends as usual. Each mounted instance keeps the type it mounted
 * with, so a load resolving mid-life never remounts it.
 *
 * ```tsx
 * const Settings = lazyWithPreload(() => import("./Settings.js"));
 * // or pick a named export:
 * const Chart = lazyWithPreload(() => import("./charts.js"), (m) => m.Chart);
 * <button {...usePreloadOnIntent(Settings)} onClick={open}>Settings</button>
 * ```
 */
declare function lazyWithPreload<P extends object>(load: () => Promise<{
    default: ComponentType<P>;
}>): PreloadableComponent<P, {
    default: ComponentType<P>;
}>;
declare function lazyWithPreload<M, P extends object>(load: () => Promise<M>, pick: (mod: M) => ComponentType<P>): PreloadableComponent<P, M>;
/** Handlers returned by {@link usePreloadOnIntent}; spread them onto the trigger element. */
interface PreloadIntentHandlers {
    onPointerEnter: () => void;
    onFocus: () => void;
}
/**
 * Preload a lazy component when the user shows intent — pointer over or focus
 * on the control that opens it — so the chunk is usually in hand by the click.
 * A failed preload is swallowed here: the render that needs the component
 * retries the load and surfaces the error through its own boundary.
 */
declare function usePreloadOnIntent(target: {
    preload: () => Promise<unknown>;
}): PreloadIntentHandlers;

interface ProgressiveListOptions {
    /** Items rendered in the commit that first shows the list. Default 30. */
    initial?: number;
    /**
     * Items added per growth step. Omitted, the rest of the list arrives in one
     * transition after the first frame; set it for lists long enough that one
     * transition would still be a long task.
     */
    step?: number;
    /**
     * Restarts the budget when it changes — pass something that changes when the
     * list is reopened or re-queried. A list whose items merely update keeps the
     * budget it has grown to.
     */
    resetKey?: string | number;
    /** An index that must always be rendered, e.g. the keyboard selection. */
    minIndex?: number;
}
interface ProgressiveListResult<T> {
    /** The prefix of `items` to render now. Stable while the items and limit are unchanged. */
    visible: readonly T[];
    /** True once every item is rendered. */
    isComplete: boolean;
}
/**
 * Render a long list progressively: the first screenful in the commit that
 * shows it, the rest in transitions scheduled after the first frame has
 * painted. Mounting hundreds of rows at once delays the frame the user is
 * waiting for; this lets the visible rows arrive immediately while the rest
 * never block input, because a keystroke interrupts a pending transition.
 *
 * Every item is eventually mounted, so this suits lists of up to a few hundred
 * rows. For thousands, use {@link useVirtualList}, which mounts only the rows
 * in view.
 */
declare function useProgressiveList<T>(items: readonly T[], options?: ProgressiveListOptions): ProgressiveListResult<T>;

interface VirtualListOptions {
    /** Number of rows. */
    count: number;
    /**
     * Row height in pixels: a number for fixed-height rows (constant-time
     * layout), or a function of the index for rows whose heights are known up
     * front. Heights are not measured from the DOM. Keep a function's identity
     * stable — a new one rebuilds the offset table, which costs O(count).
     */
    estimateSize: number | ((index: number) => number);
    /** Rows rendered beyond each edge of the viewport. Default 4. */
    overscan?: number;
    /**
     * Returns the scrolling element. Rows are assumed to start at the top of its
     * content. Called after each commit, so reading a ref here is fine.
     */
    getScrollElement: () => HTMLElement | null;
}
interface VirtualRow {
    index: number;
    /** Offset from the top of the scroll content, for `transform: translateY(...)` or `top`. */
    start: number;
    size: number;
}
interface VirtualListResult {
    /** The rows to mount, in order. */
    rows: readonly VirtualRow[];
    /** Height to give the inner spacer so the scrollbar reflects every row. */
    totalSize: number;
    /** Scroll so row `index` sits at the top (or bottom, with `"end"`) of the viewport. */
    scrollToIndex: (index: number, align?: "start" | "end") => void;
}
/**
 * Window a long list so only the rows in view (plus `overscan`) are mounted.
 * Re-renders only when the range of visible rows changes, not on every scroll
 * event. Deliberately minimal and dependency-free: row heights come from
 * `estimateSize` rather than DOM measurement, and there is no horizontal or
 * grid mode.
 *
 * ```tsx
 * const scrollRef = useRef<HTMLDivElement>(null);
 * const { rows, totalSize } = useVirtualList({
 *   count: items.length, estimateSize: 28, getScrollElement: () => scrollRef.current,
 * });
 * <div ref={scrollRef} style={{ overflow: "auto", height: "100%" }}>
 *   <div style={{ height: totalSize, position: "relative" }}>
 *     {rows.map((r) => (
 *       <div key={r.index} style={{ position: "absolute", top: r.start, height: r.size, width: "100%" }}>
 *         {items[r.index].name}
 *       </div>
 *     ))}
 *   </div>
 * </div>
 * ```
 */
declare function useVirtualList(options: VirtualListOptions): VirtualListResult;

/** Equality used to decide whether a selected slice changed. */
type EqualityFn<T> = (a: T, b: T) => boolean;
/**
 * One-level equality for objects and arrays: same keys (or length) with
 * `Object.is`-equal values. Pass it as `isEqual` when a selector returns a
 * fresh object or array built from unchanged parts.
 */
declare function shallowEqual<T>(a: T, b: T): boolean;
/**
 * Subscribe to any external store and re-render only when the selected slice
 * changes — `useSyncExternalStore` with a selector. The snapshot passed to the
 * selector must be immutable (replaced, not mutated, on change). A selection
 * that `isEqual` (default `Object.is`) judges unchanged keeps its previous
 * reference, so a selector may build a fresh object each call when paired with
 * {@link shallowEqual}.
 *
 * `subscribe` and `getSnapshot` should be stable (module-level, or memoised):
 * a new `subscribe` re-subscribes. `selector` and `isEqual` may be inline.
 */
declare function useHostStore<TSnapshot, TSelected>(subscribe: (onStoreChange: () => void) => () => void, getSnapshot: () => TSnapshot, selector: (snapshot: TSnapshot) => TSelected, isEqual?: EqualityFn<TSelected>): TSelected;
interface PluginEventSelectorOptions<TPayload, TSelected> {
    /** The payload the selector sees until the first push arrives. */
    initial: TPayload;
    /** Decides whether the selected slice changed. Default `Object.is`. */
    isEqual?: EqualityFn<TSelected>;
    /** Receive only pushes targeted at this panel instance, as {@link usePluginPanelEvent} does. */
    panelId?: string;
}
/**
 * The narrow-subscription form of {@link usePluginEvent}: holds the latest
 * payload pushed on `channel` and re-renders only when `selector(payload)`
 * changes. Use it when a channel pushes a large snapshot (a status map, a
 * tree) and this component shows one part of it: every other push costs a
 * selector call, not a render.
 *
 * Named after `usePluginEvent` because it consumes the same pushes; it returns
 * a value rather than calling a handler, which is what lets React skip the
 * render. {@link useHostStore} is the underlying primitive for stores the view
 * builds itself.
 *
 * ```tsx
 * const count = usePluginEventSelector(pluginId, "status", (s) => s.items.length, {
 *   initial: { items: [] },
 * });
 * ```
 *
 * The store is per hook instance and resets to `initial` when `pluginId`,
 * `channel` or `panelId` changes; pushes sent before the view subscribed are not
 * replayed.
 */
declare function usePluginEventSelector<TPayload, TSelected>(pluginId: string, channel: string, selector: (payload: TPayload) => TSelected, options: PluginEventSelectorOptions<TPayload, TSelected>): TSelected;

interface CachedHostChannelOptions {
    /**
     * How long a cached result counts as fresh, in ms. A fresh entry is painted
     * without revalidating; a stale one is painted and then revalidated. Default
     * 0: always revalidate on mount, but never wait for it to paint.
     */
    staleMs?: number;
    /**
     * Cache key for `args`. Omitted, `args` is encoded with sorted object keys,
     * which requires plain data (primitives, arrays, plain objects); pass a key
     * when they are not, or when a cheaper identity is at hand.
     */
    cacheKey?: string;
    /**
     * The view's `disposeSignal` (or a {@link ViewScope}'s `signal`). Once it
     * aborts the hook starts no further requests and `revalidate()` resolves
     * `undefined`. A request already sent still completes and fills the cache for
     * the next mount — the host bridge has no cancellation.
     */
    signal?: AbortSignal;
    /** False skips fetching (the cached value, if any, is still returned). Default true. */
    enabled?: boolean;
}
interface CachedHostChannelResult<TResult> {
    /** The latest successful result, cached or fresh; `undefined` until the first one lands. */
    data: TResult | undefined;
    /** The latest failure. `data` keeps the last good result alongside it. */
    error: Error | null;
    /** True while a request for this key is in flight, including background revalidation. */
    validating: boolean;
    /** When `data` was fetched (epoch ms), or 0 if never. */
    updatedAt: number;
    /**
     * Fetch now, superseding any request in flight for this key (use after a
     * mutation). Resolves the new result, or `undefined` if it failed, was
     * superseded, or the signal had aborted.
     */
    revalidate: () => Promise<TResult | undefined>;
}
/**
 * Entries kept once no view is subscribed to them. Entries a mounted view is
 * showing, or with a request in flight, are kept on top of this.
 */
declare const HOST_CHANNEL_CACHE_LIMIT = 50;
/**
 * Paint-first companion to {@link useHostChannel}: returns the cached result
 * for `(pluginId, channel, args)` immediately and revalidates it in the
 * background, so reopening a view shows its last data in the first frame
 * instead of a spinner.
 *
 * The cache is module-level, shared by every view in the bundle, and bounded:
 * beyond the entries mounted views are showing, at most
 * {@link HOST_CHANNEL_CACHE_LIMIT}, least recently used evicted first. Concurrent mounts of the same key share
 * one request. Results are structured-clone copies from the host, shared by
 * reference between views — treat them as immutable.
 *
 * ```tsx
 * const { data, error, validating } = useCachedHostChannel<{ repo: string }, Pr[]>(
 *   pluginId, "list-prs", { repo }, { staleMs: 30_000, signal: disposeSignal },
 * );
 * ```
 */
declare function useCachedHostChannel<TArgs = unknown, TResult = unknown>(pluginId: string, channel: string, args: TArgs, options?: CachedHostChannelOptions): CachedHostChannelResult<TResult>;

interface ThrottledCallbackOptions {
    /**
     * Minimum gap between calls, in ms. Omitted, calls coalesce to one per
     * animation frame (trailing, with the latest arguments). With `ms`, the first
     * call runs at once and later ones within the window collapse into one
     * trailing call with the latest arguments.
     */
    ms?: number;
}
/** A throttled function from {@link useThrottledCallback}. Identity is stable for the life of the component. */
type ThrottledCallback<A extends unknown[]> = ((...args: A) => void) & {
    /** Drop a pending trailing call. */
    cancel: () => void;
};
/**
 * Coalesce a callback that fires faster than the view can usefully paint —
 * progress ticks, streamed log lines, pointer moves — so it runs at most once
 * per frame (or per `ms`) with the latest arguments. Wrap the state setter
 * rather than the render: pushes still arrive at full rate, React just commits
 * once per frame.
 *
 * ```tsx
 * const [progress, setProgress] = useState(0);
 * const onTick = useThrottledCallback((p: { done: number }) => setProgress(p.done));
 * usePluginEvent(pluginId, "build-progress", onTick);
 * ```
 *
 * The latest `callback` is always the one called. A pending call is dropped on
 * unmount, and calls after unmount do nothing.
 */
declare function useThrottledCallback<A extends unknown[]>(callback: (...args: A) => void, options?: ThrottledCallbackOptions): ThrottledCallback<A>;

export { type CachedHostChannelOptions, type CachedHostChannelResult, type EqualityFn, HOST_CHANNEL_CACHE_LIMIT, type PluginDocumentPackage, type PluginEventHandler, type PluginEventSelectorOptions, type PluginMarkdownFontSize, type PluginMarkdownProps, type PreloadIntentHandlers, type PreloadableComponent, type ProgressiveListOptions, type ProgressiveListResult, type ThrottledCallback, type ThrottledCallbackOptions, type UseHostChannelResult, type ViewScope, type ViewScopeOptions, type ViewScopeStats, type VirtualListOptions, type VirtualListResult, type VirtualRow, createViewScope, lazyWithPreload, loadDocumentPackage, shallowEqual, useCachedHostChannel, useHostChannel, useHostStore, usePluginEvent, usePluginEventSelector, usePluginPanelEvent, usePreloadOnIntent, useProgressiveList, useThrottledCallback, useVirtualList };
