// API surface snapshot for @daintreehq/plugin-sdk.
// AUTO-GENERATED by scripts/ci/check-api-surface.mjs; do not edit by hand.
// Run `npm run api-surface:update` after an intentional public API change and commit the result.

/**
 * Public renderer-SDK type surface for `@daintreehq/plugin-sdk/react`.
 *
 * The runtime hooks (`useHostChannel`, `usePluginEvent`) live in `src/hooks/`
 * — the renderer's canonical home, where the `window.electron` ambient global
 * is in scope — and are re-exported verbatim by `packages/plugin-sdk/src/react`
 * so plugin authors and the host bundle share one implementation. These types
 * carry the public signatures; the package's declaration build inlines them.
 */
/**
 * Return shape of the `useHostChannel(pluginId, channel)` hook. `invoke`
 * resolves with the validated channel result on success, or `undefined` if
 * the host rejected the call (the rejection is surfaced via `error`). Only
 * the latest `invoke()` updates `loading` / `error` — stale earlier calls are
 * dropped to keep concurrent invocations coherent.
 */
interface UseHostChannelResult<TArgs, TResult> {
    invoke: (args: TArgs) => Promise<TResult | undefined>;
    loading: boolean;
    error: Error | null;
}
/**
 * Handler signature for `usePluginEvent(pluginId, channel, handler)`. Receives
 * each payload pushed by the plugin's main-side `host.postToPanel(channel,
 * payload)`. Payloads arrive untyped over IPC; `TPayload` narrows the call site
 * — the hook performs no runtime validation (the plugin owns the shape it
 * pushes, mirroring `useHostChannel`'s host-owns-validation contract).
 */
type PluginEventHandler<TPayload> = (payload: TPayload) => void;

/**
 * Typed companion to `host.registerHandler(channel, schema, handler)` for
 * plugin views. Wraps `window.electron.plugin.invoke(pluginId, channel, args)`
 * with single-flight `loading` / `error` state, so a plugin view can call
 * `invoke(args)` from an event handler and render the result without
 * hand-rolling the try/catch shape every time.
 *
 * The hook does not subscribe to the channel's schema — the host owns
 * validation and throws `SCHEMA_ERROR:` / `PERMISSION_REQUIRED:` prefixed
 * errors that surface here as the rejected promise / `error` value. Plugin
 * authors should treat both prefixes as authoring bugs (manifest capability
 * missing, or wrong args shape) rather than runtime failures to surface to
 * end users.
 *
 * Concurrent `invoke()` calls keep only the latest result/error — stale
 * resolutions are dropped so a fast click that triggers two invokes never
 * lets the older response overwrite the newer one. `loading` reflects the
 * latest call only.
 */
declare function useHostChannel<TArgs = unknown, TResult = unknown>(pluginId: string, channel: string): UseHostChannelResult<TArgs, TResult>;

/**
 * Subscribe a plugin view to a host push channel — the renderer side of
 * `host.postToPanel(channel, payload)`. Wraps
 * `window.electron.plugin.on(pluginId, channel, cb)` with automatic teardown so
 * a panel can consume a live stream (poll results, subscription pushes) without
 * hand-managing the unsubscribe disposer on unmount.
 *
 * The latest `handler` is kept in a ref and invoked through a stable wrapper, so
 * passing a fresh inline closure each render does NOT re-subscribe (which would
 * drop in-flight pushes during the resubscribe gap). Only a change to
 * `pluginId` or `channel` tears down and re-opens the subscription.
 *
 * Payloads arrive untyped over IPC (structured-clone). `TPayload` narrows the
 * handler signature for the call site; the hook performs no runtime validation —
 * a plugin owns the shape it pushes, mirroring `useHostChannel`'s
 * host-owns-validation contract.
 */
declare function usePluginEvent<TPayload = unknown>(pluginId: string, channel: string, handler: PluginEventHandler<TPayload>): void;
/**
 * Per-instance sibling of {@link usePluginEvent} — subscribes only to the pushes
 * the plugin's main side targeted at this exact `panelId` via
 * `host.postToPanel(channel, payload, panelId)` (#10618). Two open instances of
 * the same panel kind, each calling this with their own `panelId`, no longer
 * receive each other's pushes. Broadcast pushes (`postToPanel` with no panelId)
 * are NOT delivered here — use {@link usePluginEvent} for those. A panel view
 * gets its instance id from the `panelId` prop the host passes it.
 *
 * Same teardown contract as {@link usePluginEvent}: the latest `handler` is held
 * in a ref behind a stable wrapper, so a fresh inline closure each render does
 * NOT re-subscribe; only a change to `pluginId`, `channel`, or `panelId` tears
 * down and re-opens the subscription.
 */
declare function usePluginPanelEvent<TPayload = unknown>(pluginId: string, channel: string, panelId: string, handler: PluginEventHandler<TPayload>): void;

export { type PluginEventHandler, type UseHostChannelResult, useHostChannel, usePluginEvent, usePluginPanelEvent };
