import type { SettingsTab, SettingsScope } from "./SettingsDialog";
import { BUILT_IN_AGENT_IDS } from "@shared/config/agentIds";
import { AGENT_REGISTRY } from "@shared/config/agentRegistry";

export interface SettingsSearchEntry {
  id: string;
  tab: SettingsTab;
  tabLabel: string;
  scope: SettingsScope;
  /** Optional subtab id to activate when navigating to this result. */
  subtab?: string;
  /** Human-readable subtab label used in search breadcrumbs and haystack. */
  subtabLabel?: string;
  section: string;
  title: string;
  description: string;
  keywords?: string[];
  /** When set, indicates this setting is only visible when a parent setting is enabled. */
  requiresEnabled?: {
    /** id of the gate entry in the search index (e.g. "mcp-server-enable") */
    settingId: string;
    /** Human-readable label shown in warnings (e.g. "MCP Server") */
    label: string;
  };
}

export const SETTINGS_SEARCH_INDEX: SettingsSearchEntry[] = [
  // ── Tab-level navigation entries (one per tab) ──
  // tabLabel values must match tabTitles in SettingsDialog.tsx
  {
    id: "tab-nav-general",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    section: "Settings Navigation",
    title: "General",
    description: "About, system status, hibernation, and display settings",
    keywords: ["general", "settings", "about", "status"],
  },
  {
    id: "tab-nav-keyboard",
    tab: "keyboard",
    scope: "global",
    tabLabel: "Keyboard Shortcuts",
    section: "Settings Navigation",
    title: "Keyboard Shortcuts",
    description: "View and customize keyboard shortcut bindings",
    keywords: ["general", "keyboard", "keybindings", "hotkeys", "shortcuts"],
  },
  {
    id: "tab-nav-terminalAppearance",
    tab: "terminalAppearance",
    scope: "global",
    tabLabel: "Appearance",
    section: "Settings Navigation",
    title: "Appearance",
    description: "Theme, terminal colors, font size, and font family",
    keywords: ["general", "appearance", "theme", "colors", "font"],
  },
  {
    id: "tab-nav-notifications",
    tab: "notifications",
    scope: "global",
    tabLabel: "Notifications",
    section: "Settings Navigation",
    title: "Notifications",
    description: "Agent notification alerts and sound settings",
    keywords: ["general", "notifications", "alerts", "sounds"],
  },
  {
    id: "tab-nav-terminal",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    section: "Settings Navigation",
    title: "Panel Grid",
    description: "Panel grid layout, scrollback, split pane, and performance settings",
    keywords: ["terminal", "panel", "grid", "layout", "panes"],
  },
  {
    id: "tab-nav-worktree",
    tab: "worktree",
    scope: "global",
    tabLabel: "Worktree Paths",
    section: "Settings Navigation",
    title: "Worktree Paths",
    description: "Configure where git worktrees are created",
    keywords: ["terminal", "worktree", "paths", "git", "directory"],
  },
  {
    id: "tab-nav-toolbar",
    tab: "toolbar",
    scope: "global",
    tabLabel: "Toolbar Customization",
    section: "Settings Navigation",
    title: "Toolbar Customization",
    description: "Reorder, show, and hide toolbar buttons and launcher settings",
    keywords: ["terminal", "toolbar", "buttons", "customize"],
  },
  {
    id: "tab-nav-agents",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    section: "Settings Navigation",
    title: "CLI Agents",
    description: "Configure CLI agent settings",
    keywords: [
      "integrations",
      "agents",
      ...BUILT_IN_AGENT_IDS.flatMap((id) =>
        [id, AGENT_REGISTRY[id]?.name?.toLowerCase()].filter((s): s is string => Boolean(s))
      ),
    ],
  },
  {
    id: "tab-nav-github",
    tab: "github",
    scope: "global",
    tabLabel: "GitHub Integration",
    section: "Settings Navigation",
    title: "GitHub Integration",
    description: "GitHub personal access token and authentication",
    keywords: ["integrations", "github", "token", "authentication"],
  },
  {
    id: "tab-nav-integrations",
    tab: "integrations",
    scope: "global",
    tabLabel: "Integrations",
    section: "Settings Navigation",
    title: "Integrations",
    description: "External editor, image viewer, and other tool integrations",
    keywords: ["integrations", "editor", "vscode", "cursor", "ide", "image", "viewer", "photo"],
  },
  {
    id: "tab-nav-voice",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "Settings Navigation",
    title: "Voice Input",
    description: "Speech-to-text transcription and AI text correction settings",
    keywords: ["voice", "microphone", "speech", "dictation", "deepgram", "openai", "transcription"],
  },
  {
    id: "tab-nav-portal",
    tab: "portal",
    scope: "global",
    tabLabel: "Portal Links",
    section: "Settings Navigation",
    title: "Portal Links",
    description: "Default and custom links for the portal browser panel",
    keywords: ["integrations", "portal", "links", "browser", "bookmarks"],
  },
  {
    id: "tab-nav-mcp",
    tab: "mcp",
    scope: "global",
    tabLabel: "MCP Server",
    section: "Settings Navigation",
    title: "MCP Server",
    description: "Local MCP server for AI agent automation",
    keywords: ["integrations", "mcp", "server", "automation", "api"],
  },
  {
    id: "tab-nav-environment",
    tab: "environment",
    scope: "global",
    tabLabel: "Environment Variables",
    section: "Settings Navigation",
    title: "Environment Variables",
    description: "Per-project environment variables injected into all terminals",
    keywords: ["terminal", "environment", "variables", "env", "project", "inject", "secrets"],
  },
  {
    id: "tab-nav-privacy",
    tab: "privacy",
    scope: "global",
    tabLabel: "Privacy & Data",
    section: "Settings Navigation",
    title: "Privacy & Data",
    description: "Telemetry level, log retention, data folder, cache, and factory reset",
    keywords: ["privacy", "data", "telemetry", "reset", "cache", "logs"],
  },
  {
    id: "tab-nav-troubleshooting",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "Settings Navigation",
    title: "Troubleshooting",
    description: "System health, logs, diagnostics, and developer mode",
    keywords: ["support", "troubleshooting", "debug", "logs", "health"],
  },

  // ── Field-level entries ──

  // General
  {
    id: "general-about",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "overview",
    subtabLabel: "Overview",
    section: "About",
    title: "About Daintree",
    description: "App version and description",
    keywords: ["version", "about", "info", "beta"],
  },
  {
    id: "general-system-status",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "overview",
    subtabLabel: "Overview",
    section: "System Status",
    title: "System Status",
    description: "Installed agents and their operational status",
    keywords: ["agents", "cli", "available", "status", "check", "ready"],
  },
  {
    id: "general-update-channel",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "overview",
    subtabLabel: "Overview",
    section: "Update Channel",
    title: "Update Channel",
    description: "Switch between stable and nightly update channels",
    keywords: ["update", "channel", "stable", "nightly", "releases"],
  },
  {
    id: "general-hibernation",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "hibernation",
    subtabLabel: "Hibernation",
    section: "Auto-Hibernation",
    title: "Auto-Hibernation",
    description:
      "Automatically stop terminals and servers for inactive projects. Reduces system resource usage.",
    keywords: ["hibernate", "sleep", "inactive", "stop", "resources", "idle", "auto"],
  },
  {
    id: "general-hibernation-threshold",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "hibernation",
    subtabLabel: "Hibernation",
    section: "Auto-Hibernation",
    title: "Inactivity Threshold",
    description: "How long before a project is hibernated: 12h, 24h, 48h, or 72h",
    keywords: ["hibernate", "threshold", "hours", "timeout", "inactivity"],
  },
  {
    id: "general-idle-terminal-notify",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "hibernation",
    subtabLabel: "Hibernation",
    section: "Idle Terminal Notifications",
    title: "Idle Terminal Notifications",
    description:
      "Notify when background project terminals have been idle past a threshold. Includes Close Them / Dismiss actions.",
    keywords: ["idle", "notify", "terminal", "background", "reminder", "inactive", "close"],
  },
  {
    id: "general-idle-terminal-threshold",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "hibernation",
    subtabLabel: "Hibernation",
    section: "Idle Terminal Notifications",
    title: "Idle Threshold",
    description: "Minutes of inactivity before notifying: 30m, 1h, 2h, or 4h",
    keywords: ["idle", "threshold", "minutes", "notify", "inactivity", "background"],
  },
  {
    id: "general-project-pulse",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "display",
    subtabLabel: "Display",
    section: "Display",
    title: "Project Pulse",
    description: "Show activity heatmap on the empty panel grid",
    keywords: ["heatmap", "activity", "pulse", "display", "visualization"],
  },
  {
    id: "general-developer-tools",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "display",
    subtabLabel: "Display",
    section: "Display",
    title: "Developer Tools",
    description: "Show problems panel button in the toolbar",
    keywords: ["developer", "debug", "problems", "panel", "toolbar"],
  },
  {
    id: "general-grid-agent-highlights",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "display",
    subtabLabel: "Display",
    section: "Display",
    title: "Grid Panel Agent Highlights",
    description: "Show waiting and working state borders on grid panels",
    keywords: ["agent", "highlight", "border", "waiting", "working", "grid", "panel", "state"],
  },
  {
    id: "general-dock-agent-highlights",
    tab: "general",
    scope: "global",
    tabLabel: "General",
    subtab: "display",
    subtabLabel: "Display",
    section: "Display",
    title: "Dock Item Agent Highlights",
    description: "Show waiting state borders on dock items",
    keywords: ["agent", "highlight", "border", "waiting", "dock", "item", "state"],
  },

  // Keyboard Shortcuts
  {
    id: "keyboard-shortcuts",
    tab: "keyboard",
    scope: "global",
    tabLabel: "Keyboard Shortcuts",
    section: "Keyboard Shortcuts",
    title: "Keyboard Shortcuts",
    description:
      "View and customize keyboard bindings for all actions. Search and override shortcuts.",
    keywords: ["keybindings", "shortcuts", "hotkeys", "bindings", "key", "remap"],
  },
  {
    id: "keyboard-profiles",
    tab: "keyboard",
    scope: "global",
    tabLabel: "Keyboard Shortcuts",
    section: "Keyboard Shortcuts",
    title: "Shortcut Profiles",
    description: "Import and export shortcut profile configurations",
    keywords: ["profile", "import", "export", "backup", "keybindings"],
  },
  {
    id: "keyboard-reset",
    tab: "keyboard",
    scope: "global",
    tabLabel: "Keyboard Shortcuts",
    section: "Keyboard Shortcuts",
    title: "Reset All Shortcuts",
    description: "Reset all keyboard shortcuts to their default bindings",
    keywords: ["reset", "default", "shortcuts", "restore", "keybindings"],
  },

  // Terminal (Panel Grid)
  {
    id: "terminal-performance-mode",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "performance",
    subtabLabel: "Performance",
    section: "Performance Mode",
    title: "Performance Mode",
    description:
      "Reduces scrollback and disables animations for maximum performance on low-end hardware",
    keywords: ["performance", "speed", "low-end", "memory", "animation", "disable"],
  },
  {
    id: "terminal-panel-limits",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "performance",
    subtabLabel: "Performance",
    section: "Panel Limits",
    title: "Panel Limits",
    description:
      "Hardware-aware panel limits with soft warning, confirmation, and hard limit thresholds",
    keywords: [
      "panel",
      "limit",
      "warning",
      "hardware",
      "RAM",
      "memory",
      "disable",
      "threshold",
      "confirm",
    ],
  },
  {
    id: "terminal-panel-warnings-toggle",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "performance",
    subtabLabel: "Performance",
    section: "Panel Limits",
    title: "Disable Panel Warnings",
    description:
      "Turn off soft warning banner and confirmation dialog while keeping the hard limit",
    keywords: ["disable", "warning", "panel", "nag", "dismiss", "suppress"],
  },
  {
    id: "terminal-hybrid-input",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "input",
    subtabLabel: "Input",
    section: "Hybrid Input Bar",
    title: "Hybrid Input Bar",
    description: "Show the multi-line input bar on agent terminals",
    keywords: ["input", "hybrid", "bar", "multi-line", "agent", "textarea"],
  },
  {
    id: "terminal-hybrid-autofocus",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "input",
    subtabLabel: "Input",
    section: "Hybrid Input Bar",
    title: "Auto-Focus Input",
    description: "Selecting a pane focuses the input bar or the terminal (xterm)",
    keywords: ["focus", "autofocus", "input", "pane", "select"],
  },
  {
    id: "terminal-two-pane-split",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "layout",
    subtabLabel: "Layout",
    section: "Two-Pane Split Layout",
    title: "Two-Pane Split Layout",
    description: "When exactly two panels are open, display them with a resizable divider",
    keywords: ["split", "two pane", "layout", "divider", "resize", "ratio"],
  },
  {
    id: "terminal-scrollback",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "scrollback",
    subtabLabel: "Scrollback",
    section: "Scrollback History",
    title: "Scrollback History",
    description:
      "Set base scrollback lines for terminal history: 500, 1,000, 2,500, or 5,000 lines",
    keywords: ["scrollback", "history", "lines", "buffer", "memory", "terminal"],
  },
  {
    id: "terminal-grid-layout",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "layout",
    subtabLabel: "Layout",
    section: "Grid Layout Strategy",
    title: "Grid Layout Strategy",
    description: "Control how panels arrange in the grid: automatic, fixed columns, or fixed rows",
    keywords: ["grid", "layout", "columns", "rows", "panels", "arrangement", "strategy"],
  },

  {
    id: "terminal-screen-reader",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "accessibility",
    subtabLabel: "Accessibility",
    section: "Screen Reader Mode",
    title: "Screen Reader Mode",
    description:
      "Enable screen reader support for terminal output. Auto mode follows OS accessibility state.",
    keywords: [
      "screen reader",
      "accessibility",
      "a11y",
      "voiceover",
      "jaws",
      "nvda",
      "screenReaderMode",
      "assistive",
    ],
  },

  // Appearance
  {
    id: "appearance-theme",
    tab: "terminalAppearance",
    scope: "global",
    tabLabel: "Appearance",
    subtab: "app",
    subtabLabel: "App",
    section: "App Theme",
    title: "App Theme",
    description: "Choose the application color theme",
    keywords: ["theme", "dark", "light", "color", "scheme", "appearance", "mode"],
  },
  {
    id: "appearance-color-vision",
    tab: "terminalAppearance",
    scope: "global",
    tabLabel: "Appearance",
    subtab: "app",
    subtabLabel: "App",
    section: "Color Vision",
    title: "Color Vision",
    description: "Adjust colors for color vision deficiency (colorblind mode)",
    keywords: [
      "colorblind",
      "color vision",
      "deuteranopia",
      "protanopia",
      "tritanopia",
      "accessibility",
      "CVD",
      "red-green",
      "blue-yellow",
    ],
  },
  {
    id: "appearance-dock-density",
    tab: "terminalAppearance",
    scope: "global",
    tabLabel: "Appearance",
    subtab: "app",
    subtabLabel: "App",
    section: "Dock Density",
    title: "Dock Density",
    description: "Control dock bar height: compact, normal, or comfortable",
    keywords: ["dock", "density", "compact", "comfortable", "height", "size", "spacing"],
  },
  {
    id: "appearance-color-scheme",
    tab: "terminalAppearance",
    scope: "global",
    tabLabel: "Appearance",
    subtab: "terminal",
    subtabLabel: "Terminal",
    section: "Terminal Color Scheme",
    title: "Terminal Color Scheme",
    description: "Choose the terminal color scheme and palette",
    keywords: ["color", "scheme", "terminal", "colors", "palette", "theme"],
  },
  {
    id: "appearance-font-size",
    tab: "terminalAppearance",
    scope: "global",
    tabLabel: "Appearance",
    subtab: "terminal",
    subtabLabel: "Terminal",
    section: "Font Size",
    title: "Font Size",
    description: "Set terminal font size from 8px to 24px",
    keywords: ["font", "size", "text", "px", "terminal", "larger", "smaller"],
  },
  {
    id: "appearance-font-family",
    tab: "terminalAppearance",
    scope: "global",
    tabLabel: "Appearance",
    subtab: "terminal",
    subtabLabel: "Terminal",
    section: "Font Family",
    title: "Font Family",
    description: "Choose terminal font: JetBrains Mono or system monospace",
    keywords: ["font", "family", "mono", "JetBrains", "monospace", "typeface"],
  },

  // Worktree Paths
  {
    id: "worktree-path-pattern",
    tab: "worktree",
    scope: "global",
    tabLabel: "Worktree Paths",
    section: "Worktree Path Pattern",
    title: "Worktree Path Pattern",
    description:
      "Customize where worktrees are created using variables: {base-folder}, {branch-slug}, {repo-name}, {parent-dir}",
    keywords: ["worktree", "path", "pattern", "branch", "folder", "directory", "location", "git"],
  },

  // CLI Agents — General subtab
  {
    id: "agents-default-agent",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    subtab: "general",
    subtabLabel: "General",
    section: "Global Agent Settings",
    title: "Default Agent",
    description:
      'Agent used for the help dock button (\u2318\u21e7H) and automated workflows ("What\'s Next?", onboarding, project explanations). Distinct from the Portal "Default New Tab Agent".',
    keywords: [
      "default",
      "agent",
      "workflow",
      "automated",
      "whats next",
      "onboarding",
      "help",
      "dock",
      "launch",
      "keyboard shortcut",
      ...BUILT_IN_AGENT_IDS,
    ],
  },

  // CLI Agents — per-agent subtabs (default to "claude" subtab so search results land inside an agent card)
  {
    id: "agents-enable",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    subtab: "claude",
    subtabLabel: "Claude",
    section: "Agent Runtime Settings",
    title: "Enable / Disable Agent",
    description: "Enable or disable individual CLI agents",
    keywords: ["agent", "enable", "disable", ...BUILT_IN_AGENT_IDS, "select"],
  },
  {
    id: "agents-skip-permissions",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    subtab: "claude",
    subtabLabel: "Claude",
    section: "Agent Runtime Settings",
    title: "Skip Permissions",
    description: "Auto-approve all agent actions without confirmation prompts",
    keywords: ["permissions", "auto-approve", "confirm", "prompts", "dangerous", "allow", "bypass"],
  },
  {
    id: "agents-inline-mode",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    subtab: "claude",
    subtabLabel: "Claude",
    section: "Agent Runtime Settings",
    title: "Inline Mode",
    description: "Disable fullscreen TUI for better resize handling and scrollback",
    keywords: ["inline", "mode", "tui", "fullscreen", "resize", "tty"],
  },
  {
    id: "agents-clipboard",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    subtab: "gemini",
    subtabLabel: "Gemini",
    section: "Agent Runtime Settings",
    title: "Share Clipboard Directory",
    description: "Allow Gemini to read pasted clipboard images",
    keywords: ["clipboard", "images", "share", "gemini", "paste", "screenshot"],
  },
  {
    id: "agents-custom-args",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    subtab: "claude",
    subtabLabel: "Claude",
    section: "Agent Runtime Settings",
    title: "Custom Arguments",
    description: "Extra CLI flags appended when launching agents",
    keywords: ["args", "arguments", "flags", "cli", "custom", "launch", "options"],
  },
  {
    id: "agents-installation",
    tab: "agents",
    scope: "global",
    tabLabel: "CLI Agents",
    subtab: "claude",
    subtabLabel: "Claude",
    section: "Installation",
    title: "Agent Installation",
    description: "Install and set up CLI agents. Run setup wizard to install.",
    keywords: ["install", "setup", "wizard", "cli", "download", "npm", "brew"],
  },

  // GitHub Integration
  {
    id: "github-token",
    tab: "github",
    scope: "global",
    tabLabel: "GitHub Integration",
    section: "Personal Access Token",
    title: "GitHub Personal Access Token",
    description: "Configure GitHub authentication token. Required scopes: repo, read:org",
    keywords: ["github", "token", "authentication", "auth", "PAT", "access", "scopes", "API"],
  },

  // Portal Links
  {
    id: "portal-default-agent",
    tab: "portal",
    scope: "global",
    tabLabel: "Portal Links",
    section: "Default New Tab Agent",
    title: "Default New Tab Agent",
    description: "Choose which agent opens when you click the + button in the portal",
    keywords: ["portal", "agent", "default", "new tab", "browser"],
  },
  {
    id: "portal-default-links",
    tab: "portal",
    scope: "global",
    tabLabel: "Portal Links",
    section: "Default Links",
    title: "Default Links",
    description: "System-provided links shown in the portal panel",
    keywords: ["portal", "links", "default", "browser", "bookmarks"],
  },
  {
    id: "portal-custom-links",
    tab: "portal",
    scope: "global",
    tabLabel: "Portal Links",
    section: "Custom Links",
    title: "Custom Links",
    description: "Add custom URLs and links to the portal panel",
    keywords: ["portal", "custom", "links", "url", "add", "bookmark"],
  },

  // Toolbar Customization
  {
    id: "toolbar-left-buttons",
    tab: "toolbar",
    scope: "global",
    tabLabel: "Toolbar Customization",
    section: "Left Side Buttons",
    title: "Left Toolbar Buttons",
    description: "Drag to reorder, uncheck to hide left toolbar buttons",
    keywords: ["toolbar", "buttons", "left", "reorder", "customize", "hide"],
  },
  {
    id: "toolbar-right-buttons",
    tab: "toolbar",
    scope: "global",
    tabLabel: "Toolbar Customization",
    section: "Right Side Buttons",
    title: "Right Toolbar Buttons",
    description: "Drag to reorder, uncheck to hide right toolbar buttons",
    keywords: ["toolbar", "buttons", "right", "reorder", "customize", "hide"],
  },
  {
    id: "toolbar-launcher",
    tab: "toolbar",
    scope: "global",
    tabLabel: "Toolbar Customization",
    section: "Launcher Palette",
    title: "Launcher Palette Settings",
    description:
      "Configure the default panel type highlighted when opening the launcher. Always show dev server option.",
    keywords: ["launcher", "palette", "default", "panel", "dev server", "open", "selection"],
  },
  {
    id: "toolbar-reset",
    tab: "toolbar",
    scope: "global",
    tabLabel: "Toolbar Customization",
    section: "Toolbar Customization",
    title: "Reset Toolbar to Defaults",
    description: "Reset all toolbar button positions and visibility to defaults",
    keywords: ["reset", "default", "toolbar", "restore"],
  },

  // Notifications
  {
    id: "notifications-completed",
    tab: "notifications",
    scope: "global",
    tabLabel: "Notifications",
    section: "Agent Notifications",
    title: "Agent Completed Notification",
    description: "Show a notification when an agent finishes its task",
    keywords: ["notification", "alert", "complete", "done", "agent", "finish"],
  },
  {
    id: "notifications-waiting",
    tab: "notifications",
    scope: "global",
    tabLabel: "Notifications",
    section: "Agent Notifications",
    title: "Agent Waiting for Input",
    description: "Show a notification when an agent needs input",
    keywords: ["notification", "waiting", "input", "agent", "prompt", "pause"],
  },
  {
    id: "notifications-sound",
    tab: "notifications",
    scope: "global",
    tabLabel: "Notifications",
    section: "Sound",
    title: "Notification Sound",
    description:
      "Play a sound when notifications fire. Choose from chime, ping, complete, waiting, or error sounds.",
    keywords: ["sound", "audio", "chime", "ping", "notification", "alert", "volume"],
  },

  // Editor Integration
  {
    id: "editor-external",
    tab: "integrations",
    scope: "global",
    tabLabel: "Integrations",
    section: "External Editor",
    title: "External Editor",
    description:
      "Configure external editor: VS Code, Cursor, Windsurf, Zed, Neovim, WebStorm, Sublime Text, or custom",
    keywords: [
      "editor",
      "vscode",
      "cursor",
      "zed",
      "neovim",
      "webstorm",
      "sublime",
      "external",
      "open",
      "ide",
      "windsurf",
    ],
  },

  // Image Viewer
  {
    id: "image-viewer",
    tab: "integrations",
    scope: "global",
    tabLabel: "Integrations",
    section: "Image Viewer",
    title: "Image Viewer",
    description:
      "Configure image viewer: use OS default (Preview, Photos) or a custom command (Photoshop, GIMP)",
    keywords: [
      "image",
      "viewer",
      "photo",
      "picture",
      "preview",
      "png",
      "jpg",
      "svg",
      "gif",
      "open",
      "photoshop",
      "gimp",
    ],
  },

  // Voice Input
  {
    id: "voice-enable",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "Speech-to-Text",
    title: "Voice Input Enable",
    description: "Enable or disable voice input for speech-to-text transcription",
    keywords: ["voice", "microphone", "dictate", "speech", "recording", "enable", "mic"],
  },
  {
    id: "voice-deepgram-key",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "Speech-to-Text",
    title: "Deepgram API Key",
    description: "Configure your Deepgram API key for speech recognition",
    keywords: ["deepgram", "api", "key", "speech-to-text", "stt", "nova"],
    requiresEnabled: { settingId: "voice-enable", label: "Voice Input" },
  },
  {
    id: "voice-language",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "Speech-to-Text",
    title: "Transcription Language",
    description: "Select the language for speech transcription",
    keywords: ["language", "locale", "english", "multilingual", "transcription"],
    requiresEnabled: { settingId: "voice-enable", label: "Voice Input" },
  },
  {
    id: "voice-transcription-model",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "Speech-to-Text",
    title: "Transcription Model",
    description: "Choose the Deepgram model for transcription accuracy",
    keywords: ["nova-3", "nova-2", "model", "deepgram", "accuracy", "transcription"],
    requiresEnabled: { settingId: "voice-enable", label: "Voice Input" },
  },
  {
    id: "voice-paragraph-breaks",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "Speech-to-Text",
    title: "Paragraph Breaks",
    description: "Insert paragraph breaks via spoken commands",
    keywords: ["paragraph", "break", "enter", "formatting", "spoken"],
    requiresEnabled: { settingId: "voice-enable", label: "Voice Input" },
  },
  {
    id: "voice-custom-dictionary",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "Speech-to-Text",
    title: "Custom Dictionary",
    description: "Add domain-specific terms to improve recognition accuracy",
    keywords: ["dictionary", "terms", "domain", "vocabulary", "recognition", "custom"],
    requiresEnabled: { settingId: "voice-enable", label: "Voice Input" },
  },
  {
    id: "voice-ai-correction-enable",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "AI Text Correction",
    title: "AI Text Correction",
    description: "Enable AI-powered post-processing to clean up transcribed text",
    keywords: ["correction", "ai", "cleanup", "post-process", "filler"],
    requiresEnabled: { settingId: "voice-enable", label: "Voice Input" },
  },
  {
    id: "voice-openai-key",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "AI Text Correction",
    title: "OpenAI API Key",
    description: "Configure your OpenAI API key for AI text correction",
    keywords: ["openai", "api", "key", "correction", "gpt"],
    requiresEnabled: { settingId: "voice-ai-correction-enable", label: "AI Text Correction" },
  },
  {
    id: "voice-correction-model",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "AI Text Correction",
    title: "Correction Model",
    description: "Choose the OpenAI model used for text correction",
    keywords: ["gpt", "model", "correction", "openai"],
    requiresEnabled: { settingId: "voice-ai-correction-enable", label: "AI Text Correction" },
  },
  {
    id: "voice-custom-instructions",
    tab: "voice",
    scope: "global",
    tabLabel: "Voice Input",
    section: "AI Text Correction",
    title: "Custom Instructions",
    description: "Add project-specific rules for AI text correction",
    keywords: ["instructions", "prompt", "rules", "custom", "project-specific"],
    requiresEnabled: { settingId: "voice-ai-correction-enable", label: "AI Text Correction" },
  },

  // Privacy & Data
  {
    id: "privacy-telemetry-level",
    tab: "privacy",
    scope: "global",
    tabLabel: "Privacy & Data",
    subtab: "telemetry",
    subtabLabel: "Telemetry",
    section: "Telemetry & Diagnostics",
    title: "Telemetry Level",
    description: "Control what data is collected: Off, Errors Only, or Full Usage analytics",
    keywords: ["telemetry", "crash", "reporting", "analytics", "privacy", "sentry", "diagnostics"],
  },
  {
    id: "privacy-log-retention",
    tab: "privacy",
    scope: "global",
    tabLabel: "Privacy & Data",
    subtab: "storage",
    subtabLabel: "Data & Storage",
    section: "Log Retention",
    title: "Log Retention",
    description: "Auto-prune log files older than 7, 30, or 90 days on startup",
    keywords: ["log", "retention", "prune", "cleanup", "days", "storage"],
  },
  {
    id: "privacy-data-folder",
    tab: "privacy",
    scope: "global",
    tabLabel: "Privacy & Data",
    subtab: "storage",
    subtabLabel: "Data & Storage",
    section: "Data Folder",
    title: "Data Folder",
    description: "View and open the app data folder in your file manager",
    keywords: ["data", "folder", "path", "storage", "finder", "explorer"],
  },
  {
    id: "privacy-clear-cache",
    tab: "privacy",
    scope: "global",
    tabLabel: "Privacy & Data",
    subtab: "storage",
    subtabLabel: "Data & Storage",
    section: "Clear Cache",
    title: "Clear Cache",
    description: "Clear HTTP disk cache and code caches without affecting settings",
    keywords: ["cache", "clear", "disk", "http", "cleanup"],
  },
  {
    id: "privacy-reset-data",
    tab: "privacy",
    scope: "global",
    tabLabel: "Privacy & Data",
    subtab: "storage",
    subtabLabel: "Data & Storage",
    section: "Reset All App Data",
    title: "Reset All App Data",
    description:
      "Permanently delete all settings, API keys, session data, and logs. Factory reset.",
    keywords: ["reset", "wipe", "factory", "delete", "all", "data", "fresh"],
  },

  // Troubleshooting
  {
    id: "troubleshooting-gpu-acceleration",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "Hardware Acceleration",
    title: "Hardware Acceleration",
    description:
      "Disable GPU hardware acceleration if you experience blank panels or rendering issues",
    keywords: [
      "gpu",
      "hardware",
      "acceleration",
      "blank",
      "white",
      "crash",
      "rendering",
      "graphics",
    ],
  },
  {
    id: "troubleshooting-health",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "System Health Check",
    title: "System Health Check",
    description: "Verify Git, Node.js, npm installation and system dependencies",
    keywords: ["health", "check", "git", "node", "npm", "system", "verify", "diagnosis"],
  },
  {
    id: "troubleshooting-logs",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "Application Logs",
    title: "Application Logs",
    description: "Open log file and clear application logs",
    keywords: ["logs", "debug", "log file", "clear", "application", "output"],
  },
  {
    id: "troubleshooting-crash",
    tab: "privacy",
    scope: "global",
    tabLabel: "Privacy & Data",
    subtab: "telemetry",
    subtabLabel: "Telemetry",
    section: "Telemetry & Diagnostics",
    title: "Crash Reporting",
    description: "Configure crash reporting and telemetry level in Privacy & Data settings",
    keywords: ["crash", "reporting", "telemetry", "error", "stack trace", "sentry"],
  },
  {
    id: "troubleshooting-devmode",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "Developer Mode",
    title: "Developer Mode",
    description:
      "Enable developer mode, auto-open diagnostics, verbose logging, persistent verbose logging",
    keywords: [
      "developer",
      "debug",
      "verbose",
      "logging",
      "diagnostics",
      "devtools",
      "DAINTREE_DEBUG",
    ],
  },
  {
    id: "troubleshooting-auto-diagnostics",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "Developer Mode",
    title: "Auto-Open Diagnostics Dock",
    description: "Automatically open the diagnostics panel on app startup",
    keywords: ["diagnostics", "dock", "auto", "startup", "open", "developer"],
  },
  {
    id: "troubleshooting-focus-events",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "Developer Mode",
    title: "Focus Events Tab",
    description: "Default to the Events tab when the diagnostics panel opens",
    keywords: ["events", "focus", "diagnostics", "tab", "developer"],
  },
  {
    id: "troubleshooting-verbose-logging",
    tab: "troubleshooting",
    scope: "global",
    tabLabel: "Troubleshooting",
    section: "Developer Mode",
    title: "Enable Verbose Logging",
    description: "Enable verbose logging for this session only. Resets on app restart.",
    keywords: ["verbose", "logging", "debug", "log level", "session"],
  },

  // Terminal sub-controls
  {
    id: "terminal-preview-layout",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "layout",
    subtabLabel: "Layout",
    section: "Two-Pane Split Layout",
    title: "Preview-Focused Layout",
    description:
      "Give more space to browser or dev-preview panels (65/35 split) vs balanced layout (50/50)",
    keywords: ["preview", "browser", "focused", "ratio", "split", "layout", "two pane"],
  },
  {
    id: "terminal-default-ratio",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "layout",
    subtabLabel: "Layout",
    section: "Two-Pane Split Layout",
    title: "Default Split Ratio",
    description: "Set the default left/right split ratio for two-pane layout",
    keywords: ["ratio", "split", "default", "percentage", "slider", "two pane"],
  },
  {
    id: "terminal-reset-ratios",
    tab: "terminal",
    scope: "global",
    tabLabel: "Panel Grid",
    subtab: "layout",
    subtabLabel: "Layout",
    section: "Two-Pane Split Layout",
    title: "Reset All Worktree Split Ratios",
    description: "Clear all per-worktree split ratio overrides and return to the default ratio",
    keywords: ["reset", "worktree", "ratio", "split", "default", "clear"],
  },

  // MCP Server
  {
    id: "mcp-server-enable",
    tab: "mcp",
    scope: "global",
    tabLabel: "MCP Server",
    section: "MCP Server",
    title: "Enable MCP Server",
    description:
      "Start a local MCP server so AI agents can invoke Daintree actions (open terminals, inject context, switch worktrees, etc.)",
    keywords: ["mcp", "server", "agent", "local", "tools", "automation", "api", "enable"],
  },
  {
    id: "mcp-server-config",
    tab: "mcp",
    scope: "global",
    tabLabel: "MCP Server",
    section: "Connection",
    title: "Copy MCP Config",
    description:
      "Copy the MCP server config snippet (JSON) to paste into your MCP client configuration",
    keywords: ["mcp", "config", "copy", "snippet", "json", "client", "cursor", "claude"],
    requiresEnabled: { settingId: "mcp-server-enable", label: "MCP Server" },
  },
  {
    id: "mcp-server-port",
    tab: "mcp",
    scope: "global",
    tabLabel: "MCP Server",
    section: "Port",
    title: "Server Port",
    description:
      "Set a fixed port for the MCP server or leave empty for automatic ephemeral port assignment",
    keywords: ["mcp", "port", "fixed", "ephemeral", "network", "bind"],
    requiresEnabled: { settingId: "mcp-server-enable", label: "MCP Server" },
  },
  {
    id: "mcp-server-auth",
    tab: "mcp",
    scope: "global",
    tabLabel: "MCP Server",
    section: "Authentication",
    title: "API Key Authentication",
    description:
      "Generate a bearer token to secure MCP connections. Clients must include the token in the Authorization header.",
    keywords: ["mcp", "api", "key", "auth", "token", "bearer", "security", "password"],
    requiresEnabled: { settingId: "mcp-server-enable", label: "MCP Server" },
  },

  // Environment Variables
  {
    id: "environment-variables",
    tab: "environment",
    scope: "global",
    tabLabel: "Environment Variables",
    section: "Environment Variables",
    title: "Project Environment Variables",
    description:
      "Add, edit, and delete key/value environment variables for the current project. Injected into new terminals at spawn time.",
    keywords: [
      "env",
      "environment",
      "variables",
      "project",
      "api key",
      "secret",
      "token",
      "password",
      "PATH",
      "inject",
      "terminal",
      "encryption",
      "dotenv",
    ],
  },

  // ── Project settings entries ──
  {
    id: "tab-nav-project:general",
    tab: "project:general",
    scope: "project",
    tabLabel: "General",
    section: "Settings Navigation",
    title: "General",
    description: "Project name, emoji, color, icon, and dev server configuration",
    keywords: ["project", "name", "emoji", "color", "icon", "dev server"],
  },
  {
    id: "project-name",
    tab: "project:general",
    scope: "project",
    tabLabel: "General",
    section: "Project Identity",
    title: "Project Name",
    description: "Display name for the project",
    keywords: ["name", "title", "label"],
  },
  {
    id: "project-dev-server",
    tab: "project:general",
    scope: "project",
    tabLabel: "General",
    section: "Dev Server",
    title: "Dev Server Command",
    description: "Command to start the development server for live preview",
    keywords: ["dev", "server", "preview", "start", "command"],
  },
  {
    id: "project-in-repo-settings",
    tab: "project:general",
    scope: "project",
    tabLabel: "General",
    section: "In-Repo Settings",
    title: "In-Repo Settings",
    description: "Store project settings in the repository for team sharing",
    keywords: ["repo", "repository", "shared", "team", "daintree.json"],
  },
  {
    id: "tab-nav-project:context",
    tab: "project:context",
    scope: "project",
    tabLabel: "Context",
    section: "Settings Navigation",
    title: "Context",
    description: "Excluded paths and copy tree settings",
    keywords: ["project", "context", "exclude", "paths", "copy tree"],
  },
  {
    id: "project-excluded-paths",
    tab: "project:context",
    scope: "project",
    tabLabel: "Context",
    section: "Excluded Paths",
    title: "Excluded Paths",
    description: "Paths to exclude from context tree and file operations",
    keywords: ["exclude", "ignore", "paths", "gitignore", "filter"],
  },
  {
    id: "project-copy-tree",
    tab: "project:context",
    scope: "project",
    tabLabel: "Context",
    section: "Copy Tree",
    title: "Copy Tree Settings",
    description: "Configure context size limits, file size limits, and include/exclude patterns",
    keywords: ["copy", "tree", "context", "size", "limit", "include", "exclude"],
  },
  {
    id: "project-env-vars",
    tab: "project:variables",
    scope: "project",
    tabLabel: "Variables",
    section: "Environment Variables",
    title: "Environment Variables",
    description: "Project-specific environment variables injected into terminals",
    keywords: ["env", "environment", "variables", "secrets", "inject"],
  },
  {
    id: "tab-nav-project:variables",
    tab: "project:variables",
    scope: "project",
    tabLabel: "Variables",
    section: "Settings Navigation",
    title: "Variables",
    description: "Project environment variables injected into terminals",
    keywords: ["project", "variables", "environment", "env", "secrets", "inject"],
  },
  {
    id: "tab-nav-project:automation",
    tab: "project:automation",
    scope: "project",
    tabLabel: "Worktree Setup",
    section: "Settings Navigation",
    title: "Worktree Setup",
    description: "Configure worktree paths, run commands, branch prefix, and terminal defaults",
    keywords: ["project", "automation", "run", "commands", "worktree", "terminal", "branch"],
  },
  {
    id: "project-run-commands",
    tab: "project:automation",
    scope: "project",
    tabLabel: "Worktree Setup",
    section: "Run Commands",
    title: "Run Commands",
    description: "Named commands to run in worktree terminals on creation",
    keywords: ["run", "commands", "startup", "init", "worktree"],
  },
  {
    id: "project-branch-prefix",
    tab: "project:automation",
    scope: "project",
    tabLabel: "Worktree Setup",
    section: "Branch Prefix",
    title: "Branch Prefix",
    description: "Automatic prefix for new branch names (none, username, or custom)",
    keywords: ["branch", "prefix", "username", "git", "naming"],
  },
  {
    id: "project-terminal-settings",
    tab: "project:automation",
    scope: "project",
    tabLabel: "Worktree Setup",
    section: "Terminal Settings",
    title: "Terminal Settings",
    description: "Project-specific shell, shell args, working directory, and scrollback",
    keywords: ["terminal", "shell", "bash", "zsh", "scrollback", "cwd"],
  },
  {
    id: "tab-nav-project:recipes",
    tab: "project:recipes",
    scope: "project",
    tabLabel: "Recipes",
    section: "Settings Navigation",
    title: "Recipes",
    description: "Manage terminal recipes for the project",
    keywords: ["project", "recipes", "template", "terminal"],
  },
  {
    id: "tab-nav-project:commands",
    tab: "project:commands",
    scope: "project",
    tabLabel: "Commands",
    section: "Settings Navigation",
    title: "Commands",
    description: "Project-specific command overrides",
    keywords: ["project", "commands", "overrides", "alias"],
  },
  {
    id: "tab-nav-project:notifications",
    tab: "project:notifications",
    scope: "project",
    tabLabel: "Notifications",
    section: "Settings Navigation",
    title: "Notifications",
    description: "Project-specific notification overrides",
    keywords: ["project", "notifications", "alerts", "sounds", "overrides"],
  },
  {
    id: "tab-nav-project:github",
    tab: "project:github",
    scope: "project",
    tabLabel: "GitHub",
    section: "Settings Navigation",
    title: "GitHub",
    description: "Per-project GitHub remote configuration for issues, PRs, and pulse data",
    keywords: ["project", "github", "remote", "origin", "repository", "pull requests", "issues"],
  },
  {
    id: "project-github-remote",
    tab: "project:github",
    scope: "project",
    tabLabel: "GitHub",
    section: "GitHub Remote",
    title: "GitHub Remote",
    description: "Select which git remote to use for GitHub integration",
    keywords: ["github", "remote", "origin", "git", "repository", "fetch", "push"],
  },
  {
    id: "tab-nav-project:environments",
    tab: "project:automation",
    scope: "project",
    tabLabel: "Worktree Setup",
    section: "Resource Environments",
    title: "Resources",
    description: "Remote resource definitions and default worktree mode",
    keywords: ["project", "resources", "environments", "remote", "docker", "akash", "worktree"],
  },
];
