import fs from "fs";
import path from "path";
import os from "os";
import { app } from "electron";
import type { CliInstallStatus } from "../../shared/types/ipc/system.js";

const CLI_COMMAND_NAME = IS_LEGACY_BUILD ? "canopy-app" : "daintree";
const CLI_SCRIPT_FILE = IS_LEGACY_BUILD ? "canopy-cli.sh" : "daintree-cli.sh";
const INSTALL_TARGETS_MACOS = [
  `/usr/local/bin/${CLI_COMMAND_NAME}`,
  `${os.homedir()}/.local/bin/${CLI_COMMAND_NAME}`,
];
const INSTALL_TARGETS_LINUX = [
  `/usr/local/bin/${CLI_COMMAND_NAME}`,
  `${os.homedir()}/.local/bin/${CLI_COMMAND_NAME}`,
];
const SYMLINK_FALLBACK_ERROR_CODES = new Set(["EINVAL", "ENOSYS", "EOPNOTSUPP", "EPERM"]);

function isAppImage(): boolean {
  return (
    process.platform === "linux" &&
    typeof process.env.APPIMAGE === "string" &&
    process.env.APPIMAGE.length > 0
  );
}

function getAppImageWrapperDir(): string {
  const xdgDataHome = process.env.XDG_DATA_HOME || path.join(os.homedir(), ".local", "share");
  return path.join(xdgDataHome, CLI_COMMAND_NAME);
}

function getAppImageWrapperPath(): string {
  return path.join(getAppImageWrapperDir(), CLI_SCRIPT_FILE);
}

function generateAppImageWrapper(appImagePath: string): string {
  const escaped = appImagePath.replace(/'/g, "'\\''");
  const productName = IS_LEGACY_BUILD ? "Canopy" : "Daintree";
  return [
    "#!/usr/bin/env bash",
    `# Auto-generated by ${productName} — do not edit`,
    "set -euo pipefail",
    'TARGET="${1:-.}"',
    `ABSOLUTE_PATH="$(cd -- "$TARGET" 2>/dev/null && pwd -P)" || { echo "${CLI_COMMAND_NAME}: '$TARGET' is not a directory" >&2; exit 1; }`,
    `'${escaped}' --cli-path "$ABSOLUTE_PATH" &`,
    "exit 0",
    "",
  ].join("\n");
}

function ensureAppImageWrapper(): string {
  const wrapperDir = getAppImageWrapperDir();
  const wrapperPath = getAppImageWrapperPath();
  const content = generateAppImageWrapper(process.env.APPIMAGE!);

  fs.mkdirSync(wrapperDir, { recursive: true });
  fs.writeFileSync(wrapperPath, content, { mode: 0o755 });

  return wrapperPath;
}

function getInstallTargets(): string[] {
  if (process.platform === "darwin") return INSTALL_TARGETS_MACOS;
  if (process.platform === "linux") return INSTALL_TARGETS_LINUX;
  return [];
}

function getScriptSourcePath(): string {
  if (isAppImage()) {
    return getAppImageWrapperPath();
  }
  if (app.isPackaged) {
    return path.join(process.resourcesPath, CLI_SCRIPT_FILE);
  }
  // Dev: app path points at project root when running `electron .`
  const devDir = IS_LEGACY_BUILD ? path.join("scripts", "legacy") : "scripts";
  return path.join(app.getAppPath(), devDir, CLI_SCRIPT_FILE);
}

function readFileIfExists(filePath: string): string | null {
  try {
    return fs.readFileSync(filePath, "utf8");
  } catch {
    return null;
  }
}

function getRealPath(filePath: string): string | null {
  try {
    return fs.realpathSync(filePath);
  } catch {
    return null;
  }
}

function asNodeError(err: unknown): NodeJS.ErrnoException {
  return err instanceof Error ? (err as NodeJS.ErrnoException) : new Error(String(err));
}

function canFallbackToCopy(err: unknown): boolean {
  const code = asNodeError(err).code;
  return typeof code === "string" && SYMLINK_FALLBACK_ERROR_CODES.has(code);
}

function isInstallUpToDate(targetPath: string, sourcePath: string): boolean {
  const sourceRealPath = getRealPath(sourcePath);
  if (!sourceRealPath) {
    return false;
  }

  try {
    const targetStats = fs.lstatSync(targetPath);
    if (targetStats.isSymbolicLink()) {
      return getRealPath(targetPath) === sourceRealPath;
    }
  } catch {
    return false;
  }

  const sourceContent = readFileIfExists(sourcePath);
  const targetContent = readFileIfExists(targetPath);
  return sourceContent !== null && targetContent !== null && sourceContent === targetContent;
}

function installAtTarget(targetPath: string, sourcePath: string): void {
  const dir = path.dirname(targetPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  if (fs.existsSync(targetPath)) {
    if (isInstallUpToDate(targetPath, sourcePath)) {
      return;
    }
    fs.unlinkSync(targetPath);
  }

  try {
    fs.symlinkSync(sourcePath, targetPath);
  } catch (err) {
    if (!canFallbackToCopy(err)) {
      throw err;
    }

    const sourceContent = fs.readFileSync(sourcePath, "utf8");
    fs.writeFileSync(targetPath, sourceContent, { mode: 0o755 });
    fs.chmodSync(targetPath, 0o755);
  }
}

export async function install(): Promise<CliInstallStatus> {
  if (isAppImage()) {
    ensureAppImageWrapper();
  }

  const sourcePath = getScriptSourcePath();

  if (!fs.existsSync(sourcePath)) {
    throw new Error(`CLI script source not found: ${sourcePath}`);
  }

  const targets = getInstallTargets();
  if (targets.length === 0) {
    throw new Error("CLI installation is not supported on this platform.");
  }

  let lastError: Error | null = null;

  for (const target of targets) {
    try {
      installAtTarget(target, sourcePath);
      console.log(`[CliInstallService] Installed to ${target}`);
      return { installed: true, upToDate: true, path: target };
    } catch (err) {
      lastError = asNodeError(err);
      console.warn(`[CliInstallService] Could not write to ${target}:`, lastError.message);
    }
  }

  throw lastError ?? new Error("Failed to install CLI: no writable target found.");
}

export function getStatus(): CliInstallStatus {
  const sourcePath = getScriptSourcePath();
  const targets = getInstallTargets();

  for (const target of targets) {
    if (fs.existsSync(target)) {
      return {
        installed: true,
        upToDate: isInstallUpToDate(target, sourcePath),
        path: target,
      };
    }
  }

  return { installed: false, upToDate: false, path: targets[0] ?? "" };
}
