/**
 * Renders `docs/plugins/actions.md` from a built action registry.
 *
 * Kept free of Vite and the filesystem so the freshness gate can live in the
 * test suite, where the registry is already built: loading the renderer graph
 * through a one-shot Vite server takes minutes, which is the wrong price for
 * `npm run check` to pay on every run. The CLI in `plugin-actions-doc.ts` owns
 * the loading and the I/O; this owns the text.
 */
import { z } from "zod";
import type { ActionDefinition } from "../../shared/types/actions.js";
import type { ActionRegistry } from "../../src/services/actions/actionTypes.js";
import {
  BUILT_IN_ACTION_IDS,
  DENY_PLUGIN_DISPATCH_ACTION_IDS,
} from "../../shared/config/actionIds.js";

/** Top-level argument names, marking the required ones. Empty when the action takes none. */
function argSummary(def: ActionDefinition): string {
  if (!def.argsSchema) return "—";
  let emitted: { properties?: Record<string, unknown>; required?: string[] };
  try {
    emitted = z.toJSONSchema(def.argsSchema as z.ZodType, {
      io: "input",
      unrepresentable: "any",
      reused: "inline",
      cycles: "ref",
      target: "draft-2020-12",
    }) as { properties?: Record<string, unknown>; required?: string[] };
  } catch {
    return "—";
  }
  const names = Object.keys(emitted.properties ?? {});
  if (names.length === 0) return "—";
  const required = new Set(emitted.required ?? []);
  // Required first, then optional, each alphabetical — so a reader scanning the
  // column sees what they must send before what they may.
  const ordered = [
    ...names.filter((n) => required.has(n)).sort(),
    ...names.filter((n) => !required.has(n)).sort(),
  ];
  return ordered.map((n) => (required.has(n) ? `\`${n}\`` : `\`${n}?\``)).join(", ");
}

function escapeCell(text: string): string {
  return text.replace(/\|/g, "\\|").replace(/\n/g, " ").trim();
}

export function renderPluginActionsDoc(registry: ActionRegistry): string {
  const denied = new Set<string>(DENY_PLUGIN_DISPATCH_ACTION_IDS);

  const rows: Array<{ id: string; category: string; title: string; danger: string; args: string }> =
    [];
  for (const id of BUILT_IN_ACTION_IDS) {
    if (denied.has(id)) continue;
    const factory = registry.get(id);
    if (!factory) continue;
    const def = factory();
    // A plugin's dispatch is refused for `restricted` whatever its tier, so
    // listing one would be listing something that cannot be called.
    if (def.danger === "restricted") continue;
    rows.push({
      id,
      category: def.category,
      title: escapeCell(def.title),
      danger: def.danger,
      args: argSummary(def),
    });
  }
  rows.sort((a, b) => a.category.localeCompare(b.category) || a.id.localeCompare(b.id));

  const lines: string[] = [];
  lines.push("<!-- Generated by `npm run codegen:plugin-actions`. Do not edit by hand. -->");
  lines.push("");
  lines.push("# Built-in actions a plugin may dispatch");
  lines.push("");
  lines.push(
    "Every built-in action a plugin can see through `host.actions` and name in `host.dispatch(id, args)`, generated from the action manifest itself so it cannot drift from what the host actually accepts. Only the `safe` rows run from a plugin; the `confirm` rows are listed so a plugin can recognise them, and the host refuses them."
  );
  lines.push("");
  lines.push(
    "Two sets are absent by construction. Actions on the plugin-dispatch deny list are refused at the boundary no matter what a plugin declares — they inject input or run commands on the user's behalf, and a plugin that needs one is asking for a capability rather than an action. Actions classed `restricted` are refused for every caller, plugins included."
  );
  lines.push("");
  lines.push(
    '`danger` is the host\'s own classification, not advice. A `confirm` action cannot run from `host.dispatch`: plugins have no confirmation path, so the dispatch resolves `{ ok: false }` with a `CONFIRMATION_REQUIRED` error and no dialog is shown to the user. Call `host.actions.canDispatch(id)` first: it resolves `"ok"` for a `safe` action, `"confirm"` for one the dispatch would refuse, and `"restricted"` for an unknown or unavailable id.'
  );
  lines.push("");
  lines.push(
    "`canDispatch` sees only the id, and some `safe` actions are refused for particular arguments. `terminal.new` with `command` or `cwd` is raised to `confirm` for a plugin and refused; without either it opens a plain terminal. `worktree.createWithRecipe` and `workflow.startWorkOnIssue` fail when the arguments carry a `recipeId`, so a plugin cannot start a recipe's terminals through them (and `recipe.run` is `confirm`). `file.showItemInFolder` fails when `allowOutsideRoots` is set. `session.bookmark.promote`, `session.bookmark.rename` and `session.bookmark.delete` fail when the dispatch has no project in scope, and when the session does not belong to that project. Each of these resolves `{ ok: false }` with an error rather than running."
  );
  lines.push("");
  lines.push(
    "An argument shown as `name?` is optional. Argument names come from each action's schema; the schema is the authority on their types and bounds."
  );
  lines.push("");

  let currentCategory: string | null = null;
  for (const row of rows) {
    if (row.category !== currentCategory) {
      currentCategory = row.category;
      lines.push("");
      lines.push(`## ${currentCategory}`);
      lines.push("");
      lines.push("| Action | Title | Danger | Arguments |");
      lines.push("| --- | --- | --- | --- |");
    }
    lines.push(`| \`${row.id}\` | ${row.title} | ${row.danger} | ${row.args} |`);
  }
  lines.push("");
  lines.push("## See also");
  lines.push("");
  lines.push("- [host-api.md](./host-api.md) — what `host` can do inside `activate()`");
  lines.push("- [trust-model.md](./trust-model.md) — what the capability tokens mean");
  lines.push("");
  return lines.join("\n");
}
