import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";
import { projectRemoteAppearance } from "../../shared/theme/remoteAppearance.js";
import { BUILT_IN_APP_SCHEMES } from "../../shared/theme/themes.js";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "../..");
const outputPath = path.join(root, "apps/portal/lib/theme/generated_daintree_appearance.dart");
const source = BUILT_IN_APP_SCHEMES.find((scheme) => scheme.id === "daintree");
const bondiSource = BUILT_IN_APP_SCHEMES.find((scheme) => scheme.id === "bondi");

if (!source) throw new Error("The Daintree built-in theme source is missing");
if (!bondiSource) throw new Error("The Bondi built-in theme source is missing");

const snapshot = projectRemoteAppearance(source, { revision: 0 });
const bondiSnapshot = projectRemoteAppearance(bondiSource, { revision: 0 });
const generated = `// AUTO-GENERATED by scripts/codegen/portal-theme.ts — do not edit by hand.
// Run \`npm run codegen:portal-theme\` to regenerate from the TypeScript Daintree theme source.

const Map<String, Object?> generatedDaintreeAppearanceJson = <String, Object?>${JSON.stringify(snapshot, null, 2)};

const Map<String, Object?> generatedBondiAppearanceJson = <String, Object?>${JSON.stringify(bondiSnapshot, null, 2)};
`;

if (process.argv.includes("--check")) {
  const current = await readFile(outputPath, "utf8").catch(() => "");
  if (current !== generated) {
    console.error(
      "Portal theme drift detected. Run `npm run codegen:portal-theme` and commit the generated Dart source."
    );
    process.exitCode = 1;
  } else {
    console.log("[portal-theme] generated Dart appearance matches the TypeScript source");
  }
} else {
  await writeFile(outputPath, generated, "utf8");
}
