import path from "node:path";
import { checkBaselineCoverage } from "./lib/baselineCoverage";
import { loadBudgetConfig } from "./lib/budgets";
import { readJson } from "./lib/io";
import { getScenariosForMode } from "./scenarios";
import type { BaselineSummary, PerfMode } from "./types";

/**
 * Integrity gate for the perf-update-baselines job.
 *
 * That job regenerates all four baselines with `continue-on-error: true` on
 * each step, because a budget regression still writes a valid baseline and
 * then exits 1. The side effect is that a step which dies from a harness
 * exception — writing nothing — is indistinguishable from a healthy one, so
 * the job would happily open a PR staging some freshly-regenerated modes
 * alongside other modes left stale. That is not theoretical: the existing
 * `perf/update-baselines-automated` branch carries a soak-only baseline commit
 * from exactly this path.
 *
 * Run this between the regen steps and the PR step so a partial or degenerate
 * set fails the job instead of becoming a PR someone might merge.
 */

const MODES: PerfMode[] = ["smoke", "ci", "nightly", "soak"];
const DEFAULT_MAX_AGE_MINUTES = 720;

function parseMaxAgeMinutes(argv: string[]): number {
  const index = argv.indexOf("--max-age-minutes");
  if (index === -1) return DEFAULT_MAX_AGE_MINUTES;
  const raw = Number(argv[index + 1]);
  if (!Number.isFinite(raw) || raw <= 0) {
    throw new Error(`--max-age-minutes expects a positive number, got "${argv[index + 1]}"`);
  }
  return raw;
}

function verifyMode(
  mode: PerfMode,
  maxAgeMinutes: number,
  budgetConfig: ReturnType<typeof loadBudgetConfig>
): string[] {
  const baselinePath = path.resolve(process.cwd(), `scripts/perf/config/baseline.${mode}.json`);
  const problems: string[] = [];

  let baseline: BaselineSummary | null;
  try {
    baseline = readJson<BaselineSummary>(baselinePath);
  } catch (error) {
    return [`unreadable or malformed JSON (${(error as Error).message})`];
  }

  if (!baseline) return [`missing or empty (${baselinePath})`];

  if (baseline.mode !== mode) {
    problems.push(`mode field is "${baseline.mode}", expected "${mode}" — wrong file written`);
  }

  const generatedAtMs = new Date(baseline.generatedAt).getTime();
  if (!Number.isFinite(generatedAtMs)) {
    problems.push(`generatedAt is unparseable ("${baseline.generatedAt}")`);
  } else {
    const ageMinutes = (Date.now() - generatedAtMs) / 60_000;
    if (ageMinutes > maxAgeMinutes) {
      problems.push(
        `not regenerated by this run — generatedAt is ${Math.round(ageMinutes)}min old ` +
          `(limit ${maxAgeMinutes}min), so its regen step failed and left the previous file`
      );
    }
  }

  const p95 = baseline.p95ByScenario ?? {};
  const entries = Object.entries(p95);
  if (entries.length === 0) {
    problems.push("p95ByScenario is empty");
  }

  const nonFinite = entries.filter(([, value]) => !Number.isFinite(value)).map(([id]) => id);
  if (nonFinite.length > 0) {
    problems.push(`non-finite p95 values: ${nonFinite.join(", ")}`);
  }

  // A literal-zero p95 sinks the scenario under gate.ts's
  // MIN_REGRESSION_BASELINE_MS floor, silently disabling its regression gate.
  // This is how the `durationMs: 0` sentinel regression stayed invisible.
  const zeros = entries.filter(([, value]) => value === 0).map(([id]) => id);
  if (zeros.length > 0) {
    problems.push(
      `zero p95 baselines (regression gate would be silently skipped): ${zeros.join(", ")}`
    );
  }

  const scenariosForMode = getScenariosForMode(mode);

  const gaps = checkBaselineCoverage(baseline, budgetConfig, scenariosForMode);
  if (gaps.length > 0) {
    problems.push(`budgeted scenarios absent: ${gaps.map((gap) => gap.scenarioId).join(", ")}`);
  }

  // `checkBaselineCoverage` only inspects scenarios carrying a regression
  // reference, so a scenario with neither a reference nor a baseline entry
  // slips past it. A committed baseline is supposed to describe the whole
  // matrix for its mode, and this is the one place that can say so.
  const missingEntries = scenariosForMode
    .map((scenario) => scenario.id)
    .filter((id) => !Number.isFinite(p95[id]));
  if (missingEntries.length > 0) {
    problems.push(`scenarios absent from the baseline: ${missingEntries.join(", ")}`);
  }

  return problems;
}

function main(): void {
  const maxAgeMinutes = parseMaxAgeMinutes(process.argv.slice(2));
  const budgetConfig = loadBudgetConfig();
  let failed = false;

  for (const mode of MODES) {
    const problems = verifyMode(mode, maxAgeMinutes, budgetConfig);
    if (problems.length === 0) {
      console.log(`[perf:verify-baselines] OK ${mode}`);
      continue;
    }
    failed = true;
    for (const problem of problems) {
      console.error(`[perf:verify-baselines] FAIL ${mode}: ${problem}`);
    }
  }

  if (failed) {
    console.error(
      "[perf:verify-baselines] refusing to open a baseline PR — fix the failing regen step first"
    );
    process.exit(1);
  }

  console.log(`[perf:verify-baselines] all ${MODES.length} baselines verified`);
}

main();
